// generated by src/ntt/pow/expand.json
#include <algorithm>
#include <array>
#include <bit>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <immintrin.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <utility>
#include <vector>

template <typename T> T *alloc(std::size_t n) {
  const std::size_t bytes = (n * sizeof(T) + 63) & ~std::size_t(63);
  return static_cast<T *>(std::aligned_alloc(64, bytes));
}

struct mont32 {
  uint32_t mod = 998244353;
  uint32_t mod2 = 998244353 * 2;
  uint32_t ir = 998244351;
  uint32_t root = 3;
  uint32_t r = 301989884;
  uint32_t r2 = 932051910;

  static mont32 make(uint32_t mod = 998244353, uint32_t root = 3) {
    mont32 info;
    info.mod = mod;
    info.mod2 = mod * 2;
    info.ir = uint32_t(0) - inv_mod_u32(mod);
    info.root = root;
    info.r = uint32_t((uint64_t(1) << 32) % mod);
    info.r2 = uint32_t((uint64_t(0) - uint64_t(mod)) % mod);
    return info;
  }

  static uint32_t inv_mod_u32(uint32_t x) {
    uint32_t y = 1;
    for (int i = 0; i < 5; ++i) {
      y *= 2 - y * x;
    }
    return y;
  }

  uint32_t reduce(uint64_t x) const {
    return uint32_t((x + uint64_t(uint32_t(x) * ir) * mod) >> 32);
  }

  uint32_t add(uint32_t a, uint32_t b) const {
    uint32_t x = a + b - mod2;
    return x >> 31 ? x + mod2 : x;
  }

  uint32_t sub(uint32_t a, uint32_t b) const {
    uint32_t x = a - b;
    return x >> 31 ? x + mod2 : x;
  }

  uint32_t mul(uint32_t a, uint32_t b) const { return reduce(uint64_t(a) * b); }

  uint32_t shift2(uint32_t x) const {
    return ((x & 1) != 0 ? x + mod : x) >> 1;
  }

  uint32_t to_mont(uint32_t x) const {
    uint32_t y = reduce(uint64_t(x) * r2);
    return y < mod ? y : y - mod;
  }

  uint32_t from_mont(uint32_t x) const {
    x = reduce(x) - mod;
    return x >> 31 ? x + mod : x;
  }

  uint32_t one() const { return r; }

  uint32_t pow(uint32_t a, uint64_t n) const {
    uint32_t r = one();
    while (n > 0) {
      if (n & 1) {
        r = mul(r, a);
      }
      a = mul(a, a);
      n >>= 1;
    }
    return r;
  }

  uint32_t inv(uint32_t a) const { return pow(a, mod - 2); }
};

struct mont32x8 {
  mont32 info;
  __m256i mod8;
  __m256i mod2_8;
  __m256i ir8;
  __m256i one8;
  __m256i r2_8;

  explicit mont32x8(mont32 info_)
      : info(info_), mod8(_mm256_set1_epi32(int(info.mod))),
        mod2_8(_mm256_set1_epi32(int(info.mod2))),
        ir8(_mm256_set1_epi32(int(info.ir))), one8(_mm256_set1_epi32(1)),
        r2_8(_mm256_set1_epi32(int(info.r2))) {}

  __m256i load(const uint32_t *p) const {
    return _mm256_loadu_si256(reinterpret_cast<const __m256i_u *>(p));
  }

  void store(uint32_t *p, __m256i x) const {
    _mm256_storeu_si256(reinterpret_cast<__m256i_u *>(p), x);
  }

  __m256i add(__m256i a, __m256i b) const {
    __m256i x = _mm256_add_epi32(a, b);
    return _mm256_min_epu32(x, _mm256_sub_epi32(x, mod2_8));
  }

  __m256i sub(__m256i a, __m256i b) const {
    __m256i x = _mm256_sub_epi32(a, b);
    return _mm256_min_epu32(x, _mm256_add_epi32(x, mod2_8));
  }

  __m256i mul(__m256i a, __m256i b) const {
    __m256i x0246 = _mm256_mul_epu32(a, b);
    __m256i x1357 = _mm256_mul_epu32(_mm256_shuffle_epi32(a, 0b11110101),
                                     _mm256_shuffle_epi32(b, 0b11110101));
    __m256i y0246 = _mm256_mul_epu32(_mm256_mul_epu32(x0246, ir8), mod8);
    __m256i y1357 = _mm256_mul_epu32(_mm256_mul_epu32(x1357, ir8), mod8);
    __m256i z0246 = _mm256_add_epi64(x0246, y0246);
    z0246 = _mm256_shuffle_epi32(z0246, 0b11110101);
    __m256i z1357 = _mm256_add_epi64(x1357, y1357);
    return _mm256_blend_epi32(z0246, z1357, 0b10101010);
  }

  template <int imm> __m256i mul_odd(__m256i a, __m256i b) const {
    __m256i sa = _mm256_shuffle_epi32(a, 0b11110101);
    __m256i sb = _mm256_shuffle_epi32(b, 0b11110101);
    __m256i x = _mm256_mul_epu32(sa, sb);
    __m256i y = _mm256_mul_epu32(_mm256_mul_epu32(x, ir8), mod8);
    __m256i z = _mm256_add_epi64(x, y);
    return _mm256_blend_epi32(a, z, imm);
  }

  __m256i to_mont(__m256i x) const {
    __m256i y = mul(x, r2_8);
    return _mm256_min_epu32(y, _mm256_sub_epi32(y, mod8));
  }

  __m256i from_mont(__m256i x) const {
    __m256i y = mul(x, one8);
    return _mm256_min_epu32(y, _mm256_sub_epi32(y, mod8));
  }

  __m256i pow(__m256i a, uint64_t n) const {
    __m256i r = _mm256_set1_epi32(int(info.one()));
    while (n > 0) {
      if ((n & 1) != 0) {
        r = mul(r, a);
      }
      a = mul(a, a);
      n >>= 1;
    }
    return r;
  }

  __m256i inv(__m256i a) const { return pow(a, info.mod - 2); }

  __m256i shift2(__m256i x) const {
    __m256i one = _mm256_set1_epi32(1);
    __m256i mask = _mm256_sub_epi32(_mm256_and_si256(x, one), one);
    __m256i add_mod = _mm256_andnot_si256(mask, mod8);
    return _mm256_srli_epi32(_mm256_add_epi32(x, add_mod), 1);
  }

  template <int imm> __m256i neg(__m256i x) const {
    __m256i sub = _mm256_sub_epi32(mod2_8, x);
    return _mm256_blend_epi32(x, sub, imm);
  }
};

struct NttTwistedNativeRadix2Info {
  mont32 info;
  std::vector<uint32_t> rt;
  std::vector<uint32_t> irt;
  std::vector<uint32_t> inv_len;

  explicit NttTwistedNativeRadix2Info(mont32 info = mont32::make());

  void prepare(std::size_t n);

  void ntt(uint32_t *f, std::size_t n) const;
  void intt(uint32_t *f, std::size_t n) const;
  void intt_irt(uint32_t *f, std::size_t n) const;
  void intt_impl(uint32_t *f, std::size_t n, const uint32_t *roots) const;
};

struct NttTwistedAvxRadix2Info : NttTwistedNativeRadix2Info {
  mont32x8 info8;
  __m256i rt2{};
  __m256i rt4{};
  __m256i irt2{};
  __m256i irt4{};

  explicit NttTwistedAvxRadix2Info(mont32 info = mont32::make());

  void prepare(std::size_t n);

  void ntt(uint32_t *f, std::size_t n) const;
  void intt(uint32_t *f, std::size_t n) const;
  void intt_irt(uint32_t *f, std::size_t n) const;
  void intt_impl(uint32_t *f, std::size_t n, const uint32_t *roots, __m256i rt2,
                 __m256i rt4) const;
};

struct NttTwistedAvxRadix4Info : NttTwistedAvxRadix2Info {
  explicit NttTwistedAvxRadix4Info(mont32 info = mont32::make());

  void ntt(uint32_t *f, std::size_t n) const;
  void intt(uint32_t *f, std::size_t n) const;
  void intt_irt(uint32_t *f, std::size_t n) const;
  void intt_impl(uint32_t *f, std::size_t n, const uint32_t *roots,
                 __m256i root2, __m256i root4) const;
};

NttTwistedNativeRadix2Info::NttTwistedNativeRadix2Info(mont32 info_)
    : info(info_), inv_len(32) {
  inv_len[0] = info.one();
  for (std::size_t k = 1; k < inv_len.size(); ++k) {
    inv_len[k] = info.shift2(inv_len[k - 1]);
  }
  prepare(16);
}

void NttTwistedNativeRadix2Info::prepare(std::size_t n) {
  n = std::bit_ceil(n);
  assert(n <= (std::size_t(1) << std::countr_zero(info.mod - 1)));

  std::size_t old_n = rt.size();
  if (old_n >= n) {
    return;
  }
  rt.resize(n);
  irt.resize(n);
  if (old_n == 0) {
    old_n = 2;
    rt[0] = info.one();
    rt[1] = info.one();
    irt[0] = info.one();
    irt[1] = info.one();
  }
  const uint32_t g = info.to_mont(info.root);
  const uint32_t ig = info.inv(g);
  for (; old_n < n; old_n *= 2) {
    uint32_t p = info.pow(g, (info.mod - 1) / old_n / 2);
    uint32_t ip = info.pow(ig, (info.mod - 1) / old_n / 2);
    for (std::size_t i = old_n; i < old_n * 2; i += 2) {
      rt[i] = rt[i / 2];
      rt[i + 1] = info.mul(p, rt[i]);
      irt[i] = irt[i / 2];
      irt[i + 1] = info.mul(ip, irt[i]);
    }
  }
}
void NttTwistedNativeRadix2Info::ntt(uint32_t *f, std::size_t n) const {
  assert(std::has_single_bit(n));
  assert(n <= rt.size());
  const mont32 info = this->info;
  for (std::size_t l = n / 2; l > 0; l /= 2) {
    for (std::size_t i = 0; i < n; i += l * 2) {
      for (std::size_t j = 0; j < l; ++j) {
        uint32_t x = f[i + j];
        uint32_t y = f[i + j + l];
        f[i + j] = info.add(x, y);
        f[i + j + l] = info.mul(info.sub(x, y), rt[j + l]);
      }
    }
  }
}

void NttTwistedNativeRadix2Info::intt_impl(uint32_t *f, std::size_t n,
                                           const uint32_t *roots) const {
  assert(std::has_single_bit(n));
  const mont32 info = this->info;
  for (std::size_t l = 1; l < n; l *= 2) {
    for (std::size_t i = 0; i < n; i += l * 2) {
      for (std::size_t j = 0; j < l; ++j) {
        uint32_t x = f[i + j];
        uint32_t y = info.mul(roots[j + l], f[i + j + l]);
        f[i + j] = info.add(x, y);
        f[i + j + l] = info.sub(x, y);
      }
    }
  }
  const uint32_t inv_n = inv_len[std::countr_zero(n)];
  for (std::size_t i = 0; i < n; ++i) {
    f[i] = info.mul(f[i], inv_n);
  }
}
void NttTwistedNativeRadix2Info::intt_irt(uint32_t *f, std::size_t n) const {
  assert(n <= irt.size());
  intt_impl(f, n, irt.data());
}

void NttTwistedNativeRadix2Info::intt(uint32_t *f, std::size_t n) const {
  assert(n <= rt.size());
  intt_impl(f, n, rt.data());
  std::reverse(f + 1, f + n);
}

NttTwistedAvxRadix2Info::NttTwistedAvxRadix2Info(mont32 info_)
    : NttTwistedNativeRadix2Info(info_), info8(info_) {
  uint32_t r[8]{};
  uint32_t ir[8]{};
  std::fill(r, r + 8, rt[2]);
  r[3] = r[7] = rt[3];
  rt2 = info8.load(r);
  std::fill(ir, ir + 8, irt[2]);
  ir[3] = ir[7] = irt[3];
  irt2 = info8.load(ir);

  std::fill(r, r + 8, rt[4]);
  r[5] = rt[5];
  r[6] = rt[6];
  r[7] = rt[7];
  rt4 = info8.load(r);
  std::fill(ir, ir + 8, irt[4]);
  ir[5] = irt[5];
  ir[6] = irt[6];
  ir[7] = irt[7];
  irt4 = info8.load(ir);
}
void NttTwistedAvxRadix2Info::prepare(std::size_t n) {
  NttTwistedNativeRadix2Info::prepare(n);
}

void NttTwistedAvxRadix2Info::ntt(uint32_t *f, std::size_t n) const {
  assert(std::has_single_bit(n));
  if (n < 16) {
    NttTwistedNativeRadix2Info::ntt(f, n);
    return;
  }
  assert(n % 16 == 0);
  assert(n <= rt.size());

  for (std::size_t l = n / 2; l >= 8; l /= 2) {
    for (std::size_t i = 0; i < n; i += l * 2) {
      for (std::size_t j = 0; j < l; j += 8) {
        __m256i fx = info8.load(f + i + j);
        __m256i fy = info8.load(f + i + j + l);
        info8.store(f + i + j, info8.add(fx, fy));
        info8.store(f + i + j + l, info8.mul(info8.sub(fx, fy),
                                             info8.load(rt.data() + j + l)));
      }
    }
  }

  for (std::size_t i = 0; i < n; i += 8) {
    __m256i fi = info8.load(f + i);
    fi = info8.add(info8.neg<0b11110000>(fi),
                   _mm256_permute2x128_si256(fi, fi, 0b01));
    fi = info8.mul(fi, rt4);
    fi = info8.add(info8.neg<0b11001100>(fi),
                   _mm256_shuffle_epi32(fi, 0b01001110));
    fi = info8.mul_odd<0b10001000>(fi, rt2);
    fi = info8.add(info8.neg<0b10101010>(fi),
                   _mm256_shuffle_epi32(fi, 0b10110001));
    info8.store(f + i, fi);
  }
}
void NttTwistedAvxRadix2Info::intt_impl(uint32_t *f, std::size_t n,
                                        const uint32_t *roots, __m256i root2,
                                        __m256i root4) const {
  assert(std::has_single_bit(n));
  assert(n % 16 == 0);

  const uint32_t inv_n = inv_len[std::countr_zero(n)];
  const __m256i inv8_n = _mm256_set1_epi32(int(inv_n));
  root4 = info8.mul(root4, inv8_n);

  for (std::size_t i = 0; i < n; i += 8) {
    __m256i fi = info8.load(f + i);
    fi = info8.add(info8.neg<0b10101010>(fi),
                   _mm256_shuffle_epi32(fi, 0b10110001));
    fi = info8.mul_odd<0b10001000>(fi, root2);
    fi = info8.add(info8.neg<0b11001100>(fi),
                   _mm256_shuffle_epi32(fi, 0b01001110));
    fi = info8.mul(fi, root4);
    fi = info8.add(info8.neg<0b11110000>(fi),
                   _mm256_permute2x128_si256(fi, fi, 0b01));
    info8.store(f + i, fi);
  }

  for (std::size_t l = 8; l < n; l *= 2) {
    for (std::size_t i = 0; i < n; i += l * 2) {
      for (std::size_t j = 0; j < l; j += 8) {
        __m256i fx = info8.load(f + i + j);
        __m256i fy =
            info8.mul(info8.load(f + i + j + l), info8.load(roots + j + l));
        info8.store(f + i + j, info8.add(fx, fy));
        info8.store(f + i + j + l, info8.sub(fx, fy));
      }
    }
  }
}

void NttTwistedAvxRadix2Info::intt_irt(uint32_t *f, std::size_t n) const {
  if (n < 16) {
    NttTwistedNativeRadix2Info::intt_irt(f, n);
    return;
  }
  assert(n <= irt.size());
  intt_impl(f, n, irt.data(), irt2, irt4);
}

void NttTwistedAvxRadix2Info::intt(uint32_t *f, std::size_t n) const {
  if (n < 16) {
    NttTwistedNativeRadix2Info::intt(f, n);
    return;
  }
  assert(n <= rt.size());
  intt_impl(f, n, rt.data(), rt2, rt4);
  std::reverse(f + 1, f + n);
}

NttTwistedAvxRadix4Info::NttTwistedAvxRadix4Info(mont32 info_)
    : NttTwistedAvxRadix2Info(info_) {}
void NttTwistedAvxRadix4Info::ntt(uint32_t *f, std::size_t n) const {
  assert(std::has_single_bit(n));
  assert(n % 16 == 0);
  assert(n <= rt.size());

  std::size_t l = n / 2;
  const bool n_4b = ((std::countr_zero(n) - 3) & 1) != 0;
  if (n_4b) {
    for (std::size_t i = 0; i < n; i += l * 2) {
      for (std::size_t j = 0; j < l; j += 8) {
        __m256i x = info8.load(f + i + j);
        __m256i y = info8.load(f + i + j + l);
        info8.store(f + i + j, info8.add(x, y));
        info8.store(f + i + j + l,
                    info8.mul(info8.sub(x, y), info8.load(rt.data() + l + j)));
      }
    }
    l >>= 1;
  }

  for (l /= 2; l >= 8; l /= 4) {
    for (std::size_t i = 0; i < n; i += l * 2 * 2) {
      for (std::size_t j = 0; j < l; j += 8) {
        __m256i x0 = info8.load(f + i + j);
        __m256i x1 = info8.load(f + i + j + l);
        __m256i x2 = info8.load(f + i + j + l * 2);
        __m256i x3 = info8.load(f + i + j + l * 3);

        __m256i s0 = info8.add(x0, x2);
        __m256i s1 = info8.add(x1, x3);
        __m256i d0 =
            info8.mul(info8.sub(x0, x2), info8.load(rt.data() + l * 2 + j));
        __m256i d1 =
            info8.mul(info8.sub(x1, x3), info8.load(rt.data() + l * 3 + j));
        __m256i tw = info8.load(rt.data() + l + j);

        info8.store(f + i + j, info8.add(s0, s1));
        info8.store(f + i + j + l, info8.mul(info8.sub(s0, s1), tw));
        info8.store(f + i + l * 2 + j, info8.add(d0, d1));
        info8.store(f + i + l * 3 + j, info8.mul(info8.sub(d0, d1), tw));
      }
    }
  }

  for (std::size_t i = 0; i < n; i += 8) {
    __m256i fi = info8.load(f + i);
    fi = info8.add(info8.neg<0b11110000>(fi),
                   _mm256_permute2x128_si256(fi, fi, 0b01));
    fi = info8.mul(fi, rt4);
    fi = info8.add(info8.neg<0b11001100>(fi),
                   _mm256_shuffle_epi32(fi, 0b01001110));
    fi = info8.mul_odd<0b10001000>(fi, rt2);
    fi = info8.add(info8.neg<0b10101010>(fi),
                   _mm256_shuffle_epi32(fi, 0b10110001));
    info8.store(f + i, fi);
  }
}

void NttTwistedAvxRadix4Info::intt_impl(uint32_t *f, std::size_t n,
                                        const uint32_t *roots, __m256i root2,
                                        __m256i root4) const {
  assert(std::has_single_bit(n));
  assert(n % 16 == 0);

  const uint32_t inv_n = inv_len[std::countr_zero(n)];
  const __m256i inv8_n = _mm256_set1_epi32(int(inv_n));
  root4 = info8.mul(root4, inv8_n);

  for (std::size_t i = 0; i < n; i += 8) {
    __m256i fi = info8.load(f + i);
    fi = info8.add(info8.neg<0b10101010>(fi),
                   _mm256_shuffle_epi32(fi, 0b10110001));
    fi = info8.mul_odd<0b10001000>(fi, root2);
    fi = info8.add(info8.neg<0b11001100>(fi),
                   _mm256_shuffle_epi32(fi, 0b01001110));
    fi = info8.mul(fi, root4);
    fi = info8.add(info8.neg<0b11110000>(fi),
                   _mm256_permute2x128_si256(fi, fi, 0b01));
    info8.store(f + i, fi);
  }

  const bool n_4b = ((std::countr_zero(n) - 3) & 1) != 0;
  std::size_t l = 8;
  for (; l < (n_4b ? n / 2 : n); l *= 4) {
    for (std::size_t i = 0; i < n; i += l * 2 * 2) {
      for (std::size_t j = 0; j < l; j += 8) {
        __m256i x0 = info8.load(f + i + j);
        __m256i x1 = info8.load(f + i + j + l);
        __m256i x2 = info8.load(f + i + j + l * 2);
        __m256i x3 = info8.load(f + i + j + l * 3);

        __m256i tw = info8.load(roots + l + j);
        __m256i y1 = info8.mul(x1, tw);
        __m256i y3 = info8.mul(x3, tw);
        __m256i s0 = info8.add(x0, y1);
        __m256i d0 = info8.sub(x0, y1);
        __m256i s1 = info8.add(x2, y3);
        __m256i d1 = info8.sub(x2, y3);
        __m256i z0 = info8.mul(s1, info8.load(roots + l * 2 + j));
        __m256i z1 = info8.mul(d1, info8.load(roots + l * 3 + j));

        info8.store(f + i + j, info8.add(s0, z0));
        info8.store(f + i + j + l, info8.add(d0, z1));
        info8.store(f + i + l * 2 + j, info8.sub(s0, z0));
        info8.store(f + i + l * 3 + j, info8.sub(d0, z1));
      }
    }
  }

  if (n_4b) {
    for (std::size_t i = 0; i < n; i += l * 2) {
      for (std::size_t j = 0; j < l; j += 8) {
        __m256i fx = info8.load(f + i + j);
        __m256i fy =
            info8.mul(info8.load(f + i + j + l), info8.load(roots + l + j));
        info8.store(f + i + j, info8.add(fx, fy));
        info8.store(f + i + j + l, info8.sub(fx, fy));
      }
    }
  }
}

void NttTwistedAvxRadix4Info::intt_irt(uint32_t *f, std::size_t n) const {
  assert(n <= irt.size());
  intt_impl(f, n, irt.data(), irt2, irt4);
}

void NttTwistedAvxRadix4Info::intt(uint32_t *f, std::size_t n) const {
  assert(n <= rt.size());
  intt_impl(f, n, rt.data(), rt2, rt4);
  std::reverse(f + 1, f + n);
}

struct ModInfo32x8 {
  mont32 info;
  mont32x8 info8;
  mutable std::vector<uint32_t> idx;
  mutable std::vector<uint32_t> inv;

  explicit ModInfo32x8(const mont32 &info_) : info(info_), info8(info_) {
    idx.resize(8);
    inv.resize(8);
    for (std::size_t i = 0; i < 8; ++i) {
      idx[i] = info.to_mont(uint32_t(i));
    }
    info8.store(inv.data(), info8.inv(info8.load(idx.data())));
  }

  void prepare(std::size_t n) const {
    if (n == 0) {
      return;
    }

    std::size_t target = idx.size();
    while (target < n) {
      target *= 2;
    }

    assert(idx.size() == inv.size());
    if (inv.size() < target) {
      const std::size_t old = inv.size();
      idx.resize(target);
      inv.resize(target);

      __m256i values = info8.load(idx.data() + old - 8);
      const __m256i step = _mm256_set1_epi32(int(info.to_mont(8)));
      __m256i product = _mm256_set1_epi32(int(info.one()));
      for (std::size_t i = old; i < target; i += 8) {
        assert(i + 7 < info.mod);
        values = info8.add(values, step);
        info8.store(idx.data() + i, values);
        product = info8.mul(product, values);
        info8.store(inv.data() + i, product);
      }

      __m256i inv_product = info8.inv(product);
      const __m256i one = _mm256_set1_epi32(int(info.one()));
      for (std::size_t i = target; i > old;) {
        i -= 8;
        const __m256i prefix = i == old ? one : info8.load(inv.data() + i - 8);
        const __m256i idxv = info8.load(idx.data() + i);
        info8.store(inv.data() + i, info8.mul(inv_product, prefix));
        inv_product = info8.mul(inv_product, idxv);
      }
    }
  }
};

struct AvxInfo {
  mont32 info;
  mutable NttTwistedAvxRadix4Info ntt_info;
  ModInfo32x8 mod_info;

  explicit AvxInfo(mont32 info_ = mont32::make())
      : info(info_), ntt_info(info), mod_info(info) {}

  void prepare_ntt(std::size_t n) const { ntt_info.prepare(n); }

  void ntt(uint32_t *f, std::size_t n) const {
    prepare_ntt(n);
    ntt_info.ntt(f, n);
  }

  void intt(uint32_t *f, std::size_t n) const {
    prepare_ntt(n);
    ntt_info.intt_irt(f, n);
  }

  void inv_n2(const uint32_t *f, uint32_t *out, std::size_t n) const;
  void inv_9_33e_4th(const uint32_t *f, uint32_t *out, std::size_t n) const;

  void ln_n2(const uint32_t *f, uint32_t *out, std::size_t n) const;

  void exp_n2(const uint32_t *f, uint32_t *out, std::size_t n) const;

  void pow_n2(const uint32_t *f, uint32_t *out, std::size_t n,
              uint64_t k) const;
  void pow_18e_block(const uint32_t *f, uint32_t *out, std::size_t n,
                     uint64_t k) const;
  void safe_pow(const uint32_t *f, uint32_t *out, std::size_t n,
                uint64_t k) const;
};

inline std::pair<std::size_t, std::size_t> pow_nt_block_len(std::size_t m) {
  const std::size_t target_blocks =
      std::max<std::size_t>(2, std::bit_width(m) - 1);
  const std::size_t n = std::bit_ceil((m - 1) / target_blocks + 1);
  const std::size_t u = (m - 1) / n + 1;
  return {n, u};
}

inline void ntt_block(const AvxInfo &ctx, const uint32_t *src,
                      std::size_t src_len, uint32_t *dst, std::size_t n) {
  std::copy_n(src, src_len, dst);
  std::fill_n(dst + src_len, n * 2 - src_len, 0);
  ctx.ntt(dst, n * 2);
}

inline void fold_adjacent_blocks(uint32_t *blocks, std::size_t u, std::size_t n,
                                 const mont32x8 &info8) {
  const std::size_t len = n * 2;
  for (std::size_t block = u - 1; block > 0; --block) {
    uint32_t *cur = blocks + block * len;
    const uint32_t *prev = cur - len;
    for (std::size_t i = 0; i < n; i += 8) {
      info8.store(cur + i,
                  info8.add(info8.load(cur + i), info8.load(prev + i)));
      info8.store(cur + n + i,
                  info8.sub(info8.load(cur + n + i), info8.load(prev + n + i)));
    }
  }
}

inline void block_convolution_from_pairs(uint32_t *out,
                                         const uint32_t *lhs_pairs,
                                         const uint32_t *rhs_blocks,
                                         std::size_t k, std::size_t n,
                                         const mont32x8 &info8) {
  const std::size_t len = n * 2;
  const uint32_t *first_pair = lhs_pairs + k * len;
  const uint32_t *first_rhs = rhs_blocks;
  for (std::size_t i = 0; i < n; i += 8) {
    info8.store(out + i, info8.mul(info8.load(first_pair + i),
                                   info8.load(first_rhs + i)));
    info8.store(out + n + i, info8.mul(info8.load(first_pair + n + i),
                                       info8.load(first_rhs + n + i)));
  }
  for (std::size_t j = 1; j < k; ++j) {
    const uint32_t *lhs_pair = lhs_pairs + (k - j) * len;
    const uint32_t *rhsj = rhs_blocks + j * len;
    for (std::size_t i = 0; i < n; i += 8) {
      const __m256i lo =
          info8.mul(info8.load(lhs_pair + i), info8.load(rhsj + i));
      info8.store(out + i, info8.add(info8.load(out + i), lo));
      const __m256i hi =
          info8.mul(info8.load(lhs_pair + n + i), info8.load(rhsj + n + i));
      info8.store(out + n + i, info8.add(info8.load(out + n + i), hi));
    }
  }
}

inline void low_product_with_fixed(const AvxInfo &ctx, const uint32_t *src,
                                   const uint32_t *fixed, uint32_t *out,
                                   std::size_t n) {
  const std::size_t len = n * 2;
  if (src != out) {
    std::copy_n(src, n, out);
  }
  std::fill_n(out + n, n, 0);
  ctx.ntt(out, len);
  const auto &info8 = ctx.ntt_info.info8;
  for (std::size_t i = 0; i < len; i += 8) {
    info8.store(out + i, info8.mul(info8.load(out + i), info8.load(fixed + i)));
  }
  ctx.intt(out, len);
}

void AvxInfo::inv_n2(const uint32_t *f, uint32_t *out, std::size_t n) const {
  assert(n > 0);
  const uint32_t inv_f0 = info.inv(f[0]);
  out[0] = inv_f0;
  for (std::size_t i = 1; i < n; ++i) {
    uint32_t sum = 0;
    for (std::size_t j = 1; j <= i; ++j) {
      sum = info.add(sum, info.mul(f[j], out[i - j]));
    }
    out[i] = info.mul(info.sub(0, sum), inv_f0);
  }
}

void AvxInfo::inv_9_33e_4th(const uint32_t *f, uint32_t *out,
                            std::size_t m) const {
  assert(m > 0);

  if (m <= 16) {
    inv_n2(f, out, m);
    return;
  }

  const std::size_t n = std::bit_ceil(m);
  prepare_ntt(n);

  auto *work = alloc<uint32_t>(n * 4);
  uint32_t *x = work;
  uint32_t *x_hat = x + n;
  uint32_t *f_hat = x_hat + n;
  uint32_t *a0_hat = f_hat + n;
  uint32_t *d_hat = a0_hat + n / 2;

  const std::size_t log_n = std::countr_zero(n);
  const std::size_t base = (log_n & 1) == 0 ? 16 : 8;
  inv_n2(f, x, std::min(base, m));

  const auto &info8 = ntt_info.info8;
  const __m256i zero8 = _mm256_setzero_si256();
  for (std::size_t t = base; t < n; t *= 4) {
    const std::size_t size = t * 4;
    std::copy_n(x, t, x_hat);
    std::fill_n(x_hat + t, size - t, 0);
    const std::size_t f_len = std::min(size, m);
    std::copy_n(f, f_len, f_hat);
    std::fill_n(f_hat + f_len, size - f_len, 0);

    ntt(x_hat, size);
    ntt(f_hat, size);
    for (std::size_t i = 0; i < size; i += 8) {
      info8.store(f_hat + i,
                  info8.mul(info8.load(f_hat + i), info8.load(x_hat + i)));
    }
    intt(f_hat, size);

    const uint32_t *a0 = f_hat + t;
    const uint32_t *a1 = f_hat + t * 2;
    const uint32_t *a2 = f_hat + t * 3;

    std::copy_n(a0, t, a0_hat);
    std::fill_n(a0_hat + t, t, 0);
    ntt(a0_hat, t * 2);
    for (std::size_t i = 0; i < t * 2; i += 8) {
      const __m256i a0i = info8.load(a0_hat + i);
      info8.store(d_hat + i, info8.mul(a0i, a0i));
    }
    intt(d_hat, t * 2);

    uint32_t *q0 = d_hat;
    uint32_t *q1 = d_hat + t;
    for (std::size_t i = 0; i < t; i += 8) {
      const __m256i a0i = info8.load(a0 + i);
      const __m256i a1i = info8.load(a1 + i);
      const __m256i q0i = info8.load(q0 + i);
      info8.store(f_hat + i, info8.sub(zero8, a0i));
      info8.store(f_hat + t + i, info8.sub(q0i, a1i));
      info8.store(f_hat + t * 2 + i,
                  info8.sub(info8.load(q1 + i), info8.load(a2 + i)));
      const __m256i delta = info8.sub(info8.add(a1i, a1i), q0i);
      info8.store(d_hat + i, delta);
    }
    std::fill_n(d_hat + t, t, 0);
    ntt(d_hat, t * 2);
    for (std::size_t i = 0; i < t * 2; i += 8) {
      info8.store(d_hat + i,
                  info8.mul(info8.load(a0_hat + i), info8.load(d_hat + i)));
    }
    intt(d_hat, t * 2);
    for (std::size_t i = 0; i < t; i += 8) {
      info8.store(f_hat + t * 2 + i, info8.add(info8.load(f_hat + t * 2 + i),
                                               info8.load(d_hat + i)));
    }
    std::fill_n(f_hat + t * 3, t, 0);

    ntt(f_hat, size);
    for (std::size_t i = 0; i < size; i += 8) {
      info8.store(f_hat + i,
                  info8.mul(info8.load(x_hat + i), info8.load(f_hat + i)));
    }
    intt(f_hat, size);
    if (m > t) {
      std::copy_n(f_hat, std::min(t * 3, m - t), x + t);
    }
  }

  std::copy_n(x, m, out);
  std::free(work);
}

void AvxInfo::ln_n2(const uint32_t *f, uint32_t *out, std::size_t n) const {
  assert(n > 0);

  mod_info.prepare(n);
  auto *q = alloc<uint32_t>(n);
  const uint32_t inv_f0 = info.inv(f[0]);
  const uint32_t *idx = mod_info.idx.data();
  const uint32_t *iv = mod_info.inv.data();
  for (std::size_t i = 0; i < n; ++i) {
    uint32_t sum = 0;
    for (std::size_t j = 1; j <= i; ++j) {
      sum = info.add(sum, info.mul(f[j], q[i - j]));
    }
    const uint32_t lhs = info.mul(f[i], idx[i]);
    q[i] = info.mul(info.sub(lhs, sum), inv_f0);
  }

  out[0] = 0;
  for (std::size_t i = 1; i < n; ++i) {
    out[i] = info.mul(q[i], iv[i]);
  }
  std::free(q);
}

void AvxInfo::exp_n2(const uint32_t *f, uint32_t *out, std::size_t n) const {
  assert(n > 0);
  assert(f[0] == 0);

  mod_info.prepare(n);
  const uint32_t *idx = mod_info.idx.data();
  const uint32_t *iv = mod_info.inv.data();
  out[0] = info.one();
  for (std::size_t i = 1; i < n; ++i) {
    uint32_t sum = 0;
    for (std::size_t j = 1; j <= i; ++j) {
      const uint32_t jf = info.mul(f[j], idx[j]);
      sum = info.add(sum, info.mul(jf, out[i - j]));
    }
    out[i] = info.mul(sum, iv[i]);
  }
}

void AvxInfo::pow_n2(const uint32_t *f, uint32_t *out, std::size_t n,
                     uint64_t k) const {
  assert(n > 0);
  if (k == 0) {
    out[0] = info.one();
    std::fill_n(out + 1, n - 1, 0);
    return;
  }
  assert(f[0] == info.one());

  auto *work = alloc<uint32_t>(n);
  ln_n2(f, work, n);
  const uint32_t k_mont = info.to_mont(uint32_t(k % info.mod));
  for (std::size_t i = 0; i < n; ++i) {
    work[i] = info.mul(work[i], k_mont);
  }
  exp_n2(work, out, n);
  std::free(work);
}

void AvxInfo::pow_18e_block(const uint32_t *f, uint32_t *out, std::size_t m,
                            uint64_t k) const {
  const auto &info = this->info;
  const auto &mod_info = this->mod_info;
  const auto &info8 = ntt_info.info8;

  assert(m > 0);
  if (k == 0) {
    out[0] = info.one();
    std::fill_n(out + 1, m - 1, 0);
    return;
  }
  assert(f[0] == info.one());
  if (m <= 16) {
    pow_n2(f, out, m, k);
    return;
  }
  assert(m % 8 == 0);

  const auto [n, u] = pow_nt_block_len(m);
  assert(n >= 8);
  prepare_ntt(n * 2);
  mod_info.prepare(n * u);

  auto *work = alloc<uint32_t>(n * u + n * 2 * (u * 3 + 3));
  uint32_t *g = work;
  uint32_t *nf = g + n * u;
  uint32_t *ndf = nf + n * 2 * u;
  uint32_t *ng = ndf + n * 2 * u;
  uint32_t *h = ng + n * 2 * u;
  uint32_t *psi = h + n * 2;
  uint32_t *phi = psi + n * 2;
  uint32_t *f0 = nf;
  uint32_t *g0 = ng;

  pow_18e_block(f, g, n, k);

  ntt_block(*this, f, std::min(n, m), f0, n);
  ntt_block(*this, g, n, g0, n);

  uint32_t *f0g0 = psi;
  std::copy_n(f0, n * 2, f0g0);
  for (std::size_t i = 0; i < n * 2; i += 8) {
    info8.store(f0g0 + i, info8.mul(info8.load(f0g0 + i), info8.load(g0 + i)));
  }
  intt(f0g0, n * 2);
  inv_9_33e_4th(f0g0, h, n);
  ntt_block(*this, h, n, h, n);

  const uint32_t *idx = mod_info.idx.data();
  for (std::size_t block = 0; block < u; ++block) {
    const std::size_t offset = block * n;
    const std::size_t src_len = offset < m ? std::min(n, m - offset) : 0;
    if (block != 0) {
      ntt_block(*this, f + offset, src_len, nf + block * n * 2, n);
    }
    assert(src_len % 8 == 0);
    uint32_t *delta_f = ndf + block * n * 2;
    for (std::size_t i = 0; i < src_len; i += 8) {
      info8.store(delta_f + i, info8.mul(info8.load(f + offset + i),
                                         info8.load(idx + offset + i)));
    }
    std::fill_n(delta_f + src_len, n * 2 - src_len, 0);
    ntt(delta_f, n * 2);
  }
  fold_adjacent_blocks(nf, u, n, info8);
  fold_adjacent_blocks(ndf, u, n, info8);

  const uint32_t k_plus_one =
      info.to_mont(uint32_t((k % info.mod + 1) % info.mod));
  const __m256i k_plus_one8 = _mm256_set1_epi32(int(k_plus_one));
  for (std::size_t block = 1; block < u; ++block) {
    const std::size_t offset = block * n;
    if (block > 1) {
      ntt_block(*this, g + offset - n, n, ng + (block - 1) * n * 2, n);
    }

    block_convolution_from_pairs(psi, nf, ng, block, n, info8);
    block_convolution_from_pairs(phi, ndf, ng, block, n, info8);
    intt(psi, n * 2);
    intt(phi, n * 2);

    uint32_t *rho = psi;
    for (std::size_t i = 0; i < n; i += 8) {
      const __m256i lhs = info8.mul(info8.load(phi + i), k_plus_one8);
      const __m256i rhs =
          info8.mul(info8.load(psi + i), info8.load(idx + offset + i));
      info8.store(rho + i, info8.sub(lhs, rhs));
    }

    uint32_t *v = phi;
    low_product_with_fixed(*this, rho, h, v, n);
    const uint32_t *inv = mod_info.inv.data();
    for (std::size_t i = 0; i < n; i += 8) {
      info8.store(v + i,
                  info8.mul(info8.load(v + i), info8.load(inv + offset + i)));
    }
    uint32_t *u_block = v;
    uint32_t *g_block = rho;
    low_product_with_fixed(*this, u_block, g0, g_block, n);

    std::copy_n(g_block, n, g + offset);
  }

  std::copy_n(g, m, out);
  std::free(work);
}

void AvxInfo::safe_pow(const uint32_t *f, uint32_t *out, std::size_t n,
                       uint64_t k) const {
  if (n == 0) {
    return;
  }
  assert(n < 8 || n % 8 == 0);
  const auto &info8 = ntt_info.info8;
  const __m256i zero = _mm256_setzero_si256();
  if (k == 0) {
    std::fill_n(out, n, 0);
    out[0] = info.one();
    return;
  }

  std::size_t lead = 0;
  if (n >= 8) {
    for (; lead < n; lead += 8) {
      const __m256i v = info8.load(f + lead);
      const unsigned zero_mask = unsigned(
          _mm256_movemask_ps(_mm256_castsi256_ps(_mm256_cmpeq_epi32(v, zero))));
      if (zero_mask != 0xffu) {
        lead += std::countr_zero((~zero_mask) & 0xffu);
        break;
      }
    }
  } else {
    while (lead < n && f[lead] == 0) {
      ++lead;
    }
  }
  if (lead == n || (lead != 0 && k > (n - 1) / lead)) {
    std::fill_n(out, n, 0);
    return;
  }

  const std::size_t shift = std::size_t(k) * lead;
  const std::size_t len = n - shift;
  const std::size_t work_len = len < 8 ? len : (len + 7) & ~std::size_t(7);
  auto *work = alloc<uint32_t>(work_len * 2);
  uint32_t *x = work;
  uint32_t *y = x + work_len;

  const uint32_t f0 = f[lead];
  const uint32_t inv_f0 = info.inv(f0);
  const uint32_t f0k = info.pow(f0, k);
  const std::size_t src_len = std::min(work_len, n - lead);
  std::copy_n(f + lead, src_len, x);
  std::fill_n(x + src_len, work_len - src_len, 0);

  const __m256i inv_f0_8 = _mm256_set1_epi32(int(inv_f0));
  std::size_t i = 0;
  for (; i + 8 <= work_len; i += 8) {
    info8.store(x + i, info8.mul(info8.load(x + i), inv_f0_8));
  }
  for (; i < work_len; ++i) {
    x[i] = info.mul(x[i], inv_f0);
  }

  pow_18e_block(x, y, work_len, k);

  std::fill_n(out, shift, 0);
  const __m256i f0k_8 = _mm256_set1_epi32(int(f0k));
  i = 0;
  if (len >= 8) {
    for (; i < len; i += 8) {
      info8.store(out + shift + i, info8.mul(info8.load(y + i), f0k_8));
    }
  } else {
    for (; i < len; ++i) {
      out[shift + i] = info.mul(y[i], f0k);
    }
  }

  std::free(work);
}

class FastI {
  static constexpr std::size_t table_size = 0x10000;
  static inline const std::array<std::uint32_t, table_size> table = [] {
    std::array<std::uint32_t, table_size> t;
    t.fill(0xffffffffu);
    for (std::uint32_t hi = 0; hi < 0x100; ++hi) {
      for (std::uint32_t lo = 0; lo < 10; ++lo) {
        const std::uint32_t key = (hi << 8) | (lo | '0');
        t[key] = ('0' <= hi && hi <= '9') ? lo * 10 + hi - '0' : lo | 0x100;
      }
    }
    return t;
  }();

public:
  explicit FastI(FILE *file) {
    const int fd = fileno(file);
    fstat(fd, &stat_);
    size_ = std::size_t(stat_.st_size);
    data_ = static_cast<const char *>(
        mmap(nullptr, size_, PROT_READ, MAP_PRIVATE, fd, 0));
    ptr_ = data_;
    end_ = data_ + size_;
    madvise(const_cast<char *>(data_), size_, MADV_SEQUENTIAL);
  }

  ~FastI() { munmap(const_cast<char *>(data_), size_); }

  FastI &operator>>(std::uint32_t &x) {
    x = std::uint32_t(read_u64());
    return *this;
  }

  FastI &operator>>(std::uint64_t &x) {
    x = read_u64();
    return *this;
  }

private:
  std::uint64_t read_u64() {
    std::uint8_t c = std::uint8_t(*ptr_++ - '0');
    while (c > 9) {
      c = std::uint8_t(*ptr_++ - '0');
    }

    std::uint64_t x = c;
    while (ptr_ + 1 < end_) {
      std::uint16_t key;
      std::memcpy(&key, ptr_, sizeof(key));
      const std::uint32_t y = table[key];
      ptr_ += 2;
      if (y < 100) {
        x = x * 100 + y;
      } else {
        if (y < 0x1000) {
          x = x * 10 + y - 0x100;
        } else {
          --ptr_;
        }
        return x;
      }
    }
    while (ptr_ < end_) {
      const std::uint8_t d = std::uint8_t(*ptr_ - '0');
      if (d > 9) {
        return x;
      }
      x = x * 10 + d;
      ++ptr_;
    }
    return x;
  }

  struct stat stat_{};
  std::size_t size_ = 0;
  const char *data_ = nullptr;
  const char *ptr_ = nullptr;
  const char *end_ = nullptr;
};

class FastO {
  static constexpr std::size_t table_size = 10000;
  static constexpr std::uint32_t e4 = table_size;
  static constexpr std::uint32_t e8 = 100000000;
  static inline const std::array<std::uint32_t, table_size> table = [] {
    std::array<std::uint32_t, table_size> t{};
    for (std::uint32_t i = 0; i < t.size(); ++i) {
      std::uint32_t x = i;
      for (int j = 0; j < 4; ++j) {
        t[i] = (t[i] << 8) | (x % 10) | '0';
        x /= 10;
      }
    }
    return t;
  }();

public:
  explicit FastO(FILE *file, std::size_t size = 1 << 20)
      : file_(file), data_(new char[size]), ptr_(data_),
        end_(data_ + size - 16) {}

  ~FastO() {
    flush();
    delete[] data_;
  }

  FastO &operator<<(char c) {
    *ptr_++ = c;
    if (ptr_ > end_) {
      flush();
    }
    return *this;
  }

  FastO &operator<<(std::uint32_t x) {
    write_u32(x);
    if (ptr_ > end_) {
      flush();
    }
    return *this;
  }

private:
  void flush() {
    std::fwrite(data_, 1, ptr_ - data_, file_);
    ptr_ = data_;
  }

  void output4(std::uint32_t x) {
    const char *s = reinterpret_cast<const char *>(&table[x]);
    if (x >= 100) {
      if (x >= 1000) {
        std::memcpy(ptr_, s, 4);
        ptr_ += 4;
      } else {
        std::memcpy(ptr_, s + 1, 3);
        ptr_ += 3;
      }
    } else if (x >= 10) {
      std::memcpy(ptr_, s + 2, 2);
      ptr_ += 2;
    } else {
      *ptr_++ = char(x | '0');
    }
  }

  void write_u32(std::uint32_t x) {
    if (x >= e8) {
      const std::uint32_t q = x / e8;
      const std::uint32_t r = x % e8;
      output4(q);
      std::memcpy(ptr_, &table[r / e4], 4);
      ptr_ += 4;
      std::memcpy(ptr_, &table[r % e4], 4);
      ptr_ += 4;
    } else if (x >= e4) {
      output4(x / e4);
      std::memcpy(ptr_, &table[x % e4], 4);
      ptr_ += 4;
    } else {
      output4(x);
    }
  }

  FILE *file_;
  char *data_;
  char *ptr_;
  char *end_;
};

int main() {
  FastI fin(stdin);
  FastO fout(stdout);

  std::uint32_t input_n;
  std::uint64_t k;
  fin >> input_n >> k;
  const std::size_t n = input_n;

  const auto info = mont32::make();
  const AvxInfo pow_info(info);
  const auto &info8 = pow_info.ntt_info.info8;
  const std::size_t len = (n + 7) & ~std::size_t(7);
  std::vector<std::uint32_t> f(len), out(len + 8);
  for (std::size_t i = 0; i < n; ++i) {
    fin >> f[i];
  }
  for (std::size_t i = 0; i < len; i += 8) {
    info8.store(f.data() + i, info8.to_mont(info8.load(f.data() + i)));
  }

  pow_info.safe_pow(f.data(), out.data(), len, k);
  for (std::size_t i = 0; i < len; i += 8) {
    info8.store(out.data() + i, info8.from_mont(info8.load(out.data() + i)));
  }
  for (std::size_t i = 0; i < n; ++i) {
    fout << out[i] << ' ';
  }
  fout << '\n';
  return 0;
}
