// Generated by tools/bundle.py from problems/convolution/convolution_F_2_64/solution.cpp. Edit that file instead.
// c = a * b over F = F_2[x] / (x^64 + x^4 + x^3 + x + 1), by the additive FFT of Lin, Chung and
// Han (novel polynomial basis) on a Cantor basis beta_0 = 1, beta_{i+1}^2 + beta_{i+1} = beta_i.
//
// With W_i = span(beta_0, ..., beta_{i-1}) and s_i the subspace polynomial of W_i, the novel basis
// is X_j = prod s_i^{j_i} over the bits j_i of j. On a Cantor basis s_i(beta_i) = 1 and
// s_{2^k}(x) = x^{2^{2^k}} + x, so the change from the monomial basis to X takes XORs only
// (Taylor expansions in x^tau + x). The transform evaluates f = sum d_j X_j at omega_k =
// sum_{bits of k} beta_b, k < 2^l; stage i uses the twiddle s_i(omega_c) = omega_{c >> i} for the
// block at c.
#include <sys/mman.h>
#include <unistd.h>

#include <array>
#include <bit>
#include <utility>

// lib/io/bulk64.hpp
// Bulk read of uint64 arrays with AVX2, on top of io::Reader:
//
//   io::Reader in;
//   io::read_bulk(in, a.data(), n);  // same values as in.read(a.data(), n), faster
//
// Kept apart from io.hpp so that the code of the programs that do not need it stays unchanged.
// Design and measurements: lib/io/notes.md.

// lib/io/io.hpp
// Fast integer and text I/O on file descriptors (stdin and stdout by default).
// Linux, x86-64 with AVX2. Design and measurements: lib/io/notes.md.
//
//   io::Reader in;                            // takes all of stdin
//   io::Writer out;                           // flushes in its destructor
//   const auto n = in.read<std::uint32_t>();
//   std::vector<std::uint32_t> a(n);
//   in.read(a.data(), n);                     // bulk; AVX2 for uint32_t
//   const auto s = in.read<std::uint64_t, 16>();  // promise: at most 16 digits (faster)
//   out.write("n = ", n, '\n');               // any mix of integers, chars, strings
//   out.write<16>(s, '\n');                   // promise: integers of at most 16 digits
//   out.write_array(a.data(), n, ' ');        // bulk; AVX2 for uint32_t
//   out.write('\n');
//
// Input: tokens separated by whitespace (any bytes <= ' '). Integer tokens are an optional '-'
// (signed types only) followed by decimal digits, and fit the requested type. Reading past the
// last token is undefined. The 64 bytes before the input and after its end are readable zeros, so
// custom parsers may load up to 64 bytes around any token from word().

#include <fcntl.h>
#include <immintrin.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>

#include <algorithm>
#include <array>
#include <bit>
#include <cerrno>
#include <concepts>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <string_view>
#include <type_traits>

namespace io {
namespace detail {

// Zero bytes before and after the input. Loads reach at most 63 bytes past either end.
inline constexpr std::size_t kPadding = 64;
inline constexpr std::size_t kPage = 4096;

// Input as mapped or read: data [start, end), kPadding zero bytes before and after it.
struct Input {
    char* base;           // allocation or mapping to release
    std::size_t mapped;   // bytes mapped, or 0 for a heap buffer
    const char* start;
    const char* end;
};

inline Input map_input(int fd, std::size_t size) {
    const off_t offset = ::lseek(fd, 0, SEEK_CUR);
    if (offset < 0 || std::size_t(offset) >= size) return {};
    // One anonymous zero page before the file. After it, the rest of the last file page reads as
    // zero; if fewer than kPadding bytes remain, one more anonymous page follows.
    const std::size_t file_bytes = (size + kPage - 1) & ~(kPage - 1);
    const std::size_t mapped = kPage + file_bytes + (file_bytes - size < kPadding ? kPage : 0);
    void* base = ::mmap(nullptr, mapped, PROT_READ, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    if (base == MAP_FAILED) return {};
    char* const file = static_cast<char*>(base) + kPage;
    if (::mmap(file, file_bytes, PROT_READ, MAP_PRIVATE | MAP_FIXED, fd, 0) == MAP_FAILED) {
        ::munmap(base, mapped);
        return {};
    }
    return {static_cast<char*>(base), mapped, file + offset, file + size};
}

// Capacity bytes for data, with kPadding bytes before and after; returns the data start.
inline char* allocate(std::size_t capacity) {
    auto* p = static_cast<char*>(std::aligned_alloc(64, capacity + 2 * kPadding));
    if (!p) std::abort();
    std::memset(p, 0, kPadding);
    return p + kPadding;
}

// Reads fd until end of file, or until size bytes for a regular file of that size.
inline Input read_input(int fd, std::size_t size = std::size_t(-1)) {
    std::size_t done = 0, capacity = std::size_t(1) << 16;
    char* data = allocate(capacity);
    while (done < size) {
        if (done == capacity) {
            char* bigger = allocate(capacity *= 2);
            std::memcpy(bigger, data, done);
            std::free(data - kPadding);
            data = bigger;
        }
        const ssize_t got = ::read(fd, data + done, capacity - done);
        if (got > 0) done += std::size_t(got);
        else if (got == 0) break;
        else if (errno != EINTR) std::abort();
    }
    std::memset(data + done, 0, kPadding);
    return {data - kPadding, 0, data, data + done};
}

// Files over kMapAbove bytes are mapped; smaller ones and other inputs are read, which takes
// fewer system calls.
inline constexpr std::size_t kMapAbove = std::size_t(1) << 16;

inline Input open_input(int fd) {
    struct stat st;
    if (::fstat(fd, &st) == 0 && S_ISREG(st.st_mode)) {
        const auto size = std::size_t(st.st_size);
        if (size <= kMapAbove) return read_input(fd, size);
        if (const Input input = map_input(fd, size); input.base) return input;
    }
    return read_input(fd);
}

inline void release(const Input& input) {
    if (input.mapped) ::munmap(input.base, input.mapped);
    else std::free(input.base);
}

// Bit i set iff byte i is whitespace (<= ' ').
inline unsigned separators(__m128i bytes) {
    return unsigned(_mm_movemask_epi8(_mm_cmpgt_epi8(_mm_set1_epi8(' ' + 1), bytes)));
}

inline std::uint32_t separators(__m256i bytes) {
    return std::uint32_t(_mm256_movemask_epi8(_mm256_cmpgt_epi8(_mm256_set1_epi8(' ' + 1), bytes)));
}

// Separators in the 64-byte aligned block.
inline std::uint64_t block_separators(const char* block) {
    const std::uint64_t low = separators(_mm256_load_si256(reinterpret_cast<const __m256i*>(block)));
    const std::uint64_t high = separators(_mm256_load_si256(reinterpret_cast<const __m256i*>(block + 32)));
    return low | high << 32;
}

// The 16 bytes at kRightAlign[n + 1] move the first n bytes (1 <= n <= 16) of a 16-byte window
// to its end and zero the rest: byte k + 1 is k - 16 for 16 <= k < 32, else -128. For the other
// lengths (-1, 0, 17..32) byte 15 of the window is negative, which marks the token as invalid.
alignas(64) inline constexpr auto kRightAlign = [] {
    std::array<std::int8_t, 64> t{};
    for (int k = -1; k < 63; ++k) t[k + 1] = k >= 16 && k < 32 ? std::int8_t(k - 16) : std::int8_t(-128);
    return t;
}();

// Shuffle control for a token of length index - 1.
inline __m128i align_row(std::size_t index) {
    return _mm_loadu_si128(reinterpret_cast<const __m128i*>(kRightAlign.data() + index));
}

// Right-aligned digits (byte values 0..9) -> 4-digit groups, one per dword.
inline __m128i digit_groups(__m128i digits) {
    return _mm_madd_epi16(_mm_maddubs_epi16(digits, _mm_set1_epi16(0x010A)), _mm_set1_epi32(0x00010064));
}

inline __m256i digit_groups(__m256i digits) {
    return _mm256_madd_epi16(_mm256_maddubs_epi16(digits, _mm256_set1_epi16(0x010A)), _mm256_set1_epi32(0x00010064));
}

// Value of the first n digits (0 <= n <= 16) of the window. Result < 10^16.
inline std::uint64_t parse16(__m128i window, unsigned n) {
    const __m128i digits = _mm_shuffle_epi8(_mm_subs_epu8(window, _mm_set1_epi8('0')), align_row(n + 1));
    const __m128i groups = digit_groups(digits);
    const __m128i halves = _mm_madd_epi16(_mm_packus_epi32(groups, groups), _mm_set1_epi32(0x00012710));
    const auto both = std::uint64_t(_mm_cvtsi128_si64(halves));  // 8-digit halves, high one first
    return (both & 0xFFFFFFFF) * 100000000 + (both >> 32);
}

// kKeep[32 - k..64 - k) keeps the last k bytes of 32.
alignas(64) inline constexpr auto kKeep = [] {
    std::array<std::uint8_t, 64> t{};
    for (std::size_t i = 32; i < 64; ++i) t[i] = 0xFF;
    return t;
}();

// Value of the n <= 16 digits that end at end. Bytes below '0' before them (a sign) count as 0.
inline std::uint64_t parse_ending16(const char* end, unsigned n) {
    const __m128i bytes = _mm_loadu_si128(reinterpret_cast<const __m128i*>(end - 16));
    const __m128i keep = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kKeep.data() + 16 + n));
    const __m128i groups = digit_groups(_mm_and_si128(_mm_subs_epu8(bytes, _mm_set1_epi8('0')), keep));
    const __m128i halves = _mm_madd_epi16(_mm_packus_epi32(groups, groups), _mm_set1_epi32(0x00012710));
    const auto both = std::uint64_t(_mm_cvtsi128_si64(halves));  // 8-digit halves, high one first
    return (both & 0xFFFFFFFF) * 100000000 + (both >> 32);
}

// Value of the n <= 24 digits that end at end; at most 20 for a result below 2^64.
inline std::uint64_t parse_ending24(const char* end, unsigned n) {
    const __m256i bytes = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(end - 32));
    const __m256i keep = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(kKeep.data() + n));
    const __m256i groups = digit_groups(_mm256_and_si256(_mm256_subs_epu8(bytes, _mm256_set1_epi8('0')), keep));
    // 8-digit quarters; the first is 0. Dword 1 of the low lane, dwords 0 and 1 of the high lane.
    const __m256i quarters = _mm256_madd_epi16(_mm256_packus_epi32(groups, groups), _mm256_set1_epi32(0x00012710));
    const std::uint64_t high = std::uint64_t(_mm256_extract_epi64(quarters, 0)) >> 32;
    const auto low = std::uint64_t(_mm256_extract_epi64(quarters, 2));
    return (high * 100000000 + (low & 0xFFFFFFFF)) * 100000000 + (low >> 32);
}

// kQuad[x] for x < 10^4: its 4 digits with leading zeros, first digit in the lowest byte.
alignas(64) inline constexpr auto kQuad = [] {
    std::array<std::uint32_t, 10000> t{};
    for (std::uint32_t x = 0; x < t.size(); ++x)
        t[x] = ('0' + x / 1000) | ('0' + x / 100 % 10) << 8 | ('0' + x / 10 % 10) << 16 | ('0' + x % 10) << 24;
    return t;
}();

// Digits of x (x >= 1) = (x + kDigitCount32[floor(log2(x))]) >> 32: the low word of an entry
// carries into the high word exactly when x reaches the next power of ten.
inline constexpr auto kDigitCount32 = [] {
    std::array<std::uint64_t, 32> t{};
    for (int i = 0; i < 32; ++i) {
        const std::uint64_t low = std::uint64_t(1) << i, high = 2 * low - 1;
        std::uint64_t digits = 0, power = 1;
        while (power <= low) power *= 10, ++digits;
        t[i] = (digits << 32) + (power <= high ? (std::uint64_t(1) << 32) - power : 0);
    }
    return t;
}();

inline unsigned digit_count(std::uint32_t x) {
    return unsigned((x + kDigitCount32[31 - std::countl_zero(x | 1)]) >> 32);
}

// Digits of x = kDigitCount64[0][b] + (x > kDigitCount64[1][b]), where b = bit width of x | 1.
inline constexpr auto kDigitCount64 = [] {
    std::array<std::array<std::uint64_t, 65>, 2> t{};
    for (int b = 1; b <= 64; ++b) {
        const unsigned __int128 low = (unsigned __int128)1 << (b - 1), high = 2 * low - 1;
        std::uint64_t digits = 1;
        unsigned __int128 power = 10;
        while (power <= low) power *= 10, ++digits;
        t[0][b] = digits;
        t[1][b] = power <= high ? std::uint64_t(power - 1) : ~std::uint64_t(0);
    }
    return t;
}();

inline unsigned digit_count(std::uint64_t x) {
    const int b = std::bit_width(x | 1);
    return unsigned(kDigitCount64[0][b] + (x > kDigitCount64[1][b]));
}

// Bytes kShiftWindow[k..k + 16) shuffle a vector down by k bytes.
alignas(32) inline constexpr std::int8_t kShiftWindow[32] = {0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  10,
                                                             11, 12, 13, 14, 15, -1, -1, -1, -1, -1, -1,
                                                             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1};

inline __m128i shift_down(__m128i v, unsigned k) {
    return _mm_shuffle_epi8(v, _mm_loadu_si128(reinterpret_cast<const __m128i*>(kShiftWindow + k)));
}

// Writes x in decimal at p and returns the end. Stores 16 bytes.
inline char* format(char* p, std::uint32_t x) {
    // Twelve digits with leading zeros, as three groups of four, then shifted down past the zeros.
    const std::uint32_t top = x / 100000000, rest = x % 100000000;
    const std::uint32_t high = rest / 10000, low = rest % 10000;
    const __m128i digits = _mm_insert_epi32(
        _mm_cvtsi64_si128(std::int64_t(kQuad[top] | std::uint64_t(kQuad[high]) << 32)), int(kQuad[low]), 2);
    const unsigned n = digit_count(x);
    _mm_storeu_si128(reinterpret_cast<__m128i*>(p), shift_down(digits, 12 - n));
    return p + n;
}

// high, low < 10^8 as 16 digits with leading zeros.
inline __m128i sixteen_digits(std::uint32_t high, std::uint32_t low) {
    return _mm_set_epi64x(std::int64_t(kQuad[low / 10000] | std::uint64_t(kQuad[low % 10000]) << 32),
                          std::int64_t(kQuad[high / 10000] | std::uint64_t(kQuad[high % 10000]) << 32));
}

// Writes x in decimal at p and returns the end. Stores up to 20 bytes. MaxDigits <= 16 promises
// x < 10^16, which saves a division.
template <int MaxDigits>
inline char* format64(char* p, std::uint64_t x) {
    const std::uint64_t q = x / 100000000;  // < 1.9 * 10^11
    const auto low = std::uint32_t(x - q * 100000000);
    const unsigned n = digit_count(x);
    if constexpr (MaxDigits <= 16) {
        _mm_storeu_si128(reinterpret_cast<__m128i*>(p), shift_down(sixteen_digits(std::uint32_t(q), low), 16 - n));
        return p + n;
    } else {
        // Twenty digits with leading zeros: a head of four, then sixteen.
        const auto top = std::uint32_t(q / 100000000);  // < 1845
        const auto middle = std::uint32_t(q - std::uint64_t(top) * 100000000);
        const unsigned head = n > 16 ? n - 16 : 0;
        const auto head_digits = std::uint32_t(std::uint64_t(kQuad[top]) >> (32 - 8 * head));
        std::memcpy(p, &head_digits, 4);
        _mm_storeu_si128(reinterpret_cast<__m128i*>(p + head), shift_down(sixteen_digits(middle, low), 16 - (n - head)));
        return p + n;
    }
}

// floor(x / d) for every dword x, as (x * Magic) >> Shift. The test checks each use exhaustively.
template <std::uint32_t Magic, int Shift>
inline __m256i divide(__m256i x) {
    const __m256i magic = _mm256_set1_epi64x(Magic);
    const __m256i even = _mm256_srli_epi64(_mm256_mul_epu32(x, magic), Shift);
    const __m256i odd = _mm256_srli_epi64(_mm256_mul_epu32(_mm256_srli_epi64(x, 32), magic), Shift);
    return _mm256_blend_epi32(even, _mm256_slli_epi64(odd, 32), 0xAA);
}

// Each dword g < 10^4 -> its 4 ASCII digits, first digit in the lowest byte.
inline __m256i quad_digits(__m256i g) {
    const __m256i high = _mm256_srli_epi16(_mm256_mulhi_epu16(g, _mm256_set1_epi16(5243)), 3);  // g / 100
    const __m256i low = _mm256_sub_epi16(g, _mm256_mullo_epi16(high, _mm256_set1_epi16(100)));
    const __m256i pairs = _mm256_or_si256(high, _mm256_slli_epi32(low, 16));  // 16-bit halves < 100
    const __m256i tens = _mm256_mulhi_epu16(pairs, _mm256_set1_epi16(6554));  // pair / 10
    const __m256i units = _mm256_sub_epi16(pairs, _mm256_mullo_epi16(tens, _mm256_set1_epi16(10)));
    return _mm256_or_si256(_mm256_or_si256(tens, _mm256_slli_epi16(units, 8)), _mm256_set1_epi8('0'));
}

// Digit counts of the eight dwords of v, one per byte in order.
inline std::uint64_t digit_counts(__m256i v) {
    // Unsigned v >= 10^k via a signed compare after flipping the sign bits; summed as a tree.
    const __m256i x = _mm256_xor_si256(v, _mm256_set1_epi32(int(0x80000000)));
    const auto at_least = [&](std::uint32_t power) {
        return _mm256_cmpgt_epi32(x, _mm256_set1_epi32(int((power - 1) ^ 0x80000000)));
    };
    const __m256i a = _mm256_add_epi32(_mm256_add_epi32(at_least(10), at_least(100)),
                                       _mm256_add_epi32(at_least(1000), at_least(10000)));
    const __m256i b = _mm256_add_epi32(_mm256_add_epi32(at_least(100000), at_least(1000000)),
                                       _mm256_add_epi32(at_least(10000000), at_least(100000000)));
    const __m256i n = _mm256_sub_epi32(_mm256_sub_epi32(_mm256_set1_epi32(1), at_least(1000000000)),
                                       _mm256_add_epi32(a, b));
    const __m256i bytes = _mm256_packus_epi16(_mm256_packus_epi32(n, n), n);  // per lane: 4 counts first
    return std::uint64_t(_mm256_extract_epi32(bytes, 0)) | std::uint64_t(_mm256_extract_epi32(bytes, 4)) << 32;
}

// Stores the two 16-byte lanes of w, values of 12 digits with leading zeros and a separator, as
// their last n0 and n1 digits and the separator. Returns the end; stores 16 bytes per lane.
inline char* put_pair(char* p, __m256i w, unsigned n0, unsigned n1) {
    const __m256i shifted = _mm256_shuffle_epi8(w, _mm256_loadu2_m128i(
        reinterpret_cast<const __m128i*>(kShiftWindow + 12 - n1), reinterpret_cast<const __m128i*>(kShiftWindow + 12 - n0)));
    _mm_storeu_si128(reinterpret_cast<__m128i*>(p), _mm256_castsi256_si128(shifted));
    p += n0 + 1;
    _mm_storeu_si128(reinterpret_cast<__m128i*>(p), _mm256_extracti128_si256(shifted, 1));
    return p + n1 + 1;
}

// Writes the eight dwords of v in decimal, each followed by separator, and returns the end.
// Stores up to 15 bytes past the end.
inline char* format8(char* p, __m256i v, char separator) {
    // Digit counts first, from v: the store addresses then do not wait for the digits.
    const std::uint64_t n = digit_counts(v);
    // Lanes [v0 v2 v4 v6 | v1 v3 v5 v7], so the transpose below pairs consecutive values.
    v = _mm256_permutevar8x32_epi32(v, _mm256_setr_epi32(0, 2, 4, 6, 1, 3, 5, 7));
    const __m256i top = divide<1441151881, 57>(v);  // v / 10^8
    const __m256i rest = _mm256_sub_epi32(v, _mm256_mullo_epi32(top, _mm256_set1_epi32(100000000)));
    const __m256i high = divide<3518437209, 45>(rest);  // rest / 10^4
    const __m256i low = _mm256_sub_epi32(rest, _mm256_madd_epi16(high, _mm256_set1_epi32(10000)));
    const __m256i t = quad_digits(top), h = quad_digits(high), l = quad_digits(low);
    const __m256i s = _mm256_set1_epi32(static_cast<unsigned char>(separator));
    // Transpose: each 16-byte lane becomes one value as dwords [top, high, low, separator].
    const __m256i th_low = _mm256_unpacklo_epi32(t, h), th_high = _mm256_unpackhi_epi32(t, h);
    const __m256i ls_low = _mm256_unpacklo_epi32(l, s), ls_high = _mm256_unpackhi_epi32(l, s);
    const auto count = [n](int i) { return unsigned(n >> 8 * i & 0xFF); };
    p = put_pair(p, _mm256_unpacklo_epi64(th_low, ls_low), count(0), count(1));
    p = put_pair(p, _mm256_unpackhi_epi64(th_low, ls_low), count(2), count(3));
    p = put_pair(p, _mm256_unpacklo_epi64(th_high, ls_high), count(4), count(5));
    return put_pair(p, _mm256_unpackhi_epi64(th_high, ls_high), count(6), count(7));
}

// Parses uint32 tokens from the token at p into dst: at most count, from input that is valid up
// to limit. Stops when fewer than kMinTokens tokens or 1 KiB of input remain. Returns where it
// stopped and the tokens parsed. Each chunk of input is cut
// into four streams at token boundaries. The streams advance in lockstep, two tokens per step, so
// four independent pointer chains overlap.
class BulkParser {
public:
    static constexpr std::size_t kMinTokens = 1024;

    struct Result {
        const char* end;
        std::size_t parsed;
    };

    static Result parse(const char* p, const char* limit, std::uint32_t* dst, std::size_t count) {
        std::uint32_t* const first = dst;
        while (count >= kMinTokens && limit - p >= 1024 + 64) {
            // With tokens of at most 16 bytes a chunk spans at most chunk + 33 bytes, so it holds
            // at most chunk / 2 + 17 < count tokens: all of them belong to this array. It ends
            // before limit.
            const std::size_t chunk =
                std::min({kChunk, 2 * (count - 32), std::size_t(limit - p) - 64}) & ~std::size_t(3);
            const std::size_t stream = chunk / 4;
            const char* s[4] = {p, after_separator(p + stream), after_separator(p + 2 * stream),
                                after_separator(p + 3 * stream)};
            const char* const end[4] = {s[1], s[2], s[3], after_separator(p + chunk)};
            std::uint32_t* const out[4] = {dst, scratch_[0], scratch_[1], scratch_[2]};
            __m256i invalid = _mm256_setzero_si256();
            const std::size_t done = lockstep(s, end, out, invalid);
            std::size_t n[4];
            bool overrun = false;
            for (int k = 0; k < 4; ++k) {
                n[k] = done;
                while (s[k] < end[k] && n[k] < kCapacity) out[k][n[k]++] = one_token(s[k], invalid);
                overrun |= s[k] != end[k];
            }
            if (overrun || (std::uint32_t(_mm256_movemask_epi8(invalid)) & 0x80008000)) [[unlikely]] {
                // Irregular whitespace or tokens: this chunk one token at a time.
                const std::size_t tokens = std::min(count_tokens(p, end[3]), count);
                p = parse_slowly(p, dst, tokens);
                dst += tokens;
                count -= tokens;
                continue;
            }
            std::uint32_t* next = dst + n[0];
            for (int k = 1; k < 4; ++k) {
                std::memcpy(next, out[k], n[k] * sizeof(std::uint32_t));
                next += n[k];
            }
            dst = next;
            count -= n[0] + n[1] + n[2] + n[3];
            p = skip_whitespace(end[3]);
        }
        return {p, std::size_t(dst - first)};
    }

private:
    static constexpr std::size_t kChunk = std::size_t(1) << 17;
    // A step advances a stream by 2..33 bytes and yields two values, so a stream of at most
    // kChunk / 4 + 33 bytes yields at most kChunk / 4 + 66 values.
    static constexpr std::size_t kCapacity = kChunk / 4 + 66;
    alignas(64) static inline std::uint32_t scratch_[3][kCapacity];

    // Steps all streams while each has 33 bytes left; returns the values per stream. Works on
    // local copies of the stream state, which stay in registers.
    static std::size_t lockstep(const char* (&streams)[4], const char* const (&end)[4],
                                std::uint32_t* const (&outputs)[4], __m256i& flags) {
        const char* s[4] = {streams[0], streams[1], streams[2], streams[3]};
        std::uint32_t* const out[4] = {outputs[0], outputs[1], outputs[2], outputs[3]};
        __m256i invalid = flags;
        std::size_t done = 0;
        for (;;) {
            std::ptrdiff_t left = end[0] - s[0];
            for (int k = 1; k < 4; ++k) left = std::min(left, end[k] - s[k]);
            if (left < 33) break;
            for (std::ptrdiff_t steps = left / 33; steps; --steps, done += 2) {
                const __m256i g0 = two_tokens(s[0], invalid), g1 = two_tokens(s[1], invalid);
                const __m256i g2 = two_tokens(s[2], invalid), g3 = two_tokens(s[3], invalid);
                const __m256i k = _mm256_set1_epi32(0x00012710);
                // 8-digit halves: [s0 high, s0 low, s1 high, s1 low | second tokens likewise].
                const __m256 h01 = _mm256_castsi256_ps(_mm256_madd_epi16(_mm256_packus_epi32(g0, g1), k));
                const __m256 h23 = _mm256_castsi256_ps(_mm256_madd_epi16(_mm256_packus_epi32(g2, g3), k));
                const __m256i high = _mm256_castps_si256(_mm256_shuffle_ps(h01, h23, 0x88));
                const __m256i low = _mm256_castps_si256(_mm256_shuffle_ps(h01, h23, 0xDD));
                const __m256i v = _mm256_add_epi32(_mm256_mullo_epi32(high, _mm256_set1_epi32(100000000)), low);
                // [s0 a, s0 b, s1 a, s1 b | s2 a, s2 b, s3 a, s3 b]
                const __m256i q = _mm256_permutevar8x32_epi32(v, _mm256_setr_epi32(0, 4, 1, 5, 2, 6, 3, 7));
                const __m128i q01 = _mm256_castsi256_si128(q), q23 = _mm256_extracti128_si256(q, 1);
                _mm_storel_epi64(reinterpret_cast<__m128i*>(out[0] + done), q01);
                _mm_storeh_pd(reinterpret_cast<double*>(out[1] + done), _mm_castsi128_pd(q01));
                _mm_storel_epi64(reinterpret_cast<__m128i*>(out[2] + done), q23);
                _mm_storeh_pd(reinterpret_cast<double*>(out[3] + done), _mm_castsi128_pd(q23));
            }
        }
        for (int k = 0; k < 4; ++k) streams[k] = s[k];
        flags = invalid;
        return done;
    }

    // Two tokens at s, as 4-digit groups [first | second]. Lengths outside 1..16 (repeated
    // whitespace, long tokens) set the sign bit of byte 15 or 31 of invalid.
    [[gnu::always_inline]] static __m256i two_tokens(const char*& s, __m256i& invalid) {
        const __m256i bytes = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(s));
        const std::uint32_t sep = separators(bytes);
        const auto first = std::size_t(std::countr_zero(sep));              // length of the first token
        const auto second = std::size_t(std::countr_zero(sep & (sep - 1)));  // 32 if none
        const __m256i windows =
            _mm256_inserti128_si256(bytes, _mm_loadu_si128(reinterpret_cast<const __m128i*>(s + first + 1)), 1);
        const __m256i rows = _mm256_set_m128i(align_row(second - first), align_row(first + 1));
        invalid = _mm256_or_si256(invalid, rows);
        s += second + 1;
        return digit_groups(_mm256_shuffle_epi8(_mm256_subs_epu8(windows, _mm256_set1_epi8('0')), rows));
    }

    static std::uint32_t one_token(const char*& s, __m256i& invalid) {
        const __m128i window = _mm_loadu_si128(reinterpret_cast<const __m128i*>(s));
        const unsigned n = unsigned(std::countr_zero(separators(window) | 0x10000));
        invalid = _mm256_or_si256(invalid, _mm256_castsi128_si256(align_row(n + 1)));
        s += n + 1;
        return std::uint32_t(parse16(window, n));
    }

    // The byte after the first separator at or after q.
    static const char* after_separator(const char* q) {
        for (;; q += 32)
            if (const std::uint32_t sep = separators(_mm256_loadu_si256(reinterpret_cast<const __m256i*>(q))))
                return q + std::countr_zero(sep) + 1;
    }

    static const char* skip_whitespace(const char* p) {
        while (static_cast<unsigned char>(*p) <= ' ') ++p;
        return p;
    }

    // Tokens in [p, end), where p starts a token.
    static std::size_t count_tokens(const char* p, const char* end) {
        std::size_t tokens = 1;
        for (const char* q = p + 1; q < end; ++q)
            tokens += static_cast<unsigned char>(*q) > ' ' && static_cast<unsigned char>(q[-1]) <= ' ';
        return tokens;
    }

    static const char* parse_slowly(const char* p, std::uint32_t* dst, std::size_t count) {
        for (std::size_t i = 0; i < count; ++i) {
            p = skip_whitespace(p);
            const __m128i window = _mm_loadu_si128(reinterpret_cast<const __m128i*>(p));
            const unsigned n = unsigned(std::countr_zero(separators(window) | 0x10000));
            dst[i] = std::uint32_t(parse16(window, n));
            p += n + 1;
        }
        return p;
    }
};

}  // namespace detail

// Token boundaries come from separator bitmasks of aligned 64-byte blocks: finding the next token
// clears one bit, so consecutive reads do not wait on each other's parsing.
class Reader {
public:
    // Takes everything that remains on fd (stdin by default).
    explicit Reader(int fd = 0) : input_(detail::open_input(fd)) { seek(input_.start); }

    ~Reader() { detail::release(input_); }

    Reader(const Reader&) = delete;
    Reader& operator=(const Reader&) = delete;

    // Next integer token, or the next non-whitespace character for char. MaxDigits, if set, promises
    // at most that many digits; for 64-bit types, 16 or fewer selects a faster parser.
    // Non-negative values parse faster as unsigned types (10-18%, see notes.md).
    template <class T, int MaxDigits = 0>
        requires std::integral<T> && (!std::same_as<T, bool>)
    T read() {
        if constexpr (std::same_as<T, char>) {
            skip_whitespace();
            return *cur_++;
        } else {
            const auto [start, length] = next_token();
            // A leading '-' sits below '0' and parses as a zero digit.
            const auto magnitude = parse<(sizeof(T) > 4), MaxDigits>(start + length, length);
            if constexpr (std::is_unsigned_v<T>) return T(magnitude);
            else return T(*start == '-' ? 0 - magnitude : magnitude);
        }
    }

    // count tokens into dst. uint32_t uses the AVX2 bulk parser; other types read one by one.
    template <int MaxDigits = 0, class T>
    void read(T* dst, std::size_t count) {
        if constexpr (std::same_as<T, std::uint32_t>) {
            skip_whitespace();
            const auto [stop, parsed] = detail::BulkParser::parse(cur_, input_.end, dst, count);
            seek(stop);
            for (std::size_t i = parsed; i < count; ++i) dst[i] = read<T>();
        } else {
            for (std::size_t i = 0; i < count; ++i) dst[i] = read<T, MaxDigits>();
        }
    }

    // Next token; valid while the Reader lives.
    std::string_view word() {
        const auto [start, length] = next_token();
        return {start, length};
    }

    // Tokenizer state, for custom token loops. separators has one bit per whitespace byte of the
    // 64-byte block at block, at or after cur. The lowest bit is the end of the token at cur: clear
    // it to move on. With no bits left, advance block by 64 and take detail::block_separators.
    struct Scan {
        const char* cur;
        const char* block;
        std::uint64_t separators;
    };

    Scan scan() const { return {cur_, block_, separators_}; }

    void resume(const Scan& scan) {
        cur_ = scan.cur;
        block_ = scan.block;
        separators_ = scan.separators;
    }

private:
    struct Token {
        const char* start;
        unsigned length;
    };

    // Continue reading at p.
    void seek(const char* p) {
        cur_ = p;
        block_ = reinterpret_cast<const char*>(reinterpret_cast<std::uintptr_t>(p) & ~std::uintptr_t(63));
        separators_ = detail::block_separators(block_) & ~std::uint64_t(0) << (cur_ - block_);
    }

    // Position of the next separator; at or after cur_.
    const char* next_separator() {
        while (!separators_) [[unlikely]] {
            block_ += 64;
            separators_ = detail::block_separators(block_);
        }
        return block_ + std::countr_zero(separators_);
    }

    void skip_whitespace() {
        while (next_separator() == cur_) {
            separators_ &= separators_ - 1;
            ++cur_;
        }
    }

    Token next_token() {
        for (;;) {
            const char* end = next_separator();
            separators_ &= separators_ - 1;
            const char* start = cur_;
            cur_ = end + 1;
            if (end != start) [[likely]] return {start, unsigned(end - start)};
        }
    }

    // Value of the n characters that end at end.
    template <bool Wide, int MaxDigits>
    static auto parse(const char* end, unsigned n) {
        if constexpr (!Wide) return std::uint32_t(detail::parse_ending16(end, n));
        else if constexpr (MaxDigits > 0 && MaxDigits <= 16) return detail::parse_ending16(end, n);
        else return detail::parse_ending24(end, n);
    }

    detail::Input input_;
    const char* cur_;             // next unread byte
    const char* block_;           // 64-byte block holding the next separator
    std::uint64_t separators_;    // separators in block_ at or after cur_
};

// Buffered output. write() takes any mix of integers, chars and strings:
//   out.write(x, ' ', y, '\n');
// MaxDigits, if set, promises integers of at most that many digits; for 64-bit types, 16 or fewer
// selects a faster formatter: out.write<16>(sum, '\n').
class Writer {
public:
    explicit Writer(int fd = 1) : fd_(fd) {}
    ~Writer() { flush(); }

    Writer(const Writer&) = delete;
    Writer& operator=(const Writer&) = delete;

    template <int MaxDigits = 0, class... Ts>
    void write(const Ts&... values) {
        const std::size_t needed = (std::size_t(0) + ... + max_size(values));
        if (needed > kCapacity) [[unlikely]] {
            (write_alone<MaxDigits>(values), ...);
            return;
        }
        if (std::size_t(buffer_ + kCapacity - cur_) < needed) [[unlikely]] flush();
        char* p = cur_;
        ((p = put<MaxDigits>(p, values)), ...);
        cur_ = p;
    }

    // Custom formatting: fill(p) may store up to max_size <= 64 KiB bytes at p and returns the end
    // of what it wrote.
    template <class Fill>
    void write_with(std::size_t max_size, Fill fill) {
        if (std::size_t(buffer_ + kCapacity - cur_) < max_size) [[unlikely]] flush();
        cur_ = fill(cur_);
    }

    // values[0..count) joined by separator. uint32_t uses the AVX2 formatter.
    template <int MaxDigits = 0, class T>
    void write_array(const T* values, std::size_t count, char separator) {
        if (!count) return;
        std::size_t i = 0;
        if constexpr (std::same_as<T, std::uint32_t>) {
            constexpr std::size_t kBatch = 8 * 11 + 16;  // eight values and separators, plus overhang
            char* p = cur_;
            for (; i + 8 <= count; i += 8) {
                if (std::size_t(buffer_ + kCapacity - p) < kBatch) [[unlikely]] {
                    cur_ = p;
                    flush();
                    p = cur_;
                }
                p = detail::format8(p, _mm256_loadu_si256(reinterpret_cast<const __m256i*>(values + i)), separator);
            }
            cur_ = p;
        }
        for (; i < count; ++i) write<MaxDigits>(values[i], separator);
        --cur_;  // no separator after the last value
    }

    void flush() {
        write_all(fd_, buffer_, std::size_t(cur_ - buffer_));
        cur_ = buffer_;
    }

private:
    static constexpr std::size_t kCapacity = std::size_t(1) << 16;

    template <class T>
    static constexpr bool kInteger = std::integral<T> && !std::same_as<T, char> && !std::same_as<T, bool>;

    // Bytes put() may store, which can exceed what it writes.
    template <class T>
    static std::size_t max_size(const T& value) {
        if constexpr (std::same_as<T, char>) return 1;
        else if constexpr (kInteger<T>) return 1 + 20;  // a sign, then format() stores up to 20 bytes
        else return std::string_view(value).size();
    }

    template <int MaxDigits, class T>
    static char* put(char* p, const T& value) {
        if constexpr (std::same_as<T, char>) {
            *p = value;
            return p + 1;
        } else if constexpr (kInteger<T>) {
            using U = std::conditional_t<sizeof(T) <= 4, std::uint32_t, std::uint64_t>;
            if constexpr (std::is_signed_v<T>) {
                *p = '-';
                p += value < 0;
                return put<MaxDigits>(p, value < 0 ? U(0 - U(value)) : U(value));
            } else if constexpr (sizeof(T) <= 4) {
                return detail::format(p, U(value));
            } else {
                return detail::format64<MaxDigits == 0 ? 20 : MaxDigits>(p, U(value));
            }
        } else {
            const std::string_view s(value);
            std::memcpy(p, s.data(), s.size());
            return p + s.size();
        }
    }

    // A value longer than the buffer: flush, then write it directly.
    template <int MaxDigits, class T>
    void write_alone(const T& value) {
        if constexpr (std::same_as<T, char> || kInteger<T>) {
            write<MaxDigits>(value);
        } else {
            flush();
            const std::string_view s(value);
            write_all(fd_, s.data(), s.size());
        }
    }

    static void write_all(int fd, const char* data, std::size_t size) {
        while (size) {
            const ssize_t put = ::write(fd, data, size);
            if (put > 0) data += put, size -= std::size_t(put);
            else if (put < 0 && errno == EINTR) continue;
            else std::abort();
        }
    }

    int fd_;
    char* cur_ = buffer_;
    alignas(64) char buffer_[kCapacity];
};

}  // namespace io

namespace io {
namespace detail {

// The 32 bytes at kDigitMask[n] (n <= 64), subtracted with unsigned saturation from the 32 bytes
// that end at a token of length n, give its digit values and zero the bytes before it.
alignas(64) inline constexpr auto kDigitMask = [] {
    std::array<std::uint8_t, 96> t{};
    for (std::size_t i = 0; i < t.size(); ++i) t[i] = i < 32 ? 0xFF : '0';
    return t;
}();

// Parses uint64 tokens of at most 20 digits from the token at p into dst: at most count, which
// must be the tokens that follow. Each chunk of input is cut into four streams at token
// boundaries; the streams advance in lockstep, two tokens per step. Stops when fewer than
// kMinTokens tokens remain. Returns where it stopped and the tokens parsed.
class BulkParser64 {
public:
    static constexpr std::size_t kMinTokens = 1024;

    struct Result {
        const char* end;
        std::size_t parsed;
    };

    static Result parse(const char* p, std::uint64_t* dst, std::size_t count) {
        std::uint64_t* const first = dst;
        while (count >= kMinTokens) {
            // The count tokens span at least 2 * count - 1 bytes. A chunk spans at most chunk + 21
            // bytes, so it holds at most chunk / 2 + 11 < count tokens, and steps load at most 64
            // bytes past a stream position: all within those bytes.
            const std::size_t chunk = std::min(kChunk, 2 * (count - 64)) & ~std::size_t(3);
            const std::size_t stream = chunk / 4;
            const char* s[4] = {p, after_separator(p + stream), after_separator(p + 2 * stream),
                                after_separator(p + 3 * stream)};
            const char* const end[4] = {s[1], s[2], s[3], after_separator(p + chunk)};
            std::uint64_t* const out[4] = {dst, scratch_[0], scratch_[1], scratch_[2]};
            std::uint64_t lengths = 0;
            const std::size_t done = lockstep(s, end, out, lengths);
            std::size_t n[4];
            bool overrun = false;
            for (int k = 0; k < 4; ++k) {
                n[k] = done;
                while (s[k] < end[k] && n[k] < kCapacity) out[k][n[k]++] = one_token(s[k], lengths);
                overrun |= s[k] != end[k];
            }
            if (overrun || lengths >= 32) [[unlikely]] {
                // Irregular whitespace: this chunk one token at a time.
                const std::size_t tokens = std::min(count_tokens(p, end[3]), count);
                p = parse_slowly(p, dst, tokens);
                dst += tokens;
                count -= tokens;
                continue;
            }
            std::uint64_t* next = dst + n[0];
            for (int k = 1; k < 4; ++k) {
                std::memcpy(next, out[k], n[k] * sizeof(std::uint64_t));
                next += n[k];
            }
            dst = next;
            count -= n[0] + n[1] + n[2] + n[3];
            p = skip_whitespace(end[3]);
        }
        return {p, std::size_t(dst - first)};
    }

    static const char* skip_whitespace(const char* p) {
        while (static_cast<unsigned char>(*p) <= ' ') ++p;
        return p;
    }

private:
    static constexpr std::size_t kChunk = std::size_t(1) << 17;
    // A step advances a stream by at least 2 bytes and yields two values.
    static constexpr std::size_t kCapacity = kChunk / 4 + 64;
    alignas(64) static inline std::uint64_t scratch_[3][kCapacity];

    // Steps all streams while each has 42 bytes left (two tokens of 21 bytes) and the outputs have
    // room; returns the values per stream. lengths collects (length - 1) of each token by OR: 32
    // or more flags an empty token. Works on local copies of the stream state.
    static std::size_t lockstep(const char* (&streams)[4], const char* const (&end)[4],
                                std::uint64_t* const (&outputs)[4], std::uint64_t& flags) {
        const char* s[4] = {streams[0], streams[1], streams[2], streams[3]};
        std::uint64_t* const out[4] = {outputs[0], outputs[1], outputs[2], outputs[3]};
        std::uint64_t lengths = flags;
        std::size_t done = 0;
        for (;;) {
            std::ptrdiff_t left = end[0] - s[0];
            for (int k = 1; k < 4; ++k) left = std::min(left, end[k] - s[k]);
            const std::ptrdiff_t steps = std::min(left / 42, std::ptrdiff_t(kCapacity - done) / 2);
            if (steps == 0) break;
            for (std::ptrdiff_t step = 0; step < steps; ++step, done += 2) {
                const __m256i l0 = two_tokens(s[0], lengths), l1 = two_tokens(s[1], lengths);
                const __m256i l2 = two_tokens(s[2], lengths), l3 = two_tokens(s[3], lengths);
                const __m256i v01 = values(l0, l1), v23 = values(l2, l3);
                _mm_storeu_si128(reinterpret_cast<__m128i*>(out[0] + done), _mm256_castsi256_si128(v01));
                _mm_storeu_si128(reinterpret_cast<__m128i*>(out[1] + done), _mm256_extracti128_si256(v01, 1));
                _mm_storeu_si128(reinterpret_cast<__m128i*>(out[2] + done), _mm256_castsi256_si128(v23));
                _mm_storeu_si128(reinterpret_cast<__m128i*>(out[3] + done), _mm256_extracti128_si256(v23, 1));
            }
        }
        for (int k = 0; k < 4; ++k) streams[k] = s[k];
        flags = lengths;
        return done;
    }

    // 4-digit groups of the n <= 64 bytes that end at end: dwords 3..7 for 20 digits, 0 before.
    [[gnu::always_inline]] static __m256i groups_ending(const char* end, std::size_t n) {
        const __m256i bytes = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(end - 32));
        const __m256i mask = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(kDigitMask.data() + n));
        return digit_groups(_mm256_subs_epu8(bytes, mask));
    }

    // Two tokens a, b at s as 8-digit limbs [0, top a, 0, top b | mid a, low a, mid b, low b],
    // value = top * 10^16 + mid * 10^8 + low. Bit 63 of the separator mask keeps both lengths
    // below 64, so the loads stay within 64 bytes of s.
    [[gnu::always_inline]] static __m256i two_tokens(const char*& s, std::uint64_t& lengths) {
        const std::uint64_t low = separators(_mm256_loadu_si256(reinterpret_cast<const __m256i*>(s)));
        const std::uint64_t high = separators(_mm256_loadu_si256(reinterpret_cast<const __m256i*>(s + 32)));
        const std::uint64_t sep = low | (high | 0x80000000) << 32;
        const auto first = std::size_t(std::countr_zero(sep));              // length of a
        const auto second = std::size_t(std::countr_zero(sep & (sep - 1)));  // 64 if none
        const std::size_t length = second - first - 1;                       // of b
        lengths |= (first - 1) | (length - 1);
        const __m256i a = groups_ending(s + first, first), b = groups_ending(s + second, length);
        s += second + 1;
        return _mm256_madd_epi16(_mm256_packus_epi32(a, b), _mm256_set1_epi32(0x00012710));
    }

    // Limbs of two token pairs j, k -> values [j a, j b | k a, k b].
    static __m256i values(__m256i j, __m256i k) {
        constexpr std::uint64_t kTen16 = 10000000000000000;  // top * kTen16 in two 32-bit halves, mod 2^64
        const __m256i tops = _mm256_permute2x128_si256(j, k, 0x20);  // top in each high dword
        const __m256i rest = _mm256_permute2x128_si256(j, k, 0x31);  // [mid, low] per qword
        const __m256i top_low = _mm256_mul_epu32(_mm256_srli_epi64(tops, 32), _mm256_set1_epi64x(kTen16 & 0xFFFFFFFF));
        const __m256i top_high = _mm256_mullo_epi32(tops, _mm256_set1_epi64x(std::int64_t(kTen16 >> 32 << 32)));
        const __m256i mid = _mm256_mul_epu32(rest, _mm256_set1_epi64x(100000000));
        return _mm256_add_epi64(_mm256_add_epi64(top_low, top_high), _mm256_add_epi64(mid, _mm256_srli_epi64(rest, 32)));
    }

    static std::uint64_t one_token(const char*& s, std::uint64_t& lengths) {
        const std::uint32_t sep = separators(_mm256_loadu_si256(reinterpret_cast<const __m256i*>(s)));
        const auto n = unsigned(std::countr_zero(sep | 0x80000000));
        lengths |= std::uint64_t(n) - 1;
        s += n + 1;
        return parse_ending24(s - 1, n);
    }

    // The byte after the first separator at or after q.
    static const char* after_separator(const char* q) {
        for (;; q += 32)
            if (const std::uint32_t sep = separators(_mm256_loadu_si256(reinterpret_cast<const __m256i*>(q))))
                return q + std::countr_zero(sep) + 1;
    }

    // Tokens in [p, end), where p starts a token.
    static std::size_t count_tokens(const char* p, const char* end) {
        std::size_t tokens = 1;
        for (const char* q = p + 1; q < end; ++q)
            tokens += static_cast<unsigned char>(*q) > ' ' && static_cast<unsigned char>(q[-1]) <= ' ';
        return tokens;
    }

    static const char* parse_slowly(const char* p, std::uint64_t* dst, std::size_t count) {
        for (std::size_t i = 0; i < count; ++i) {
            p = skip_whitespace(p);
            const std::uint32_t sep = separators(_mm256_loadu_si256(reinterpret_cast<const __m256i*>(p)));
            const auto n = unsigned(std::countr_zero(sep | 0x80000000));
            dst[i] = parse_ending24(p + n, n);
            p += n + 1;
        }
        return p;
    }
};

}  // namespace detail

// count uint64 tokens into dst, as in.read(dst, count) but with the AVX2 bulk parser.
inline void read_bulk(Reader& in, std::uint64_t* dst, std::size_t count) {
    std::size_t parsed = 0;
    if (count >= detail::BulkParser64::kMinTokens) {
        const char* const start = detail::BulkParser64::skip_whitespace(in.scan().cur);
        const auto [stop, done] = detail::BulkParser64::parse(start, dst, count);
        // Continue the Reader at stop: its separator mask from there on.
        const auto* block = reinterpret_cast<const char*>(reinterpret_cast<std::uintptr_t>(stop) & ~std::uintptr_t(63));
        in.resume({stop, block, detail::block_separators(block) & ~std::uint64_t(0) << (stop - block)});
        parsed = done;
    }
    for (std::size_t i = parsed; i < count; ++i) dst[i] = in.read<std::uint64_t>();
}

}  // namespace io
// problems/convolution/convolution_F_2_64/fields.hpp
// Output of uint64 values separated by spaces, then a newline. Blocks of mostly large values are
// printed in fixed width: each value right-aligned in 20 characters, then a separator.
// Judge-specific: the checker (testlib wcmp) compares tokens, so the padding is accepted. Blocks
// with many short values stay variable-width, where padding would cost more in write(2).
//
// A value x = h * 10^16 + m * 10^8 + l is split by scalar code; h < 1845 is looked up as text with
// its leading spaces, m and l become 8 digits each in AVX2, four values per step. Values below
// 10^16 (h = 0, rare) get their leading zeros blanked afterwards.

#include <immintrin.h>

#include <array>
#include <cstdint>
#include <cstring>


namespace fields {

inline constexpr std::size_t kWidth = 21;  // 20 characters and a separator

namespace detail {

using u64 = std::uint64_t;
using u32 = std::uint32_t;

constexpr u64 kTen8 = 100000000, kTen16 = kTen8 * kTen8;
constexpr u32 kHighCount = 1845;  // 2^64 / 10^16 < 1845

// The 4 characters of h < 10000 in memory order, leading zeros as spaces; h = 0 is 4 spaces.
constexpr std::array<u32, kHighCount> kHigh = [] {
    std::array<u32, kHighCount> t{};
    for (u32 h = 0; h < kHighCount; ++h) {
        u32 v = h;
        for (int i = 3; i >= 0; --i) {
            const u32 c = v ? '0' + v % 10 : ' ';
            t[h] |= c << 8 * i;
            v /= 10;
        }
    }
    return t;
}();

// Each 64-bit lane n < 10^8 to its 8 digits as text, most significant at the lowest address.
// Each step splits a part x into [x % d, x / d] in place as x + (x / d) * (2^k - d); the digits
// come out least significant first and one byte shuffle reverses them.
inline __m256i digits8(__m256i n) {
    const __m256i q4 = _mm256_srli_epi64(_mm256_mul_epu32(n, _mm256_set1_epi64x(109951163)), 40);  // n / 10^4
    const __m256i w4 = _mm256_add_epi64(n, _mm256_mul_epu32(q4, _mm256_set1_epi64x(0xFFFFD8F0)));  // dwords < 10^4
    const __m256i q2 = _mm256_srli_epi16(_mm256_mulhi_epu16(w4, _mm256_set1_epi32(5243)), 3);  // / 100
    const __m256i w2 = _mm256_add_epi32(w4, _mm256_mullo_epi32(q2, _mm256_set1_epi32(65436)));  // words < 100
    const __m256i q1 = _mm256_mulhi_epu16(w2, _mm256_set1_epi16(6554));  // / 10
    const __m256i w1 = _mm256_add_epi16(w2, _mm256_mullo_epi16(q1, _mm256_set1_epi16(246)));  // digits
    const __m256i reverse = _mm256_setr_epi8(7, 6, 5, 4, 3, 2, 1, 0, 15, 14, 13, 12, 11, 10, 9, 8,  //
                                             7, 6, 5, 4, 3, 2, 1, 0, 15, 14, 13, 12, 11, 10, 9, 8);
    return _mm256_add_epi8(_mm256_shuffle_epi8(w1, reverse), _mm256_set1_epi8('0'));
}

inline void store16(char* p, __m128i v) { _mm_storeu_si128(reinterpret_cast<__m128i*>(p), v); }
inline void store8(char* p, __m128i v) { _mm_storel_epi64(reinterpret_cast<__m128i*>(p), v); }

// Fields of four values from their parts; stores 3 bytes past the last field.
inline void format4(char* p, const u32* high, const u32* mid, const u32* low) {
    const __m256i hd = _mm256_cvtepu32_epi64(_mm_loadu_si128(reinterpret_cast<const __m128i*>(high)));
    const __m256i md = digits8(_mm256_cvtepu32_epi64(_mm_loadu_si128(reinterpret_cast<const __m128i*>(mid))));
    const __m256i ld = digits8(_mm256_cvtepu32_epi64(_mm_loadu_si128(reinterpret_cast<const __m128i*>(low))));
    const __m256i a = _mm256_or_si256(hd, _mm256_slli_epi64(md, 32));  // characters 0..7
    const __m256i b = _mm256_or_si256(_mm256_srli_epi64(md, 32), _mm256_slli_epi64(ld, 32));  // 8..15
    const __m256i c = _mm256_or_si256(_mm256_srli_epi64(ld, 32), _mm256_set1_epi64x(u64(' ') << 32));  // 16..20
    const __m256i even = _mm256_unpacklo_epi64(a, b), odd = _mm256_unpackhi_epi64(a, b);
    const __m128i c01 = _mm256_castsi256_si128(c), c23 = _mm256_extracti128_si256(c, 1);
    store16(p, _mm256_castsi256_si128(even));
    store8(p + 16, c01);
    store16(p + kWidth, _mm256_castsi256_si128(odd));
    store8(p + kWidth + 16, _mm_unpackhi_epi64(c01, c01));
    store16(p + 2 * kWidth, _mm256_extracti128_si256(even, 1));
    store8(p + 2 * kWidth + 16, c23);
    store16(p + 3 * kWidth, _mm256_extracti128_si256(odd, 1));
    store8(p + 3 * kWidth + 16, _mm_unpackhi_epi64(c23, c23));
}

inline constexpr std::size_t kBlock = 3104;  // values per write(2): 65184 bytes, then 3 overhang

// values[0, count), count <= kBlock, as fields at text; stores up to 3 bytes past them.
inline void format(char* text, const u64* values, std::size_t count) {
    alignas(32) static u32 high[kBlock + 4], mid[kBlock + 4], low[kBlock + 4];
    alignas(32) static u32 small[kBlock];  // indices of values below 10^16
    std::size_t smalls = 0;
    const auto split = [&](std::size_t i) {
        const u64 x = values[i], h = x / kTen16, r = x - h * kTen16, m = r / kTen8;
        high[i] = kHigh[h];
        mid[i] = u32(m);
        low[i] = u32(r - m * kTen8);
        small[smalls] = u32(i);
        smalls += h == 0;
    };
    for (std::size_t i = count; i % 4; ++i) high[i] = mid[i] = low[i] = 0;
    // The scalar split runs kAhead values ahead of the vector digits in one loop, so the two
    // overlap on separate ports; the digits load parts stored long before (no forwarding stall).
    constexpr std::size_t kAhead = 64;
    const std::size_t first = std::min(count, kAhead);
    for (std::size_t i = 0; i < first; ++i) split(i);
    std::size_t i = 0;
    for (; i + kAhead + 4 <= count; i += 4) {
        split(i + kAhead), split(i + kAhead + 1), split(i + kAhead + 2), split(i + kAhead + 3);
        format4(text + i * kWidth, high + i, mid + i, low + i);
    }
    for (std::size_t j = std::max(first, i + kAhead); j < count; ++j) split(j);
    for (; i < count; i += 4) format4(text + i * kWidth, high + i, mid + i, low + i);
    for (std::size_t s = 0; s < smalls; ++s) {
        char* p = text + small[s] * kWidth;
        for (std::size_t j = 4; j < 19 && p[j] == '0'; ++j) p[j] = ' ';
    }
}

// Whether at least 1/8 of values[0, count) are below 2^53 (at most 16 digits).
inline bool mostly_short(const u64* values, std::size_t count) {
    __m256i shorts = _mm256_setzero_si256();  // minus the count per lane
    std::size_t i = 0;
    for (; i + 4 <= count; i += 4) {
        const __m256i top = _mm256_srli_epi64(_mm256_loadu_si256(reinterpret_cast<const __m256i*>(values + i)), 53);
        shorts = _mm256_add_epi64(shorts, _mm256_cmpeq_epi64(top, _mm256_setzero_si256()));
    }
    alignas(32) std::int64_t lanes[4];
    _mm256_store_si256(reinterpret_cast<__m256i*>(lanes), shorts);
    std::size_t n = std::size_t(-(lanes[0] + lanes[1] + lanes[2] + lanes[3]));
    for (; i < count; ++i) n += values[i] >> 53 == 0;
    return 8 * n >= count;
}

}  // namespace detail

// values[0, count), count >= 1.
inline void write(io::Writer& out, const std::uint64_t* values, std::size_t count) {
    for (std::size_t i = 0; i < count; i += detail::kBlock) {
        const std::size_t n = std::min(detail::kBlock, count - i);
        if (detail::mostly_short(values + i, n)) {
            out.write_array(values + i, n, ' ');
            out.write(i + n == count ? '\n' : ' ');
            continue;
        }
        out.write_with(kWidth * n + 3, [&](char* text) {
            detail::format(text, values + i, n);
            if (i + n == count) text[kWidth * n - 1] = '\n';
            return text + kWidth * n;
        });
    }
}

}  // namespace fields

namespace {

using u64 = std::uint64_t;

constexpr int kMaxLog = 20;  // N + M - 1 < 2^20
constexpr int kMinLog = 4;   // stages 3 to 0 run on groups of 16 words

// Field arithmetic. The polynomial's low part: x^64 = x^4 + x^3 + x + 1.

constexpr u64 clmul_low_portable(u64 a, u64 b, u64& high) {
    u64 low = 0;
    high = 0;
    for (int i = 0; i < 64; ++i) {
        if (b >> i & 1) {
            low ^= a << i;
            high ^= i ? a >> (64 - i) : 0;
        }
    }
    return low;
}

// (high, low) mod P: high * x^64 = high * (x^4 + x^3 + x + 1); the bits of that above x^63 are
// g = high >> 60 ^ high >> 61 ^ high >> 63, folded once more. Both folds use q = high ^ g.
constexpr u64 reduce_scalar(u64 low, u64 high) {
    const u64 q = high ^ high >> 60 ^ high >> 61 ^ high >> 63;
    return low ^ q ^ q << 1 ^ q << 3 ^ q << 4;
}

constexpr u64 multiply_scalar(u64 a, u64 b) {
    u64 high = 0;
    const u64 low = clmul_low_portable(a, b, high);
    return reduce_scalar(low, high);
}

// y with y^2 + y = c (c of trace 0). y -> y^2 + y is F_2-linear: eliminate on its images of the
// unit vectors, tracking which unit vectors make up each basis vector.
constexpr u64 solve_artin_schreier(u64 c) {
    std::array<u64, 64> pivot{}, source{};
    for (int j = 0; j < 64; ++j) {
        const u64 unit = u64(1) << j;
        u64 v = multiply_scalar(unit, unit) ^ unit, s = unit;
        for (int b = 63; b >= 0 && v; --b) {
            if (!(v >> b & 1)) continue;
            if (!pivot[b]) {
                pivot[b] = v, source[b] = s;
                v = 0;
            } else {
                v ^= pivot[b], s ^= source[b];
            }
        }
    }
    u64 y = 0;
    for (int b = 63; b >= 0; --b) {
        if (c >> b & 1) c ^= pivot[b], y ^= source[b];
    }
    return c == 0 ? y : throw "no root";
}

constexpr std::array<u64, kMaxLog> kBeta = [] {
    std::array<u64, kMaxLog> beta{1};
    for (int i = 1; i < kMaxLog; ++i) beta[i] = solve_artin_schreier(beta[i - 1]);
    return beta;
}();

// omega_m = kOmegaLow[m & 1023] ^ kOmegaHigh[m >> 10], m < 2^20.
struct OmegaTable {
    std::array<u64, 1024> low, high;
};

constexpr OmegaTable kOmega = [] {
    OmegaTable t{};
    for (int m = 1; m < 1024; ++m) {
        const int b = std::countr_zero(unsigned(m));
        t.low[m] = t.low[m & (m - 1)] ^ kBeta[b];
        t.high[m] = t.high[m & (m - 1)] ^ kBeta[b + 10];
    }
    return t;
}();

inline u64 omega(std::size_t m) { return kOmega.low[m & 1023] ^ kOmega.high[m >> 10]; }

// Four field elements per vector.

using Vec = __m256i;

inline Vec load(const u64* p) { return _mm256_load_si256(reinterpret_cast<const Vec*>(p)); }
inline void store(u64* p, Vec v) { _mm256_store_si256(reinterpret_cast<Vec*>(p), v); }
inline Vec broadcast(u64 x) { return _mm256_set1_epi64x(std::int64_t(x)); }

// acc + (high, low) mod P, as reduce_scalar: low ^ (high * (x^4 + x^3 + x + 1) mod x^64) ^ g(high >> 60),
// where g(n) < 256 folds the bits above x^63; looked up by vpshufb.
inline Vec reduce_add(Vec acc, Vec low, Vec high) {
    constexpr auto kFold = [] {
        std::array<std::int8_t, 16> t{};
        for (u64 n = 0; n < 16; ++n) t[n] = std::int8_t(reduce_scalar(0, n << 60));
        return t;
    }();
    const Vec fold = _mm256_setr_epi8(kFold[0], kFold[1], kFold[2], kFold[3], kFold[4], kFold[5], kFold[6], kFold[7],
                                      kFold[8], kFold[9], kFold[10], kFold[11], kFold[12], kFold[13], kFold[14],
                                      kFold[15], kFold[0], kFold[1], kFold[2], kFold[3], kFold[4], kFold[5], kFold[6],
                                      kFold[7], kFold[8], kFold[9], kFold[10], kFold[11], kFold[12], kFold[13],
                                      kFold[14], kFold[15]);
    const Vec s = _mm256_xor_si256(high, _mm256_add_epi64(high, high));  // high << 1 off the shift pipes
    const Vec top = _mm256_shuffle_epi8(fold, _mm256_srli_epi64(high, 60));
    // high * (x^4 + x^3 + x + 1) = s ^ (s << 3) mod x^64. s << 3 is ready last, so it is added last;
    // the empty asm keeps GCC from reassociating it to the front of the XOR chain (1 cycle shorter).
    Vec sum = _mm256_xor_si256(_mm256_xor_si256(acc, low), _mm256_xor_si256(top, s));
    __asm__("" : "+x"(sum));
    return _mm256_xor_si256(sum, _mm256_slli_epi64(s, 3));
}

// acc + a * b in F, lane-wise.
inline Vec multiply_add(Vec acc, Vec a, Vec b) {
#ifdef __VPCLMULQDQ__
    const Vec even = _mm256_clmulepi64_epi128(a, b, 0x00);  // lanes 0 and 2: low, high
    const Vec odd = _mm256_clmulepi64_epi128(a, b, 0x11);   // lanes 1 and 3
    return reduce_add(acc, _mm256_unpacklo_epi64(even, odd), _mm256_unpackhi_epi64(even, odd));
#elif defined(__PCLMUL__)
    __m128i half[2][2];  // [128-bit half][even, odd]
    for (int h = 0; h < 2; ++h) {
        const __m128i x = h ? _mm256_extracti128_si256(a, 1) : _mm256_castsi256_si128(a);
        const __m128i y = h ? _mm256_extracti128_si256(b, 1) : _mm256_castsi256_si128(b);
        half[h][0] = _mm_clmulepi64_si128(x, y, 0x00);
        half[h][1] = _mm_clmulepi64_si128(x, y, 0x11);
    }
    const Vec even = _mm256_set_m128i(half[1][0], half[0][0]), odd = _mm256_set_m128i(half[1][1], half[0][1]);
    return reduce_add(acc, _mm256_unpacklo_epi64(even, odd), _mm256_unpackhi_epi64(even, odd));
#else
    alignas(32) u64 x[4], y[4];
    _mm256_store_si256(reinterpret_cast<Vec*>(x), a);
    _mm256_store_si256(reinterpret_cast<Vec*>(y), b);
    for (int k = 0; k < 4; ++k) x[k] = multiply_scalar(x[k], y[k]);
    return _mm256_xor_si256(acc, _mm256_load_si256(reinterpret_cast<const Vec*>(x)));
#endif
}

inline Vec multiply(Vec a, Vec b) { return multiply_add(_mm256_setzero_si256(), a, b); }

// Change of basis between monomials and X. A sequence's element e spans the W words at f + e * S
// (W <= S); elements are xored as units. Forward passes take size: elements [size, length) are zero.

template <std::size_t W, std::size_t S>
inline void xor_rows(u64* dst, const u64* src, std::size_t count) {
    if constexpr (W == S) {
        for (std::size_t k = 0; k < count * W; ++k) dst[k] ^= src[k];
    } else {
        for (std::size_t e = 0; e < count; ++e) {
            for (std::size_t k = 0; k < W; ++k) dst[e * S + k] ^= src[e * S + k];
        }
    }
}

// change_basis<4> in registers. Its XOR steps, as (dst, src) element pairs, are recorded at
// compile time by running the recursion of taylor and change_basis on element indices.
struct XorStep {
    std::uint8_t dst, src;
};

struct XorProgram {
    std::array<XorStep, 64> step{};
    std::size_t count = 0;

    // Element dst + e * s ^= element src + e * s for e < n.
    constexpr void rows(std::size_t dst, std::size_t src, std::size_t n, std::size_t s) {
        for (std::size_t e = 0; e < n; ++e) step[count++] = {std::uint8_t(dst + e * s), std::uint8_t(src + e * s)};
    }
};

constexpr void record_taylor(XorProgram& p, std::size_t f, std::size_t s, std::size_t len, std::size_t tau, bool inverse,
                             std::size_t size) {
    if (len <= tau) return;
    const std::size_t half = len / 2, d = half / tau, a = f, b = f + half * s;
    if (inverse) {
        record_taylor(p, a, s, half, tau, true, half);
        record_taylor(p, b, s, half, tau, true, half);
        p.rows(b, b + (half - d) * s, d, s);
        p.rows(a + d * s, b, half - d, s);
        p.rows(a + d * s, b + (half - d) * s, d, s);
    } else if (size <= half) {
        record_taylor(p, a, s, half, tau, false, size);
    } else {
        p.rows(a + d * s, b, half - d, s);
        p.rows(a + d * s, b + (half - d) * s, d, s);
        p.rows(b, b + (half - d) * s, d, s);
        record_taylor(p, a, s, half, tau, false, half);
        record_taylor(p, b, s, half, tau, false, size - half);
    }
}

constexpr void record_change(XorProgram& p, std::size_t f, std::size_t s, int l, bool inverse, std::size_t size) {
    if (l < 2) return;
    const int k = 1 << (std::bit_width(unsigned(l - 1)) - 1);
    const std::size_t tau = std::size_t(1) << k, rows = std::size_t(1) << (l - k), len = std::size_t(1) << l;
    if (inverse) {
        for (std::size_t c = 0; c < tau; ++c) record_change(p, f + c * s, tau * s, l - k, true, rows);
        for (std::size_t r = 0; r < rows; ++r) record_change(p, f + r * tau * s, s, k, true, tau);
        record_taylor(p, f, s, len, tau, true, len);
    } else {
        record_taylor(p, f, s, len, tau, false, size);
        const std::size_t used = (size + tau - 1) / tau;
        for (std::size_t r = 0; r < used; ++r) record_change(p, f + r * tau * s, s, k, false, tau);
        for (std::size_t c = 0; c < tau; ++c) record_change(p, f + c * s, tau * s, l - k, false, used);
    }
}

// The forward change maps elements [0, Size) to themselves (deg X_j = j). Inputs [Size, 16) are
// zero, so steps whose source is still zero are dropped.
template <bool Inverse, std::size_t Size>
constexpr XorProgram kProgram4 = [] {
    XorProgram all, p;
    record_change(all, 0, 1, 4, Inverse, Size);
    std::uint32_t live = (std::uint32_t(1) << Size) - 1;
    for (std::size_t i = 0; i < all.count; ++i) {
        if (!(live >> all.step[i].src & 1)) continue;
        p.step[p.count++] = all.step[i];
        live |= std::uint32_t(1) << all.step[i].dst;
    }
    return live >> Size ? throw "output outside [0, Size)" : p;
}();

template <const XorProgram& P, std::size_t... I>
inline void run(Vec* x, std::index_sequence<I...>) {
    ((x[P.step[I].dst] = _mm256_xor_si256(x[P.step[I].dst], x[P.step[I].src])), ...);
}

// change_basis<4> on the first Size of 16 elements (W words at stride S), four words at a time.
template <std::size_t Size, std::size_t W, std::size_t S, bool Inverse>
void change_basis4(u64* f) {
    for (std::size_t k = 0; k < W; k += 4) {
        Vec x[Size];
#pragma GCC unroll 16
        for (std::size_t e = 0; e < Size; ++e) x[e] = load(f + e * S + k);
        run<kProgram4<Inverse, Size>>(x, std::make_index_sequence<kProgram4<Inverse, Size>.count>{});
#pragma GCC unroll 16
        for (std::size_t e = 0; e < Size; ++e) store(f + e * S + k, x[e]);
    }
}

// The Taylor expansion below for rows <= 16 long rows, in one pass. With y = x^Tau,
// f = sum_r f_r(x) y^r; substituting y = t + x gives sum_k H_k(x) t^k, H_k = sum_r C(r, k) x^(r-k) f_r
// (a Taylor shift by x, its own inverse), deg H_k < Tau + 15. Split H_k = lo_k + x^Tau hi_k:
// x^Tau = t + x, so g_k = lo_k + x hi_k + hi_(k-1). The inverse shifts g the same way and
// f_r = lo_r + hi_(r-1). The shift moves data at most 15 columns right, so it runs on column
// blocks from right to left, each with the 16 still unchanged columns before it.
namespace wide {

constexpr std::size_t kHalo = 16, kBlock = 128, kWidth = kHalo + kBlock;

// The shift on buf's rows; exact for columns j >= kHalo. A level with distance d needs columns
// >= kHalo - (d - 1) of the previous one, so columns below 4 are never needed after d = 4.
template <std::size_t Rows>
void shift(u64 (*buf)[kWidth]) {
#pragma GCC unroll 4
    for (std::size_t d = Rows / 2; d >= 1; d /= 2) {
#pragma GCC unroll 16
        for (std::size_t r = 0; r < Rows; ++r) {
            if (r & d) continue;  // r in the lower half of its block of 2d rows
            for (std::size_t j = std::max<std::size_t>(d, 4); j < kWidth; j += 4) {
                const Vec moved = _mm256_loadu_si256(reinterpret_cast<const Vec*>(buf[r + d] + j - d));
                store(buf[r] + j, _mm256_xor_si256(load(buf[r] + j), moved));
            }
        }
    }
}

// H for columns [c, c + width) of f's rows (each Tau words), zero past Tau, into buf[r][kHalo, ...).
// With Columns, change_basis<4> across the 16 rows first: see taylor.
template <std::size_t Tau, std::size_t Rows, bool Columns>
void block(const u64* f, std::size_t c, std::size_t width, u64 (*buf)[kWidth]) {
    const bool inside = c >= kHalo && width == kBlock;  // c + kBlock <= Tau
    for (std::size_t r = 0; r < Rows; ++r) {
        if (inside) {
            std::memcpy(buf[r], f + r * Tau + c - kHalo, kWidth * sizeof(u64));
            continue;
        }
        for (std::size_t j = 0; j < kWidth; ++j) {
            const std::size_t col = c + j - kHalo;  // wraps below 0
            buf[r][j] = c + j >= kHalo && col < Tau && j < kHalo + width ? f[r * Tau + col] : 0;
        }
    }
    if constexpr (Columns) change_basis4<16, kWidth, kWidth, true>(buf[0]);
    shift<Rows>(buf);
}

// The fixes of columns [0, kHalo) from the high parts; row r starts at f + r * stride.
template <std::size_t Rows, bool Inverse>
void fix_low(u64* f, std::size_t stride, const u64 (*high)[kHalo]) {
    for (std::size_t r = 1; r < Rows; ++r) {
        for (std::size_t e = 0; e < kHalo; ++e) f[r * stride + e] ^= high[r - 1][e];
    }
    if constexpr (!Inverse) {
        for (std::size_t r = 0; r < Rows; ++r) {
            for (std::size_t e = 0; e + 1 < kHalo; ++e) f[r * stride + e + 1] ^= high[r][e];
        }
    }
}

// With Columns, change_basis<4> across the rows (one element per row and column) also runs in
// this pass: after the forward Taylor step, or before the inverse one (Rows = 16 there).
template <std::size_t Tau, std::size_t Rows, bool Inverse, bool Columns>
void taylor(u64* f) {
    static_assert(Tau % kBlock == 0 && (!Columns || !Inverse || Rows == 16));
    constexpr bool before = Columns && Inverse, after = Columns && !Inverse;
    alignas(32) static u64 buf[Rows][kWidth];
    alignas(32) static u64 high[Rows][kHalo];
    block<Tau, Rows, before>(f, Tau, 0, buf);
    for (std::size_t r = 0; r < Rows; ++r) std::memcpy(high[r], buf[r] + kHalo, sizeof(high[r]));
    for (std::size_t c = Tau; c > 0;) {
        c -= kBlock;
        block<Tau, Rows, before>(f, c, kBlock, buf);
        if constexpr (after) {
            if (c == 0) fix_low<Rows, false>(buf[0] + kHalo, kWidth, high);
            change_basis4<Rows, kBlock, kWidth, false>(buf[0] + kHalo);
        }
        for (std::size_t r = 0; r < Rows; ++r) std::memcpy(f + r * Tau + c, buf[r] + kHalo, kBlock * sizeof(u64));
    }
    if constexpr (!after) fix_low<Rows, Inverse>(f, Tau, high);
}

template <std::size_t Tau, bool Inverse, bool Columns>
void taylor(u64* f, std::size_t rows) {
    switch (rows) {
    case 2: return taylor<Tau, 2, Inverse, Columns>(f);
    case 4: return taylor<Tau, 4, Inverse, Columns>(f);
    case 8: return taylor<Tau, 8, Inverse, Columns>(f);
    case 16: return taylor<Tau, 16, Inverse, Columns>(f);
    }
}

}  // namespace wide

// The Taylor step for 16 rows of Tau elements of E words (rows Stride words apart), in one pass.
// In sheared columns g_r[J] = f_r[J - r], the shift H of wide:: becomes G_k[J] = sum over r with
// k's bits among r's of g_r[J], with H_k[c] = G_k[c + k]. Sheared column J reads f_r[J - r] and
// writes H_k[J - k] to the same places, except H_k[Tau + i] (i < 15), which is xored straight into
// the low columns as the fixes of wide::taylor.
inline void superset_sums(Vec* x) {
#pragma GCC unroll 4
    for (std::size_t bit = 1; bit < 16; bit *= 2) {
#pragma GCC unroll 16
        for (std::size_t k = 0; k < 16; ++k) {
            if (!(k & bit)) x[k] = _mm256_xor_si256(x[k], x[k | bit]);
        }
    }
}

template <std::size_t Tau, std::size_t E, std::size_t Stride, bool Inverse>
void sheared_taylor(u64* f) {
    static_assert(Tau >= 16 && E % 4 == 0);
    const auto at = [f](std::size_t r, std::size_t c) { return f + r * Stride + c * E; };
    for (std::size_t j = 15; j < Tau; ++j) {
        for (std::size_t q = 0; q < E; q += 4) {
            Vec x[16];
#pragma GCC unroll 16
            for (std::size_t r = 0; r < 16; ++r) x[r] = load(at(r, j - r) + q);
            superset_sums(x);
#pragma GCC unroll 16
            for (std::size_t k = 0; k < 16; ++k) store(at(k, j - k) + q, x[k]);
        }
    }
    // Partial columns: rows r <= j with j - r < Tau; H_k[c] = 0 for c < 0.
    for (std::size_t n = 0; n < 30; ++n) {
        const std::size_t j = n < 15 ? n : Tau + n - 15;
        for (std::size_t q = 0; q < E; q += 4) {
            Vec x[16];
            for (std::size_t r = 0; r < 16; ++r) {
                x[r] = r <= j && j - r < Tau ? load(at(r, j - r) + q) : _mm256_setzero_si256();
            }
            superset_sums(x);
            for (std::size_t k = 0; k <= std::min<std::size_t>(j, 15); ++k) {
                const std::size_t c = j - k;
                if (c < Tau) {
                    store(at(k, c) + q, x[k]);
                    continue;
                }
                if (k < 15) store(at(k + 1, c - Tau) + q, _mm256_xor_si256(load(at(k + 1, c - Tau) + q), x[k]));
                if (!Inverse) store(at(k, c - Tau + 1) + q, _mm256_xor_si256(load(at(k, c - Tau + 1) + q), x[k]));
            }
        }
    }
}

// f[0, Len) = sum_m g_m(x) t^m with t = x^Tau + x, deg g_m < Tau: g_m in f[m * Tau, (m + 1) * Tau).
// With A, B the halves and d = Len / 2 / Tau: x^(Len/2) = t^d + x^d, so
// f = (A + x^d B_low + x^d B_high) + t^d (B + B_high), B_high the top d entries of B.
template <std::size_t Len, std::size_t Tau, std::size_t W, std::size_t S, bool Inverse>
void taylor(u64* f, std::size_t size) {
    if constexpr (W == 1 && S == 1 && Tau >= 4096 && Len / Tau <= 16) {
        const std::size_t rows = Inverse ? Len / Tau : std::bit_ceil((size + Tau - 1) / Tau);
        if (rows > 1) wide::taylor<Tau, Inverse, false>(f, rows);
    } else if constexpr (Len > Tau) {
        constexpr std::size_t half = Len / 2, d = half / Tau;
        u64* a = f;
        u64* b = f + half * S;
        if constexpr (Inverse) {
            taylor<half, Tau, W, S, true>(a, half);
            taylor<half, Tau, W, S, true>(b, half);
            xor_rows<W, S>(b, b + (half - d) * S, d);
            xor_rows<W, S>(a + d * S, b, half - d);
            xor_rows<W, S>(a + d * S, b + (half - d) * S, d);
        } else {
            if (size <= half) return taylor<half, Tau, W, S, false>(a, size);
            xor_rows<W, S>(a + d * S, b, half - d);
            xor_rows<W, S>(a + d * S, b + (half - d) * S, d);
            xor_rows<W, S>(b, b + (half - d) * S, d);
            taylor<half, Tau, W, S, false>(a, half);
            taylor<half, Tau, W, S, false>(b, size - half);
        }
    }
}

constexpr std::size_t kColumnWords = 8192;  // column passes run on blocks of at most 64 KiB

template <int L, std::size_t W, std::size_t S, bool Inverse>
void change_basis(u64* f, std::size_t size);

// The column step of change_basis<L>: rows [0, used) of 2^(L-K) rows, each Tau elements.
// Rows of at least kGatherWords words: column slices of two cache lines are copied into two
// contiguous buffers of one line per row, transformed there and copied back (long strides alias
// in L1 and L2; fewer, wider visits per row cost less). Shorter contiguous rows are cut into
// column blocks; all column stages run per block.
constexpr std::size_t kGatherWords = 256, kLine = 8, kLines = 2;

template <int L, int K, std::size_t W, std::size_t S, bool Inverse>
void change_columns(u64* f, std::size_t used) {
    constexpr std::size_t tau = std::size_t(1) << K, width = tau * W, rows = std::size_t(1) << (L - K);
    if constexpr (W == S && width >= kGatherWords) {
        alignas(64) static u64 buf[kLines][rows * kLine];
        for (std::size_t p = 0; p < width; p += kLines * kLine) {
            for (std::size_t r = 0; r < used; ++r) {
                for (std::size_t k = 0; k < kLines * kLine; k += 4) store(buf[k / kLine] + r * kLine + k % kLine, load(f + r * width + p + k));
            }
            for (std::size_t h = 0; h < kLines; ++h) {
                std::memset(buf[h] + used * kLine, 0, (rows - used) * kLine * sizeof(u64));
                change_basis<L - K, kLine, kLine, Inverse>(buf[h], used);
            }
            for (std::size_t r = 0; r < used; ++r) {
                for (std::size_t k = 0; k < kLines * kLine; k += 4) store(f + r * width + p + k, load(buf[k / kLine] + r * kLine + k % kLine));
            }
        }
    } else if constexpr (W == S) {
        constexpr std::size_t chunk = std::min(width, std::max<std::size_t>(kColumnWords / rows, 4));
        for (std::size_t p = 0; p < width; p += chunk) change_basis<L - K, chunk, width, Inverse>(f + p, used);
    } else {
        for (std::size_t p = 0; p < tau; ++p) change_basis<L - K, W, tau * S, Inverse>(f + p * S, used);
    }
}

// x[0, 4) to [x0[k], x1[k], x2[k], x3[k]] for k < 4.
inline void transpose4(Vec& x0, Vec& x1, Vec& x2, Vec& x3) {
    const Vec t0 = _mm256_unpacklo_epi64(x0, x1), t1 = _mm256_unpackhi_epi64(x0, x1);
    const Vec t2 = _mm256_unpacklo_epi64(x2, x3), t3 = _mm256_unpackhi_epi64(x2, x3);
    x0 = _mm256_permute2x128_si256(t0, t2, 0x20);
    x1 = _mm256_permute2x128_si256(t1, t3, 0x20);
    x2 = _mm256_permute2x128_si256(t0, t2, 0x31);
    x3 = _mm256_permute2x128_si256(t1, t3, 0x31);
}

// Four rows of Tau words, f[r * Tau + k], to buf[4 * k + r], or back.
template <std::size_t Tau, bool Back>
void transpose_rows(u64* f, u64* buf) {
    for (std::size_t k = 0; k < Tau; k += 4) {
        if constexpr (Back) {
            Vec x0 = load(buf + 4 * k), x1 = load(buf + 4 * k + 4), x2 = load(buf + 4 * k + 8), x3 = load(buf + 4 * k + 12);
            transpose4(x0, x1, x2, x3);
            store(f + k, x0), store(f + Tau + k, x1), store(f + 2 * Tau + k, x2), store(f + 3 * Tau + k, x3);
        } else {
            Vec x0 = load(f + k), x1 = load(f + Tau + k), x2 = load(f + 2 * Tau + k), x3 = load(f + 3 * Tau + k);
            transpose4(x0, x1, x2, x3);
            store(buf + 4 * k, x0), store(buf + 4 * k + 4, x1), store(buf + 4 * k + 8, x2), store(buf + 4 * k + 12, x3);
        }
    }
}

// The row step of change_basis: change_basis<K> on rows [0, used) of Rows rows of 2^K elements.
// Rows of single words go four at a time, transposed, so that every XOR moves a whole vector.
template <int K, std::size_t Rows, std::size_t W, std::size_t S, bool Inverse>
void change_rows(u64* f, std::size_t used) {
    constexpr std::size_t tau = std::size_t(1) << K;
    if constexpr (W == 1 && S == 1 && K >= 2 && K <= 8 && Rows >= 4) {
        alignas(32) static u64 buf[4 * tau];
        for (std::size_t m = 0; m < used; m += 4) {
            transpose_rows<tau, false>(f + m * tau, buf);
            change_basis<K, 4, 4, Inverse>(buf, tau);
            transpose_rows<tau, true>(f + m * tau, buf);
        }
    } else {
        for (std::size_t m = 0; m < used; ++m) change_basis<K, W, S, Inverse>(f + m * tau * S, tau);
    }
}

// Monomial coefficients of f[0, 2^L) to X coefficients (or back). With K = 2^k the largest power
// of two below L: expand in t = s_K = x^(2^K) + x, convert each row g_m (length 2^K), then each
// column (a polynomial in t, whose basis s_i(t) = s_{K + i}(x) for i < L - K <= K).
// The row and column steps commute. For L = 20 the column step runs inside the Taylor pass. For
// L = 16 (rows of 512 KiB, the size of L2) the steps go in three passes: the top four Taylor
// levels, then the bottom four and the row step per 32 KiB block, then the column step.
template <int L, std::size_t W, std::size_t S, bool Inverse>
void change_basis(u64* f, std::size_t size) {
    constexpr int K = L >= 2 ? 1 << (std::bit_width(unsigned(L - 1)) - 1) : 0;
    constexpr std::size_t tau = std::size_t(1) << K, rows = std::size_t(1) << (L - K), len = std::size_t(1) << L;
    const std::size_t used = Inverse ? rows : (size + tau - 1) / tau;  // deg f < size: g_m = 0 for m >= used
    if constexpr (L == 4 && W % 4 == 0 && Inverse) {
        change_basis4<16, W, S, true>(f);
    } else if constexpr (L == 4 && W % 4 == 0) {
        if (size > 8) return change_basis4<16, W, S, false>(f);
        change_basis4<8, W, S, false>(f);
    } else if constexpr (W == 1 && S == 1 && L - K == 4 && tau >= 4096) {
        if constexpr (Inverse) {
            change_rows<K, rows, W, S, true>(f, rows);
            wide::taylor<tau, rows, true, true>(f);
        } else {
            if (used > 1) wide::taylor<tau, false, true>(f, std::bit_ceil(used));
            change_rows<K, rows, W, S, false>(f, used);
        }
    } else if constexpr (W == 1 && S == 1 && L == 16) {
        constexpr std::size_t block = 16 * tau;
        if constexpr (Inverse) change_columns<L, K, W, S, true>(f, rows);
        if constexpr (!Inverse) sheared_taylor<tau, 16, block, false>(f);
        for (std::size_t b = 0; b < len; b += block) {
            if constexpr (!Inverse) taylor<block, tau, W, S, false>(f + b, block);
            change_rows<K, 16, W, S, Inverse>(f + b, 16);
            if constexpr (Inverse) taylor<block, tau, W, S, true>(f + b, block);
        }
        if constexpr (Inverse) sheared_taylor<tau, 16, block, true>(f);
        if constexpr (!Inverse) change_columns<L, K, W, S, false>(f, rows);
    } else if constexpr (L >= 2) {
        if constexpr (Inverse) {
            change_columns<L, K, W, S, true>(f, rows);
            change_rows<K, rows, W, S, true>(f, rows);
            taylor<len, tau, W, S, true>(f, len);
        } else {
            taylor<len, tau, W, S, false>(f, size);
            change_rows<K, rows, W, S, false>(f, used);
            change_columns<L, K, W, S, false>(f, used);
        }
    }
}

// f[0, 2^l), of which [size, 2^l) is zero for the forward change.
template <bool Inverse, int L = kMaxLog>
void change_basis(u64* f, int l, std::size_t size) {
    if constexpr (L >= kMinLog) {
        if (l == L) return change_basis<L, 1, 1, Inverse>(f, size);
        change_basis<Inverse, L - 1>(f, l, size);
    }
}

// The transform. Stage i maps the halves (u, v) of each block of 2^(i+1) at c to
// (u + w v, u + w v + v), w = omega_{c >> i}; the inverse undoes the stages in reverse order.
// Blocks of 2^kBlockLog words (32 KiB) run breadth first; above, depth first. Most passes do three
// stages, some two or one.

constexpr int kBlockLog = 12;

inline void stage_forward(u64* u, std::size_t half, u64 w) {
    const Vec tw = broadcast(w);
    u64* v = u + half;
    for (std::size_t j = 0; j < half; j += 4) {
        const Vec x = multiply_add(load(u + j), load(v + j), tw);
        store(u + j, x);
        store(v + j, _mm256_xor_si256(load(v + j), x));
    }
}

inline void stage_inverse(u64* u, std::size_t half, u64 w) {
    const Vec tw = broadcast(w);
    u64* v = u + half;
    for (std::size_t j = 0; j < half; j += 4) {
        const Vec y = _mm256_xor_si256(load(u + j), load(v + j));
        store(v + j, y);
        store(u + j, multiply_add(load(u + j), y, tw));
    }
}

// Stages i and i - 1 of the block p = d + c of 2^(i+1) words, in quarters x0..x3.
struct PairTwiddles {
    Vec outer, low, high;  // stage i; stage i - 1 on (x0, x1) and on (x2, x3)
};

inline PairTwiddles pair_twiddles(std::size_t c, int i) {
    const std::size_t q = std::size_t(1) << (i - 1);
    return {broadcast(omega(c >> i)), broadcast(omega(c >> (i - 1))), broadcast(omega((c + 2 * q) >> (i - 1)))};
}

void stages_forward(u64* p, std::size_t c, int i) {
    const std::size_t q = std::size_t(1) << (i - 1);
    const PairTwiddles t = pair_twiddles(c, i);
    for (std::size_t j = 0; j < q; j += 4) {
        Vec x0 = load(p + j), x1 = load(p + q + j), x2 = load(p + 2 * q + j), x3 = load(p + 3 * q + j);
        x0 = multiply_add(x0, x2, t.outer);
        x1 = multiply_add(x1, x3, t.outer);
        x2 = _mm256_xor_si256(x2, x0);
        x3 = _mm256_xor_si256(x3, x1);
        x0 = multiply_add(x0, x1, t.low);
        x2 = multiply_add(x2, x3, t.high);
        store(p + j, x0);
        store(p + q + j, _mm256_xor_si256(x1, x0));
        store(p + 2 * q + j, x2);
        store(p + 3 * q + j, _mm256_xor_si256(x3, x2));
    }
}

void stages_inverse(u64* p, std::size_t c, int i) {
    const std::size_t q = std::size_t(1) << (i - 1);
    const PairTwiddles t = pair_twiddles(c, i);
    for (std::size_t j = 0; j < q; j += 4) {
        Vec x0 = load(p + j), x1 = load(p + q + j), x2 = load(p + 2 * q + j), x3 = load(p + 3 * q + j);
        x1 = _mm256_xor_si256(x1, x0);
        x3 = _mm256_xor_si256(x3, x2);
        x0 = multiply_add(x0, x1, t.low);
        x2 = multiply_add(x2, x3, t.high);
        x2 = _mm256_xor_si256(x2, x0);
        x3 = _mm256_xor_si256(x3, x1);
        store(p + j, multiply_add(x0, x2, t.outer));
        store(p + q + j, multiply_add(x1, x3, t.outer));
        store(p + 2 * q + j, x2);
        store(p + 3 * q + j, x3);
    }
}

// Stages i, i - 1 and i - 2 of the block p = d + c of 2^(i+1) words, in eighths x0..x7: four
// independent products per stage. Stage i - 1 on x4..x7 and stage i - 2 on x2k, x2k+1 shift the
// first twiddle: omega(m + 2h) = omega(m) ^ omega(2h) for even m.
struct TripleTwiddles {
    Vec t2, t1[2], t0[4];
};

inline TripleTwiddles triple_twiddles(std::size_t c, int i) {
    TripleTwiddles t;
    t.t2 = broadcast(omega(c >> i));
    for (std::size_t h = 0; h < 2; ++h) t.t1[h] = broadcast(omega(c >> (i - 1)) ^ kOmega.low[2 * h]);
    for (std::size_t h = 0; h < 4; ++h) t.t0[h] = broadcast(omega(c >> (i - 2)) ^ kOmega.low[2 * h]);
    return t;
}

void triple_forward(u64* p, std::size_t c, int i) {
    const std::size_t q = std::size_t(1) << (i - 2);
    const TripleTwiddles t = triple_twiddles(c, i);
    for (std::size_t j = 0; j < q; j += 4) {
        Vec x[8];
#pragma GCC unroll 8
        for (std::size_t k = 0; k < 8; ++k) x[k] = load(p + k * q + j);
#pragma GCC unroll 4
        for (std::size_t k = 0; k < 4; ++k) x[k] = multiply_add(x[k], x[k + 4], t.t2);
#pragma GCC unroll 4
        for (std::size_t k = 0; k < 4; ++k) x[k + 4] = _mm256_xor_si256(x[k + 4], x[k]);
#pragma GCC unroll 4
        for (std::size_t m = 0; m < 4; ++m) x[m + m / 2 * 2] = multiply_add(x[m + m / 2 * 2], x[m + m / 2 * 2 + 2], t.t1[m / 2]);
#pragma GCC unroll 4
        for (std::size_t m = 0; m < 4; ++m) x[m + m / 2 * 2 + 2] = _mm256_xor_si256(x[m + m / 2 * 2 + 2], x[m + m / 2 * 2]);
#pragma GCC unroll 4
        for (std::size_t k = 0; k < 8; k += 2) x[k] = multiply_add(x[k], x[k + 1], t.t0[k / 2]);
#pragma GCC unroll 4
        for (std::size_t k = 0; k < 8; k += 2) x[k + 1] = _mm256_xor_si256(x[k + 1], x[k]);
#pragma GCC unroll 8
        for (std::size_t k = 0; k < 8; ++k) store(p + k * q + j, x[k]);
    }
}

void triple_inverse(u64* p, std::size_t c, int i) {
    const std::size_t q = std::size_t(1) << (i - 2);
    const TripleTwiddles t = triple_twiddles(c, i);
    for (std::size_t j = 0; j < q; j += 4) {
        Vec x[8];
#pragma GCC unroll 8
        for (std::size_t k = 0; k < 8; ++k) x[k] = load(p + k * q + j);
#pragma GCC unroll 4
        for (std::size_t k = 0; k < 8; k += 2) x[k + 1] = _mm256_xor_si256(x[k + 1], x[k]);
#pragma GCC unroll 4
        for (std::size_t k = 0; k < 8; k += 2) x[k] = multiply_add(x[k], x[k + 1], t.t0[k / 2]);
#pragma GCC unroll 4
        for (std::size_t m = 0; m < 4; ++m) x[m + m / 2 * 2 + 2] = _mm256_xor_si256(x[m + m / 2 * 2 + 2], x[m + m / 2 * 2]);
#pragma GCC unroll 4
        for (std::size_t m = 0; m < 4; ++m) x[m + m / 2 * 2] = multiply_add(x[m + m / 2 * 2], x[m + m / 2 * 2 + 2], t.t1[m / 2]);
#pragma GCC unroll 4
        for (std::size_t k = 0; k < 4; ++k) x[k + 4] = _mm256_xor_si256(x[k + 4], x[k]);
#pragma GCC unroll 4
        for (std::size_t k = 0; k < 4; ++k) x[k] = multiply_add(x[k], x[k + 4], t.t2);
#pragma GCC unroll 8
        for (std::size_t k = 0; k < 8; ++k) store(p + k * q + j, x[k]);
    }
}

// Stages 3 to 0 run in two passes over a block, on groups of 16 words x0..x3 (x[k] = words
// 4k + [0, 4) of the group). Stages 3 and 2 pair whole vectors. For stages 1 and 0 a 4x4
// transpose puts word j of x[k] in lane k of t[j]: stage 1 pairs t[0] with t[2] and t[1] with
// t[3], stage 0 t[0] with t[1] and t[2] with t[3]. The forward transform leaves each group
// transposed and the inverse starts from there; the pointwise product does not care.
//
// Twiddles live in registers. Lane k's twiddle at stage s < 2 is omega((c + 4k + j) >> s) =
// omega((c + j) >> s) ^ omega(4k >> s). From group g to g + 1 the bits g ^ (g + 1) = 2^(t+1) - 1
// flip, t = ctz(g + 1): stage s's twiddle changes by omega((2^(t+1) - 1) << (4 - s)).
alignas(32) constexpr std::array<std::array<u64, 4>, 2> kLaneOmega = [] {
    std::array<std::array<u64, 4>, 2> t{};  // [s][k] = omega(4k >> s)
    for (int s = 0; s < 2; ++s) {
        for (int k = 0; k < 4; ++k) t[s][k] = kOmega.low[(4 * k) >> s];
    }
    return t;
}();

constexpr int kSteps = 17;  // t <= 16 for groups below 2^20; the step after the last one is unused

alignas(32) constexpr std::array<std::array<std::array<u64, 4>, kSteps>, 4> kStep = [] {
    std::array<std::array<std::array<u64, 4>, kSteps>, 4> table{};  // [s][t], four equal lanes
    for (int s = 0; s < 4; ++s) {
        for (int t = 0; t < kSteps; ++t) {
            u64 v = 0;
            for (int b = 4 - s; b <= t + 4 - s && b < kMaxLog; ++b) v ^= kBeta[b];
            table[s][t] = {v, v, v, v};
        }
    }
    return table;
}();

inline void step(Vec& w, int s, std::size_t group) {
    w = _mm256_xor_si256(w, load(kStep[s][std::countr_zero(group + 1)].data()));
}

inline Vec lanes(std::size_t c, int s) {
    return _mm256_xor_si256(broadcast(omega(c >> s)), load(kLaneOmega[s].data()));
}

// (u, v) -> (u + w v, u + w v + v), and back.
inline void butterfly_forward(Vec& u, Vec& v, Vec w) {
    u = multiply_add(u, v, w);
    v = _mm256_xor_si256(v, u);
}

inline void butterfly_inverse(Vec& u, Vec& v, Vec w) {
    v = _mm256_xor_si256(v, u);
    u = multiply_add(u, v, w);
}

inline Vec plus_beta1(Vec w) { return _mm256_xor_si256(w, broadcast(kBeta[1])); }  // omega(m + 2), m % 4 = 0

// Stages 3 and 2, or 1 and 0, of the groups in d[c, end).
template <bool Low>
void group_stages_forward(u64* d, std::size_t c, std::size_t end) {
    Vec w_high = Low ? lanes(c, 1) : broadcast(omega(c >> 3)), w_low = Low ? lanes(c, 0) : broadcast(omega(c >> 2));
    for (std::size_t b = c; b < end; b += 16) {
        u64* p = d + b;
        Vec x0 = load(p), x1 = load(p + 4), x2 = load(p + 8), x3 = load(p + 12);
        if constexpr (Low) transpose4(x0, x1, x2, x3);
        butterfly_forward(x0, x2, w_high);
        butterfly_forward(x1, x3, w_high);
        butterfly_forward(x0, x1, w_low);
        butterfly_forward(x2, x3, plus_beta1(w_low));
        store(p, x0), store(p + 4, x1), store(p + 8, x2), store(p + 12, x3);
        step(w_high, Low ? 1 : 3, b / 16);
        step(w_low, Low ? 0 : 2, b / 16);
    }
}

template <bool Low>
void group_stages_inverse(u64* d, std::size_t c, std::size_t end) {
    Vec w_high = Low ? lanes(c, 1) : broadcast(omega(c >> 3)), w_low = Low ? lanes(c, 0) : broadcast(omega(c >> 2));
    for (std::size_t b = c; b < end; b += 16) {
        u64* p = d + b;
        Vec x0 = load(p), x1 = load(p + 4), x2 = load(p + 8), x3 = load(p + 12);
        butterfly_inverse(x0, x1, w_low);
        butterfly_inverse(x2, x3, plus_beta1(w_low));
        butterfly_inverse(x0, x2, w_high);
        butterfly_inverse(x1, x3, w_high);
        if constexpr (Low) transpose4(x0, x1, x2, x3);
        store(p, x0), store(p + 4, x1), store(p + 8, x2), store(p + 12, x3);
        step(w_high, Low ? 1 : 3, b / 16);
        step(w_low, Low ? 0 : 2, b / 16);
    }
}

// Block d[c, c + 2^(i+1)), 3 <= i < kBlockLog: stages i down to 0 (or back): in triples while
// at least stages 6 to 4 remain, then stages 5 and 4 (or 4 alone), then the group passes.
void forward_block(u64* d, std::size_t c, int i) {
    const std::size_t end = c + (std::size_t(2) << i);
    int s = i;
    for (; s >= 6; s -= 3) {
        for (std::size_t b = c; b < end; b += std::size_t(2) << s) triple_forward(d + b, b, s);
    }
    if (s == 5) {
        for (std::size_t b = c; b < end; b += 64) stages_forward(d + b, b, 5);
    } else if (s == 4) {
        for (std::size_t b = c; b < end; b += 32) stage_forward(d + b, 16, omega(b >> 4));
    }
    group_stages_forward<false>(d, c, end);
    group_stages_forward<true>(d, c, end);
}

void inverse_block(u64* d, std::size_t c, int i) {
    const std::size_t end = c + (std::size_t(2) << i);
    const int low = 3 + (i - 3) % 3;  // the stages above the group passes up to low run below the triples
    group_stages_inverse<true>(d, c, end);
    group_stages_inverse<false>(d, c, end);
    if (low == 5) {
        for (std::size_t b = c; b < end; b += 64) stages_inverse(d + b, b, 5);
    } else if (low == 4) {
        for (std::size_t b = c; b < end; b += 32) stage_inverse(d + b, 16, omega(b >> 4));
    }
    for (int s = low + 3; s <= i; s += 3) {
        for (std::size_t b = c; b < end; b += std::size_t(2) << s) triple_inverse(d + b, b, s);
    }
}

// Block d[c, c + 2^(i+1)), stages i down to 0.
void forward(u64* d, std::size_t c, int i) {
    const std::size_t half = std::size_t(1) << i;
    if (i < kBlockLog) {
        forward_block(d, c, i);
    } else if (i == kBlockLog) {
        stage_forward(d + c, half, omega(c >> i));
        forward(d, c, i - 1);
        forward(d, c + half, i - 1);
    } else if (i < kBlockLog + 3) {
        stages_forward(d + c, c, i);
        for (std::size_t k = 0; k < 4; ++k) forward(d, c + k * half / 2, i - 2);
    } else {
        triple_forward(d + c, c, i);
        for (std::size_t k = 0; k < 8; ++k) forward(d, c + k * half / 4, i - 3);
    }
}

// a[c, c + 2^(i+1)) holds the transform of a; b the X coefficients of b. Transforms b's block,
// multiplies it into a's and transforms a's back, depth first: each block of 2^kBlockLog words
// does all three while in L1.
void multiply_transformed(u64* a, u64* b, std::size_t c, int i) {
    const std::size_t half = std::size_t(1) << i;
    if (i < kBlockLog) {
        forward_block(b, c, i);
        for (std::size_t k = c; k < c + 2 * half; k += 4) store(a + k, multiply(load(a + k), load(b + k)));
        inverse_block(a, c, i);
    } else if (i == kBlockLog) {
        stage_forward(b + c, half, omega(c >> i));
        multiply_transformed(a, b, c, i - 1);
        multiply_transformed(a, b, c + half, i - 1);
        stage_inverse(a + c, half, omega(c >> i));
    } else if (i < kBlockLog + 3) {
        stages_forward(b + c, c, i);
        for (std::size_t k = 0; k < 4; ++k) multiply_transformed(a, b, c + k * half / 2, i - 2);
        stages_inverse(a + c, c, i);
    } else {
        triple_forward(b + c, c, i);
        for (std::size_t k = 0; k < 8; ++k) multiply_transformed(a, b, c + k * half / 4, i - 3);
        triple_inverse(a + c, c, i);
    }
}

// words u64 words, 2 MiB aligned and zeroed, in huge pages where the kernel allows.
u64* allocate(std::size_t words) {
    constexpr std::size_t kHuge = std::size_t(1) << 21;
    const std::size_t bytes = (words * sizeof(u64) + kHuge - 1) / kHuge * kHuge + kHuge;
    void* region = ::mmap(nullptr, bytes, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    if (region == MAP_FAILED) std::abort();
    const std::uintptr_t start = (reinterpret_cast<std::uintptr_t>(region) + kHuge - 1) & ~(kHuge - 1);
#ifdef MADV_HUGEPAGE
    ::madvise(reinterpret_cast<void*>(start), bytes - kHuge, MADV_HUGEPAGE);
#endif
    return reinterpret_cast<u64*>(start);
}

// a * b, the product left in a[0, n + m - 1). a and b hold 2^l words each, zero past n and m.
void convolve(u64* a, std::size_t n, u64* b, std::size_t m, int l) {
    const std::size_t half = std::size_t(1) << (l - 1);
    change_basis<false>(a, l, n);
    change_basis<false>(b, l, m);
    // The top stage has twiddle omega_0 = 0: (u, v) -> (u, u + v). With v = 0 it copies u.
    if (l - 1 > kBlockLog && n <= half) {
        std::memcpy(a + half, a, half * sizeof(u64));
        forward(a, 0, l - 2);
        forward(a, half, l - 2);
    } else {
        forward(a, 0, l - 1);
    }
    if (l - 1 > kBlockLog && m <= half) {
        std::memcpy(b + half, b, half * sizeof(u64));
        multiply_transformed(a, b, 0, l - 2);
        multiply_transformed(a, b, half, l - 2);
        stage_inverse(a, half, 0);
    } else {
        multiply_transformed(a, b, 0, l - 1);
    }
    change_basis<true>(a, l, std::size_t(1) << l);
}

void solve() {
    io::Reader in;
    const std::size_t n = in.read<std::uint32_t>(), m = in.read<std::uint32_t>();
    const int l = std::max(kMinLog, int(std::bit_width(n + m - 2)));
    u64* a = allocate(std::size_t(2) << l);
    u64* b = a + (std::size_t(1) << l);
    io::read_bulk(in, a, n);
    io::read_bulk(in, b, m);
    convolve(a, n, b, m, l);
    io::Writer out;
    fields::write(out, a, n + m - 1);
}

#ifdef __ELF__
// The program runs from the executable's pre-initializers, before the C++ runtime initializes
// iostreams and locales (unused here). _exit skips their teardown too.
void run_early(int, char**, char**) {
    solve();
    ::_exit(0);
}

[[gnu::used, gnu::section(".preinit_array")]] void (*const preinit)(int, char**, char**) = run_early;
#endif

}  // namespace

int main() { solve(); }  // reached only without .preinit_array support
