// Generated by tools/bundle.py from problems/convolution/min_plus_convolution_convex_arbitrary/solution.cpp. Edit that file instead.
// c[k] = min over i + j = k of a[i] + b[j], a convex. f_k(j) = b[j] + a[k - j] on the valid columns
// max(0, k - N + 1) <= j <= min(k, M - 1) is Monge: for rows k < k' and columns i < j valid in both,
// f_k'(j) - f_k'(i) <= f_k(j) - f_k(i). So the leftmost argmin opt(k) is nondecreasing in k, and
// between rows k < k' a column j can be opt only if it is invalid in k' or below every column
// i < j valid in k' (a strict prefix record of row k'), and invalid in k or at most every column
// i > j valid in k (a suffix minimum of row k).
//
// opt is found at every kGroup-th row (sample rows), coarse rows first. Each node of the bisection
// holds the candidates for the rows strictly between its two ends: a dense range of columns, or a
// sorted list when the middle row's records are sparse (scans give up on dense records). A node
// whose ends share their opt is settled. Each group of kGroup rows then takes its minima over its
// node's candidates, kGroup rows per column, one output block at a time.
// Wide ranges skip blocks of kBlock columns by a lower bound: the least b in the block plus the
// least a over the two aligned kBlock-windows of a that the block reads in the row.
// lib/io/io.hpp
// Fast integer and text I/O on file descriptors (stdin and stdout by default).
// Linux, x86-64 with AVX2. Design and measurements: lib/io/notes.md.
//
//   io::Reader in;                            // takes all of stdin
//   io::Writer out;                           // flushes in its destructor
//   const auto n = in.read<std::uint32_t>();
//   std::vector<std::uint32_t> a(n);
//   in.read(a.data(), n);                     // bulk; AVX2 for uint32_t
//   const auto s = in.read<std::uint64_t, 16>();  // promise: at most 16 digits (faster)
//   out.write("n = ", n, '\n');               // any mix of integers, chars, strings
//   out.write<16>(s, '\n');                   // promise: integers of at most 16 digits
//   out.write_array(a.data(), n, ' ');        // bulk; AVX2 for uint32_t
//   out.write('\n');
//
// Input: tokens separated by whitespace (any bytes <= ' '). Integer tokens are an optional '-'
// (signed types only) followed by decimal digits, and fit the requested type. Reading past the
// last token is undefined. The 64 bytes before the input and after its end are readable zeros, so
// custom parsers may load up to 64 bytes around any token from word().

#include <fcntl.h>
#include <immintrin.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>

#include <algorithm>
#include <array>
#include <bit>
#include <cerrno>
#include <concepts>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <string_view>
#include <type_traits>

namespace io {
namespace detail {

// Zero bytes before and after the input. Loads reach at most 63 bytes past either end.
inline constexpr std::size_t kPadding = 64;
inline constexpr std::size_t kPage = 4096;

// Input as mapped or read: data [start, end), kPadding zero bytes before and after it.
struct Input {
    char* base;           // allocation or mapping to release
    std::size_t mapped;   // bytes mapped, or 0 for a heap buffer
    const char* start;
    const char* end;
};

inline Input map_input(int fd, std::size_t size) {
    const off_t offset = ::lseek(fd, 0, SEEK_CUR);
    if (offset < 0 || std::size_t(offset) >= size) return {};
    // One anonymous zero page before the file. After it, the rest of the last file page reads as
    // zero; if fewer than kPadding bytes remain, one more anonymous page follows.
    const std::size_t file_bytes = (size + kPage - 1) & ~(kPage - 1);
    const std::size_t mapped = kPage + file_bytes + (file_bytes - size < kPadding ? kPage : 0);
    void* base = ::mmap(nullptr, mapped, PROT_READ, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    if (base == MAP_FAILED) return {};
    char* const file = static_cast<char*>(base) + kPage;
    if (::mmap(file, file_bytes, PROT_READ, MAP_PRIVATE | MAP_FIXED, fd, 0) == MAP_FAILED) {
        ::munmap(base, mapped);
        return {};
    }
    return {static_cast<char*>(base), mapped, file + offset, file + size};
}

// Capacity bytes for data, with kPadding bytes before and after; returns the data start.
inline char* allocate(std::size_t capacity) {
    auto* p = static_cast<char*>(std::aligned_alloc(64, capacity + 2 * kPadding));
    if (!p) std::abort();
    std::memset(p, 0, kPadding);
    return p + kPadding;
}

// Reads fd until end of file, or until size bytes for a regular file of that size.
inline Input read_input(int fd, std::size_t size = std::size_t(-1)) {
    std::size_t done = 0, capacity = std::size_t(1) << 16;
    char* data = allocate(capacity);
    while (done < size) {
        if (done == capacity) {
            char* bigger = allocate(capacity *= 2);
            std::memcpy(bigger, data, done);
            std::free(data - kPadding);
            data = bigger;
        }
        const ssize_t got = ::read(fd, data + done, capacity - done);
        if (got > 0) done += std::size_t(got);
        else if (got == 0) break;
        else if (errno != EINTR) std::abort();
    }
    std::memset(data + done, 0, kPadding);
    return {data - kPadding, 0, data, data + done};
}

// Files over kMapAbove bytes are mapped; smaller ones and other inputs are read, which takes
// fewer system calls.
inline constexpr std::size_t kMapAbove = std::size_t(1) << 16;

inline Input open_input(int fd) {
    struct stat st;
    if (::fstat(fd, &st) == 0 && S_ISREG(st.st_mode)) {
        const auto size = std::size_t(st.st_size);
        if (size <= kMapAbove) return read_input(fd, size);
        if (const Input input = map_input(fd, size); input.base) return input;
    }
    return read_input(fd);
}

inline void release(const Input& input) {
    if (input.mapped) ::munmap(input.base, input.mapped);
    else std::free(input.base);
}

// Bit i set iff byte i is whitespace (<= ' ').
inline unsigned separators(__m128i bytes) {
    return unsigned(_mm_movemask_epi8(_mm_cmpgt_epi8(_mm_set1_epi8(' ' + 1), bytes)));
}

inline std::uint32_t separators(__m256i bytes) {
    return std::uint32_t(_mm256_movemask_epi8(_mm256_cmpgt_epi8(_mm256_set1_epi8(' ' + 1), bytes)));
}

// Separators in the 64-byte aligned block.
inline std::uint64_t block_separators(const char* block) {
    const std::uint64_t low = separators(_mm256_load_si256(reinterpret_cast<const __m256i*>(block)));
    const std::uint64_t high = separators(_mm256_load_si256(reinterpret_cast<const __m256i*>(block + 32)));
    return low | high << 32;
}

// The 16 bytes at kRightAlign[n + 1] move the first n bytes (1 <= n <= 16) of a 16-byte window
// to its end and zero the rest: byte k + 1 is k - 16 for 16 <= k < 32, else -128. For the other
// lengths (-1, 0, 17..32) byte 15 of the window is negative, which marks the token as invalid.
alignas(64) inline constexpr auto kRightAlign = [] {
    std::array<std::int8_t, 64> t{};
    for (int k = -1; k < 63; ++k) t[k + 1] = k >= 16 && k < 32 ? std::int8_t(k - 16) : std::int8_t(-128);
    return t;
}();

// Shuffle control for a token of length index - 1.
inline __m128i align_row(std::size_t index) {
    return _mm_loadu_si128(reinterpret_cast<const __m128i*>(kRightAlign.data() + index));
}

// Right-aligned digits (byte values 0..9) -> 4-digit groups, one per dword.
inline __m128i digit_groups(__m128i digits) {
    return _mm_madd_epi16(_mm_maddubs_epi16(digits, _mm_set1_epi16(0x010A)), _mm_set1_epi32(0x00010064));
}

inline __m256i digit_groups(__m256i digits) {
    return _mm256_madd_epi16(_mm256_maddubs_epi16(digits, _mm256_set1_epi16(0x010A)), _mm256_set1_epi32(0x00010064));
}

// Value of the first n digits (0 <= n <= 16) of the window. Result < 10^16.
inline std::uint64_t parse16(__m128i window, unsigned n) {
    const __m128i digits = _mm_shuffle_epi8(_mm_subs_epu8(window, _mm_set1_epi8('0')), align_row(n + 1));
    const __m128i groups = digit_groups(digits);
    const __m128i halves = _mm_madd_epi16(_mm_packus_epi32(groups, groups), _mm_set1_epi32(0x00012710));
    const auto both = std::uint64_t(_mm_cvtsi128_si64(halves));  // 8-digit halves, high one first
    return (both & 0xFFFFFFFF) * 100000000 + (both >> 32);
}

// kKeep[32 - k..64 - k) keeps the last k bytes of 32.
alignas(64) inline constexpr auto kKeep = [] {
    std::array<std::uint8_t, 64> t{};
    for (std::size_t i = 32; i < 64; ++i) t[i] = 0xFF;
    return t;
}();

// Value of the n <= 16 digits that end at end. Bytes below '0' before them (a sign) count as 0.
inline std::uint64_t parse_ending16(const char* end, unsigned n) {
    const __m128i bytes = _mm_loadu_si128(reinterpret_cast<const __m128i*>(end - 16));
    const __m128i keep = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kKeep.data() + 16 + n));
    const __m128i groups = digit_groups(_mm_and_si128(_mm_subs_epu8(bytes, _mm_set1_epi8('0')), keep));
    const __m128i halves = _mm_madd_epi16(_mm_packus_epi32(groups, groups), _mm_set1_epi32(0x00012710));
    const auto both = std::uint64_t(_mm_cvtsi128_si64(halves));  // 8-digit halves, high one first
    return (both & 0xFFFFFFFF) * 100000000 + (both >> 32);
}

// Value of the n <= 24 digits that end at end; at most 20 for a result below 2^64.
inline std::uint64_t parse_ending24(const char* end, unsigned n) {
    const __m256i bytes = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(end - 32));
    const __m256i keep = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(kKeep.data() + n));
    const __m256i groups = digit_groups(_mm256_and_si256(_mm256_subs_epu8(bytes, _mm256_set1_epi8('0')), keep));
    // 8-digit quarters; the first is 0. Dword 1 of the low lane, dwords 0 and 1 of the high lane.
    const __m256i quarters = _mm256_madd_epi16(_mm256_packus_epi32(groups, groups), _mm256_set1_epi32(0x00012710));
    const std::uint64_t high = std::uint64_t(_mm256_extract_epi64(quarters, 0)) >> 32;
    const auto low = std::uint64_t(_mm256_extract_epi64(quarters, 2));
    return (high * 100000000 + (low & 0xFFFFFFFF)) * 100000000 + (low >> 32);
}

// kQuad[x] for x < 10^4: its 4 digits with leading zeros, first digit in the lowest byte.
alignas(64) inline constexpr auto kQuad = [] {
    std::array<std::uint32_t, 10000> t{};
    for (std::uint32_t x = 0; x < t.size(); ++x)
        t[x] = ('0' + x / 1000) | ('0' + x / 100 % 10) << 8 | ('0' + x / 10 % 10) << 16 | ('0' + x % 10) << 24;
    return t;
}();

// Digits of x (x >= 1) = (x + kDigitCount32[floor(log2(x))]) >> 32: the low word of an entry
// carries into the high word exactly when x reaches the next power of ten.
inline constexpr auto kDigitCount32 = [] {
    std::array<std::uint64_t, 32> t{};
    for (int i = 0; i < 32; ++i) {
        const std::uint64_t low = std::uint64_t(1) << i, high = 2 * low - 1;
        std::uint64_t digits = 0, power = 1;
        while (power <= low) power *= 10, ++digits;
        t[i] = (digits << 32) + (power <= high ? (std::uint64_t(1) << 32) - power : 0);
    }
    return t;
}();

inline unsigned digit_count(std::uint32_t x) {
    return unsigned((x + kDigitCount32[31 - std::countl_zero(x | 1)]) >> 32);
}

// Digits of x = kDigitCount64[0][b] + (x > kDigitCount64[1][b]), where b = bit width of x | 1.
inline constexpr auto kDigitCount64 = [] {
    std::array<std::array<std::uint64_t, 65>, 2> t{};
    for (int b = 1; b <= 64; ++b) {
        const unsigned __int128 low = (unsigned __int128)1 << (b - 1), high = 2 * low - 1;
        std::uint64_t digits = 1;
        unsigned __int128 power = 10;
        while (power <= low) power *= 10, ++digits;
        t[0][b] = digits;
        t[1][b] = power <= high ? std::uint64_t(power - 1) : ~std::uint64_t(0);
    }
    return t;
}();

inline unsigned digit_count(std::uint64_t x) {
    const int b = std::bit_width(x | 1);
    return unsigned(kDigitCount64[0][b] + (x > kDigitCount64[1][b]));
}

// Bytes kShiftWindow[k..k + 16) shuffle a vector down by k bytes.
alignas(32) inline constexpr std::int8_t kShiftWindow[32] = {0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  10,
                                                             11, 12, 13, 14, 15, -1, -1, -1, -1, -1, -1,
                                                             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1};

inline __m128i shift_down(__m128i v, unsigned k) {
    return _mm_shuffle_epi8(v, _mm_loadu_si128(reinterpret_cast<const __m128i*>(kShiftWindow + k)));
}

// Writes x in decimal at p and returns the end. Stores 16 bytes.
inline char* format(char* p, std::uint32_t x) {
    // Twelve digits with leading zeros, as three groups of four, then shifted down past the zeros.
    const std::uint32_t top = x / 100000000, rest = x % 100000000;
    const std::uint32_t high = rest / 10000, low = rest % 10000;
    const __m128i digits = _mm_insert_epi32(
        _mm_cvtsi64_si128(std::int64_t(kQuad[top] | std::uint64_t(kQuad[high]) << 32)), int(kQuad[low]), 2);
    const unsigned n = digit_count(x);
    _mm_storeu_si128(reinterpret_cast<__m128i*>(p), shift_down(digits, 12 - n));
    return p + n;
}

// high, low < 10^8 as 16 digits with leading zeros.
inline __m128i sixteen_digits(std::uint32_t high, std::uint32_t low) {
    return _mm_set_epi64x(std::int64_t(kQuad[low / 10000] | std::uint64_t(kQuad[low % 10000]) << 32),
                          std::int64_t(kQuad[high / 10000] | std::uint64_t(kQuad[high % 10000]) << 32));
}

// Writes x in decimal at p and returns the end. Stores up to 20 bytes. MaxDigits <= 16 promises
// x < 10^16, which saves a division.
template <int MaxDigits>
inline char* format64(char* p, std::uint64_t x) {
    const std::uint64_t q = x / 100000000;  // < 1.9 * 10^11
    const auto low = std::uint32_t(x - q * 100000000);
    const unsigned n = digit_count(x);
    if constexpr (MaxDigits <= 16) {
        _mm_storeu_si128(reinterpret_cast<__m128i*>(p), shift_down(sixteen_digits(std::uint32_t(q), low), 16 - n));
        return p + n;
    } else {
        // Twenty digits with leading zeros: a head of four, then sixteen.
        const auto top = std::uint32_t(q / 100000000);  // < 1845
        const auto middle = std::uint32_t(q - std::uint64_t(top) * 100000000);
        const unsigned head = n > 16 ? n - 16 : 0;
        const auto head_digits = std::uint32_t(std::uint64_t(kQuad[top]) >> (32 - 8 * head));
        std::memcpy(p, &head_digits, 4);
        _mm_storeu_si128(reinterpret_cast<__m128i*>(p + head), shift_down(sixteen_digits(middle, low), 16 - (n - head)));
        return p + n;
    }
}

// floor(x / d) for every dword x, as (x * Magic) >> Shift. The test checks each use exhaustively.
template <std::uint32_t Magic, int Shift>
inline __m256i divide(__m256i x) {
    const __m256i magic = _mm256_set1_epi64x(Magic);
    const __m256i even = _mm256_srli_epi64(_mm256_mul_epu32(x, magic), Shift);
    const __m256i odd = _mm256_srli_epi64(_mm256_mul_epu32(_mm256_srli_epi64(x, 32), magic), Shift);
    return _mm256_blend_epi32(even, _mm256_slli_epi64(odd, 32), 0xAA);
}

// Each dword g < 10^4 -> its 4 ASCII digits, first digit in the lowest byte.
inline __m256i quad_digits(__m256i g) {
    const __m256i high = _mm256_srli_epi16(_mm256_mulhi_epu16(g, _mm256_set1_epi16(5243)), 3);  // g / 100
    const __m256i low = _mm256_sub_epi16(g, _mm256_mullo_epi16(high, _mm256_set1_epi16(100)));
    const __m256i pairs = _mm256_or_si256(high, _mm256_slli_epi32(low, 16));  // 16-bit halves < 100
    const __m256i tens = _mm256_mulhi_epu16(pairs, _mm256_set1_epi16(6554));  // pair / 10
    const __m256i units = _mm256_sub_epi16(pairs, _mm256_mullo_epi16(tens, _mm256_set1_epi16(10)));
    return _mm256_or_si256(_mm256_or_si256(tens, _mm256_slli_epi16(units, 8)), _mm256_set1_epi8('0'));
}

// Digit counts of the eight dwords of v, one per byte in order.
inline std::uint64_t digit_counts(__m256i v) {
    // Unsigned v >= 10^k via a signed compare after flipping the sign bits; summed as a tree.
    const __m256i x = _mm256_xor_si256(v, _mm256_set1_epi32(int(0x80000000)));
    const auto at_least = [&](std::uint32_t power) {
        return _mm256_cmpgt_epi32(x, _mm256_set1_epi32(int((power - 1) ^ 0x80000000)));
    };
    const __m256i a = _mm256_add_epi32(_mm256_add_epi32(at_least(10), at_least(100)),
                                       _mm256_add_epi32(at_least(1000), at_least(10000)));
    const __m256i b = _mm256_add_epi32(_mm256_add_epi32(at_least(100000), at_least(1000000)),
                                       _mm256_add_epi32(at_least(10000000), at_least(100000000)));
    const __m256i n = _mm256_sub_epi32(_mm256_sub_epi32(_mm256_set1_epi32(1), at_least(1000000000)),
                                       _mm256_add_epi32(a, b));
    const __m256i bytes = _mm256_packus_epi16(_mm256_packus_epi32(n, n), n);  // per lane: 4 counts first
    return std::uint64_t(_mm256_extract_epi32(bytes, 0)) | std::uint64_t(_mm256_extract_epi32(bytes, 4)) << 32;
}

// Stores the two 16-byte lanes of w, values of 12 digits with leading zeros and a separator, as
// their last n0 and n1 digits and the separator. Returns the end; stores 16 bytes per lane.
inline char* put_pair(char* p, __m256i w, unsigned n0, unsigned n1) {
    const __m256i shifted = _mm256_shuffle_epi8(w, _mm256_loadu2_m128i(
        reinterpret_cast<const __m128i*>(kShiftWindow + 12 - n1), reinterpret_cast<const __m128i*>(kShiftWindow + 12 - n0)));
    _mm_storeu_si128(reinterpret_cast<__m128i*>(p), _mm256_castsi256_si128(shifted));
    p += n0 + 1;
    _mm_storeu_si128(reinterpret_cast<__m128i*>(p), _mm256_extracti128_si256(shifted, 1));
    return p + n1 + 1;
}

// Writes the eight dwords of v in decimal, each followed by separator, and returns the end.
// Stores up to 15 bytes past the end.
inline char* format8(char* p, __m256i v, char separator) {
    // Digit counts first, from v: the store addresses then do not wait for the digits.
    const std::uint64_t n = digit_counts(v);
    // Lanes [v0 v2 v4 v6 | v1 v3 v5 v7], so the transpose below pairs consecutive values.
    v = _mm256_permutevar8x32_epi32(v, _mm256_setr_epi32(0, 2, 4, 6, 1, 3, 5, 7));
    const __m256i top = divide<1441151881, 57>(v);  // v / 10^8
    const __m256i rest = _mm256_sub_epi32(v, _mm256_mullo_epi32(top, _mm256_set1_epi32(100000000)));
    const __m256i high = divide<3518437209, 45>(rest);  // rest / 10^4
    const __m256i low = _mm256_sub_epi32(rest, _mm256_madd_epi16(high, _mm256_set1_epi32(10000)));
    const __m256i t = quad_digits(top), h = quad_digits(high), l = quad_digits(low);
    const __m256i s = _mm256_set1_epi32(static_cast<unsigned char>(separator));
    // Transpose: each 16-byte lane becomes one value as dwords [top, high, low, separator].
    const __m256i th_low = _mm256_unpacklo_epi32(t, h), th_high = _mm256_unpackhi_epi32(t, h);
    const __m256i ls_low = _mm256_unpacklo_epi32(l, s), ls_high = _mm256_unpackhi_epi32(l, s);
    const auto count = [n](int i) { return unsigned(n >> 8 * i & 0xFF); };
    p = put_pair(p, _mm256_unpacklo_epi64(th_low, ls_low), count(0), count(1));
    p = put_pair(p, _mm256_unpackhi_epi64(th_low, ls_low), count(2), count(3));
    p = put_pair(p, _mm256_unpacklo_epi64(th_high, ls_high), count(4), count(5));
    return put_pair(p, _mm256_unpackhi_epi64(th_high, ls_high), count(6), count(7));
}

// Parses uint32 tokens from the token at p into dst: at most count, from input that is valid up
// to limit. Stops when fewer than kMinTokens tokens or 1 KiB of input remain. Returns where it
// stopped and the tokens parsed. Each chunk of input is cut
// into four streams at token boundaries. The streams advance in lockstep, two tokens per step, so
// four independent pointer chains overlap.
class BulkParser {
public:
    static constexpr std::size_t kMinTokens = 1024;

    struct Result {
        const char* end;
        std::size_t parsed;
    };

    static Result parse(const char* p, const char* limit, std::uint32_t* dst, std::size_t count) {
        std::uint32_t* const first = dst;
        while (count >= kMinTokens && limit - p >= 1024 + 64) {
            // With tokens of at most 16 bytes a chunk spans at most chunk + 33 bytes, so it holds
            // at most chunk / 2 + 17 < count tokens: all of them belong to this array. It ends
            // before limit.
            const std::size_t chunk =
                std::min({kChunk, 2 * (count - 32), std::size_t(limit - p) - 64}) & ~std::size_t(3);
            const std::size_t stream = chunk / 4;
            const char* s[4] = {p, after_separator(p + stream), after_separator(p + 2 * stream),
                                after_separator(p + 3 * stream)};
            const char* const end[4] = {s[1], s[2], s[3], after_separator(p + chunk)};
            std::uint32_t* const out[4] = {dst, scratch_[0], scratch_[1], scratch_[2]};
            __m256i invalid = _mm256_setzero_si256();
            const std::size_t done = lockstep(s, end, out, invalid);
            std::size_t n[4];
            bool overrun = false;
            for (int k = 0; k < 4; ++k) {
                n[k] = done;
                while (s[k] < end[k] && n[k] < kCapacity) out[k][n[k]++] = one_token(s[k], invalid);
                overrun |= s[k] != end[k];
            }
            if (overrun || (std::uint32_t(_mm256_movemask_epi8(invalid)) & 0x80008000)) [[unlikely]] {
                // Irregular whitespace or tokens: this chunk one token at a time.
                const std::size_t tokens = std::min(count_tokens(p, end[3]), count);
                p = parse_slowly(p, dst, tokens);
                dst += tokens;
                count -= tokens;
                continue;
            }
            std::uint32_t* next = dst + n[0];
            for (int k = 1; k < 4; ++k) {
                std::memcpy(next, out[k], n[k] * sizeof(std::uint32_t));
                next += n[k];
            }
            dst = next;
            count -= n[0] + n[1] + n[2] + n[3];
            p = skip_whitespace(end[3]);
        }
        return {p, std::size_t(dst - first)};
    }

private:
    static constexpr std::size_t kChunk = std::size_t(1) << 17;
    // A step advances a stream by 2..33 bytes and yields two values, so a stream of at most
    // kChunk / 4 + 33 bytes yields at most kChunk / 4 + 66 values.
    static constexpr std::size_t kCapacity = kChunk / 4 + 66;
    alignas(64) static inline std::uint32_t scratch_[3][kCapacity];

    // Steps all streams while each has 33 bytes left; returns the values per stream. Works on
    // local copies of the stream state, which stay in registers.
    static std::size_t lockstep(const char* (&streams)[4], const char* const (&end)[4],
                                std::uint32_t* const (&outputs)[4], __m256i& flags) {
        const char* s[4] = {streams[0], streams[1], streams[2], streams[3]};
        std::uint32_t* const out[4] = {outputs[0], outputs[1], outputs[2], outputs[3]};
        __m256i invalid = flags;
        std::size_t done = 0;
        for (;;) {
            std::ptrdiff_t left = end[0] - s[0];
            for (int k = 1; k < 4; ++k) left = std::min(left, end[k] - s[k]);
            if (left < 33) break;
            for (std::ptrdiff_t steps = left / 33; steps; --steps, done += 2) {
                const __m256i g0 = two_tokens(s[0], invalid), g1 = two_tokens(s[1], invalid);
                const __m256i g2 = two_tokens(s[2], invalid), g3 = two_tokens(s[3], invalid);
                const __m256i k = _mm256_set1_epi32(0x00012710);
                // 8-digit halves: [s0 high, s0 low, s1 high, s1 low | second tokens likewise].
                const __m256 h01 = _mm256_castsi256_ps(_mm256_madd_epi16(_mm256_packus_epi32(g0, g1), k));
                const __m256 h23 = _mm256_castsi256_ps(_mm256_madd_epi16(_mm256_packus_epi32(g2, g3), k));
                const __m256i high = _mm256_castps_si256(_mm256_shuffle_ps(h01, h23, 0x88));
                const __m256i low = _mm256_castps_si256(_mm256_shuffle_ps(h01, h23, 0xDD));
                const __m256i v = _mm256_add_epi32(_mm256_mullo_epi32(high, _mm256_set1_epi32(100000000)), low);
                // [s0 a, s0 b, s1 a, s1 b | s2 a, s2 b, s3 a, s3 b]
                const __m256i q = _mm256_permutevar8x32_epi32(v, _mm256_setr_epi32(0, 4, 1, 5, 2, 6, 3, 7));
                const __m128i q01 = _mm256_castsi256_si128(q), q23 = _mm256_extracti128_si256(q, 1);
                _mm_storel_epi64(reinterpret_cast<__m128i*>(out[0] + done), q01);
                _mm_storeh_pd(reinterpret_cast<double*>(out[1] + done), _mm_castsi128_pd(q01));
                _mm_storel_epi64(reinterpret_cast<__m128i*>(out[2] + done), q23);
                _mm_storeh_pd(reinterpret_cast<double*>(out[3] + done), _mm_castsi128_pd(q23));
            }
        }
        for (int k = 0; k < 4; ++k) streams[k] = s[k];
        flags = invalid;
        return done;
    }

    // Two tokens at s, as 4-digit groups [first | second]. Lengths outside 1..16 (repeated
    // whitespace, long tokens) set the sign bit of byte 15 or 31 of invalid.
    [[gnu::always_inline]] static __m256i two_tokens(const char*& s, __m256i& invalid) {
        const __m256i bytes = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(s));
        const std::uint32_t sep = separators(bytes);
        const auto first = std::size_t(std::countr_zero(sep));              // length of the first token
        const auto second = std::size_t(std::countr_zero(sep & (sep - 1)));  // 32 if none
        const __m256i windows =
            _mm256_inserti128_si256(bytes, _mm_loadu_si128(reinterpret_cast<const __m128i*>(s + first + 1)), 1);
        const __m256i rows = _mm256_set_m128i(align_row(second - first), align_row(first + 1));
        invalid = _mm256_or_si256(invalid, rows);
        s += second + 1;
        return digit_groups(_mm256_shuffle_epi8(_mm256_subs_epu8(windows, _mm256_set1_epi8('0')), rows));
    }

    static std::uint32_t one_token(const char*& s, __m256i& invalid) {
        const __m128i window = _mm_loadu_si128(reinterpret_cast<const __m128i*>(s));
        const unsigned n = unsigned(std::countr_zero(separators(window) | 0x10000));
        invalid = _mm256_or_si256(invalid, _mm256_castsi128_si256(align_row(n + 1)));
        s += n + 1;
        return std::uint32_t(parse16(window, n));
    }

    // The byte after the first separator at or after q.
    static const char* after_separator(const char* q) {
        for (;; q += 32)
            if (const std::uint32_t sep = separators(_mm256_loadu_si256(reinterpret_cast<const __m256i*>(q))))
                return q + std::countr_zero(sep) + 1;
    }

    static const char* skip_whitespace(const char* p) {
        while (static_cast<unsigned char>(*p) <= ' ') ++p;
        return p;
    }

    // Tokens in [p, end), where p starts a token.
    static std::size_t count_tokens(const char* p, const char* end) {
        std::size_t tokens = 1;
        for (const char* q = p + 1; q < end; ++q)
            tokens += static_cast<unsigned char>(*q) > ' ' && static_cast<unsigned char>(q[-1]) <= ' ';
        return tokens;
    }

    static const char* parse_slowly(const char* p, std::uint32_t* dst, std::size_t count) {
        for (std::size_t i = 0; i < count; ++i) {
            p = skip_whitespace(p);
            const __m128i window = _mm_loadu_si128(reinterpret_cast<const __m128i*>(p));
            const unsigned n = unsigned(std::countr_zero(separators(window) | 0x10000));
            dst[i] = std::uint32_t(parse16(window, n));
            p += n + 1;
        }
        return p;
    }
};

}  // namespace detail

// Token boundaries come from separator bitmasks of aligned 64-byte blocks: finding the next token
// clears one bit, so consecutive reads do not wait on each other's parsing.
class Reader {
public:
    // Takes everything that remains on fd (stdin by default).
    explicit Reader(int fd = 0) : input_(detail::open_input(fd)) { seek(input_.start); }

    ~Reader() { detail::release(input_); }

    Reader(const Reader&) = delete;
    Reader& operator=(const Reader&) = delete;

    // Next integer token, or the next non-whitespace character for char. MaxDigits, if set, promises
    // at most that many digits; for 64-bit types, 16 or fewer selects a faster parser.
    // Non-negative values parse faster as unsigned types (10-18%, see notes.md).
    template <class T, int MaxDigits = 0>
        requires std::integral<T> && (!std::same_as<T, bool>)
    T read() {
        if constexpr (std::same_as<T, char>) {
            skip_whitespace();
            return *cur_++;
        } else {
            const auto [start, length] = next_token();
            // A leading '-' sits below '0' and parses as a zero digit.
            const auto magnitude = parse<(sizeof(T) > 4), MaxDigits>(start + length, length);
            if constexpr (std::is_unsigned_v<T>) return T(magnitude);
            else return T(*start == '-' ? 0 - magnitude : magnitude);
        }
    }

    // count tokens into dst. uint32_t uses the AVX2 bulk parser; other types read one by one.
    template <int MaxDigits = 0, class T>
    void read(T* dst, std::size_t count) {
        if constexpr (std::same_as<T, std::uint32_t>) {
            skip_whitespace();
            const auto [stop, parsed] = detail::BulkParser::parse(cur_, input_.end, dst, count);
            seek(stop);
            for (std::size_t i = parsed; i < count; ++i) dst[i] = read<T>();
        } else {
            for (std::size_t i = 0; i < count; ++i) dst[i] = read<T, MaxDigits>();
        }
    }

    // Next token; valid while the Reader lives.
    std::string_view word() {
        const auto [start, length] = next_token();
        return {start, length};
    }

    // Tokenizer state, for custom token loops. separators has one bit per whitespace byte of the
    // 64-byte block at block, at or after cur. The lowest bit is the end of the token at cur: clear
    // it to move on. With no bits left, advance block by 64 and take detail::block_separators.
    struct Scan {
        const char* cur;
        const char* block;
        std::uint64_t separators;
    };

    Scan scan() const { return {cur_, block_, separators_}; }

    void resume(const Scan& scan) {
        cur_ = scan.cur;
        block_ = scan.block;
        separators_ = scan.separators;
    }

private:
    struct Token {
        const char* start;
        unsigned length;
    };

    // Continue reading at p.
    void seek(const char* p) {
        cur_ = p;
        block_ = reinterpret_cast<const char*>(reinterpret_cast<std::uintptr_t>(p) & ~std::uintptr_t(63));
        separators_ = detail::block_separators(block_) & ~std::uint64_t(0) << (cur_ - block_);
    }

    // Position of the next separator; at or after cur_.
    const char* next_separator() {
        while (!separators_) [[unlikely]] {
            block_ += 64;
            separators_ = detail::block_separators(block_);
        }
        return block_ + std::countr_zero(separators_);
    }

    void skip_whitespace() {
        while (next_separator() == cur_) {
            separators_ &= separators_ - 1;
            ++cur_;
        }
    }

    Token next_token() {
        for (;;) {
            const char* end = next_separator();
            separators_ &= separators_ - 1;
            const char* start = cur_;
            cur_ = end + 1;
            if (end != start) [[likely]] return {start, unsigned(end - start)};
        }
    }

    // Value of the n characters that end at end.
    template <bool Wide, int MaxDigits>
    static auto parse(const char* end, unsigned n) {
        if constexpr (!Wide) return std::uint32_t(detail::parse_ending16(end, n));
        else if constexpr (MaxDigits > 0 && MaxDigits <= 16) return detail::parse_ending16(end, n);
        else return detail::parse_ending24(end, n);
    }

    detail::Input input_;
    const char* cur_;             // next unread byte
    const char* block_;           // 64-byte block holding the next separator
    std::uint64_t separators_;    // separators in block_ at or after cur_
};

// Buffered output. write() takes any mix of integers, chars and strings:
//   out.write(x, ' ', y, '\n');
// MaxDigits, if set, promises integers of at most that many digits; for 64-bit types, 16 or fewer
// selects a faster formatter: out.write<16>(sum, '\n').
class Writer {
public:
    explicit Writer(int fd = 1) : fd_(fd) {}
    ~Writer() { flush(); }

    Writer(const Writer&) = delete;
    Writer& operator=(const Writer&) = delete;

    template <int MaxDigits = 0, class... Ts>
    void write(const Ts&... values) {
        const std::size_t needed = (std::size_t(0) + ... + max_size(values));
        if (needed > kCapacity) [[unlikely]] {
            (write_alone<MaxDigits>(values), ...);
            return;
        }
        if (std::size_t(buffer_ + kCapacity - cur_) < needed) [[unlikely]] flush();
        char* p = cur_;
        ((p = put<MaxDigits>(p, values)), ...);
        cur_ = p;
    }

    // Custom formatting: fill(p) may store up to max_size <= 64 KiB bytes at p and returns the end
    // of what it wrote.
    template <class Fill>
    void write_with(std::size_t max_size, Fill fill) {
        if (std::size_t(buffer_ + kCapacity - cur_) < max_size) [[unlikely]] flush();
        cur_ = fill(cur_);
    }

    // values[0..count) joined by separator. uint32_t uses the AVX2 formatter.
    template <int MaxDigits = 0, class T>
    void write_array(const T* values, std::size_t count, char separator) {
        if (!count) return;
        std::size_t i = 0;
        if constexpr (std::same_as<T, std::uint32_t>) {
            constexpr std::size_t kBatch = 8 * 11 + 16;  // eight values and separators, plus overhang
            char* p = cur_;
            for (; i + 8 <= count; i += 8) {
                if (std::size_t(buffer_ + kCapacity - p) < kBatch) [[unlikely]] {
                    cur_ = p;
                    flush();
                    p = cur_;
                }
                p = detail::format8(p, _mm256_loadu_si256(reinterpret_cast<const __m256i*>(values + i)), separator);
            }
            cur_ = p;
        }
        for (; i < count; ++i) write<MaxDigits>(values[i], separator);
        --cur_;  // no separator after the last value
    }

    void flush() {
        write_all(fd_, buffer_, std::size_t(cur_ - buffer_));
        cur_ = buffer_;
    }

private:
    static constexpr std::size_t kCapacity = std::size_t(1) << 16;

    template <class T>
    static constexpr bool kInteger = std::integral<T> && !std::same_as<T, char> && !std::same_as<T, bool>;

    // Bytes put() may store, which can exceed what it writes.
    template <class T>
    static std::size_t max_size(const T& value) {
        if constexpr (std::same_as<T, char>) return 1;
        else if constexpr (kInteger<T>) return 1 + 20;  // a sign, then format() stores up to 20 bytes
        else return std::string_view(value).size();
    }

    template <int MaxDigits, class T>
    static char* put(char* p, const T& value) {
        if constexpr (std::same_as<T, char>) {
            *p = value;
            return p + 1;
        } else if constexpr (kInteger<T>) {
            using U = std::conditional_t<sizeof(T) <= 4, std::uint32_t, std::uint64_t>;
            if constexpr (std::is_signed_v<T>) {
                *p = '-';
                p += value < 0;
                return put<MaxDigits>(p, value < 0 ? U(0 - U(value)) : U(value));
            } else if constexpr (sizeof(T) <= 4) {
                return detail::format(p, U(value));
            } else {
                return detail::format64<MaxDigits == 0 ? 20 : MaxDigits>(p, U(value));
            }
        } else {
            const std::string_view s(value);
            std::memcpy(p, s.data(), s.size());
            return p + s.size();
        }
    }

    // A value longer than the buffer: flush, then write it directly.
    template <int MaxDigits, class T>
    void write_alone(const T& value) {
        if constexpr (std::same_as<T, char> || kInteger<T>) {
            write<MaxDigits>(value);
        } else {
            flush();
            const std::string_view s(value);
            write_all(fd_, s.data(), s.size());
        }
    }

    static void write_all(int fd, const char* data, std::size_t size) {
        while (size) {
            const ssize_t put = ::write(fd, data, size);
            if (put > 0) data += put, size -= std::size_t(put);
            else if (put < 0 && errno == EINTR) continue;
            else std::abort();
        }
    }

    int fd_;
    char* cur_ = buffer_;
    alignas(64) char buffer_[kCapacity];
};

}  // namespace io
// lib/mem/huge.hpp
// Zero-filled memory in transparent huge pages (2 MiB) where the kernel allows. Never freed: the
// programs end with _exit. Linux or macOS. Measurements: lib/mem/notes.md.
//
//   auto* a = mem::huge<std::uint32_t>(n);   // n zeroed values, 2 MiB aligned
//   mem::Arena arena(bytes);                 // one mapping for several arrays
//   auto* b = arena.take<std::uint64_t>(m);  // m zeroed values, 64-byte aligned
//
// Pages fault in on first touch. An arena of B bytes holds takes whose sizes, each rounded up to
// 64 bytes, sum to at most B; it does not check.

#include <sys/mman.h>

#include <cstddef>
#include <cstdint>
#include <cstdlib>

namespace mem {

inline constexpr std::size_t kHugePage = std::size_t(1) << 21;

// bytes rounded up to whole huge pages, 2 MiB aligned.
inline void* map_huge(std::size_t bytes) {
    bytes = (bytes + kHugePage - 1) / kHugePage * kHugePage;
    void* region = ::mmap(nullptr, bytes + kHugePage, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    if (region == MAP_FAILED) std::abort();
    const std::uintptr_t aligned = (reinterpret_cast<std::uintptr_t>(region) + kHugePage - 1) & ~(kHugePage - 1);
#ifdef MADV_HUGEPAGE
    ::madvise(reinterpret_cast<void*>(aligned), bytes, MADV_HUGEPAGE);
#endif
    return reinterpret_cast<void*>(aligned);
}

// count values of T.
template <class T>
T* huge(std::size_t count) {
    return static_cast<T*>(map_huge(count * sizeof(T)));
}

// Bump allocation from one map_huge() mapping.
class Arena {
public:
    explicit Arena(std::size_t bytes) : cur_(reinterpret_cast<std::uintptr_t>(map_huge(bytes))) {}

    // count values of T; the next take starts at the next multiple of 64 bytes.
    template <class T>
    T* take(std::size_t count) {
        T* p = reinterpret_cast<T*>(cur_);
        cur_ += (count * sizeof(T) + 63) & ~std::size_t(63);
        return p;
    }

private:
    std::uintptr_t cur_;
};

}  // namespace mem
// lib/run/early.hpp
// Program entry for solutions. RUN_EARLY(solve) runs solve() from the executable's
// pre-initializers (.preinit_array), before the C++ runtime initializes iostreams and locales
// (lib/io uses neither) and before any static constructor, then ends the process with _exit(0):
// no exit handlers, no teardown, no unmapping. Elsewhere it defines main() { solve(); }.
// Measurements: lib/run/notes.md.
//
//   namespace {
//   void solve() { ... }  // flushes its output (io::Writer does on destruction)
//   }  // namespace
//
//   RUN_EARLY(solve)      // at namespace scope, once per program

#include <unistd.h>

#ifdef __ELF__
#define RUN_EARLY(solve)                                                                                  \
    namespace {                                                                                           \
    void run_early(int, char**, char**) {                                                                 \
        solve();                                                                                          \
        ::_exit(0);                                                                                       \
    }                                                                                                     \
    [[gnu::used, gnu::section(".preinit_array")]] void (*const preinit)(int, char**, char**) = run_early; \
    }                                                                                                     \
    int main() { solve(); }  // reached only if the loader skips .preinit_array
#else
#define RUN_EARLY(solve) \
    int main() { solve(); }
#endif
// problems/convolution/min_plus_convolution_convex_arbitrary/columns.hpp
// Fixed-width output of values < 2^31: each value right-aligned in W - 1 characters, then a space;
// the last separator is a newline. W = 10 for blocks whose values are all below 10^9, else 11.
// Judge-specific: the checker compares tokens, so the padding is accepted.
//
// Per value v: w = v / 10^(W - 9) as 8 digits, most significant first, in a qword (leading zeros
// blank); the tail holds the last W - 9 digits and the separator in a dword. 16 values per step,
// written as W 16-byte chunks built by pshufb from these sources. The divisions of the next step
// are issued before the digits of this one, so the two dependency chains overlap.
// Same scheme as ../convolution_mod/fields.hpp (W = 10 only); here the shuffle controls are
// generated for either width.

#include <immintrin.h>

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <string_view>
#include <utility>


namespace columns {

namespace detail {

using u32 = std::uint32_t;

struct alignas(32) Lanes {
    u32 lane[8];
};

constexpr Lanes all(u32 x) { return {{x, x, x, x, x, x, x, x}}; }
constexpr Lanes all16(u32 x) { return all(x * 0x10001); }

[[gnu::always_inline]] inline __m256i load(const Lanes& l) {
    return _mm256_load_si256(reinterpret_cast<const __m256i*>(&l));
}

// Sources of a step's text. Digit qwords: kD01 holds values [0, 1 | 8, 9], kD23 [2, 3 | 10, 11],
// kD45 [4, 5 | 12, 13], kD67 [6, 7 | 14, 15]. Tail dwords: kLowTail [0..3 | 8..11],
// kHighTail [4..7 | 12..15]. kSwapped: kD01 with its lanes exchanged (W = 11 only, for the
// digits of value 8, which end the low lane's last chunk).
enum Source { kD01, kD23, kD45, kD67, kLowTail, kHighTail, kSwapped, kSources };

constexpr int kZero = 0x80;  // shuffle control: zero byte

// Chunks of the 16W text bytes of a step: chunks [0, low) from the low lane (values 0-7, and
// value 8's digits when W = 11), chunks [low, W) from the high lane. Vector k holds chunk k in
// its low lane and chunk low + k in its high lane.
template <int W>
struct Layout {
    static constexpr int kLow = (8 * W + 15) / 16;
    static constexpr int kHigh = W - kLow;
    Lanes control[kLow][kSources] = {};
    bool used[kLow][kSources] = {};

    // Text byte at offset 16 * chunk + i, read in lane `lane`.
    constexpr void place(int k, int lane, int chunk, int i) {
        const int at = 16 * chunk + i, value = at / W, offset = at % W, j = value % 8;
        int source, byte;
        if (value / 8 != lane) {  // value 8's digits in the low lane
            source = kSwapped, byte = offset;
        } else if (offset < 8) {
            source = kD01 + j / 2, byte = 8 * (j % 2) + offset;
        } else {
            source = kLowTail + j / 4, byte = 4 * (j % 4) + offset - 8;
        }
        used[k][source] = true;
        const int b = 16 * lane + i;
        u32& word = control[k][source].lane[b / 4];
        word = (word & ~(0xFFu << 8 * (b % 4))) | u32(byte) << 8 * (b % 4);
    }

    constexpr Layout() {
        for (int k = 0; k < kLow; ++k)
            for (int s = 0; s < kSources; ++s)
                for (int b = 0; b < 32; ++b) control[k][s].lane[b / 4] |= u32(kZero) << 8 * (b % 4);
        for (int k = 0; k < kLow; ++k)
            for (int i = 0; i < 16; ++i) {
                place(k, 0, k, i);
                if (k < kHigh) place(k, 1, kLow + k, i);
            }
    }
};

template <int W>
inline constexpr Layout<W> kLayout{};

// Divisions: v / 10^(W - 9) = v * kDigits.multiplier >> kDigits.shift, exact for v < 2^31,
// and likewise v / 10^(W - 4) by kHigher.
struct Magic {
    u32 multiplier;
    int shift;
};

template <int W>
struct Constants;

template <>
struct Constants<10> {
    static constexpr Magic kDigits{429496730, 32};    // ceil(2^32 / 10), v < 2^30
    static constexpr Magic kHigher{1407374884, 47};   // ceil(2^47 / 10^5)
};

template <>
struct Constants<11> {
    static constexpr Magic kDigits{2748779070, 38};   // ceil(2^38 / 100), v < 2^32
    static constexpr Magic kHigher{2251799814, 51};   // ceil(2^51 / 10^6), v < 7 * 10^9
};

struct Common {
    Lanes pack = all(1 - 10000 * 65536u);  // [h, w - 10^4 h] in 16-bit halves = 2^16 w + h pack
    Lanes by100 = all16(5243), hundred = all16(100);  // x / 100 = (x * 5243 >> 16) >> 3 for x < 10^4
    Lanes by10 = all16(6554);       // z / 10 = z * 6554 >> 16 for z < 100
    Lanes tens_out = all16(2559);   // bytes [z / 10, z % 10] = 256 z - 2559 (z / 10)
    Lanes ones = all(~0u), zero = all(0x30303030), space = all(0x20202020);
    Lanes ten = all(10), hundred32 = all(100);
    Lanes tail10 = all(' ' << 8 | '0');               // units digit, space
    Lanes tail11 = all(' ' << 16 | '0' << 8 | '0');   // tens digit, units digit, space
    Lanes blank = all(0x10);                          // '0' - 0x10 = ' '
    Lanes digits_multiplier[2] = {all(Constants<10>::kDigits.multiplier), all(Constants<11>::kDigits.multiplier)};
    Lanes higher_multiplier[2] = {all(Constants<10>::kHigher.multiplier), all(Constants<11>::kHigher.multiplier)};
};

inline constexpr Common kCommon{};

// v / magic for eight dwords v; odd = v >> 32 per qword.
template <Magic M>
[[gnu::always_inline]] inline __m256i divide(__m256i v, __m256i odd, __m256i multiplier) {
    const __m256i even_q = _mm256_srli_epi64(_mm256_mul_epu32(v, multiplier), M.shift);
    const __m256i odd_q = _mm256_mul_epu32(odd, multiplier);
    return _mm256_blend_epi32(even_q, M.shift == 32 ? odd_q : _mm256_srli_epi64(odd_q, M.shift - 32), 0xAA);
}

// Eight values after the divisions: halves holds [w / 10^4, w % 10^4] in 16-bit halves;
// tail holds the last W - 9 digits and the separator as text.
struct Divided {
    __m256i halves, tail;
};

template <int W>
[[gnu::always_inline]] inline Divided divide(__m256i v, const Common& k) {
    const __m256i odd = _mm256_srli_epi64(v, 32);
    const __m256i w = divide<Constants<W>::kDigits>(v, odd, load(k.digits_multiplier[W - 10]));
    const __m256i h = divide<Constants<W>::kHigher>(v, odd, load(k.higher_multiplier[W - 10]));
    const __m256i halves = _mm256_add_epi32(_mm256_slli_epi32(w, 16), _mm256_mullo_epi32(h, load(k.pack)));
    if constexpr (W == 10) {
        return {halves, _mm256_sub_epi32(_mm256_add_epi32(v, load(k.tail10)), _mm256_mullo_epi32(w, load(k.ten)))};
    } else {
        // r = v % 100 < 100 in the low 16 bits; tail bytes [r / 10, r % 10, ' ', 0] as text,
        // the tens digit blank for v < 10 (then w = 0 and the digits are blank too).
        const __m256i r = _mm256_sub_epi32(v, _mm256_mullo_epi32(w, load(k.hundred32)));
        const __m256i tens = _mm256_mulhi_epu16(r, load(k.by10));
        const __m256i pair = _mm256_sub_epi16(_mm256_slli_epi16(r, 8), _mm256_mullo_epi16(tens, load(k.tens_out)));
        const __m256i small = _mm256_and_si256(_mm256_cmpgt_epi32(load(k.ten), v), load(k.blank));
        return {halves, _mm256_sub_epi32(_mm256_add_epi32(pair, load(k.tail11)), small)};
    }
}

// 16-bit z < 100 -> bytes [z / 10, z % 10].
[[gnu::always_inline]] inline __m256i two_digits(__m256i z, const Common& k) {
    const __m256i tens = _mm256_mulhi_epu16(z, load(k.by10));
    return _mm256_sub_epi16(_mm256_slli_epi16(z, 8), _mm256_mullo_epi16(tens, load(k.tens_out)));
}

// Qwords of 8 digits, most significant first -> text; leading zeros become spaces. x ^ (x - 1)
// sets the bits up to the lowest set one: 0xFF in leading zero bytes, < 0x10 in the first
// nonzero digit, 0 above. blendv takes the space where a byte's top bit is set.
[[gnu::always_inline]] inline __m256i text(__m256i digits, const Common& k) {
    const __m256i upto = _mm256_xor_si256(digits, _mm256_add_epi64(digits, load(k.ones)));
    return _mm256_blendv_epi8(_mm256_or_si256(digits, load(k.zero)), load(k.space), upto);
}

// Text of the 8 digits of w, two values per lane: values [0, 1 | 4, 5] of d in lo, [2, 3 | 6, 7]
// in hi. Per value, 16-bit [w / 10^6, w / 10^4 % 100, w / 100 % 100, w % 100] before two_digits.
[[gnu::always_inline]] inline void digits(const Divided& d, __m256i& lo, __m256i& hi, const Common& k) {
    const __m256i hundreds = _mm256_srli_epi16(_mm256_mulhi_epu16(d.halves, load(k.by100)), 3);
    const __m256i rest = _mm256_sub_epi16(d.halves, _mm256_mullo_epi16(hundreds, load(k.hundred)));
    lo = text(two_digits(_mm256_unpacklo_epi16(hundreds, rest), k), k);
    hi = text(two_digits(_mm256_unpackhi_epi16(hundreds, rest), k), k);
}

// Vector k of the step: the OR of one shuffle per source it uses.
template <int W, int K, std::size_t... S>
[[gnu::always_inline]] inline __m256i chunk(const __m256i (&source)[kSources], std::index_sequence<S...>) {
    constexpr const Layout<W>& layout = kLayout<W>;
    __m256i c = _mm256_setzero_si256();
    const auto add = [&](std::size_t s) {
        c = _mm256_or_si256(c, _mm256_shuffle_epi8(source[s], load(layout.control[K][s])));
    };
    ((layout.used[K][S] ? add(S) : void()), ...);
    return c;
}

// 16W bytes at p (16-byte aligned) for values x0..x15, divided as lo = [x0..x3 | x8..x11] and
// hi = [x4..x7 | x12..x15].
template <int W>
[[gnu::always_inline]] inline void store(char* p, const Divided& lo, const Divided& hi, const Common& k) {
    constexpr int kLow = Layout<W>::kLow, kHigh = Layout<W>::kHigh;
    __m256i source[kSources];
    digits(lo, source[kD01], source[kD23], k);
    digits(hi, source[kD45], source[kD67], k);
    source[kLowTail] = lo.tail, source[kHighTail] = hi.tail;
    source[kSwapped] = W == 11 ? _mm256_permute2x128_si256(source[kD01], source[kD01], 0x01) : source[kD01];
    __m256i c[kLow];
    [&]<std::size_t... K>(std::index_sequence<K...>) {
        ((c[K] = chunk<W, K>(source, std::make_index_sequence<kSources>())), ...);
    }(std::make_integer_sequence<std::size_t, kLow>());
    // Vector k whole at chunk kLow + k - 1: its high lane lands in place, its low lane on the slot
    // of the previous vector's high lane (or of chunk kLow - 1), which a later store fixes.
    for (int i = kHigh - 1; i >= 0; --i)
        _mm256_storeu_si256(reinterpret_cast<__m256i*>(p + 16 * (kLow + i - 1)), c[i]);
    for (int i = 0; i < kLow; ++i)
        _mm_store_si128(reinterpret_cast<__m128i*>(p + 16 * i), _mm256_castsi256_si128(c[i]));
}

// Values x[0, 16) in the lane order of store(), divided.
template <int W>
[[gnu::always_inline]] inline void divide16(const u32* x, Divided& lo, Divided& hi, const Common& k) {
    const auto at = [x](int i) { return _mm256_loadu_si256(reinterpret_cast<const __m256i*>(x + i)); };
    const auto both = [x](int i) { return _mm256_broadcastsi128_si256(_mm_loadu_si128(reinterpret_cast<const __m128i*>(x + i))); };
    lo = divide<W>(_mm256_blend_epi32(at(0), both(8), 0xF0), k);
    hi = divide<W>(_mm256_blend_epi32(at(8), both(4), 0x0F), k);
}

// Text of x[0, count), count a positive multiple of 16, at p (16-byte aligned).
template <int W>
void format(char* p, const u32* x, std::size_t count) {
    const Common& k = kCommon;
    Divided dl, dh;
    divide16<W>(x, dl, dh, k);
    for (std::size_t i = 16; i < count; i += 16, p += 16 * W) {
        Divided nl, nh;
        divide16<W>(x + i, nl, nh, k);
        store<W>(p, dl, dh, k);
        dl = nl, dh = nh;
    }
    store<W>(p, dl, dh, k);
}

inline u32 maximum(const u32* x, std::size_t count) {
    __m256i m = _mm256_setzero_si256();
    for (std::size_t i = 0; i < count; i += 8)
        m = _mm256_max_epu32(m, _mm256_loadu_si256(reinterpret_cast<const __m256i*>(x + i)));
    alignas(32) u32 lane[8];
    _mm256_store_si256(reinterpret_cast<__m256i*>(lane), m);
    return *std::max_element(lane, lane + 8);
}

}  // namespace detail

inline constexpr std::size_t kBlock = 25600;  // values per write(2), a multiple of 16
inline constexpr std::size_t kTextBytes = 11 * kBlock;

// values[0, count), count >= 1, each < 2^31; values[count, count rounded up to 16) must be
// readable and zero. text: kTextBytes bytes, 16-byte aligned. Blocks are longer than the
// Writer's buffer, so it hands each to write(2) directly.
inline void write(io::Writer& out, const std::uint32_t* values, std::size_t count, char* text) {
    for (std::size_t i = 0; i < count; i += kBlock) {
        const std::size_t n = std::min(kBlock, count - i), padded = (n + 15) / 16 * 16;
        const std::size_t width = detail::maximum(values + i, padded) < 1'000'000'000 ? 10 : 11;
        if (width == 10) detail::format<10>(text, values + i, padded);
        else detail::format<11>(text, values + i, padded);
        if (i + n == count) text[width * n - 1] = '\n';
        out.write(std::string_view(text, width * n));
    }
}

}  // namespace columns
// problems/convolution/min_plus_convolution_convex_arbitrary/runs.hpp
// Bulk read of uint32 arrays whose tokens come in long runs of one length (fixed-width or sorted
// inputs), on top of io::Reader:
//
//   runs::read(in, a, n);  // same values as io::read_bulk(in, a, n)
//
// Within a run of tokens of length L, each followed by one separator, token i starts at i (L + 1)
// bytes: 8 tokens at a time are checked against a 96-bit separator pattern and parsed without a
// separator search, so steps do not wait on each other. Elsewhere tokens go one at a time; once
// such misses pass 64 plus 1/64 of the tokens read (short runs), the rest goes to io::read_bulk.
// Same scheme as ../min_plus_convolution_convex_convex (its read_values).

#include <array>
#include <bit>

// lib/io/bulk32.hpp
// Bulk read of uint32 arrays with AVX2, on top of io::Reader:
//
//   io::Reader in;
//   io::read_bulk(in, a.data(), n);  // same values as in.read(a.data(), n); faster on Zen 3
//
// On Zen 3 (the judge's CPU) it uses BulkParser32 below; elsewhere it is Reader::read, which is
// faster there. -DIO_BULK32_TRANSPOSE=0 or 1 forces either. Kept apart from io.hpp so that the
// code of the programs that do not need it stays unchanged. Design and measurements:
// lib/io/notes.md.


#ifndef IO_BULK32_TRANSPOSE
#ifdef __znver3__
#define IO_BULK32_TRANSPOSE 1
#else
#define IO_BULK32_TRANSPOSE 0
#endif
#endif

namespace io {
namespace detail {

// Parses uint32 tokens of at most 16 characters from the token at p into dst: at most count,
// which must be the tokens that follow. Stops when fewer than kMinTokens tokens remain. Returns
// where it stopped and the tokens parsed. As BulkParser in io.hpp, each chunk of input is cut into
// four streams at token boundaries that advance in lockstep, two tokens per step. A step stores
// its eight values as one vector, [a0 a1 a2 a3 b0 b1 b2 b3] for tokens a_k, b_k of stream k, and
// a transpose then puts each stream's values in order. On Zen 3 this is 17% faster than four
// 8-byte stores per step; on Intel (Emerald Rapids) 5% slower.
class BulkParser32 {
public:
    static constexpr std::size_t kMinTokens = 1024;

    struct Result {
        const char* end;
        std::size_t parsed;
    };

    static Result parse(const char* p, std::uint32_t* dst, std::size_t count) {
        std::uint32_t* const first = dst;
        while (count >= kMinTokens) {
            // The count tokens span at least 2 * count - 1 bytes. A chunk spans at most chunk + 17
            // bytes, so it holds at most chunk / 2 + 9 < count tokens, and loads stay below
            // p + chunk + 33: all within those bytes.
            const std::size_t chunk = std::min(kChunk, 2 * (count - 32)) & ~std::size_t(3);
            const std::size_t stream = chunk / 4;
            const char* s[4] = {p, after_separator(p + stream), after_separator(p + 2 * stream),
                                after_separator(p + 3 * stream)};
            const char* const end[4] = {s[1], s[2], s[3], after_separator(p + chunk)};
            __m256i invalid = _mm256_setzero_si256();
            const std::size_t steps = lockstep(s, end, invalid);
            std::size_t tail[4];
            bool overrun = false;
            for (int k = 0; k < 4; ++k) {
                tail[k] = 0;
                while (s[k] < end[k] && tail[k] < kTail) tails_[k][tail[k]++] = one_token(s[k], invalid);
                overrun |= s[k] != end[k];
            }
            if (overrun || (std::uint32_t(_mm256_movemask_epi8(invalid)) & 0x80008000)) [[unlikely]] {
                // Irregular whitespace or tokens: this chunk one token at a time.
                const std::size_t tokens = std::min(count_tokens(p, end[3]), count);
                p = parse_slowly(p, dst, tokens);
                dst += tokens;
                count -= tokens;
                continue;
            }
            std::uint32_t* out[4] = {dst};
            for (int k = 0; k < 3; ++k) out[k + 1] = out[k] + 2 * steps + tail[k];
            transpose(steps, out);
            for (int k = 0; k < 4; ++k) std::memcpy(out[k] + 2 * steps, tails_[k], tail[k] * sizeof(std::uint32_t));
            const auto parsed = std::size_t(out[3] + 2 * steps + tail[3] - dst);
            dst += parsed;
            count -= parsed;
            p = skip_whitespace(end[3]);
        }
        return {p, std::size_t(dst - first)};
    }

    static const char* skip_whitespace(const char* p) {
        while (static_cast<unsigned char>(*p) <= ' ') ++p;
        return p;
    }

private:
    static constexpr std::size_t kChunk = std::size_t(1) << 17;
    // A step of valid tokens advances a stream by at least 4 bytes; lockstep stops at kSteps.
    static constexpr std::size_t kSteps = kChunk / 16 + 16;
    // A token takes at least 2 bytes of a stream.
    static constexpr std::size_t kTail = kChunk / 8 + 32;
    alignas(64) static inline std::uint32_t steps_[8 * kSteps];
    alignas(64) static inline std::uint32_t tails_[4][kTail];

    // Steps all streams while each has 33 bytes left; returns the steps. Step j stores its values
    // at steps_ + 8j. Works on local copies of the stream state, which stay in registers.
    static std::size_t lockstep(const char* (&streams)[4], const char* const (&end)[4], __m256i& flags) {
        const char* s[4] = {streams[0], streams[1], streams[2], streams[3]};
        __m256i invalid = flags;
        std::size_t done = 0;
        for (;;) {
            std::ptrdiff_t left = end[0] - s[0];
            for (int k = 1; k < 4; ++k) left = std::min(left, end[k] - s[k]);
            const std::ptrdiff_t steps = std::min(left / 33, std::ptrdiff_t(kSteps - done));
            if (steps <= 0) break;
            for (std::uint32_t* v = steps_ + 8 * done; v != steps_ + 8 * (done + std::size_t(steps)); v += 8) {
                const __m256i g0 = two_tokens(s[0], invalid), g1 = two_tokens(s[1], invalid);
                const __m256i g2 = two_tokens(s[2], invalid), g3 = two_tokens(s[3], invalid);
                const __m256i k = _mm256_set1_epi32(0x00012710);
                // 8-digit halves: [s0 high, s0 low, s1 high, s1 low | second tokens likewise].
                const __m256 h01 = _mm256_castsi256_ps(_mm256_madd_epi16(_mm256_packus_epi32(g0, g1), k));
                const __m256 h23 = _mm256_castsi256_ps(_mm256_madd_epi16(_mm256_packus_epi32(g2, g3), k));
                const __m256i high = _mm256_castps_si256(_mm256_shuffle_ps(h01, h23, 0x88));
                const __m256i low = _mm256_castps_si256(_mm256_shuffle_ps(h01, h23, 0xDD));
                _mm256_store_si256(reinterpret_cast<__m256i*>(v),
                                   _mm256_add_epi32(_mm256_mullo_epi32(high, _mm256_set1_epi32(100000000)), low));
            }
            done += std::size_t(steps);
        }
        for (int k = 0; k < 4; ++k) streams[k] = s[k];
        flags = invalid;
        return done;
    }

    // The 2 * steps values of stream k from steps_ to out[k]: a 4x4 transpose of value pairs.
    static void transpose(std::size_t steps, std::uint32_t* const (&out)[4]) {
        const auto pairs = [](std::size_t j) {  // step j as [a0 b0 a1 b1 | a2 b2 a3 b3]
            const __m256i v = _mm256_load_si256(reinterpret_cast<const __m256i*>(steps_ + 8 * j));
            return _mm256_permutevar8x32_epi32(v, _mm256_setr_epi32(0, 4, 1, 5, 2, 6, 3, 7));
        };
        std::size_t j = 0;
        for (; j + 4 <= steps; j += 4) {
            const __m256i p0 = pairs(j), p1 = pairs(j + 1), p2 = pairs(j + 2), p3 = pairs(j + 3);
            const __m256i t0 = _mm256_unpacklo_epi64(p0, p1), t1 = _mm256_unpackhi_epi64(p0, p1);
            const __m256i t2 = _mm256_unpacklo_epi64(p2, p3), t3 = _mm256_unpackhi_epi64(p2, p3);
            const auto put = [j](std::uint32_t* to, __m256i v) {
                _mm256_storeu_si256(reinterpret_cast<__m256i*>(to + 2 * j), v);
            };
            put(out[0], _mm256_permute2x128_si256(t0, t2, 0x20));
            put(out[1], _mm256_permute2x128_si256(t1, t3, 0x20));
            put(out[2], _mm256_permute2x128_si256(t0, t2, 0x31));
            put(out[3], _mm256_permute2x128_si256(t1, t3, 0x31));
        }
        for (; j < steps; ++j)
            for (int k = 0; k < 4; ++k) {
                out[k][2 * j] = steps_[8 * j + k];
                out[k][2 * j + 1] = steps_[8 * j + 4 + k];
            }
    }

    // Two tokens at s, as 4-digit groups [first | second]. Lengths outside 1..16 (repeated
    // whitespace, long tokens) set the sign bit of byte 15 or 31 of invalid.
    [[gnu::always_inline]] static __m256i two_tokens(const char*& s, __m256i& invalid) {
        const __m256i bytes = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(s));
        const std::uint32_t sep = separators(bytes);
        const auto first = std::size_t(std::countr_zero(sep));              // length of the first token
        const auto second = std::size_t(std::countr_zero(sep & (sep - 1)));  // 32 if none
        const __m256i windows =
            _mm256_inserti128_si256(bytes, _mm_loadu_si128(reinterpret_cast<const __m128i*>(s + first + 1)), 1);
        const __m256i rows = _mm256_set_m128i(align_row(second - first), align_row(first + 1));
        invalid = _mm256_or_si256(invalid, rows);
        s += second + 1;
        return digit_groups(_mm256_shuffle_epi8(_mm256_subs_epu8(windows, _mm256_set1_epi8('0')), rows));
    }

    static std::uint32_t one_token(const char*& s, __m256i& invalid) {
        const __m128i window = _mm_loadu_si128(reinterpret_cast<const __m128i*>(s));
        const unsigned n = unsigned(std::countr_zero(separators(window) | 0x10000));
        invalid = _mm256_or_si256(invalid, _mm256_castsi128_si256(align_row(n + 1)));
        s += n + 1;
        return std::uint32_t(parse16(window, n));
    }

    // The byte after the first separator at or after q.
    static const char* after_separator(const char* q) {
        for (;; q += 32)
            if (const std::uint32_t sep = separators(_mm256_loadu_si256(reinterpret_cast<const __m256i*>(q))))
                return q + std::countr_zero(sep) + 1;
    }

    // Tokens in [p, end), where p starts a token.
    static std::size_t count_tokens(const char* p, const char* end) {
        std::size_t tokens = 1;
        for (const char* q = p + 1; q < end; ++q)
            tokens += static_cast<unsigned char>(*q) > ' ' && static_cast<unsigned char>(q[-1]) <= ' ';
        return tokens;
    }

    static const char* parse_slowly(const char* p, std::uint32_t* dst, std::size_t count) {
        for (std::size_t i = 0; i < count; ++i) {
            p = skip_whitespace(p);
            const __m128i window = _mm_loadu_si128(reinterpret_cast<const __m128i*>(p));
            const unsigned n = unsigned(std::countr_zero(separators(window) | 0x10000));
            dst[i] = std::uint32_t(parse16(window, n));
            p += n + 1;
        }
        return p;
    }
};

// count uint32 tokens into dst with BulkParser32, the rest one at a time.
inline void read_transposed(Reader& in, std::uint32_t* dst, std::size_t count) {
    std::size_t parsed = 0;
    if (count >= BulkParser32::kMinTokens) {
        const char* const start = BulkParser32::skip_whitespace(in.scan().cur);
        const auto [stop, done] = BulkParser32::parse(start, dst, count);
        // Continue the Reader at stop: its separator mask from there on.
        const auto* block = reinterpret_cast<const char*>(reinterpret_cast<std::uintptr_t>(stop) & ~std::uintptr_t(63));
        in.resume({stop, block, block_separators(block) & ~std::uint64_t(0) << (stop - block)});
        parsed = done;
    }
    for (std::size_t i = parsed; i < count; ++i) dst[i] = in.read<std::uint32_t>();
}

}  // namespace detail

// count uint32 tokens into dst: the same values as in.read(dst, count).
inline void read_bulk(Reader& in, std::uint32_t* dst, std::size_t count) {
#if IO_BULK32_TRANSPOSE
    detail::read_transposed(in, dst, count);
#else
    in.read(dst, count);
#endif
}

}  // namespace io

namespace runs {
namespace detail {

// Separator bits of 8 tokens of length s - 1, each followed by one separator: bits s - 1, 2s - 1,
// ..., 8s - 1 of a 96-bit mask, and the bits [0, 8s) they must match.
struct Stride {
    std::uint64_t low_mask, low_bits;
    std::uint32_t high_mask, high_bits;
};

inline constexpr auto kStrides = [] {
    std::array<Stride, 12> t{};
    for (unsigned s = 2; s <= 11; ++s) {
        unsigned __int128 mask = 0, bits = 0;
        for (unsigned i = 0; i < 8 * s; ++i) mask |= (unsigned __int128)1 << i;
        for (unsigned k = 1; k <= 8; ++k) bits |= (unsigned __int128)1 << (k * s - 1);
        t[s] = {std::uint64_t(mask), std::uint64_t(bits), std::uint32_t(mask >> 64), std::uint32_t(bits >> 64)};
    }
    return t;
}();

// Separator bits of the 96 bytes at p.
struct Separators {
    std::uint64_t low;
    std::uint32_t high;
};

inline Separators separators96(const char* p) {
    const auto at = [p](int i) {
        return io::detail::separators(_mm256_loadu_si256(reinterpret_cast<const __m256i*>(p + i)));
    };
    return {at(0) | std::uint64_t(at(32)) << 32, at(64)};
}

inline bool matches(Separators x, const Stride& t) {
    return (x.low & t.low_mask) == t.low_bits && (x.high & t.high_mask) == t.high_bits;
}

// Digit groups (lib/io) of the tokens of length s - 1 at low and high, in the two lanes.
inline __m256i two_tokens(const char* low, const char* high, __m256i row) {
    const __m256i window =
        _mm256_loadu2_m128i(reinterpret_cast<const __m128i*>(high), reinterpret_cast<const __m128i*>(low));
    return io::detail::digit_groups(_mm256_shuffle_epi8(_mm256_subs_epu8(window, _mm256_set1_epi8('0')), row));
}

// Values of the 8 tokens at p, of length s - 1 each, one separator apart.
inline __m256i eight_tokens(const char* p, std::size_t s, __m256i row) {
    // Group j holds tokens j and j + 4, so the values come out in order.
    const __m256i g0 = two_tokens(p, p + 4 * s, row), g1 = two_tokens(p + s, p + 5 * s, row);
    const __m256i g2 = two_tokens(p + 2 * s, p + 6 * s, row), g3 = two_tokens(p + 3 * s, p + 7 * s, row);
    const __m256i k = _mm256_set1_epi32(0x00012710);  // 8-digit halves: high group * 10^4 + low
    const __m256 h01 = _mm256_castsi256_ps(_mm256_madd_epi16(_mm256_packus_epi32(g0, g1), k));
    const __m256 h23 = _mm256_castsi256_ps(_mm256_madd_epi16(_mm256_packus_epi32(g2, g3), k));
    const __m256i upper = _mm256_castps_si256(_mm256_shuffle_ps(h01, h23, 0x88));
    const __m256i lower = _mm256_castps_si256(_mm256_shuffle_ps(h01, h23, 0xDD));
    return _mm256_add_epi32(_mm256_mullo_epi32(upper, _mm256_set1_epi32(100000000)), lower);
}

// The token at or after p (after whitespace); p moves past its separator.
inline std::uint32_t one_token(const char*& p) {
    while (static_cast<unsigned char>(*p) <= ' ') ++p;
    const __m128i window = _mm_loadu_si128(reinterpret_cast<const __m128i*>(p));
    const unsigned length = unsigned(std::countr_zero(io::detail::separators(window) | 0x10000));
    p += length + 1;
    return std::uint32_t(io::detail::parse16(window, length));
}

}  // namespace detail

// count values into dst: the same values as io::read_bulk(in, dst, count). Tokens have at most
// 10 digits.
inline void read(io::Reader& in, std::uint32_t* dst, std::size_t count) {
    using namespace detail;
    const char* p = in.scan().cur;
    std::size_t i = 0, misses = 0;
    // 64 tokens left span >= 127 bytes, so loads (< 96 bytes from p) stay in the input.
    while (i + 64 <= count && misses <= 64 + i / 64) {
        while (static_cast<unsigned char>(*p) <= ' ') ++p;
        const Separators first = separators96(p);
        const std::size_t s = std::size_t(std::countr_zero(first.low)) + 1;  // token length + 1
        if (s >= 2 && s <= 11 && matches(first, kStrides[s])) {
            const __m256i row = _mm256_broadcastsi128_si256(io::detail::align_row(s));
            do {
                _mm256_storeu_si256(reinterpret_cast<__m256i*>(dst + i), eight_tokens(p, s, row));
                p += 8 * s, i += 8;
            } while (i + 64 <= count && matches(separators96(p), kStrides[s]));
        } else {
            ++misses;
        }
        if (i + 64 <= count) dst[i++] = one_token(p);
    }
    // Continue the Reader at p, as io::read_fixed does.
    const auto* block = reinterpret_cast<const char*>(reinterpret_cast<std::uintptr_t>(p) & ~std::uintptr_t(63));
    in.resume({p, block, io::detail::block_separators(block) & ~std::uint64_t(0) << (p - block)});
    if (i < count) io::read_bulk(in, dst + i, count - i);
}

}  // namespace runs

namespace {

using u32 = std::uint32_t;

constexpr std::size_t kGroup = 16;         // rows per group
constexpr std::size_t kVecs = kGroup / 8;  // vectors per group
constexpr u32 kInf = 3'000'000'000u;       // a outside [0, N), b past M; kInf + b <= 4e9 < 2^32
constexpr u32 kNone = INT32_MAX;           // above every value of a valid column (<= 2e9)
constexpr std::size_t kAPad = kGroup + 8;  // kInf words before a
constexpr std::size_t kBlock = 64;         // columns per bounded block; a multiple of 8
constexpr std::size_t kTail = kBlock;      // kInf words after a and after b
constexpr std::size_t kWide = 1024;        // ranges this wide (>= 9 blocks) use the bounds
constexpr std::size_t kNarrow = 128;      // dense ranges this narrow get dense children
constexpr std::size_t kListWords = std::size_t(1) << 16;  // capacity of a level's candidate lists

struct Problem {
    std::size_t n, m;    // lengths of a and b
    const u32* a;        // a[-kAPad, n + kTail)
    const u32* b;        // b[0, m + kTail)
    const u32* b_least;  // b_least[J] = min b[kBlock J, kBlock (J + 1)) for kBlock J < m
    const u32* a_least;  // a_least[w] = min a[kBlock (w - 1), kBlock (w + 1)), w <= ceil(n / kBlock)
};

u32 value(const Problem& p, std::size_t k, std::size_t j) { return p.b[j] + p.a[k - j]; }
std::size_t first_valid(const Problem& p, std::size_t k) { return k + 1 > p.n ? k + 1 - p.n : 0; }
std::size_t last_valid(const Problem& p, std::size_t k) { return std::min(k, p.m - 1); }

u32 horizontal_min(__m256i v) {
    __m128i x = _mm_min_epu32(_mm256_castsi256_si128(v), _mm256_extracti128_si256(v, 1));
    x = _mm_min_epu32(x, _mm_shuffle_epi32(x, 0x4E));
    x = _mm_min_epu32(x, _mm_shuffle_epi32(x, 0xB1));
    return u32(_mm_cvtsi128_si32(x));
}

// y[j, j + 8) + x[k - j - 8 + 1, k - j + 1) reversed: the min-plus row k of x and y at columns j..j+7.
__m256i row_chunk(const u32* x, const u32* y, std::size_t k, std::size_t j) {
    const __m256i reverse = _mm256_setr_epi32(7, 6, 5, 4, 3, 2, 1, 0);
    const __m256i lhs = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(x + (k - j) - 7));
    const __m256i rhs = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(y + j));
    return _mm256_add_epi32(rhs, _mm256_permutevar8x32_epi32(lhs, reverse));
}

// Lower bounds of blocks J..J+7 for the rows k with k / kBlock = q; bound <= 4e9.
__m256i block_bounds(const Problem& p, std::size_t q, std::size_t J) { return row_chunk(p.a_least, p.b_least, q, J); }

u32 block_bound(const Problem& p, std::size_t q, std::size_t J) { return p.b_least[J] + p.a_least[q - J]; }

// Lanes (bits 0-7) of v below limit, unsigned.
unsigned lanes_below(__m256i v, u32 limit) {
    const __m256i below = _mm256_xor_si256(_mm256_cmpeq_epi32(_mm256_max_epu32(v, _mm256_set1_epi32(int(limit))), v),
                                           _mm256_set1_epi32(-1));
    return unsigned(_mm256_movemask_ps(_mm256_castsi256_ps(below)));
}

// Leftmost column among the lanes holding the least value.
u32 leftmost(__m256i value, __m256i column) {
    const __m256i least = _mm256_set1_epi32(int(horizontal_min(value)));
    const __m256i other = _mm256_xor_si256(_mm256_cmpeq_epi32(value, least), _mm256_set1_epi32(-1));
    return horizontal_min(_mm256_or_si256(column, other));
}

// Leftmost j in [lo, hi] minimizing f_k(j); every column in range is valid.
std::size_t argmin(const Problem& p, std::size_t k, std::size_t lo, std::size_t hi) {
    if (hi - lo < 8) {
        std::size_t best = lo;
        u32 best_value = value(p, k, lo);
        for (std::size_t j = lo + 1; j <= hi; ++j) {
            const u32 v = value(p, k, j);
            if (v < best_value) best = j, best_value = v;
        }
        return best;
    }
    // Per lane, the least value and its leftmost column. Chunks start at lo, lo + 8, ...; the
    // last one at hi - 7 overlaps its predecessor, still in increasing column order per lane.
    const std::size_t last = hi - 7;
    const __m256i lanes = _mm256_setr_epi32(0, 1, 2, 3, 4, 5, 6, 7);
    __m256i column = _mm256_add_epi32(_mm256_set1_epi32(int(lo)), lanes);
    __m256i best = _mm256_set1_epi32(-1), best_column = column;
    const auto take = [&](std::size_t j) {
        const __m256i low = _mm256_min_epu32(best, row_chunk(p.a, p.b, k, j));
        best_column = _mm256_blendv_epi8(column, best_column, _mm256_cmpeq_epi32(low, best));
        best = low;
    };
    for (std::size_t j = lo; j < last; j += 8) {
        take(j);
        column = _mm256_add_epi32(column, _mm256_set1_epi32(8));
    }
    column = _mm256_add_epi32(_mm256_set1_epi32(int(last)), lanes);
    take(last);
    return leftmost(best, best_column);
}

// Blocks [first, last) (last - first >= 8) in increasing order, or decreasing with Backward, whose
// bound is below limit(): visit(J) for each, re-reading limit() after each visit.
template <bool Backward, class Limit, class Visit>
void bounded_blocks(const Problem& p, std::size_t q, std::size_t first, std::size_t last, Limit limit, Visit visit) {
    const std::size_t vectors = (last - first + 7) / 8;
    for (std::size_t i = 0; i < vectors; ++i) {
        // The vector farthest along the scan overlaps the one before; its repeated lanes are masked.
        const std::size_t left = last - first - 8 * i;  // blocks not yet scanned
        const std::size_t start = Backward ? (left > 8 ? last - 8 * i - 8 : first) : std::min(first + 8 * i, last - 8);
        const std::size_t fresh = Backward ? last - 8 * i - start : start + 8 - (first + 8 * i);  // new lanes
        const unsigned mask = Backward ? (1u << fresh) - 1 : 0xFFu << (8 - fresh) & 0xFF;
        for (unsigned lanes = lanes_below(block_bounds(p, q, start), limit()) & mask; lanes;) {
            const unsigned lane = Backward ? 31 - unsigned(std::countl_zero(lanes)) : unsigned(std::countr_zero(lanes));
            lanes &= ~(1u << lane);
            const std::size_t J = start + lane;
            if (block_bound(p, q, J) < limit()) visit(J);
        }
    }
}

// A column and its value; better: smaller value, then smaller column.
struct Candidate {
    u32 value, column;
};

void keep_better(Candidate& best, Candidate x) {
    if (x.value < best.value || (x.value == best.value && x.column < best.column)) best = x;
}

Candidate candidate(const Problem& p, std::size_t k, std::size_t j) { return {value(p, k, j), u32(j)}; }

// Leftmost argmin of row k over best and the valid columns [lo, hi]. Wide ranges search only blocks
// whose bound is at most the best value found so far, runs of up to kRun adjacent blocks at once.
std::size_t search(const Problem& p, std::size_t k, std::size_t lo, std::size_t hi, Candidate best = {kNone, 0}) {
    constexpr std::size_t kRun = 64;
    if (hi - lo < kWide) {
        keep_better(best, candidate(p, k, argmin(p, k, lo, hi)));
        return best.column;
    }
    const std::size_t first = (lo + kBlock - 1) / kBlock, last = (hi + 1) / kBlock;  // whole blocks
    keep_better(best, candidate(p, k, hi));
    keep_better(best, candidate(p, k, lo));
    if (lo < first * kBlock) keep_better(best, candidate(p, k, argmin(p, k, lo, first * kBlock - 1)));
    if (last * kBlock <= hi) keep_better(best, candidate(p, k, argmin(p, k, last * kBlock, hi)));
    std::size_t run_first = 0, run_end = 0;  // pending blocks [run_first, run_end)
    const auto flush = [&] {
        if (run_end > run_first) keep_better(best, candidate(p, k, argmin(p, k, run_first * kBlock, run_end * kBlock - 1)));
        run_first = run_end;
    };
    bounded_blocks<false>(p, k / kBlock, first, last, [&] { return best.value + 1; }, [&](std::size_t J) {
        if (J != run_end || run_end - run_first == kRun) flush(), run_first = J;
        run_end = J + 1;
    });
    flush();
    return best.column;
}

// Records of row k in scan order: forward, the columns below every value before them; backward,
// the columns at most every value after them. Stops when there are more than 32 + 1/16 of the
// columns scanned: the candidates are then dense.
struct Records {
    u32* out;            // 8 words of slack
    std::size_t origin;  // first column scanned
    u32 limit = kNone;   // a column is a record if its value is below limit
    u32 last = 0;        // the last record
    std::size_t count = 0;

    template <bool Backward>
    bool add(std::size_t j, u32 v) {
        limit = v + Backward, last = u32(j);
        out[count++] = u32(j);
        return count <= 32 + (Backward ? origin - j : j - origin) / 16;
    }
};

// Lane numbers of the set bits of each 8-bit mask, one per byte: ascending, then descending.
constexpr auto kLanes = [] {
    std::array<std::array<std::uint64_t, 256>, 2> t{};
    for (unsigned mask = 0; mask < 256; ++mask)
        for (unsigned i = 0, up = 0, down = 0; i < 8; ++i) {
            if (mask >> i & 1) t[0][mask] |= std::uint64_t(i) << 8 * up++;
            if (mask >> (7 - i) & 1) t[1][mask] |= std::uint64_t(7 - i) << 8 * down++;
        }
    return t;
}();

// Record lanes (bits 0-7) of chunk v given limit (every lane): forward, v[i] < min(limit, v[0, i));
// backward, v[i] < min(limit, v(i, 8) + 1). least: the least value of the chunk, every lane.
// Values < 2^31: signed compares are exact.
template <bool Backward>
unsigned record_lanes(__m256i v, __m256i limit, __m256i& least) {
    const auto spread = [](__m256i x, __m256i from) { return _mm256_min_epu32(x, _mm256_permutevar8x32_epi32(x, from)); };
    if constexpr (!Backward) {
        const __m256i down = _mm256_setr_epi32(0, 0, 1, 2, 3, 4, 5, 6);
        const __m256i prefix = spread(spread(spread(v, down), _mm256_setr_epi32(0, 1, 0, 1, 2, 3, 4, 5)),
                                      _mm256_setr_epi32(0, 1, 2, 3, 0, 1, 2, 3));
        const __m256i before = _mm256_min_epu32(limit, _mm256_blend_epi32(_mm256_permutevar8x32_epi32(prefix, down), limit, 0x01));
        least = _mm256_permutevar8x32_epi32(prefix, _mm256_set1_epi32(7));
        return unsigned(_mm256_movemask_ps(_mm256_castsi256_ps(_mm256_cmpgt_epi32(before, v))));
    } else {
        const __m256i up = _mm256_setr_epi32(1, 2, 3, 4, 5, 6, 7, 7);
        const __m256i suffix = spread(spread(spread(v, up), _mm256_setr_epi32(2, 3, 4, 5, 6, 7, 6, 7)),
                                      _mm256_setr_epi32(4, 5, 6, 7, 4, 5, 6, 7));
        const __m256i after_plus = _mm256_permutevar8x32_epi32(_mm256_add_epi32(suffix, _mm256_set1_epi32(1)), up);
        const __m256i after = _mm256_min_epu32(limit, _mm256_blend_epi32(after_plus, limit, 0x80));
        least = _mm256_permutevar8x32_epi32(suffix, _mm256_setzero_si256());
        return unsigned(_mm256_movemask_ps(_mm256_castsi256_ps(_mm256_cmpgt_epi32(after, v))));
    }
}

// Records of row k among the lanes of chunk j..j+7 in mask (bits 0-7); false if they overflow.
template <bool Backward>
bool chunk_records(const Problem& p, std::size_t k, std::size_t j, unsigned mask, Records& r) {
    const __m256i v = row_chunk(p.a, p.b, k, j), limit = _mm256_set1_epi32(int(r.limit));
    if (!(unsigned(_mm256_movemask_ps(_mm256_castsi256_ps(_mm256_cmpgt_epi32(limit, v)))) & mask)) [[likely]] return true;
    __m256i least;
    const unsigned lanes = record_lanes<Backward>(v, limit, least) & mask;  // not 0: the first lane below limit
    const __m256i numbers = _mm256_cvtepu8_epi32(_mm_cvtsi64_si128(std::int64_t(kLanes[Backward][lanes])));
    _mm256_storeu_si256(reinterpret_cast<__m256i*>(r.out + r.count), _mm256_add_epi32(numbers, _mm256_set1_epi32(int(j))));
    r.count += unsigned(std::popcount(lanes));
    r.limit = u32(_mm256_cvtsi256_si32(least)) + Backward;
    r.last = u32(j + (Backward ? unsigned(std::countr_zero(lanes)) : 31 - unsigned(std::countl_zero(lanes))));
    return r.count <= 32 + (Backward ? r.origin - j : j - r.origin) / 16;
}

// Records of row k over the valid columns [lo, hi], in chunks; false if they overflow.
template <bool Backward>
bool range_records(const Problem& p, std::size_t k, std::size_t lo, std::size_t hi, Records& r) {
    if (hi - lo < 8) {
        for (std::size_t i = 0; i <= hi - lo; ++i) {
            const std::size_t j = Backward ? hi - i : lo + i;
            const u32 v = value(p, k, j);
            if (v < r.limit && !r.add<Backward>(j, v)) return false;
        }
        return true;
    }
    // The chunk farthest along the scan overlaps the one before; its repeated lanes are masked.
    const std::size_t chunks = (hi - lo + 8) / 8;
    for (std::size_t i = 0; i < chunks; ++i) {
        const std::size_t j = Backward ? std::max(lo, hi - 7 - std::min(hi - 7, 8 * i)) : std::min(lo + 8 * i, hi - 7);
        const std::size_t fresh = Backward ? hi - 8 * i - j + 1 : j + 8 - (lo + 8 * i);
        const unsigned mask = Backward ? (1u << std::min<std::size_t>(fresh, 8)) - 1 : 0xFFu << (8 - fresh) & 0xFF;
        if (!chunk_records<Backward>(p, k, j, mask, r)) return false;
    }
    return true;
}

// Records of row k over the valid columns [lo, hi]; wide ranges skip blocks whose bound is not
// below the limit. False if they overflow.
template <bool Backward>
bool records(const Problem& p, std::size_t k, std::size_t lo, std::size_t hi, Records& r) {
    if (hi - lo < kWide) return range_records<Backward>(p, k, lo, hi, r);
    const std::size_t first = (lo + kBlock - 1) / kBlock, last = (hi + 1) / kBlock;  // whole blocks
    const auto head = [&] { return lo == first * kBlock || range_records<Backward>(p, k, lo, first * kBlock - 1, r); };
    const auto tail = [&] { return hi < last * kBlock || range_records<Backward>(p, k, last * kBlock, hi, r); };
    if (!(Backward ? tail() : head())) return false;
    bool fits = true;
    bounded_blocks<Backward>(p, k / kBlock, first, last, [&] { return fits ? r.limit : 0; }, [&](std::size_t J) {
        fits = range_records<Backward>(p, k, J * kBlock, J * kBlock + kBlock - 1, r);
    });
    return fits && (Backward ? head() : tail());
}

// Whether the first 8 columns scanned, from lo or back from hi (all valid), are all records:
// then most columns are (monotone rows), and a scan for records would overflow.
template <bool Backward>
bool starts_dense(const Problem& p, std::size_t k, std::size_t lo, std::size_t hi) {
    if (hi - lo < 8) return false;
    const __m256i v = row_chunk(p.a, p.b, k, Backward ? hi - 7 : lo);
    const __m256i next = _mm256_permutevar8x32_epi32(v, _mm256_setr_epi32(1, 2, 3, 4, 5, 6, 7, 7));
    const auto falls = unsigned(_mm256_movemask_ps(_mm256_castsi256_ps(_mm256_cmpgt_epi32(v, next)))) & 0x7F;
    return falls == (Backward ? 0 : 0x7F);
}

// Candidate columns of a node: dense, the range [first, first + count); else count sorted columns
// at first in the level's list buffer.
struct Candidates {
    u32 first;
    u32 count : 31;
    u32 dense : 1;
};

Candidates dense(std::size_t lo, std::size_t hi) { return {u32(lo), u32(hi - lo + 1), 1}; }

struct ListBuffer {
    u32* words;  // kListWords
    std::size_t used = 0;

    bool fits(std::size_t count) const { return used + count <= kListWords; }
    void range(std::size_t lo, std::size_t hi) {
        for (std::size_t j = lo; j < hi; ++j) words[used++] = u32(j);
    }
    void list(const u32* from, std::size_t count) {
        std::copy_n(from, count, words + used);
        used += count;
    }
    // The candidates appended since used was first.
    Candidates since(std::size_t first) const { return {u32(first), u32(used - first), 0}; }
};

struct Children {
    Candidates left, right;
};

// Row k over the dense candidates [lo, hi]: its opt, and the children's candidates in next.
// scratch: kListWords words.
Children split_dense(const Problem& p, std::size_t k, std::size_t lo, std::size_t hi, u32& opt, ListBuffer& next,
                     u32* scratch) {
    const std::size_t valid_lo = std::max(lo, first_valid(p, k)), valid_hi = std::min(hi, last_valid(p, k));
    if (valid_hi - valid_lo < kNarrow) {
        opt = u32(argmin(p, k, valid_lo, valid_hi));
        return {dense(lo, opt), dense(opt, hi)};
    }
    // A sparse child holds at most 1/8 of its range; columns invalid in row k are kept.
    const auto sparse = [](std::size_t kept, std::size_t width) { return kept * 8 <= width; };
    // Left: the columns invalid in row k, then the strict prefix records; the last record is opt.
    Records forward{scratch, valid_lo};
    bool listed = false;
    if (!sparse(valid_lo - lo, valid_hi - lo + 1) || starts_dense<false>(p, k, valid_lo, valid_hi)) {
        opt = u32(search(p, k, valid_lo, valid_hi));
    } else if (!records<false>(p, k, valid_lo, valid_hi, forward)) {  // dense: the argmin of the rest
        const Candidate best{forward.limit, forward.last};
        opt = forward.last < valid_hi ? u32(search(p, k, forward.last + 1, valid_hi, best)) : forward.last;
    } else {
        opt = forward.last;
        const std::size_t kept = valid_lo - lo + forward.count;
        listed = sparse(kept, opt - lo + 1) && next.fits(kept);
    }
    Children children{dense(lo, opt), dense(opt, hi)};
    if (listed) {
        const std::size_t first = next.used;
        next.range(lo, valid_lo);
        next.list(scratch, forward.count);
        children.left = next.since(first);
    }
    // Right: the suffix minima from opt on, then the columns invalid in row k.
    Records backward{scratch, valid_hi};
    const std::size_t width = hi - opt + 1;
    if (sparse(hi - valid_hi, width) && !starts_dense<true>(p, k, opt, valid_hi) &&
        records<true>(p, k, opt, valid_hi, backward) && sparse(backward.count + hi - valid_hi, width) &&
        next.fits(backward.count + hi - valid_hi)) {
        const std::size_t first = next.used;
        std::reverse(scratch, scratch + backward.count);
        next.list(scratch, backward.count);
        next.range(valid_hi + 1, hi + 1);
        children.right = next.since(first);
    }
    return children;
}

// Row k over the sorted candidate list[0, count): its opt, and the children's lists in next.
// values: kListWords words.
Children split_list(const Problem& p, std::size_t k, const u32* list, std::size_t count, u32& opt, ListBuffer& next,
                    u32* values) {
    const std::size_t lo = first_valid(p, k), hi = last_valid(p, k);
    std::size_t begin = 0, end = count;  // the valid columns list[begin, end)
    while (list[begin] < lo) ++begin;
    while (list[end - 1] > hi) --end;
    if (!next.fits(count + 1)) {  // children hold at most count + 1 columns
        std::size_t best = begin;
        for (std::size_t i = begin; i < end; ++i)
            if ((values[i] = value(p, k, list[i])) < values[best]) best = i;
        opt = list[best];
        return {dense(list[0], opt), dense(opt, list[count - 1])};
    }
    // Left: the invalid columns before, then the strict prefix records; the last record is opt.
    const std::size_t left_first = next.used;
    next.list(list, begin);
    u32 least = kNone;
    std::size_t best = begin;
    for (std::size_t i = begin; i < end; ++i) {
        values[i] = value(p, k, list[i]);
        if (values[i] < least) least = values[i], best = i, next.words[next.used++] = list[i];
    }
    opt = list[best];
    const Candidates left = next.since(left_first);
    // Right: the suffix minima from opt on, then the invalid columns after.
    const std::size_t right_first = next.used;
    least = kNone;
    for (std::size_t i = end; i-- > best;)
        if (values[i] <= least) least = values[i], next.words[next.used++] = list[i];
    std::reverse(next.words + right_first, next.words + next.used);
    next.list(list + end, count - end);
    return {left, next.since(right_first)};
}

// The bisection over sample rows t * kGroup, t < groups; rows t >= groups are virtual with opt
// m - 1. node[t]: candidates of the active node whose left end is t at the current level. On return,
// lists holds the last level's lists (node[t] of every unsettled group t).
struct Sampler {
    const Problem& p;
    std::size_t groups;
    u32* opt;            // [0, bit_ceil(groups)]
    Candidates* node;    // [0, bit_ceil(groups)]
    ListBuffer lists[2];
    u32* scratch;        // kListWords
    const u32* last_lists = nullptr;

    void run() {
        const std::size_t size = std::bit_ceil(groups);
        std::fill(opt + groups, opt + size + 1, u32(p.m - 1));
        opt[0] = 0;
        node[0] = dense(0, p.m - 1);
        settle(0, size);
        int current = 0;
        for (std::size_t step = size / 2; step; step /= 2) {
            ListBuffer& next = lists[current ^ 1];
            next.used = 0;
            for (std::size_t left = 0; left < size; left += 2 * step) {
                if (opt[left] == opt[left + 2 * step]) continue;  // settled
                const std::size_t t = left + step;
                const Candidates c = node[left];
                const u32* const list = c.dense ? nullptr : lists[current].words + c.first;
                if (t >= groups) {  // virtual middle: the left child keeps the candidates
                    if (c.dense) {
                        node[left] = c;
                    } else if (next.fits(c.count)) {
                        const std::size_t first = next.used;
                        next.list(list, c.count);
                        node[left] = next.since(first);
                    } else {
                        node[left] = dense(list[0], list[c.count - 1]);
                    }
                    settle(left, t);
                    continue;
                }
                const std::size_t k = t * kGroup;
                const Children children = c.dense ? split_dense(p, k, c.first, c.first + c.count - 1, opt[t], next, scratch)
                                                  : split_list(p, k, list, c.count, opt[t], next, scratch);
                node[left] = children.left;
                node[t] = children.right;
                settle(left, t);
                settle(t, left + 2 * step);
            }
            current ^= 1;
        }
        last_lists = lists[current].words;
    }

    // A node whose ends share their opt: every row between has it.
    void settle(std::size_t left, std::size_t right) {
        if (opt[left] == opt[right]) std::fill(opt + left + 1, opt + right, opt[left]);
    }
};

// low[v] lane i = min(low[v] lane i, f_{k0 + 8v + i}(j)), kInf-padded a for invalid columns.
void take_column(const Problem& p, std::size_t k0, std::size_t j, __m256i (&low)[kVecs]) {
    const __m256i b = _mm256_set1_epi32(int(p.b[j]));
    const auto* a = reinterpret_cast<const __m256i_u*>(p.a + (k0 - j));  // index >= 1 - kGroup
    for (std::size_t v = 0; v < kVecs; ++v) low[v] = _mm256_min_epu32(low[v], _mm256_add_epi32(b, _mm256_loadu_si256(a + v)));
}

// c[k0, k0 + kGroup) for group t into c: one column if settled, else its node's candidates, the
// columns of a dense range clamped to the rows' valid columns.
void group(const Problem& p, const Sampler& s, std::size_t t, u32* c) {
    const std::size_t k0 = t * kGroup;
    __m256i low[kVecs];
    for (auto& v : low) v = _mm256_set1_epi32(-1);
    if (s.opt[t] == s.opt[t + 1]) {
        take_column(p, k0, s.opt[t], low);
    } else if (const Candidates nc = s.node[t]; nc.dense) {
        const std::size_t lo = std::max(std::size_t{nc.first}, first_valid(p, k0));
        const std::size_t hi = std::min(std::size_t{nc.first} + nc.count - 1, k0 + kGroup - 1);
        for (std::size_t j = lo; j <= hi; ++j) take_column(p, k0, j, low);
    } else {
        for (std::size_t i = 0; i < nc.count; ++i) take_column(p, k0, s.last_lists[nc.first + i], low);
    }
    auto* out = reinterpret_cast<__m256i_u*>(c);
    for (std::size_t v = 0; v < kVecs; ++v) _mm256_storeu_si256(out + v, low[v]);
}

// least[J] = min x[kBlock J, kBlock (J + 1)) for J < blocks; x readable over the whole blocks.
void block_minima(const u32* x, std::size_t blocks, u32* least) {
    for (std::size_t J = 0; J < blocks; ++J) {
        const auto* v = reinterpret_cast<const __m256i_u*>(x + J * kBlock);
        __m256i low = _mm256_loadu_si256(v);
        for (std::size_t i = 1; i < kBlock / 8; ++i) low = _mm256_min_epu32(low, _mm256_loadu_si256(v + i));
        least[J] = horizontal_min(low);
    }
}

// Marks a mapped input as read once, so the kernel skips marking each page accessed when the
// Reader unmaps it (as ../bitwise_and_convolution). The mapping starts at the page of the first token.
void advise_sequential(const io::Reader& in) {
    struct stat st;
    if (::fstat(0, &st) != 0 || !S_ISREG(st.st_mode) || std::size_t(st.st_size) <= io::detail::kMapAbove) return;
    const auto start = reinterpret_cast<std::uintptr_t>(in.scan().cur) & ~std::uintptr_t(4095);
    ::madvise(reinterpret_cast<void*>(start), std::size_t(st.st_size), MADV_SEQUENTIAL);
}

void solve() {
    io::Reader in;
    const std::size_t n = in.read<u32>(), m = in.read<u32>(), count = n + m - 1;
    advise_sequential(in);
    const std::size_t groups = (count + kGroup - 1) / kGroup, nodes = std::bit_ceil(groups) + 1;
    const std::size_t a_blocks = (n + kBlock - 1) / kBlock, b_blocks = (m + kBlock - 1) / kBlock;
    mem::Arena arena(columns::kTextBytes + 4 * (kAPad + n + kTail + m + kTail + nodes + b_blocks + a_blocks + 1 +
                                                3 * kListWords + columns::kBlock + kGroup) +
                     sizeof(Candidates) * nodes + 64 * 12);
    char* const text = arena.take<char>(columns::kTextBytes);
    u32* const a = arena.take<u32>(kAPad + n + kTail);
    u32* const b = arena.take<u32>(m + kTail);
    std::fill_n(a, kAPad, kInf);
    runs::read(in, a + kAPad, n);
    std::fill_n(a + kAPad + n, kTail, kInf);
    runs::read(in, b, m);
    std::fill_n(b + m, kTail, kInf);

    // a_least[w] = min(window w - 1, window w), windows outside [0, n) all kInf.
    u32* const b_least = arena.take<u32>(b_blocks);
    u32* const a_least = arena.take<u32>(a_blocks + 1);
    block_minima(b, b_blocks, b_least);
    block_minima(a + kAPad, a_blocks, a_least + 1);
    a_least[0] = a_least[1];
    for (std::size_t w = 1; w < a_blocks; ++w) a_least[w] = std::min(a_least[w], a_least[w + 1]);

    // The list buffers last: their tails are rarely touched, so they seldom fault in another huge page.
    const Problem p{n, m, a + kAPad, b, b_least, a_least};
    u32* const opt = arena.take<u32>(nodes);
    Candidates* const node = arena.take<Candidates>(nodes);
    u32* const c = arena.take<u32>(columns::kBlock + kGroup);
    Sampler sampler{p, groups, opt, node, {{arena.take<u32>(kListWords)}, {arena.take<u32>(kListWords)}},
                    arena.take<u32>(kListWords)};
    sampler.run();

    // c by output blocks, each formatted and written while it is in cache.
    io::Writer out;
    for (std::size_t k0 = 0; k0 < count; k0 += columns::kBlock) {
        const std::size_t size = std::min(columns::kBlock, count - k0), end = (size + kGroup - 1) / kGroup * kGroup;
        for (std::size_t i = 0; i < end; i += kGroup) group(p, sampler, (k0 + i) / kGroup, c + i);
        std::fill(c + size, c + end, 0);
        columns::write(out, c, size, text);
    }
}

}  // namespace

RUN_EARLY(solve)
