#pragma once
#include <toy/mod.h>
namespace toy {
// CPUID: AVX2 (the project targets x86-64-v3).
// Scheduled Shoup butterflies adapted from Aiyiyi's submitted qasm kernel.
// Keep upstream kernel names/instruction order for comparison. All callers use
// AVX instructions; GCC/Clang handle vzeroupper at the surrounding call boundary.
// Two adjacent butterflies overlap independent products; all memory clobbers
// are explicit. Inputs <4P, outputs <4P forward and <2P inverse.
template<u32 P> struct ButterflyAsm {
    using U=u32;using V=__m256i;
    inline static constexpr U asm_const_P=P,asm_const_P2=2*P,asm_const_NI=Mod<P>::inverse;
[[gnu::always_inline]] static void fwd_ls2h(V* f, long h, const U* px, const U* py) {
    alignas(32) V tw[6];
    char* p = (char*)f; const long H = h * 32, H3 = 3 * H;
    char* q = nullptr;
    // (no source array)
    char* const end = p + H; char* const last = end - 64;
    (void)last; (void)end;
    asm volatile(
        "vpbroadcastd %[cP], %%ymm15\n\t"
        "vpbroadcastd %[cP2], %%ymm14\n\t"
        "vbroadcastss (%[px]), %%ymm0\n\t"
        "vmovdqa %%ymm0, 0(%[tw])\n\t"
        "vbroadcastss 32(%[px]), %%ymm11\n\t"
        "vbroadcastss (%[py]), %%ymm0\n\t"
        "vmovdqa %%ymm0, 64(%[tw])\n\t"
        "vbroadcastss 32(%[py]), %%ymm12\n\t"
        "vbroadcastss 4(%[py]), %%ymm0\n\t"
        "vmovdqa %%ymm0, 128(%[tw])\n\t"
        "vbroadcastss 36(%[py]), %%ymm13\n\t"
        ".p2align 5\n\t"
        "1:\n\t"
        "vmovdqa (%[p],%[H3]), %%ymm0\n\t"
        "vmovdqa 32(%[p],%[H3]), %%ymm1\n\t"
        "vmovdqa (%[p],%[H]), %%ymm2\n\t"
        "vmovdqa 32(%[p],%[H]), %%ymm3\n\t"
        "vpmuludq (%[p],%[H3]), %%ymm11, %%ymm4\n\t"
        "vpmuludq 32(%[p],%[H3]), %%ymm11, %%ymm5\n\t"
        "vpmuludq 4(%[p],%[H3]), %%ymm11, %%ymm6\n\t"
        "vpmuludq 36(%[p],%[H3]), %%ymm11, %%ymm7\n\t"
        "vmovdqa (%[p],%[H],2), %%ymm8\n\t"
        "vpsrlq $32, %%ymm4, %%ymm4\n\t"
        "vmovdqa 32(%[p],%[H],2), %%ymm9\n\t"
        "vpsrlq $32, %%ymm5, %%ymm5\n\t"
        "vpblendd $170, %%ymm6, %%ymm4, %%ymm6\n\t"
        "vpblendd $170, %%ymm7, %%ymm5, %%ymm7\n\t"
        "vmovdqa (%[p]), %%ymm5\n\t"
        "vpmulld 0(%[tw]), %%ymm0, %%ymm0\n\t"
        "vpmulld %%ymm15, %%ymm6, %%ymm6\n\t"
        "vmovdqa 32(%[p]), %%ymm4\n\t"
        "vpmulld 0(%[tw]), %%ymm1, %%ymm1\n\t"
        "vpmulld %%ymm15, %%ymm7, %%ymm7\n\t"
        "vpsubd %%ymm14, %%ymm2, %%ymm10\n\t"
        "vpminud %%ymm10, %%ymm2, %%ymm10\n\t"
        "vpmuludq (%[p],%[H],2), %%ymm11, %%ymm2\n\t"
        "vpsubd %%ymm6, %%ymm0, %%ymm6\n\t"
        "vpsubd %%ymm14, %%ymm3, %%ymm0\n\t"
        "vpminud %%ymm0, %%ymm3, %%ymm0\n\t"
        "vpsubd %%ymm7, %%ymm1, %%ymm7\n\t"
        "vpmuludq 32(%[p],%[H],2), %%ymm11, %%ymm1\n\t"
        "vpmuludq 4(%[p],%[H],2), %%ymm11, %%ymm3\n\t"
        "vpsrlq $32, %%ymm2, %%ymm2\n\t"
        "vpmulld 0(%[tw]), %%ymm8, %%ymm8\n\t"
        "vpmulld 0(%[tw]), %%ymm9, %%ymm9\n\t"
        "vpsrlq $32, %%ymm1, %%ymm1\n\t"
        "vpblendd $170, %%ymm3, %%ymm2, %%ymm3\n\t"
        "vpmuludq 36(%[p],%[H],2), %%ymm11, %%ymm2\n\t"
        "vpmulld %%ymm15, %%ymm3, %%ymm3\n\t"
        "vpblendd $170, %%ymm2, %%ymm1, %%ymm2\n\t"
        "vpaddd %%ymm14, %%ymm10, %%ymm1\n\t"
        "vpaddd %%ymm6, %%ymm10, %%ymm10\n\t"
        "vpsubd %%ymm6, %%ymm1, %%ymm6\n\t"
        "vpmulld %%ymm15, %%ymm2, %%ymm2\n\t"
        "vpsubd %%ymm3, %%ymm8, %%ymm3\n\t"
        "vpaddd %%ymm14, %%ymm0, %%ymm8\n\t"
        "vpaddd %%ymm7, %%ymm0, %%ymm0\n\t"
        "vpsubd %%ymm7, %%ymm8, %%ymm7\n\t"
        "vpsrlq $32, %%ymm10, %%ymm8\n\t"
        "vpmuludq %%ymm12, %%ymm10, %%ymm1\n\t"
        "vpmuludq %%ymm12, %%ymm8, %%ymm8\n\t"
        "vpmulld 64(%[tw]), %%ymm10, %%ymm10\n\t"
        "vpsubd %%ymm2, %%ymm9, %%ymm2\n\t"
        "vpsrlq $32, %%ymm6, %%ymm9\n\t"
        "vpmuludq %%ymm13, %%ymm9, %%ymm9\n\t"
        "vpsrlq $32, %%ymm1, %%ymm1\n\t"
        "vpblendd $170, %%ymm8, %%ymm1, %%ymm8\n\t"
        "vpmuludq %%ymm13, %%ymm6, %%ymm1\n\t"
        "vpmulld 128(%[tw]), %%ymm6, %%ymm6\n\t"
        "vpmulld %%ymm15, %%ymm8, %%ymm8\n\t"
        "vpsrlq $32, %%ymm1, %%ymm1\n\t"
        "vpblendd $170, %%ymm9, %%ymm1, %%ymm9\n\t"
        "vpsubd %%ymm8, %%ymm10, %%ymm8\n\t"
        "vpsrlq $32, %%ymm0, %%ymm10\n\t"
        "vpmuludq %%ymm12, %%ymm0, %%ymm1\n\t"
        "vpmuludq %%ymm12, %%ymm10, %%ymm10\n\t"
        "vpmulld %%ymm15, %%ymm9, %%ymm9\n\t"
        "vpmulld 64(%[tw]), %%ymm0, %%ymm0\n\t"
        "vpsrlq $32, %%ymm1, %%ymm1\n\t"
        "vpblendd $170, %%ymm10, %%ymm1, %%ymm10\n\t"
        "vpsubd %%ymm9, %%ymm6, %%ymm9\n\t"
        "vpsrlq $32, %%ymm7, %%ymm6\n\t"
        "vpmuludq %%ymm13, %%ymm7, %%ymm1\n\t"
        "vpmuludq %%ymm13, %%ymm6, %%ymm6\n\t"
        "vpmulld %%ymm15, %%ymm10, %%ymm10\n\t"
        "vpmulld 128(%[tw]), %%ymm7, %%ymm7\n\t"
        "vpsrlq $32, %%ymm1, %%ymm1\n\t"
        "vpblendd $170, %%ymm6, %%ymm1, %%ymm6\n\t"
        "vpsubd %%ymm10, %%ymm0, %%ymm10\n\t"
        "vpsubd %%ymm14, %%ymm5, %%ymm0\n\t"
        "vpsubd %%ymm14, %%ymm4, %%ymm1\n\t"
        "vpminud %%ymm0, %%ymm5, %%ymm0\n\t"
        "vpminud %%ymm1, %%ymm4, %%ymm1\n\t"
        "vpmulld %%ymm15, %%ymm6, %%ymm6\n\t"
        "vpaddd %%ymm3, %%ymm0, %%ymm4\n\t"
        "vpsubd %%ymm3, %%ymm0, %%ymm3\n\t"
        "vpaddd %%ymm2, %%ymm1, %%ymm0\n\t"
        "vpsubd %%ymm2, %%ymm1, %%ymm2\n\t"
        "vpsubd %%ymm14, %%ymm4, %%ymm1\n\t"
        "vpaddd %%ymm14, %%ymm3, %%ymm5\n\t"
        "vpminud %%ymm1, %%ymm4, %%ymm1\n\t"
        "vpminud %%ymm5, %%ymm3, %%ymm5\n\t"
        "vpsubd %%ymm6, %%ymm7, %%ymm6\n\t"
        "vpsubd %%ymm14, %%ymm0, %%ymm7\n\t"
        "vpaddd %%ymm14, %%ymm2, %%ymm3\n\t"
        "vpminud %%ymm7, %%ymm0, %%ymm7\n\t"
        "vpaddd %%ymm14, %%ymm1, %%ymm0\n\t"
        "vpaddd %%ymm14, %%ymm5, %%ymm4\n\t"
        "vpminud %%ymm3, %%ymm2, %%ymm3\n\t"
        "vpaddd %%ymm8, %%ymm1, %%ymm1\n\t"
        "vpsubd %%ymm8, %%ymm0, %%ymm8\n\t"
        "vpaddd %%ymm9, %%ymm5, %%ymm5\n\t"
        "vpaddd %%ymm14, %%ymm7, %%ymm0\n\t"
        "vpaddd %%ymm14, %%ymm3, %%ymm2\n\t"
        "vpsubd %%ymm9, %%ymm4, %%ymm9\n\t"
        "vpaddd %%ymm10, %%ymm7, %%ymm7\n\t"
        "vmovdqa %%ymm1, (%[p])\n\t"
        "vpsubd %%ymm10, %%ymm0, %%ymm10\n\t"
        "vpaddd %%ymm6, %%ymm3, %%ymm3\n\t"
        "vpsubd %%ymm6, %%ymm2, %%ymm6\n\t"
        "vmovdqa %%ymm8, (%[p],%[H])\n\t"
        "vmovdqa %%ymm5, (%[p],%[H],2)\n\t"
        "vmovdqa %%ymm9, (%[p],%[H3])\n\t"
        "vmovdqa %%ymm7, 32(%[p])\n\t"
        "vmovdqa %%ymm10, 32(%[p],%[H])\n\t"
        "vmovdqa %%ymm3, 32(%[p],%[H],2)\n\t"
        "vmovdqa %%ymm6, 32(%[p],%[H3])\n\t"
        "add $64, %[p]\n\t"
        "cmp %[end], %[p]\n\t"
        "jne 1b\n\t"
        : [p] "+r"(p), [q] "+r"(q)
        : [end] "r"(end), [last] "r"(last), [H] "r"(H), [H3] "r"(H3), [px] "r"(px), [py] "r"(py),
          [tw] "r"(tw), [cP] "m"(asm_const_P), [cP2] "m"(asm_const_P2)
        : "xmm0", "xmm1", "xmm2", "xmm3", "xmm4", "xmm5", "xmm6", "xmm7", "xmm8", "xmm9",
          "xmm10", "xmm11", "xmm12", "xmm13", "xmm14", "xmm15", "memory", "cc");
}

// inv_at71: strategy=ls step=2 fold=1 twmem=half; 116 loop instructions; search (seed, margin, jitter) = (138, 0, 0.0, 16, 2, None); llvm-mca znver3 14.54 cycles/butterfly
[[gnu::always_inline]] static void inv_at71(V* f, long h, const U* px, const U* py) {
    alignas(32) V tw[6];
    char* p = (char*)f; const long H = h * 32, H3 = 3 * H;
    char* q = nullptr;
    // (no source array)
    char* const end = p + H; char* const last = end - 64;
    (void)last; (void)end;
    asm volatile(
        "vpbroadcastd %[cP], %%ymm15\n\t"
        "vpbroadcastd %[cP2], %%ymm14\n\t"
        "vbroadcastss (%[px]), %%ymm0\n\t"
        "vmovdqa %%ymm0, 0(%[tw])\n\t"
        "vbroadcastss 32(%[px]), %%ymm11\n\t"
        "vbroadcastss (%[py]), %%ymm0\n\t"
        "vmovdqa %%ymm0, 64(%[tw])\n\t"
        "vbroadcastss 32(%[py]), %%ymm12\n\t"
        "vbroadcastss 4(%[py]), %%ymm0\n\t"
        "vmovdqa %%ymm0, 128(%[tw])\n\t"
        "vbroadcastss 36(%[py]), %%ymm13\n\t"
        ".p2align 5\n\t"
        "1:\n\t"
        "vmovdqa (%[p]), %%ymm0\n\t"
        "vmovdqa 32(%[p]), %%ymm1\n\t"
        "vmovdqa (%[p],%[H],2), %%ymm2\n\t"
        "vmovdqa 32(%[p],%[H],2), %%ymm3\n\t"
        "vpaddd %%ymm14, %%ymm0, %%ymm4\n\t"
        "vpaddd (%[p],%[H]), %%ymm0, %%ymm0\n\t"
        "vpaddd %%ymm14, %%ymm1, %%ymm5\n\t"
        "vpsubd (%[p],%[H]), %%ymm4, %%ymm4\n\t"
        "vpaddd 32(%[p],%[H]), %%ymm1, %%ymm1\n\t"
        "vpsubd %%ymm14, %%ymm0, %%ymm6\n\t"
        "vpaddd %%ymm14, %%ymm2, %%ymm7\n\t"
        "vpsubd 32(%[p],%[H]), %%ymm5, %%ymm5\n\t"
        "vpsrlq $32, %%ymm4, %%ymm8\n\t"
        "vpmuludq %%ymm12, %%ymm4, %%ymm9\n\t"
        "vpaddd %%ymm14, %%ymm3, %%ymm10\n\t"
        "vpsubd (%[p],%[H3]), %%ymm7, %%ymm7\n\t"
        "vpmuludq %%ymm12, %%ymm8, %%ymm8\n\t"
        "vpmulld 64(%[tw]), %%ymm4, %%ymm4\n\t"
        "vpsubd 32(%[p],%[H3]), %%ymm10, %%ymm10\n\t"
        "vpaddd (%[p],%[H3]), %%ymm2, %%ymm2\n\t"
        "vpminud %%ymm6, %%ymm0, %%ymm6\n\t"
        "vpsrlq $32, %%ymm5, %%ymm0\n\t"
        "vpmuludq %%ymm12, %%ymm0, %%ymm0\n\t"
        "vpsrlq $32, %%ymm9, %%ymm9\n\t"
        "vpaddd 32(%[p],%[H3]), %%ymm3, %%ymm3\n\t"
        "vpblendd $170, %%ymm8, %%ymm9, %%ymm8\n\t"
        "vpmuludq %%ymm12, %%ymm5, %%ymm9\n\t"
        "vpmulld 64(%[tw]), %%ymm5, %%ymm5\n\t"
        "vpmulld %%ymm15, %%ymm8, %%ymm8\n\t"
        "vpsrlq $32, %%ymm9, %%ymm9\n\t"
        "vpblendd $170, %%ymm0, %%ymm9, %%ymm0\n\t"
        "vpsubd %%ymm8, %%ymm4, %%ymm8\n\t"
        "vpsrlq $32, %%ymm7, %%ymm4\n\t"
        "vpmuludq %%ymm13, %%ymm7, %%ymm9\n\t"
        "vpmuludq %%ymm13, %%ymm4, %%ymm4\n\t"
        "vpmulld %%ymm15, %%ymm0, %%ymm0\n\t"
        "vpmulld 128(%[tw]), %%ymm7, %%ymm7\n\t"
        "vpsrlq $32, %%ymm9, %%ymm9\n\t"
        "vpblendd $170, %%ymm4, %%ymm9, %%ymm4\n\t"
        "vpsubd %%ymm0, %%ymm5, %%ymm0\n\t"
        "vpsrlq $32, %%ymm10, %%ymm5\n\t"
        "vpmuludq %%ymm13, %%ymm10, %%ymm9\n\t"
        "vpmuludq %%ymm13, %%ymm5, %%ymm5\n\t"
        "vpmulld %%ymm15, %%ymm4, %%ymm4\n\t"
        "vpmulld 128(%[tw]), %%ymm10, %%ymm10\n\t"
        "vpsrlq $32, %%ymm9, %%ymm9\n\t"
        "vpblendd $170, %%ymm5, %%ymm9, %%ymm5\n\t"
        "vpsubd %%ymm4, %%ymm7, %%ymm4\n\t"
        "vpsubd %%ymm14, %%ymm1, %%ymm7\n\t"
        "vpsubd %%ymm14, %%ymm2, %%ymm9\n\t"
        "vpmulld %%ymm15, %%ymm5, %%ymm5\n\t"
        "vpminud %%ymm7, %%ymm1, %%ymm7\n\t"
        "vpminud %%ymm9, %%ymm2, %%ymm9\n\t"
        "vpsubd %%ymm14, %%ymm3, %%ymm2\n\t"
        "vpaddd %%ymm14, %%ymm6, %%ymm1\n\t"
        "vpminud %%ymm2, %%ymm3, %%ymm2\n\t"
        "vpaddd %%ymm14, %%ymm7, %%ymm3\n\t"
        "vpaddd %%ymm9, %%ymm6, %%ymm6\n\t"
        "vpsubd %%ymm9, %%ymm1, %%ymm9\n\t"
        "vpsubd %%ymm2, %%ymm3, %%ymm3\n\t"
        "vpaddd %%ymm2, %%ymm7, %%ymm2\n\t"
        "vpaddd %%ymm14, %%ymm8, %%ymm7\n\t"
        "vpsubd %%ymm5, %%ymm10, %%ymm5\n\t"
        "vpaddd %%ymm14, %%ymm0, %%ymm10\n\t"
        "vpsubd %%ymm4, %%ymm7, %%ymm7\n\t"
        "vpsrlq $32, %%ymm9, %%ymm1\n\t"
        "vpsubd %%ymm5, %%ymm10, %%ymm10\n\t"
        "vpmuludq %%ymm11, %%ymm1, %%ymm1\n\t"
        "vpaddd %%ymm4, %%ymm8, %%ymm4\n\t"
        "vpaddd %%ymm5, %%ymm0, %%ymm5\n\t"
        "vpmuludq %%ymm11, %%ymm9, %%ymm0\n\t"
        "vpsrlq $32, %%ymm7, %%ymm8\n\t"
        "vpmulld 0(%[tw]), %%ymm9, %%ymm9\n\t"
        "vpmuludq %%ymm11, %%ymm8, %%ymm8\n\t"
        "vpsrlq $32, %%ymm0, %%ymm0\n\t"
        "vpblendd $170, %%ymm1, %%ymm0, %%ymm1\n\t"
        "vpmuludq %%ymm11, %%ymm7, %%ymm0\n\t"
        "vpmulld 0(%[tw]), %%ymm7, %%ymm7\n\t"
        "vpmulld %%ymm15, %%ymm1, %%ymm1\n\t"
        "vpsrlq $32, %%ymm0, %%ymm0\n\t"
        "vpblendd $170, %%ymm8, %%ymm0, %%ymm8\n\t"
        "vpsubd %%ymm1, %%ymm9, %%ymm1\n\t"
        "vpsrlq $32, %%ymm3, %%ymm9\n\t"
        "vpmuludq %%ymm11, %%ymm3, %%ymm0\n\t"
        "vpmuludq %%ymm11, %%ymm9, %%ymm9\n\t"
        "vpmulld %%ymm15, %%ymm8, %%ymm8\n\t"
        "vmovdqa %%ymm1, (%[p],%[H],2)\n\t"
        "vpsrlq $32, %%ymm10, %%ymm1\n\t"
        "vpmuludq %%ymm11, %%ymm1, %%ymm1\n\t"
        "vpmulld 0(%[tw]), %%ymm3, %%ymm3\n\t"
        "vpsrlq $32, %%ymm0, %%ymm0\n\t"
        "vpblendd $170, %%ymm9, %%ymm0, %%ymm9\n\t"
        "vpsubd %%ymm8, %%ymm7, %%ymm8\n\t"
        "vpmuludq %%ymm11, %%ymm10, %%ymm7\n\t"
        "vpmulld 0(%[tw]), %%ymm10, %%ymm10\n\t"
        "vpmulld %%ymm15, %%ymm9, %%ymm9\n\t"
        "vpsubd %%ymm14, %%ymm6, %%ymm0\n\t"
        "vmovdqa %%ymm8, (%[p],%[H3])\n\t"
        "vpsubd %%ymm14, %%ymm4, %%ymm8\n\t"
        "vpminud %%ymm0, %%ymm6, %%ymm0\n\t"
        "vpsrlq $32, %%ymm7, %%ymm7\n\t"
        "vpsubd %%ymm14, %%ymm2, %%ymm6\n\t"
        "vpminud %%ymm8, %%ymm4, %%ymm8\n\t"
        "vmovdqa %%ymm0, (%[p])\n\t"
        "vpblendd $170, %%ymm1, %%ymm7, %%ymm1\n\t"
        "vpsubd %%ymm14, %%ymm5, %%ymm7\n\t"
        "vpminud %%ymm6, %%ymm2, %%ymm6\n\t"
        "vpsubd %%ymm9, %%ymm3, %%ymm9\n\t"
        "vmovdqa %%ymm8, (%[p],%[H])\n\t"
        "vpmulld %%ymm15, %%ymm1, %%ymm1\n\t"
        "vpminud %%ymm7, %%ymm5, %%ymm7\n\t"
        "vmovdqa %%ymm6, 32(%[p])\n\t"
        "vmovdqa %%ymm7, 32(%[p],%[H])\n\t"
        "vmovdqa %%ymm9, 32(%[p],%[H],2)\n\t"
        "vpsubd %%ymm1, %%ymm10, %%ymm1\n\t"
        "vmovdqa %%ymm1, 32(%[p],%[H3])\n\t"
        "add $64, %[p]\n\t"
        "cmp %[end], %[p]\n\t"
        "jne 1b\n\t"
        : [p] "+r"(p), [q] "+r"(q)
        : [end] "r"(end), [last] "r"(last), [H] "r"(H), [H3] "r"(H3), [px] "r"(px), [py] "r"(py),
          [tw] "r"(tw), [cP] "m"(asm_const_P), [cP2] "m"(asm_const_P2)
        : "xmm0", "xmm1", "xmm2", "xmm3", "xmm4", "xmm5", "xmm6", "xmm7", "xmm8", "xmm9",
          "xmm10", "xmm11", "xmm12", "xmm13", "xmm14", "xmm15", "memory", "cc");
}

// fwd_at104: strategy=ab step=1 fold=1 twmem=half; 114 loop instructions; search (seed, margin, jitter) = (129, 1, 0.0, 8, 3, None); llvm-mca znver3 32.04 cycles/butterfly
[[gnu::always_inline]] static void fwd_at104(V* f, V* g, long h, const U* px, const U* py) {
    alignas(32) V tw[6];
    char* p = (char*)f; const long H = h * 32, H3 = 3 * H;
    char* q = (char*)g;
    // (no source array)
    char* const end = p + H; char* const last = end - 32;
    (void)last; (void)end;
    asm volatile(
        "vpbroadcastd %[cP], %%ymm15\n\t"
        "vpbroadcastd %[cP2], %%ymm14\n\t"
        "vbroadcastss (%[px]), %%ymm0\n\t"
        "vmovdqa %%ymm0, 0(%[tw])\n\t"
        "vbroadcastss 32(%[px]), %%ymm11\n\t"
        "vbroadcastss (%[py]), %%ymm0\n\t"
        "vmovdqa %%ymm0, 64(%[tw])\n\t"
        "vbroadcastss 32(%[py]), %%ymm12\n\t"
        "vbroadcastss 4(%[py]), %%ymm0\n\t"
        "vmovdqa %%ymm0, 128(%[tw])\n\t"
        "vbroadcastss 36(%[py]), %%ymm13\n\t"
        ".p2align 5\n\t"
        "1:\n\t"
        "vmovdqa (%[p],%[H3]), %%ymm0\n\t"
        "vmovdqa (%[q],%[H3]), %%ymm1\n\t"
        "vmovdqa (%[p],%[H]), %%ymm2\n\t"
        "vmovdqa (%[q],%[H]), %%ymm3\n\t"
        "vpmuludq (%[p],%[H3]), %%ymm11, %%ymm4\n\t"
        "vpmuludq (%[q],%[H3]), %%ymm11, %%ymm5\n\t"
        "vmovdqa (%[p],%[H],2), %%ymm6\n\t"
        "vpmuludq 4(%[p],%[H3]), %%ymm11, %%ymm7\n\t"
        "vpmuludq 4(%[q],%[H3]), %%ymm11, %%ymm8\n\t"
        "vmovdqa (%[q],%[H],2), %%ymm9\n\t"
        "vmovdqa (%[p]), %%ymm10\n\t"
        "vpsrlq $32, %%ymm4, %%ymm4\n\t"
        "vpsrlq $32, %%ymm5, %%ymm5\n\t"
        "vpblendd $170, %%ymm7, %%ymm4, %%ymm7\n\t"
        "vpblendd $170, %%ymm8, %%ymm5, %%ymm8\n\t"
        "vmovdqa (%[q]), %%ymm5\n\t"
        "vpmuludq (%[p],%[H],2), %%ymm11, %%ymm4\n\t"
        "vpmulld %%ymm15, %%ymm7, %%ymm7\n\t"
        "vpmulld %%ymm15, %%ymm8, %%ymm8\n\t"
        "vpmulld 0(%[tw]), %%ymm0, %%ymm0\n\t"
        "vpmulld 0(%[tw]), %%ymm1, %%ymm1\n\t"
        "vpsrlq $32, %%ymm4, %%ymm4\n\t"
        "vpmulld 0(%[tw]), %%ymm6, %%ymm6\n\t"
        "vpsubd %%ymm7, %%ymm0, %%ymm7\n\t"
        "vpsubd %%ymm8, %%ymm1, %%ymm8\n\t"
        "vpmulld 0(%[tw]), %%ymm9, %%ymm9\n\t"
        "vpsubd %%ymm14, %%ymm2, %%ymm1\n\t"
        "vpminud %%ymm1, %%ymm2, %%ymm1\n\t"
        "vpsubd %%ymm14, %%ymm3, %%ymm2\n\t"
        "vpmuludq (%[q],%[H],2), %%ymm11, %%ymm0\n\t"
        "vpminud %%ymm2, %%ymm3, %%ymm2\n\t"
        "vpmuludq 4(%[p],%[H],2), %%ymm11, %%ymm3\n\t"
        "vpsrlq $32, %%ymm0, %%ymm0\n\t"
        "vpblendd $170, %%ymm3, %%ymm4, %%ymm3\n\t"
        "vpmuludq 4(%[q],%[H],2), %%ymm11, %%ymm4\n\t"
        "vpmulld %%ymm15, %%ymm3, %%ymm3\n\t"
        "vpblendd $170, %%ymm4, %%ymm0, %%ymm4\n\t"
        "vpaddd %%ymm14, %%ymm1, %%ymm0\n\t"
        "vpaddd %%ymm7, %%ymm1, %%ymm1\n\t"
        "vpsubd %%ymm7, %%ymm0, %%ymm7\n\t"
        "vpmulld %%ymm15, %%ymm4, %%ymm4\n\t"
        "vpsubd %%ymm3, %%ymm6, %%ymm3\n\t"
        "vpaddd %%ymm14, %%ymm2, %%ymm6\n\t"
        "vpaddd %%ymm8, %%ymm2, %%ymm2\n\t"
        "vpsubd %%ymm8, %%ymm6, %%ymm8\n\t"
        "vpsrlq $32, %%ymm1, %%ymm6\n\t"
        "vpmuludq %%ymm12, %%ymm1, %%ymm0\n\t"
        "vpmuludq %%ymm12, %%ymm6, %%ymm6\n\t"
        "vpmulld 64(%[tw]), %%ymm1, %%ymm1\n\t"
        "vpsubd %%ymm4, %%ymm9, %%ymm4\n\t"
        "vpsrlq $32, %%ymm7, %%ymm9\n\t"
        "vpmuludq %%ymm13, %%ymm9, %%ymm9\n\t"
        "vpsrlq $32, %%ymm0, %%ymm0\n\t"
        "vpblendd $170, %%ymm6, %%ymm0, %%ymm6\n\t"
        "vpmuludq %%ymm13, %%ymm7, %%ymm0\n\t"
        "vpmulld 128(%[tw]), %%ymm7, %%ymm7\n\t"
        "vpmulld %%ymm15, %%ymm6, %%ymm6\n\t"
        "vpsrlq $32, %%ymm0, %%ymm0\n\t"
        "vpblendd $170, %%ymm9, %%ymm0, %%ymm9\n\t"
        "vpsubd %%ymm6, %%ymm1, %%ymm6\n\t"
        "vpsrlq $32, %%ymm2, %%ymm1\n\t"
        "vpmuludq %%ymm12, %%ymm2, %%ymm0\n\t"
        "vpmuludq %%ymm12, %%ymm1, %%ymm1\n\t"
        "vpmulld %%ymm15, %%ymm9, %%ymm9\n\t"
        "vpmulld 64(%[tw]), %%ymm2, %%ymm2\n\t"
        "vpsrlq $32, %%ymm0, %%ymm0\n\t"
        "vpblendd $170, %%ymm1, %%ymm0, %%ymm1\n\t"
        "vpsubd %%ymm9, %%ymm7, %%ymm9\n\t"
        "vpsrlq $32, %%ymm8, %%ymm7\n\t"
        "vpmuludq %%ymm13, %%ymm8, %%ymm0\n\t"
        "vpmuludq %%ymm13, %%ymm7, %%ymm7\n\t"
        "vpmulld %%ymm15, %%ymm1, %%ymm1\n\t"
        "vpmulld 128(%[tw]), %%ymm8, %%ymm8\n\t"
        "vpsrlq $32, %%ymm0, %%ymm0\n\t"
        "vpblendd $170, %%ymm7, %%ymm0, %%ymm7\n\t"
        "vpsubd %%ymm1, %%ymm2, %%ymm1\n\t"
        "vpsubd %%ymm14, %%ymm10, %%ymm2\n\t"
        "vpsubd %%ymm14, %%ymm5, %%ymm0\n\t"
        "vpminud %%ymm2, %%ymm10, %%ymm2\n\t"
        "vpminud %%ymm0, %%ymm5, %%ymm0\n\t"
        "vpmulld %%ymm15, %%ymm7, %%ymm7\n\t"
        "vpaddd %%ymm3, %%ymm2, %%ymm5\n\t"
        "vpsubd %%ymm3, %%ymm2, %%ymm3\n\t"
        "vpaddd %%ymm4, %%ymm0, %%ymm2\n\t"
        "vpsubd %%ymm4, %%ymm0, %%ymm4\n\t"
        "vpsubd %%ymm14, %%ymm5, %%ymm0\n\t"
        "vpaddd %%ymm14, %%ymm3, %%ymm10\n\t"
        "vpminud %%ymm0, %%ymm5, %%ymm0\n\t"
        "vpminud %%ymm10, %%ymm3, %%ymm10\n\t"
        "vpsubd %%ymm7, %%ymm8, %%ymm7\n\t"
        "vpsubd %%ymm14, %%ymm2, %%ymm8\n\t"
        "vpaddd %%ymm14, %%ymm4, %%ymm3\n\t"
        "vpminud %%ymm8, %%ymm2, %%ymm8\n\t"
        "vpaddd %%ymm14, %%ymm0, %%ymm2\n\t"
        "vpaddd %%ymm14, %%ymm10, %%ymm5\n\t"
        "vpminud %%ymm3, %%ymm4, %%ymm3\n\t"
        "vpaddd %%ymm6, %%ymm0, %%ymm0\n\t"
        "vpsubd %%ymm6, %%ymm2, %%ymm6\n\t"
        "vpaddd %%ymm9, %%ymm10, %%ymm10\n\t"
        "vpaddd %%ymm14, %%ymm8, %%ymm2\n\t"
        "vpaddd %%ymm14, %%ymm3, %%ymm4\n\t"
        "vpsubd %%ymm9, %%ymm5, %%ymm9\n\t"
        "vpaddd %%ymm1, %%ymm8, %%ymm8\n\t"
        "vmovdqa %%ymm0, (%[p])\n\t"
        "vpsubd %%ymm1, %%ymm2, %%ymm1\n\t"
        "vpaddd %%ymm7, %%ymm3, %%ymm3\n\t"
        "vpsubd %%ymm7, %%ymm4, %%ymm7\n\t"
        "vmovdqa %%ymm6, (%[p],%[H])\n\t"
        "vmovdqa %%ymm10, (%[p],%[H],2)\n\t"
        "vmovdqa %%ymm9, (%[p],%[H3])\n\t"
        "vmovdqa %%ymm8, (%[q])\n\t"
        "vmovdqa %%ymm1, (%[q],%[H])\n\t"
        "vmovdqa %%ymm3, (%[q],%[H],2)\n\t"
        "vmovdqa %%ymm7, (%[q],%[H3])\n\t"
        "add $32, %[q]\n\t"
        "add $32, %[p]\n\t"
        "cmp %[end], %[p]\n\t"
        "jne 1b\n\t"
        : [p] "+r"(p), [q] "+r"(q)
        : [end] "r"(end), [last] "r"(last), [H] "r"(H), [H3] "r"(H3), [px] "r"(px), [py] "r"(py),
          [tw] "r"(tw), [cP] "m"(asm_const_P), [cP2] "m"(asm_const_P2)
        : "xmm0", "xmm1", "xmm2", "xmm3", "xmm4", "xmm5", "xmm6", "xmm7", "xmm8", "xmm9",
          "xmm10", "xmm11", "xmm12", "xmm13", "xmm14", "xmm15", "memory", "cc");
}

#define ASM_FWD_IDS " 11 104 "
#define ASM_INV_IDS " 71 "
[[gnu::always_inline]] static void bottom23_s12(const void* an, const void* bn, const void* Ln, const void* px, const void* py, const void* lw, const void* ac, const void* Lc, const void* ipx, const void* ipy) {
    asm volatile(
        "vpbroadcastd %[cP], %%ymm15\n\t"
        "vpbroadcastd %[cP2], %%ymm14\n\t"
        "vpbroadcastd %[cNI], %%ymm13\n\t"
        "vmovdqa 32(%[an]), %%ymm0\n\t"
        "vmovdqu 36(%[Lc]), %%ymm1\n\t"
        "vbroadcastss 256(%[Lc]), %%ymm2\n\t"
        "vbroadcastss 32(%[px]), %%ymm3\n\t"
        "vbroadcastss 32(%[px]), %%ymm4\n\t"
        "vbroadcastss 0(%[px]), %%ymm5\n\t"
        "vmovdqa 32(%[Lc]), %%ymm6\n\t"
        "vbroadcastss 256(%[Lc]), %%ymm7\n\t"
        "vmovdqa 0(%[an]), %%ymm8\n\t"
        "vpsubd %%ymm14, %%ymm0, %%ymm9\n\t"
        "vpminud %%ymm9, %%ymm0, %%ymm9\n\t"
        "vbroadcastss 260(%[Lc]), %%ymm0\n\t"
        "vpmuludq %%ymm2, %%ymm1, %%ymm2\n\t"
        "vpmuludq 64(%[an]), %%ymm3, %%ymm3\n\t"
        "vbroadcastss 32(%[px]), %%ymm1\n\t"
        "vpmuludq 68(%[an]), %%ymm4, %%ymm4\n\t"
        "vmovdqu 28(%[Lc]), %%ymm10\n\t"
        "vbroadcastss 260(%[Lc]), %%ymm11\n\t"
        "vpmuludq %%ymm7, %%ymm6, %%ymm7\n\t"
        "vpsrlq $32, %%ymm3, %%ymm3\n\t"
        "vpmulld 64(%[an]), %%ymm5, %%ymm5\n\t"
        "vpsubd %%ymm14, %%ymm8, %%ymm12\n\t"
        "vpblendd $170, %%ymm4, %%ymm3, %%ymm4\n\t"
        "vpminud %%ymm12, %%ymm8, %%ymm12\n\t"
        "vbroadcastss 264(%[Lc]), %%ymm8\n\t"
        "vbroadcastss 32(%[px]), %%ymm3\n\t"
        "vpmulld %%ymm15, %%ymm4, %%ymm4\n\t"
        "vpmuludq %%ymm0, %%ymm6, %%ymm0\n\t"
        "vpsubd %%ymm4, %%ymm5, %%ymm4\n\t"
        "vmovdqu 24(%[Lc]), %%ymm5\n\t"
        "vbroadcastss 264(%[Lc]), %%ymm6\n\t"
        "vpmuludq 96(%[an]), %%ymm1, %%ymm1\n\t"
        "vpmuludq %%ymm11, %%ymm10, %%ymm11\n\t"
        "vpaddq %%ymm0, %%ymm2, %%ymm0\n\t"
        "vbroadcastss 0(%[px]), %%ymm2\n\t"
        "vpmuludq %%ymm8, %%ymm10, %%ymm8\n\t"
        "vpmuludq 100(%[an]), %%ymm3, %%ymm3\n\t"
        "vpsrlq $32, %%ymm1, %%ymm1\n\t"
        "vbroadcastss 268(%[Lc]), %%ymm10\n\t"
        "vpaddq %%ymm11, %%ymm7, %%ymm11\n\t"
        "vmovdqu 20(%[Lc]), %%ymm7\n\t"
        "vpaddq %%ymm8, %%ymm0, %%ymm8\n\t"
        "vpblendd $170, %%ymm3, %%ymm1, %%ymm3\n\t"
        "vbroadcastss 268(%[Lc]), %%ymm1\n\t"
        "vpaddd %%ymm4, %%ymm12, %%ymm0\n\t"
        "vpmulld %%ymm15, %%ymm3, %%ymm3\n\t"
        "vpsubd %%ymm4, %%ymm12, %%ymm4\n\t"
        "vpsubd %%ymm14, %%ymm0, %%ymm12\n\t"
        "vpmuludq %%ymm6, %%ymm5, %%ymm6\n\t"
        "vpminud %%ymm12, %%ymm0, %%ymm12\n\t"
        "vbroadcastss 272(%[Lc]), %%ymm0\n\t"
        "vpmulld 96(%[an]), %%ymm2, %%ymm2\n\t"
        "vpmuludq %%ymm10, %%ymm5, %%ymm10\n\t"
        "vpaddq %%ymm6, %%ymm11, %%ymm6\n\t"
        "vmovdqu 16(%[Lc]), %%ymm11\n\t"
        "vpaddd %%ymm14, %%ymm4, %%ymm5\n\t"
        "vpminud %%ymm5, %%ymm4, %%ymm5\n\t"
        "vbroadcastss 272(%[Lc]), %%ymm4\n\t"
        "vpsubd %%ymm3, %%ymm2, %%ymm3\n\t"
        "vbroadcastss 276(%[Lc]), %%ymm2\n\t"
        "vpmuludq %%ymm1, %%ymm7, %%ymm1\n\t"
        "vpaddq %%ymm10, %%ymm8, %%ymm10\n\t"
        "vpaddd %%ymm14, %%ymm9, %%ymm8\n\t"
        "vpaddd %%ymm3, %%ymm9, %%ymm9\n\t"
        "vpsubd %%ymm3, %%ymm8, %%ymm3\n\t"
        "vbroadcastss 276(%[Lc]), %%ymm8\n\t"
        "vpmuludq %%ymm0, %%ymm7, %%ymm0\n\t"
        "vmovdqu 12(%[Lc]), %%ymm7\n\t"
        "vpaddq %%ymm1, %%ymm6, %%ymm1\n\t"
        "vbroadcastss 32(%[py]), %%ymm6\n\t"
        "vpaddq %%ymm0, %%ymm10, %%ymm0\n\t"
        "vbroadcastss 280(%[Lc]), %%ymm10\n\t"
        "vpmuludq %%ymm4, %%ymm11, %%ymm4\n\t"
        "vpmuludq %%ymm2, %%ymm11, %%ymm2\n\t"
        "vbroadcastss 32(%[py]), %%ymm11\n\t"
        "vpaddq %%ymm4, %%ymm1, %%ymm4\n\t"
        "vmovdqu 8(%[Lc]), %%ymm1\n\t"
        "vpmuludq %%ymm8, %%ymm7, %%ymm8\n\t"
        "vpaddq %%ymm2, %%ymm0, %%ymm2\n\t"
        "vbroadcastss 280(%[Lc]), %%ymm0\n\t"
        "vpmuludq %%ymm6, %%ymm9, %%ymm6\n\t"
        "vpmuludq %%ymm10, %%ymm7, %%ymm10\n\t"
        "vpaddq %%ymm8, %%ymm4, %%ymm8\n\t"
        "vbroadcastss 284(%[Lc]), %%ymm4\n\t"
        "vbroadcastss 0(%[py]), %%ymm7\n\t"
        "vpsrlq $32, %%ymm6, %%ymm6\n\t"
        "vpaddq %%ymm10, %%ymm2, %%ymm10\n\t"
        "vmovdqu 4(%[Lc]), %%ymm2\n\t"
        "vpmuludq %%ymm0, %%ymm1, %%ymm0\n\t"
        "vpaddq %%ymm0, %%ymm8, %%ymm0\n\t"
        "vpmuludq %%ymm4, %%ymm1, %%ymm4\n\t"
        "vpmulld %%ymm7, %%ymm9, %%ymm7\n\t"
        "vbroadcastss 284(%[Lc]), %%ymm1\n\t"
        "vpsrlq $32, %%ymm3, %%ymm8\n\t"
        "vpsrlq $32, %%ymm9, %%ymm9\n\t"
        "vpmuludq %%ymm11, %%ymm9, %%ymm11\n\t"
        "vbroadcastss 36(%[py]), %%ymm9\n\t"
        "vpaddq %%ymm4, %%ymm10, %%ymm4\n\t"
        "vbroadcastss 36(%[py]), %%ymm10\n\t"
        "vpblendd $170, %%ymm11, %%ymm6, %%ymm11\n\t"
        "vpmuludq %%ymm13, %%ymm4, %%ymm6\n\t"
        "vpmulld %%ymm15, %%ymm11, %%ymm11\n\t"
        "vpmuludq %%ymm1, %%ymm2, %%ymm1\n\t"
        "vpmuludq %%ymm15, %%ymm6, %%ymm6\n\t"
        "vbroadcastss 4(%[py]), %%ymm2\n\t"
        "vpsubd %%ymm11, %%ymm7, %%ymm11\n\t"
        "vpmuludq %%ymm9, %%ymm3, %%ymm9\n\t"
        "vpaddq %%ymm1, %%ymm0, %%ymm1\n\t"
        "vpaddq %%ymm6, %%ymm4, %%ymm6\n\t"
        "vpmuludq %%ymm10, %%ymm8, %%ymm10\n\t"
        "vmovdqu 100(%[Lc]), %%ymm8\n\t"
        "vpmuludq %%ymm13, %%ymm1, %%ymm4\n\t"
        "vbroadcastss 288(%[Lc]), %%ymm0\n\t"
        "vpsrlq $32, %%ymm9, %%ymm9\n\t"
        "vpblendd $170, %%ymm10, %%ymm9, %%ymm10\n\t"
        "vpaddd %%ymm11, %%ymm12, %%ymm9\n\t"
        "vbroadcastss 288(%[Lc]), %%ymm7\n\t"
        "vpmuludq %%ymm15, %%ymm4, %%ymm4\n\t"
        "vpmulld %%ymm15, %%ymm10, %%ymm10\n\t"
        "vpaddd %%ymm14, %%ymm12, %%ymm12\n\t"
        "vpmulld %%ymm2, %%ymm3, %%ymm2\n\t"
        "vpsubd %%ymm11, %%ymm12, %%ymm11\n\t"
        "vmovdqa 96(%[Lc]), %%ymm12\n\t"
        "vbroadcastss 292(%[Lc]), %%ymm3\n\t"
        "vpaddq %%ymm4, %%ymm1, %%ymm4\n\t"
        "vmovdqu 92(%[Lc]), %%ymm1\n\t"
        "vpsrlq $32, %%ymm4, %%ymm4\n\t"
        "vpblendd $170, %%ymm6, %%ymm4, %%ymm6\n\t"
        "vpsubd %%ymm10, %%ymm2, %%ymm10\n\t"
        "vbroadcastss 292(%[Lc]), %%ymm2\n\t"
        "vpaddd %%ymm14, %%ymm5, %%ymm4\n\t"
        "vpmuludq %%ymm0, %%ymm8, %%ymm0\n\t"
        "vpaddd %%ymm10, %%ymm5, %%ymm5\n\t"
        "vpsubd %%ymm10, %%ymm4, %%ymm10\n\t"
        "vbroadcastss 296(%[Lc]), %%ymm4\n\t"
        "vpsubd %%ymm14, %%ymm6, %%ymm8\n\t"
        "vpminud %%ymm8, %%ymm6, %%ymm8\n\t"
        "vmovdqu 88(%[Lc]), %%ymm6\n\t"
        "vpmuludq %%ymm7, %%ymm12, %%ymm7\n\t"
        "vpmuludq %%ymm3, %%ymm12, %%ymm3\n\t"
        "vbroadcastss 296(%[Lc]), %%ymm12\n\t"
        "vpmuludq %%ymm2, %%ymm1, %%ymm2\n\t"
        "vpmuludq %%ymm4, %%ymm1, %%ymm4\n\t"
        "vpaddq %%ymm3, %%ymm0, %%ymm3\n\t"
        "vpsubd %%ymm14, %%ymm9, %%ymm0\n\t"
        "vbroadcastss 300(%[Lc]), %%ymm1\n\t"
        "vpminud %%ymm0, %%ymm9, %%ymm0\n\t"
        "vpaddq %%ymm2, %%ymm7, %%ymm2\n\t"
        "vbroadcastss 16(%[lw]), %%ymm7\n\t"
        "vpsubd %%ymm15, %%ymm0, %%ymm9\n\t"
        "vpaddq %%ymm4, %%ymm3, %%ymm4\n\t"
        "vpminud %%ymm9, %%ymm0, %%ymm9\n\t"
        "vbroadcastss 300(%[Lc]), %%ymm0\n\t"
        "vmovdqu 84(%[Lc]), %%ymm3\n\t"
        "vmovdqa %%ymm9, 32(%[Ln])\n\t"
        "vpmuludq %%ymm12, %%ymm6, %%ymm12\n\t"
        "vpaddq %%ymm12, %%ymm2, %%ymm12\n\t"
        "vbroadcastss 304(%[Lc]), %%ymm2\n\t"
        "vpmuludq %%ymm1, %%ymm6, %%ymm1\n\t"
        "vbroadcastss 16(%[lw]), %%ymm6\n\t"
        "vpmuludq %%ymm7, %%ymm9, %%ymm7\n\t"
        "vpmuludq %%ymm0, %%ymm3, %%ymm0\n\t"
        "vpaddq %%ymm1, %%ymm4, %%ymm1\n\t"
        "vbroadcastss 304(%[Lc]), %%ymm4\n\t"
        "vpsrlq $32, %%ymm7, %%ymm7\n\t"
        "vpaddq %%ymm0, %%ymm12, %%ymm0\n\t"
        "vmovdqu 80(%[Lc]), %%ymm12\n\t"
        "vpmuludq %%ymm2, %%ymm3, %%ymm2\n\t"
        "vbroadcastss 308(%[Lc]), %%ymm3\n\t"
        "vpaddq %%ymm2, %%ymm1, %%ymm2\n\t"
        "vbroadcastss 0(%[lw]), %%ymm1\n\t"
        "vpmuludq %%ymm4, %%ymm12, %%ymm4\n\t"
        "vpmuludq %%ymm3, %%ymm12, %%ymm3\n\t"
        "vmovdqu 76(%[Lc]), %%ymm12\n\t"
        "vpaddq %%ymm4, %%ymm0, %%ymm4\n\t"
        "vbroadcastss 308(%[Lc]), %%ymm0\n\t"
        "vpaddq %%ymm3, %%ymm2, %%ymm3\n\t"
        "vpmulld %%ymm1, %%ymm9, %%ymm1\n\t"
        "vpsubd %%ymm14, %%ymm11, %%ymm2\n\t"
        "vpsrlq $32, %%ymm9, %%ymm9\n\t"
        "vpminud %%ymm2, %%ymm11, %%ymm2\n\t"
        "vpmuludq %%ymm6, %%ymm9, %%ymm6\n\t"
        "vbroadcastss 312(%[Lc]), %%ymm9\n\t"
        "vmovdqu 72(%[Lc]), %%ymm11\n\t"
        "vpblendd $170, %%ymm6, %%ymm7, %%ymm6\n\t"
        "vpsubd %%ymm15, %%ymm2, %%ymm7\n\t"
        "vpminud %%ymm7, %%ymm2, %%ymm7\n\t"
        "vpmulld %%ymm15, %%ymm6, %%ymm6\n\t"
        "vbroadcastss 312(%[Lc]), %%ymm2\n\t"
        "vpmuludq %%ymm0, %%ymm12, %%ymm0\n\t"
        "vmovdqa %%ymm7, 96(%[Ln])\n\t"
        "vpsubd %%ymm6, %%ymm1, %%ymm6\n\t"
        "vbroadcastss 316(%[Lc]), %%ymm1\n\t"
        "vpmuludq %%ymm9, %%ymm12, %%ymm9\n\t"
        "vpaddq %%ymm0, %%ymm4, %%ymm0\n\t"
        "vbroadcastss 20(%[lw]), %%ymm4\n\t"
        "vpsrlq $32, %%ymm7, %%ymm12\n\t"
        "vpaddq %%ymm9, %%ymm3, %%ymm9\n\t"
        "vbroadcastss 316(%[Lc]), %%ymm3\n\t"
        "vpmuludq %%ymm2, %%ymm11, %%ymm2\n\t"
        "vpmuludq %%ymm1, %%ymm11, %%ymm1\n\t"
        "vpaddq %%ymm2, %%ymm0, %%ymm2\n\t"
        "vmovdqu 68(%[Lc]), %%ymm0\n\t"
        "vpsubd %%ymm15, %%ymm6, %%ymm11\n\t"
        "vpmuludq %%ymm4, %%ymm7, %%ymm4\n\t"
        "vpminud %%ymm11, %%ymm6, %%ymm11\n\t"
        "vbroadcastss 20(%[lw]), %%ymm6\n\t"
        "vmovdqa %%ymm11, 0(%[Ln])\n\t"
        "vbroadcastss 4(%[lw]), %%ymm11\n\t"
        "vpaddq %%ymm1, %%ymm9, %%ymm1\n\t"
        "vpmuludq %%ymm13, %%ymm1, %%ymm9\n\t"
        "vpsrlq $32, %%ymm4, %%ymm4\n\t"
        "vpmuludq %%ymm15, %%ymm9, %%ymm9\n\t"
        "vpmuludq %%ymm3, %%ymm0, %%ymm3\n\t"
        "vpmuludq %%ymm6, %%ymm12, %%ymm6\n\t"
        "vpaddq %%ymm9, %%ymm1, %%ymm9\n\t"
        "vpmulld %%ymm11, %%ymm7, %%ymm11\n\t"
        "vpaddq %%ymm3, %%ymm2, %%ymm3\n\t"
        "vpmuludq %%ymm13, %%ymm3, %%ymm2\n\t"
        "vpblendd $170, %%ymm6, %%ymm4, %%ymm6\n\t"
        "vmovdqu 164(%[Lc]), %%ymm4\n\t"
        "vpmulld %%ymm15, %%ymm6, %%ymm6\n\t"
        "vbroadcastss 320(%[Lc]), %%ymm7\n\t"
        "vpmuludq %%ymm15, %%ymm2, %%ymm2\n\t"
        "vpsubd %%ymm14, %%ymm5, %%ymm1\n\t"
        "vbroadcastss 320(%[Lc]), %%ymm12\n\t"
        "vmovdqa 160(%[Lc]), %%ymm0\n\t"
        "vpminud %%ymm1, %%ymm5, %%ymm1\n\t"
        "vpsubd %%ymm6, %%ymm11, %%ymm6\n\t"
        "vbroadcastss 324(%[Lc]), %%ymm11\n\t"
        "vpaddq %%ymm2, %%ymm3, %%ymm2\n\t"
        "vpsubd %%ymm15, %%ymm1, %%ymm3\n\t"
        "vpsubd %%ymm15, %%ymm6, %%ymm5\n\t"
        "vpsrlq $32, %%ymm2, %%ymm2\n\t"
        "vpminud %%ymm3, %%ymm1, %%ymm3\n\t"
        "vpminud %%ymm5, %%ymm6, %%ymm5\n\t"
        "vbroadcastss 324(%[Lc]), %%ymm6\n\t"
        "vmovdqu 156(%[Lc]), %%ymm1\n\t"
        "vpblendd $170, %%ymm9, %%ymm2, %%ymm9\n\t"
        "vmovdqa %%ymm5, 64(%[Ln])\n\t"
        "vbroadcastss 24(%[lw]), %%ymm5\n\t"
        "vpsrlq $32, %%ymm3, %%ymm2\n\t"
        "vpmuludq %%ymm7, %%ymm4, %%ymm7\n\t"
        "vmovdqa %%ymm3, 160(%[Ln])\n\t"
        "vbroadcastss 328(%[Lc]), %%ymm4\n\t"
        "vpmuludq %%ymm12, %%ymm0, %%ymm12\n\t"
        "vpmuludq %%ymm11, %%ymm0, %%ymm11\n\t"
        "vmovdqu 152(%[Lc]), %%ymm0\n\t"
        "vpmuludq %%ymm6, %%ymm1, %%ymm6\n\t"
        "vpaddq %%ymm11, %%ymm7, %%ymm11\n\t"
        "vpmuludq %%ymm5, %%ymm3, %%ymm5\n\t"
        "vbroadcastss 328(%[Lc]), %%ymm7\n\t"
        "vpmuludq %%ymm4, %%ymm1, %%ymm4\n\t"
        "vbroadcastss 332(%[Lc]), %%ymm1\n\t"
        "vpaddq %%ymm6, %%ymm12, %%ymm6\n\t"
        "vpsubd %%ymm14, %%ymm9, %%ymm12\n\t"
        "vpminud %%ymm12, %%ymm9, %%ymm12\n\t"
        "vpsrlq $32, %%ymm5, %%ymm5\n\t"
        "vbroadcastss 24(%[lw]), %%ymm9\n\t"
        "vpaddq %%ymm4, %%ymm11, %%ymm4\n\t"
        "vbroadcastss 332(%[Lc]), %%ymm11\n\t"
        "vpmuludq %%ymm7, %%ymm0, %%ymm7\n\t"
        "vpmuludq %%ymm1, %%ymm0, %%ymm1\n\t"
        "vmovdqu 148(%[Lc]), %%ymm0\n\t"
        "vpaddq %%ymm7, %%ymm6, %%ymm7\n\t"
        "vpmuludq %%ymm9, %%ymm2, %%ymm9\n\t"
        "vbroadcastss 336(%[Lc]), %%ymm2\n\t"
        "vbroadcastss 8(%[lw]), %%ymm6\n\t"
        "vpaddq %%ymm1, %%ymm4, %%ymm1\n\t"
        "vmovdqu 144(%[Lc]), %%ymm4\n\t"
        "vpblendd $170, %%ymm9, %%ymm5, %%ymm9\n\t"
        "vpsubd %%ymm14, %%ymm10, %%ymm5\n\t"
        "vpmulld %%ymm15, %%ymm9, %%ymm9\n\t"
        "vpminud %%ymm5, %%ymm10, %%ymm5\n\t"
        "vbroadcastss 336(%[Lc]), %%ymm10\n\t"
        "vpmuludq %%ymm11, %%ymm0, %%ymm11\n\t"
        "vpmuludq %%ymm2, %%ymm0, %%ymm2\n\t"
        "vpmulld %%ymm6, %%ymm3, %%ymm6\n\t"
        "vbroadcastss 340(%[Lc]), %%ymm3\n\t"
        "vpsubd %%ymm15, %%ymm5, %%ymm0\n\t"
        "vpaddq %%ymm11, %%ymm7, %%ymm11\n\t"
        "vpminud %%ymm0, %%ymm5, %%ymm0\n\t"
        "vbroadcastss 340(%[Lc]), %%ymm5\n\t"
        "vmovdqu 140(%[Lc]), %%ymm7\n\t"
        "vpaddq %%ymm2, %%ymm1, %%ymm2\n\t"
        "vpsubd %%ymm9, %%ymm6, %%ymm9\n\t"
        "vmovdqa %%ymm0, 224(%[Ln])\n\t"
        "vpsrlq $32, %%ymm0, %%ymm6\n\t"
        "vbroadcastss 344(%[Lc]), %%ymm1\n\t"
        "vpmuludq %%ymm10, %%ymm4, %%ymm10\n\t"
        "vpmuludq %%ymm3, %%ymm4, %%ymm3\n\t"
        "vpaddq %%ymm10, %%ymm11, %%ymm10\n\t"
        "vbroadcastss 28(%[lw]), %%ymm11\n\t"
        "vbroadcastss 28(%[lw]), %%ymm4\n\t"
        "vpmuludq %%ymm5, %%ymm7, %%ymm5\n\t"
        "vpaddq %%ymm3, %%ymm2, %%ymm3\n\t"
        "vbroadcastss 344(%[Lc]), %%ymm2\n\t"
        "vpmuludq %%ymm1, %%ymm7, %%ymm1\n\t"
        "vmovdqu 136(%[Lc]), %%ymm7\n\t"
        "vpaddq %%ymm5, %%ymm10, %%ymm5\n\t"
        "vbroadcastss 348(%[Lc]), %%ymm10\n\t"
        "vpaddq %%ymm1, %%ymm3, %%ymm1\n\t"
        "vbroadcastss 12(%[lw]), %%ymm3\n\t"
        "vpmuludq %%ymm4, %%ymm6, %%ymm4\n\t"
        "vpmuludq %%ymm11, %%ymm0, %%ymm11\n\t"
        "vpsubd %%ymm15, %%ymm9, %%ymm6\n\t"
        "vpminud %%ymm6, %%ymm9, %%ymm6\n\t"
        "vbroadcastss 348(%[Lc]), %%ymm9\n\t"
        "vmovdqa %%ymm6, 128(%[Ln])\n\t"
        "vmovdqu 132(%[Lc]), %%ymm6\n\t"
        "vpsrlq $32, %%ymm11, %%ymm11\n\t"
        "vpmuludq %%ymm2, %%ymm7, %%ymm2\n\t"
        "vpblendd $170, %%ymm4, %%ymm11, %%ymm4\n\t"
        "vpmuludq %%ymm10, %%ymm7, %%ymm10\n\t"
        "vpmulld %%ymm15, %%ymm4, %%ymm4\n\t"
        "vpaddq %%ymm2, %%ymm5, %%ymm2\n\t"
        "vpmulld %%ymm3, %%ymm0, %%ymm3\n\t"
        "vpaddq %%ymm10, %%ymm1, %%ymm10\n\t"
        "vmovdqa 0(%[bn]), %%ymm1\n\t"
        "vpmuludq %%ymm13, %%ymm10, %%ymm0\n\t"
        "vpmuludq %%ymm9, %%ymm6, %%ymm9\n\t"
        "vpsubd %%ymm4, %%ymm3, %%ymm4\n\t"
        "vpsubd %%ymm15, %%ymm4, %%ymm3\n\t"
        "vpmuludq %%ymm15, %%ymm0, %%ymm0\n\t"
        "vpminud %%ymm3, %%ymm4, %%ymm3\n\t"
        "vpaddq %%ymm9, %%ymm2, %%ymm9\n\t"
        "vmovdqa 32(%[bn]), %%ymm2\n\t"
        "vmovdqa %%ymm3, 192(%[Ln])\n\t"
        "vmovdqu 228(%[Lc]), %%ymm3\n\t"
        "vpmuludq %%ymm13, %%ymm9, %%ymm4\n\t"
        "vbroadcastss 352(%[Lc]), %%ymm6\n\t"
        "vpaddq %%ymm0, %%ymm10, %%ymm0\n\t"
        "vbroadcastss 32(%[px]), %%ymm10\n\t"
        "vpsubd %%ymm14, %%ymm1, %%ymm5\n\t"
        "vmovdqa 224(%[Lc]), %%ymm7\n\t"
        "vpmuludq %%ymm15, %%ymm4, %%ymm4\n\t"
        "vpminud %%ymm5, %%ymm1, %%ymm5\n\t"
        "vbroadcastss 352(%[Lc]), %%ymm1\n\t"
        "vbroadcastss 32(%[px]), %%ymm11\n\t"
        "vpaddq %%ymm4, %%ymm9, %%ymm4\n\t"
        "vbroadcastss 356(%[Lc]), %%ymm9\n\t"
        "vpsrlq $32, %%ymm4, %%ymm4\n\t"
        "vpblendd $170, %%ymm0, %%ymm4, %%ymm0\n\t"
        "vpsubd %%ymm14, %%ymm2, %%ymm4\n\t"
        "vpmuludq %%ymm6, %%ymm3, %%ymm6\n\t"
        "vpminud %%ymm4, %%ymm2, %%ymm4\n\t"
        "vbroadcastss 356(%[Lc]), %%ymm2\n\t"
        "vmovdqu 220(%[Lc]), %%ymm3\n\t"
        "vpmuludq 64(%[bn]), %%ymm10, %%ymm10\n\t"
        "vpmuludq %%ymm1, %%ymm7, %%ymm1\n\t"
        "vpmuludq 68(%[bn]), %%ymm11, %%ymm11\n\t"
        "vpsrlq $32, %%ymm10, %%ymm10\n\t"
        "vpmuludq %%ymm9, %%ymm7, %%ymm9\n\t"
        "vbroadcastss 360(%[Lc]), %%ymm7\n\t"
        "vpblendd $170, %%ymm11, %%ymm10, %%ymm11\n\t"
        "vmovdqu 216(%[Lc]), %%ymm10\n\t"
        "vpmulld %%ymm15, %%ymm11, %%ymm11\n\t"
        "vpmuludq %%ymm2, %%ymm3, %%ymm2\n\t"
        "vpaddq %%ymm9, %%ymm6, %%ymm9\n\t"
        "vbroadcastss 360(%[Lc]), %%ymm6\n\t"
        "vpaddq %%ymm2, %%ymm1, %%ymm2\n\t"
        "vbroadcastss 32(%[px]), %%ymm1\n\t"
        "vpmuludq %%ymm7, %%ymm3, %%ymm7\n\t"
        "vbroadcastss 364(%[Lc]), %%ymm3\n\t"
        "vpmuludq %%ymm6, %%ymm10, %%ymm6\n\t"
        "vpaddq %%ymm7, %%ymm9, %%ymm7\n\t"
        "vbroadcastss 32(%[px]), %%ymm9\n\t"
        "vpaddq %%ymm6, %%ymm2, %%ymm6\n\t"
        "vpmuludq 96(%[bn]), %%ymm1, %%ymm1\n\t"
        "vmovdqu 212(%[Lc]), %%ymm2\n\t"
        "vpmuludq %%ymm3, %%ymm10, %%ymm3\n\t"
        "vbroadcastss 364(%[Lc]), %%ymm10\n\t"
        "vpsrlq $32, %%ymm1, %%ymm1\n\t"
        "vpaddq %%ymm3, %%ymm7, %%ymm3\n\t"
        "vpmuludq 100(%[bn]), %%ymm9, %%ymm9\n\t"
        "vbroadcastss 368(%[Lc]), %%ymm7\n\t"
        "vpblendd $170, %%ymm9, %%ymm1, %%ymm9\n\t"
        "vbroadcastss 0(%[px]), %%ymm1\n\t"
        "vpmulld %%ymm15, %%ymm9, %%ymm9\n\t"
        "vpmuludq %%ymm10, %%ymm2, %%ymm10\n\t"
        "vpaddq %%ymm10, %%ymm6, %%ymm10\n\t"
        "vpmuludq %%ymm7, %%ymm2, %%ymm7\n\t"
        "vbroadcastss 368(%[Lc]), %%ymm2\n\t"
        "vmovdqu 208(%[Lc]), %%ymm6\n\t"
        "vpaddq %%ymm7, %%ymm3, %%ymm7\n\t"
        "vpmulld 96(%[bn]), %%ymm1, %%ymm1\n\t"
        "vpsubd %%ymm14, %%ymm0, %%ymm3\n\t"
        "vpminud %%ymm3, %%ymm0, %%ymm3\n\t"
        "vbroadcastss 372(%[Lc]), %%ymm0\n\t"
        "vpsubd %%ymm9, %%ymm1, %%ymm9\n\t"
        "vbroadcastss 0(%[px]), %%ymm1\n\t"
        "vpmuludq %%ymm2, %%ymm6, %%ymm2\n\t"
        "vpaddq %%ymm2, %%ymm10, %%ymm2\n\t"
        "vmovdqu 204(%[Lc]), %%ymm10\n\t"
        "vpmuludq %%ymm0, %%ymm6, %%ymm0\n\t"
        "vbroadcastss 372(%[Lc]), %%ymm6\n\t"
        "vpmulld 64(%[bn]), %%ymm1, %%ymm1\n\t"
        "vpaddq %%ymm0, %%ymm7, %%ymm0\n\t"
        "vbroadcastss 376(%[Lc]), %%ymm7\n\t"
        "vpsubd %%ymm11, %%ymm1, %%ymm11\n\t"
        "vpaddd %%ymm14, %%ymm4, %%ymm1\n\t"
        "vpaddd %%ymm9, %%ymm4, %%ymm4\n\t"
        "vpsubd %%ymm9, %%ymm1, %%ymm9\n\t"
        "vmovdqu 200(%[Lc]), %%ymm1\n\t"
        "vpmuludq %%ymm6, %%ymm10, %%ymm6\n\t"
        "vpmuludq %%ymm7, %%ymm10, %%ymm7\n\t"
        "vpaddq %%ymm6, %%ymm2, %%ymm6\n\t"
        "vbroadcastss 376(%[Lc]), %%ymm2\n\t"
        "vpsrlq $32, %%ymm4, %%ymm10\n\t"
        "vpaddq %%ymm7, %%ymm0, %%ymm7\n\t"
        "vbroadcastss 380(%[Lc]), %%ymm0\n\t"
        "vpmuludq %%ymm2, %%ymm1, %%ymm2\n\t"
        "vpmuludq %%ymm0, %%ymm1, %%ymm0\n\t"
        "vpaddq %%ymm2, %%ymm6, %%ymm2\n\t"
        "vbroadcastss 32(%[py]), %%ymm6\n\t"
        "vbroadcastss 32(%[py]), %%ymm1\n\t"
        "vpaddq %%ymm0, %%ymm7, %%ymm0\n\t"
        "vmovdqu 196(%[Lc]), %%ymm7\n\t"
        "vpmuludq %%ymm1, %%ymm10, %%ymm1\n\t"
        "vpmuludq %%ymm6, %%ymm4, %%ymm6\n\t"
        "vbroadcastss 380(%[Lc]), %%ymm10\n\t"
        "vpsrlq $32, %%ymm6, %%ymm6\n\t"
        "vpblendd $170, %%ymm1, %%ymm6, %%ymm1\n\t"
        "vbroadcastss 0(%[py]), %%ymm6\n\t"
        "vpmuludq %%ymm10, %%ymm7, %%ymm10\n\t"
        "vpsubd %%ymm11, %%ymm5, %%ymm7\n\t"
        "vpaddd %%ymm11, %%ymm5, %%ymm11\n\t"
        "vpmuludq %%ymm13, %%ymm0, %%ymm5\n\t"
        "vpmulld %%ymm15, %%ymm1, %%ymm1\n\t"
        "vpaddq %%ymm10, %%ymm2, %%ymm10\n\t"
        "vpaddd %%ymm14, %%ymm7, %%ymm2\n\t"
        "vpmuludq %%ymm15, %%ymm5, %%ymm5\n\t"
        "vpmulld %%ymm6, %%ymm4, %%ymm6\n\t"
        "vpminud %%ymm2, %%ymm7, %%ymm2\n\t"
        "vpsrlq $32, %%ymm9, %%ymm7\n\t"
        "vpmuludq %%ymm13, %%ymm10, %%ymm4\n\t"
        "vpaddq %%ymm5, %%ymm0, %%ymm5\n\t"
        "vpsubd %%ymm1, %%ymm6, %%ymm1\n\t"
        "vbroadcastss 36(%[py]), %%ymm6\n\t"
        "vpsubd %%ymm14, %%ymm11, %%ymm0\n\t"
        "vpmuludq %%ymm15, %%ymm4, %%ymm4\n\t"
        "vpminud %%ymm0, %%ymm11, %%ymm0\n\t"
        "vbroadcastss 36(%[py]), %%ymm11\n\t"
        "vpaddq %%ymm4, %%ymm10, %%ymm4\n\t"
        "vpaddd %%ymm12, %%ymm8, %%ymm10\n\t"
        "vpsrlq $32, %%ymm4, %%ymm4\n\t"
        "vpblendd $170, %%ymm5, %%ymm4, %%ymm5\n\t"
        "vpsubd %%ymm14, %%ymm10, %%ymm4\n\t"
        "vpaddd %%ymm14, %%ymm8, %%ymm8\n\t"
        "vpminud %%ymm4, %%ymm10, %%ymm4\n\t"
        "vpsubd %%ymm14, %%ymm5, %%ymm10\n\t"
        "vpminud %%ymm10, %%ymm5, %%ymm10\n\t"
        "vpsubd %%ymm12, %%ymm8, %%ymm12\n\t"
        "vpmuludq %%ymm6, %%ymm9, %%ymm6\n\t"
        "vbroadcastss 4(%[py]), %%ymm8\n\t"
        "vbroadcastss 32(%[ipy]), %%ymm5\n\t"
        "vpmuludq %%ymm11, %%ymm7, %%ymm11\n\t"
        "vbroadcastss 32(%[ipy]), %%ymm7\n\t"
        "vpsrlq $32, %%ymm6, %%ymm6\n\t"
        "vpblendd $170, %%ymm11, %%ymm6, %%ymm11\n\t"
        "vpsrlq $32, %%ymm12, %%ymm6\n\t"
        "vpmulld %%ymm15, %%ymm11, %%ymm11\n\t"
        "vpmulld %%ymm8, %%ymm9, %%ymm8\n\t"
        "vbroadcastss 0(%[ipy]), %%ymm9\n\t"
        "vpmuludq %%ymm5, %%ymm12, %%ymm5\n\t"
        "vpmuludq %%ymm7, %%ymm6, %%ymm7\n\t"
        "vpaddd %%ymm10, %%ymm3, %%ymm6\n\t"
        "vpsubd %%ymm11, %%ymm8, %%ymm11\n\t"
        "vpsubd %%ymm14, %%ymm6, %%ymm8\n\t"
        "vpaddd %%ymm14, %%ymm3, %%ymm3\n\t"
        "vpsrlq $32, %%ymm5, %%ymm5\n\t"
        "vpminud %%ymm8, %%ymm6, %%ymm8\n\t"
        "vpaddd %%ymm14, %%ymm2, %%ymm6\n\t"
        "vpsubd %%ymm10, %%ymm3, %%ymm10\n\t"
        "vpblendd $170, %%ymm7, %%ymm5, %%ymm7\n\t"
        "vpsubd %%ymm11, %%ymm6, %%ymm6\n\t"
        "vpaddd %%ymm11, %%ymm2, %%ymm11\n\t"
        "vbroadcastss 36(%[ipy]), %%ymm2\n\t"
        "vbroadcastss 36(%[ipy]), %%ymm5\n\t"
        "vpsrlq $32, %%ymm10, %%ymm3\n\t"
        "vpmulld %%ymm15, %%ymm7, %%ymm7\n\t"
        "vpmulld %%ymm9, %%ymm12, %%ymm9\n\t"
        "vpaddd %%ymm14, %%ymm0, %%ymm12\n\t"
        "vpaddd %%ymm1, %%ymm0, %%ymm0\n\t"
        "vpsubd %%ymm1, %%ymm12, %%ymm1\n\t"
        "vbroadcastss 4(%[ipy]), %%ymm12\n\t"
        "vpsubd %%ymm7, %%ymm9, %%ymm7\n\t"
        "vpsubd %%ymm14, %%ymm1, %%ymm9\n\t"
        "vpminud %%ymm9, %%ymm1, %%ymm9\n\t"
        "vpsubd %%ymm14, %%ymm0, %%ymm1\n\t"
        "vpmuludq %%ymm2, %%ymm10, %%ymm2\n\t"
        "vpminud %%ymm1, %%ymm0, %%ymm1\n\t"
        "vpaddd %%ymm8, %%ymm4, %%ymm0\n\t"
        "vpmuludq %%ymm5, %%ymm3, %%ymm5\n\t"
        "vpsubd %%ymm15, %%ymm1, %%ymm3\n\t"
        "vpminud %%ymm3, %%ymm1, %%ymm3\n\t"
        "vpsubd %%ymm15, %%ymm9, %%ymm1\n\t"
        "vpsrlq $32, %%ymm2, %%ymm2\n\t"
        "vmovdqa %%ymm3, 256(%[Ln])\n\t"
        "vpminud %%ymm1, %%ymm9, %%ymm1\n\t"
        "vpsubd %%ymm14, %%ymm0, %%ymm9\n\t"
        "vpblendd $170, %%ymm5, %%ymm2, %%ymm5\n\t"
        "vpmulld %%ymm12, %%ymm10, %%ymm12\n\t"
        "vpsubd %%ymm14, %%ymm11, %%ymm10\n\t"
        "vmovdqa %%ymm1, 288(%[Ln])\n\t"
        "vpminud %%ymm9, %%ymm0, %%ymm9\n\t"
        "vpmulld %%ymm15, %%ymm5, %%ymm5\n\t"
        "vpaddd %%ymm14, %%ymm4, %%ymm4\n\t"
        "vpminud %%ymm10, %%ymm11, %%ymm10\n\t"
        "vmovdqa %%ymm9, 0(%[ac])\n\t"
        "vbroadcastss 32(%[ipx]), %%ymm9\n\t"
        "vpsubd %%ymm8, %%ymm4, %%ymm8\n\t"
        "vpsubd %%ymm15, %%ymm10, %%ymm4\n\t"
        "vbroadcastss 32(%[ipx]), %%ymm11\n\t"
        "vpsrlq $32, %%ymm8, %%ymm0\n\t"
        "vpsubd %%ymm14, %%ymm6, %%ymm1\n\t"
        "vpminud %%ymm4, %%ymm10, %%ymm4\n\t"
        "vpsubd %%ymm5, %%ymm12, %%ymm5\n\t"
        "vpminud %%ymm1, %%ymm6, %%ymm1\n\t"
        "vmovdqa %%ymm4, 320(%[Ln])\n\t"
        "vbroadcastss 0(%[ipx]), %%ymm4\n\t"
        "vpaddd %%ymm5, %%ymm7, %%ymm6\n\t"
        "vpsubd %%ymm15, %%ymm1, %%ymm12\n\t"
        "vpsubd %%ymm14, %%ymm6, %%ymm10\n\t"
        "vpminud %%ymm12, %%ymm1, %%ymm12\n\t"
        "vpaddd %%ymm14, %%ymm7, %%ymm7\n\t"
        "vpminud %%ymm10, %%ymm6, %%ymm10\n\t"
        "vmovdqa %%ymm12, 352(%[Ln])\n\t"
        "vbroadcastss 32(%[ipx]), %%ymm12\n\t"
        "vpsubd %%ymm5, %%ymm7, %%ymm5\n\t"
        "vmovdqa %%ymm10, 32(%[ac])\n\t"
        "vbroadcastss 32(%[ipx]), %%ymm10\n\t"
        "vpsrlq $32, %%ymm5, %%ymm7\n\t"
        "vpmuludq %%ymm9, %%ymm8, %%ymm9\n\t"
        "vbroadcastss 0(%[ipx]), %%ymm6\n\t"
        "vpmuludq %%ymm11, %%ymm0, %%ymm11\n\t"
        "vpsrlq $32, %%ymm9, %%ymm9\n\t"
        "vpmulld %%ymm4, %%ymm8, %%ymm4\n\t"
        "vpblendd $170, %%ymm11, %%ymm9, %%ymm11\n\t"
        "vpmulld %%ymm15, %%ymm11, %%ymm11\n\t"
        "vpmuludq %%ymm12, %%ymm5, %%ymm12\n\t"
        "vpmuludq %%ymm10, %%ymm7, %%ymm10\n\t"
        "vpsubd %%ymm11, %%ymm4, %%ymm11\n\t"
        "vpsrlq $32, %%ymm12, %%ymm12\n\t"
        "vpmulld %%ymm6, %%ymm5, %%ymm6\n\t"
        "vmovdqa %%ymm11, 64(%[ac])\n\t"
        "vpblendd $170, %%ymm10, %%ymm12, %%ymm10\n\t"
        "vpmulld %%ymm15, %%ymm10, %%ymm10\n\t"
        "vpsubd %%ymm10, %%ymm6, %%ymm10\n\t"
        "vmovdqa %%ymm10, 96(%[ac])\n\t"
        :
        : [an] "r"(an), [bn] "r"(bn), [Ln] "r"(Ln), [px] "r"(px), [py] "r"(py), [lw] "r"(lw), [ac] "r"(ac), [Lc] "r"(Lc), [ipx] "r"(ipx), [ipy] "r"(ipy),
          [cP] "m"(asm_const_P), [cP2] "m"(asm_const_P2), [cNI] "m"(asm_const_NI)
        : "xmm0", "xmm1", "xmm2", "xmm3", "xmm4", "xmm5", "xmm6", "xmm7", "xmm8", "xmm9",
          "xmm10", "xmm11", "xmm12", "xmm13", "xmm14", "xmm15", "memory");
}

};
}
