// Generated by tools/bundle.py from problems/convolution/min_plus_convolution_concave_arbitrary/solution.cpp. Edit that file instead.
// c_k = min over i + j = k of a_i + b_j, with a concave (N, M <= 2^19, values <= 10^9, so
// c_k < 2^31). Column j is the curve f_j(x) = a_{x-j} + b_j on [j, j + N). For j < j', f_j' - f_j
// is non-decreasing on their common domain (a's slopes fall): f_j' wins a prefix of it.
//
// Columns go in blocks [j0, j1) of at most N. Rows [j0, j0 + N) see no column end; a forward
// sweep adds column x at row x, and the newest column wins a prefix of the rows left, so the
// envelope is a stack, newest on top, each column owning the rows from where the one above it
// stops to where it starts losing to the one below. Rows [j1 - 1, j1 + N - 1) see no column start;
// a backward sweep is the mirror image. The two sweeps cover the block's rows.
//
// Each entry keeps its exact crossing with the entry below. A new column's crossing with the entry
// it lands on is bracketed first: from below by the crossing of the entry it popped last (close
// for far columns), from both sides by a rank among a's slopes (narrow for near columns); then
// bisection down to 8 rows and one 8-row vector compare.
#include <immintrin.h>

#include <algorithm>
#include <bit>
#include <cstddef>
#include <cstdint>

// lib/io/bulk32.hpp
// Bulk read of uint32 arrays with AVX2, on top of io::Reader:
//
//   io::Reader in;
//   io::read_bulk(in, a.data(), n);  // same values as in.read(a.data(), n); faster on Zen 3
//
// On Zen 3 (the judge's CPU) it uses BulkParser32 below; elsewhere it is Reader::read, which is
// faster there. -DIO_BULK32_TRANSPOSE=0 or 1 forces either. Kept apart from io.hpp so that the
// code of the programs that do not need it stays unchanged. Design and measurements:
// lib/io/notes.md.

// lib/io/io.hpp
// Fast integer and text I/O on file descriptors (stdin and stdout by default).
// Linux, x86-64 with AVX2. Design and measurements: lib/io/notes.md.
//
//   io::Reader in;                            // takes all of stdin
//   io::Writer out;                           // flushes in its destructor
//   const auto n = in.read<std::uint32_t>();
//   std::vector<std::uint32_t> a(n);
//   in.read(a.data(), n);                     // bulk; AVX2 for uint32_t
//   const auto s = in.read<std::uint64_t, 16>();  // promise: at most 16 digits (faster)
//   out.write("n = ", n, '\n');               // any mix of integers, chars, strings
//   out.write<16>(s, '\n');                   // promise: integers of at most 16 digits
//   out.write_array(a.data(), n, ' ');        // bulk; AVX2 for uint32_t
//   out.write('\n');
//
// Input: tokens separated by whitespace (any bytes <= ' '). Integer tokens are an optional '-'
// (signed types only) followed by decimal digits, and fit the requested type. Reading past the
// last token is undefined. The 64 bytes before the input and after its end are readable zeros, so
// custom parsers may load up to 64 bytes around any token from word().

#include <fcntl.h>
#include <immintrin.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>

#include <algorithm>
#include <array>
#include <bit>
#include <cerrno>
#include <concepts>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <string_view>
#include <type_traits>

namespace io {
namespace detail {

// Zero bytes before and after the input. Loads reach at most 63 bytes past either end.
inline constexpr std::size_t kPadding = 64;
inline constexpr std::size_t kPage = 4096;

// Input as mapped or read: data [start, end), kPadding zero bytes before and after it.
struct Input {
    char* base;           // allocation or mapping to release
    std::size_t mapped;   // bytes mapped, or 0 for a heap buffer
    const char* start;
    const char* end;
};

inline Input map_input(int fd, std::size_t size) {
    const off_t offset = ::lseek(fd, 0, SEEK_CUR);
    if (offset < 0 || std::size_t(offset) >= size) return {};
    // One anonymous zero page before the file. After it, the rest of the last file page reads as
    // zero; if fewer than kPadding bytes remain, one more anonymous page follows.
    const std::size_t file_bytes = (size + kPage - 1) & ~(kPage - 1);
    const std::size_t mapped = kPage + file_bytes + (file_bytes - size < kPadding ? kPage : 0);
    void* base = ::mmap(nullptr, mapped, PROT_READ, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    if (base == MAP_FAILED) return {};
    char* const file = static_cast<char*>(base) + kPage;
    if (::mmap(file, file_bytes, PROT_READ, MAP_PRIVATE | MAP_FIXED, fd, 0) == MAP_FAILED) {
        ::munmap(base, mapped);
        return {};
    }
    return {static_cast<char*>(base), mapped, file + offset, file + size};
}

// Capacity bytes for data, with kPadding bytes before and after; returns the data start.
inline char* allocate(std::size_t capacity) {
    auto* p = static_cast<char*>(std::aligned_alloc(64, capacity + 2 * kPadding));
    if (!p) std::abort();
    std::memset(p, 0, kPadding);
    return p + kPadding;
}

// Reads fd until end of file, or until size bytes for a regular file of that size.
inline Input read_input(int fd, std::size_t size = std::size_t(-1)) {
    std::size_t done = 0, capacity = std::size_t(1) << 16;
    char* data = allocate(capacity);
    while (done < size) {
        if (done == capacity) {
            char* bigger = allocate(capacity *= 2);
            std::memcpy(bigger, data, done);
            std::free(data - kPadding);
            data = bigger;
        }
        const ssize_t got = ::read(fd, data + done, capacity - done);
        if (got > 0) done += std::size_t(got);
        else if (got == 0) break;
        else if (errno != EINTR) std::abort();
    }
    std::memset(data + done, 0, kPadding);
    return {data - kPadding, 0, data, data + done};
}

// Files over kMapAbove bytes are mapped; smaller ones and other inputs are read, which takes
// fewer system calls.
inline constexpr std::size_t kMapAbove = std::size_t(1) << 16;

inline Input open_input(int fd) {
    struct stat st;
    if (::fstat(fd, &st) == 0 && S_ISREG(st.st_mode)) {
        const auto size = std::size_t(st.st_size);
        if (size <= kMapAbove) return read_input(fd, size);
        if (const Input input = map_input(fd, size); input.base) return input;
    }
    return read_input(fd);
}

inline void release(const Input& input) {
    if (input.mapped) ::munmap(input.base, input.mapped);
    else std::free(input.base);
}

// Bit i set iff byte i is whitespace (<= ' ').
inline unsigned separators(__m128i bytes) {
    return unsigned(_mm_movemask_epi8(_mm_cmpgt_epi8(_mm_set1_epi8(' ' + 1), bytes)));
}

inline std::uint32_t separators(__m256i bytes) {
    return std::uint32_t(_mm256_movemask_epi8(_mm256_cmpgt_epi8(_mm256_set1_epi8(' ' + 1), bytes)));
}

// Separators in the 64-byte aligned block.
inline std::uint64_t block_separators(const char* block) {
    const std::uint64_t low = separators(_mm256_load_si256(reinterpret_cast<const __m256i*>(block)));
    const std::uint64_t high = separators(_mm256_load_si256(reinterpret_cast<const __m256i*>(block + 32)));
    return low | high << 32;
}

// The 16 bytes at kRightAlign[n + 1] move the first n bytes (1 <= n <= 16) of a 16-byte window
// to its end and zero the rest: byte k + 1 is k - 16 for 16 <= k < 32, else -128. For the other
// lengths (-1, 0, 17..32) byte 15 of the window is negative, which marks the token as invalid.
alignas(64) inline constexpr auto kRightAlign = [] {
    std::array<std::int8_t, 64> t{};
    for (int k = -1; k < 63; ++k) t[k + 1] = k >= 16 && k < 32 ? std::int8_t(k - 16) : std::int8_t(-128);
    return t;
}();

// Shuffle control for a token of length index - 1.
inline __m128i align_row(std::size_t index) {
    return _mm_loadu_si128(reinterpret_cast<const __m128i*>(kRightAlign.data() + index));
}

// Right-aligned digits (byte values 0..9) -> 4-digit groups, one per dword.
inline __m128i digit_groups(__m128i digits) {
    return _mm_madd_epi16(_mm_maddubs_epi16(digits, _mm_set1_epi16(0x010A)), _mm_set1_epi32(0x00010064));
}

inline __m256i digit_groups(__m256i digits) {
    return _mm256_madd_epi16(_mm256_maddubs_epi16(digits, _mm256_set1_epi16(0x010A)), _mm256_set1_epi32(0x00010064));
}

// Value of the first n digits (0 <= n <= 16) of the window. Result < 10^16.
inline std::uint64_t parse16(__m128i window, unsigned n) {
    const __m128i digits = _mm_shuffle_epi8(_mm_subs_epu8(window, _mm_set1_epi8('0')), align_row(n + 1));
    const __m128i groups = digit_groups(digits);
    const __m128i halves = _mm_madd_epi16(_mm_packus_epi32(groups, groups), _mm_set1_epi32(0x00012710));
    const auto both = std::uint64_t(_mm_cvtsi128_si64(halves));  // 8-digit halves, high one first
    return (both & 0xFFFFFFFF) * 100000000 + (both >> 32);
}

// kKeep[32 - k..64 - k) keeps the last k bytes of 32.
alignas(64) inline constexpr auto kKeep = [] {
    std::array<std::uint8_t, 64> t{};
    for (std::size_t i = 32; i < 64; ++i) t[i] = 0xFF;
    return t;
}();

// Value of the n <= 16 digits that end at end. Bytes below '0' before them (a sign) count as 0.
inline std::uint64_t parse_ending16(const char* end, unsigned n) {
    const __m128i bytes = _mm_loadu_si128(reinterpret_cast<const __m128i*>(end - 16));
    const __m128i keep = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kKeep.data() + 16 + n));
    const __m128i groups = digit_groups(_mm_and_si128(_mm_subs_epu8(bytes, _mm_set1_epi8('0')), keep));
    const __m128i halves = _mm_madd_epi16(_mm_packus_epi32(groups, groups), _mm_set1_epi32(0x00012710));
    const auto both = std::uint64_t(_mm_cvtsi128_si64(halves));  // 8-digit halves, high one first
    return (both & 0xFFFFFFFF) * 100000000 + (both >> 32);
}

// Value of the n <= 24 digits that end at end; at most 20 for a result below 2^64.
inline std::uint64_t parse_ending24(const char* end, unsigned n) {
    const __m256i bytes = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(end - 32));
    const __m256i keep = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(kKeep.data() + n));
    const __m256i groups = digit_groups(_mm256_and_si256(_mm256_subs_epu8(bytes, _mm256_set1_epi8('0')), keep));
    // 8-digit quarters; the first is 0. Dword 1 of the low lane, dwords 0 and 1 of the high lane.
    const __m256i quarters = _mm256_madd_epi16(_mm256_packus_epi32(groups, groups), _mm256_set1_epi32(0x00012710));
    const std::uint64_t high = std::uint64_t(_mm256_extract_epi64(quarters, 0)) >> 32;
    const auto low = std::uint64_t(_mm256_extract_epi64(quarters, 2));
    return (high * 100000000 + (low & 0xFFFFFFFF)) * 100000000 + (low >> 32);
}

// kQuad[x] for x < 10^4: its 4 digits with leading zeros, first digit in the lowest byte.
alignas(64) inline constexpr auto kQuad = [] {
    std::array<std::uint32_t, 10000> t{};
    for (std::uint32_t x = 0; x < t.size(); ++x)
        t[x] = ('0' + x / 1000) | ('0' + x / 100 % 10) << 8 | ('0' + x / 10 % 10) << 16 | ('0' + x % 10) << 24;
    return t;
}();

// Digits of x (x >= 1) = (x + kDigitCount32[floor(log2(x))]) >> 32: the low word of an entry
// carries into the high word exactly when x reaches the next power of ten.
inline constexpr auto kDigitCount32 = [] {
    std::array<std::uint64_t, 32> t{};
    for (int i = 0; i < 32; ++i) {
        const std::uint64_t low = std::uint64_t(1) << i, high = 2 * low - 1;
        std::uint64_t digits = 0, power = 1;
        while (power <= low) power *= 10, ++digits;
        t[i] = (digits << 32) + (power <= high ? (std::uint64_t(1) << 32) - power : 0);
    }
    return t;
}();

inline unsigned digit_count(std::uint32_t x) {
    return unsigned((x + kDigitCount32[31 - std::countl_zero(x | 1)]) >> 32);
}

// Digits of x = kDigitCount64[0][b] + (x > kDigitCount64[1][b]), where b = bit width of x | 1.
inline constexpr auto kDigitCount64 = [] {
    std::array<std::array<std::uint64_t, 65>, 2> t{};
    for (int b = 1; b <= 64; ++b) {
        const unsigned __int128 low = (unsigned __int128)1 << (b - 1), high = 2 * low - 1;
        std::uint64_t digits = 1;
        unsigned __int128 power = 10;
        while (power <= low) power *= 10, ++digits;
        t[0][b] = digits;
        t[1][b] = power <= high ? std::uint64_t(power - 1) : ~std::uint64_t(0);
    }
    return t;
}();

inline unsigned digit_count(std::uint64_t x) {
    const int b = std::bit_width(x | 1);
    return unsigned(kDigitCount64[0][b] + (x > kDigitCount64[1][b]));
}

// Bytes kShiftWindow[k..k + 16) shuffle a vector down by k bytes.
alignas(32) inline constexpr std::int8_t kShiftWindow[32] = {0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  10,
                                                             11, 12, 13, 14, 15, -1, -1, -1, -1, -1, -1,
                                                             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1};

inline __m128i shift_down(__m128i v, unsigned k) {
    return _mm_shuffle_epi8(v, _mm_loadu_si128(reinterpret_cast<const __m128i*>(kShiftWindow + k)));
}

// Writes x in decimal at p and returns the end. Stores 16 bytes.
inline char* format(char* p, std::uint32_t x) {
    // Twelve digits with leading zeros, as three groups of four, then shifted down past the zeros.
    const std::uint32_t top = x / 100000000, rest = x % 100000000;
    const std::uint32_t high = rest / 10000, low = rest % 10000;
    const __m128i digits = _mm_insert_epi32(
        _mm_cvtsi64_si128(std::int64_t(kQuad[top] | std::uint64_t(kQuad[high]) << 32)), int(kQuad[low]), 2);
    const unsigned n = digit_count(x);
    _mm_storeu_si128(reinterpret_cast<__m128i*>(p), shift_down(digits, 12 - n));
    return p + n;
}

// high, low < 10^8 as 16 digits with leading zeros.
inline __m128i sixteen_digits(std::uint32_t high, std::uint32_t low) {
    return _mm_set_epi64x(std::int64_t(kQuad[low / 10000] | std::uint64_t(kQuad[low % 10000]) << 32),
                          std::int64_t(kQuad[high / 10000] | std::uint64_t(kQuad[high % 10000]) << 32));
}

// Writes x in decimal at p and returns the end. Stores up to 20 bytes. MaxDigits <= 16 promises
// x < 10^16, which saves a division.
template <int MaxDigits>
inline char* format64(char* p, std::uint64_t x) {
    const std::uint64_t q = x / 100000000;  // < 1.9 * 10^11
    const auto low = std::uint32_t(x - q * 100000000);
    const unsigned n = digit_count(x);
    if constexpr (MaxDigits <= 16) {
        _mm_storeu_si128(reinterpret_cast<__m128i*>(p), shift_down(sixteen_digits(std::uint32_t(q), low), 16 - n));
        return p + n;
    } else {
        // Twenty digits with leading zeros: a head of four, then sixteen.
        const auto top = std::uint32_t(q / 100000000);  // < 1845
        const auto middle = std::uint32_t(q - std::uint64_t(top) * 100000000);
        const unsigned head = n > 16 ? n - 16 : 0;
        const auto head_digits = std::uint32_t(std::uint64_t(kQuad[top]) >> (32 - 8 * head));
        std::memcpy(p, &head_digits, 4);
        _mm_storeu_si128(reinterpret_cast<__m128i*>(p + head), shift_down(sixteen_digits(middle, low), 16 - (n - head)));
        return p + n;
    }
}

// floor(x / d) for every dword x, as (x * Magic) >> Shift. The test checks each use exhaustively.
template <std::uint32_t Magic, int Shift>
inline __m256i divide(__m256i x) {
    const __m256i magic = _mm256_set1_epi64x(Magic);
    const __m256i even = _mm256_srli_epi64(_mm256_mul_epu32(x, magic), Shift);
    const __m256i odd = _mm256_srli_epi64(_mm256_mul_epu32(_mm256_srli_epi64(x, 32), magic), Shift);
    return _mm256_blend_epi32(even, _mm256_slli_epi64(odd, 32), 0xAA);
}

// Each dword g < 10^4 -> its 4 ASCII digits, first digit in the lowest byte.
inline __m256i quad_digits(__m256i g) {
    const __m256i high = _mm256_srli_epi16(_mm256_mulhi_epu16(g, _mm256_set1_epi16(5243)), 3);  // g / 100
    const __m256i low = _mm256_sub_epi16(g, _mm256_mullo_epi16(high, _mm256_set1_epi16(100)));
    const __m256i pairs = _mm256_or_si256(high, _mm256_slli_epi32(low, 16));  // 16-bit halves < 100
    const __m256i tens = _mm256_mulhi_epu16(pairs, _mm256_set1_epi16(6554));  // pair / 10
    const __m256i units = _mm256_sub_epi16(pairs, _mm256_mullo_epi16(tens, _mm256_set1_epi16(10)));
    return _mm256_or_si256(_mm256_or_si256(tens, _mm256_slli_epi16(units, 8)), _mm256_set1_epi8('0'));
}

// Digit counts of the eight dwords of v, one per byte in order.
inline std::uint64_t digit_counts(__m256i v) {
    // Unsigned v >= 10^k via a signed compare after flipping the sign bits; summed as a tree.
    const __m256i x = _mm256_xor_si256(v, _mm256_set1_epi32(int(0x80000000)));
    const auto at_least = [&](std::uint32_t power) {
        return _mm256_cmpgt_epi32(x, _mm256_set1_epi32(int((power - 1) ^ 0x80000000)));
    };
    const __m256i a = _mm256_add_epi32(_mm256_add_epi32(at_least(10), at_least(100)),
                                       _mm256_add_epi32(at_least(1000), at_least(10000)));
    const __m256i b = _mm256_add_epi32(_mm256_add_epi32(at_least(100000), at_least(1000000)),
                                       _mm256_add_epi32(at_least(10000000), at_least(100000000)));
    const __m256i n = _mm256_sub_epi32(_mm256_sub_epi32(_mm256_set1_epi32(1), at_least(1000000000)),
                                       _mm256_add_epi32(a, b));
    const __m256i bytes = _mm256_packus_epi16(_mm256_packus_epi32(n, n), n);  // per lane: 4 counts first
    return std::uint64_t(_mm256_extract_epi32(bytes, 0)) | std::uint64_t(_mm256_extract_epi32(bytes, 4)) << 32;
}

// Stores the two 16-byte lanes of w, values of 12 digits with leading zeros and a separator, as
// their last n0 and n1 digits and the separator. Returns the end; stores 16 bytes per lane.
inline char* put_pair(char* p, __m256i w, unsigned n0, unsigned n1) {
    const __m256i shifted = _mm256_shuffle_epi8(w, _mm256_loadu2_m128i(
        reinterpret_cast<const __m128i*>(kShiftWindow + 12 - n1), reinterpret_cast<const __m128i*>(kShiftWindow + 12 - n0)));
    _mm_storeu_si128(reinterpret_cast<__m128i*>(p), _mm256_castsi256_si128(shifted));
    p += n0 + 1;
    _mm_storeu_si128(reinterpret_cast<__m128i*>(p), _mm256_extracti128_si256(shifted, 1));
    return p + n1 + 1;
}

// Writes the eight dwords of v in decimal, each followed by separator, and returns the end.
// Stores up to 15 bytes past the end.
inline char* format8(char* p, __m256i v, char separator) {
    // Digit counts first, from v: the store addresses then do not wait for the digits.
    const std::uint64_t n = digit_counts(v);
    // Lanes [v0 v2 v4 v6 | v1 v3 v5 v7], so the transpose below pairs consecutive values.
    v = _mm256_permutevar8x32_epi32(v, _mm256_setr_epi32(0, 2, 4, 6, 1, 3, 5, 7));
    const __m256i top = divide<1441151881, 57>(v);  // v / 10^8
    const __m256i rest = _mm256_sub_epi32(v, _mm256_mullo_epi32(top, _mm256_set1_epi32(100000000)));
    const __m256i high = divide<3518437209, 45>(rest);  // rest / 10^4
    const __m256i low = _mm256_sub_epi32(rest, _mm256_madd_epi16(high, _mm256_set1_epi32(10000)));
    const __m256i t = quad_digits(top), h = quad_digits(high), l = quad_digits(low);
    const __m256i s = _mm256_set1_epi32(static_cast<unsigned char>(separator));
    // Transpose: each 16-byte lane becomes one value as dwords [top, high, low, separator].
    const __m256i th_low = _mm256_unpacklo_epi32(t, h), th_high = _mm256_unpackhi_epi32(t, h);
    const __m256i ls_low = _mm256_unpacklo_epi32(l, s), ls_high = _mm256_unpackhi_epi32(l, s);
    const auto count = [n](int i) { return unsigned(n >> 8 * i & 0xFF); };
    p = put_pair(p, _mm256_unpacklo_epi64(th_low, ls_low), count(0), count(1));
    p = put_pair(p, _mm256_unpackhi_epi64(th_low, ls_low), count(2), count(3));
    p = put_pair(p, _mm256_unpacklo_epi64(th_high, ls_high), count(4), count(5));
    return put_pair(p, _mm256_unpackhi_epi64(th_high, ls_high), count(6), count(7));
}

// Parses uint32 tokens from the token at p into dst: at most count, from input that is valid up
// to limit. Stops when fewer than kMinTokens tokens or 1 KiB of input remain. Returns where it
// stopped and the tokens parsed. Each chunk of input is cut
// into four streams at token boundaries. The streams advance in lockstep, two tokens per step, so
// four independent pointer chains overlap.
class BulkParser {
public:
    static constexpr std::size_t kMinTokens = 1024;

    struct Result {
        const char* end;
        std::size_t parsed;
    };

    static Result parse(const char* p, const char* limit, std::uint32_t* dst, std::size_t count) {
        std::uint32_t* const first = dst;
        while (count >= kMinTokens && limit - p >= 1024 + 64) {
            // With tokens of at most 16 bytes a chunk spans at most chunk + 33 bytes, so it holds
            // at most chunk / 2 + 17 < count tokens: all of them belong to this array. It ends
            // before limit.
            const std::size_t chunk =
                std::min({kChunk, 2 * (count - 32), std::size_t(limit - p) - 64}) & ~std::size_t(3);
            const std::size_t stream = chunk / 4;
            const char* s[4] = {p, after_separator(p + stream), after_separator(p + 2 * stream),
                                after_separator(p + 3 * stream)};
            const char* const end[4] = {s[1], s[2], s[3], after_separator(p + chunk)};
            std::uint32_t* const out[4] = {dst, scratch_[0], scratch_[1], scratch_[2]};
            __m256i invalid = _mm256_setzero_si256();
            const std::size_t done = lockstep(s, end, out, invalid);
            std::size_t n[4];
            bool overrun = false;
            for (int k = 0; k < 4; ++k) {
                n[k] = done;
                while (s[k] < end[k] && n[k] < kCapacity) out[k][n[k]++] = one_token(s[k], invalid);
                overrun |= s[k] != end[k];
            }
            if (overrun || (std::uint32_t(_mm256_movemask_epi8(invalid)) & 0x80008000)) [[unlikely]] {
                // Irregular whitespace or tokens: this chunk one token at a time.
                const std::size_t tokens = std::min(count_tokens(p, end[3]), count);
                p = parse_slowly(p, dst, tokens);
                dst += tokens;
                count -= tokens;
                continue;
            }
            std::uint32_t* next = dst + n[0];
            for (int k = 1; k < 4; ++k) {
                std::memcpy(next, out[k], n[k] * sizeof(std::uint32_t));
                next += n[k];
            }
            dst = next;
            count -= n[0] + n[1] + n[2] + n[3];
            p = skip_whitespace(end[3]);
        }
        return {p, std::size_t(dst - first)};
    }

private:
    static constexpr std::size_t kChunk = std::size_t(1) << 17;
    // A step advances a stream by 2..33 bytes and yields two values, so a stream of at most
    // kChunk / 4 + 33 bytes yields at most kChunk / 4 + 66 values.
    static constexpr std::size_t kCapacity = kChunk / 4 + 66;
    alignas(64) static inline std::uint32_t scratch_[3][kCapacity];

    // Steps all streams while each has 33 bytes left; returns the values per stream. Works on
    // local copies of the stream state, which stay in registers.
    static std::size_t lockstep(const char* (&streams)[4], const char* const (&end)[4],
                                std::uint32_t* const (&outputs)[4], __m256i& flags) {
        const char* s[4] = {streams[0], streams[1], streams[2], streams[3]};
        std::uint32_t* const out[4] = {outputs[0], outputs[1], outputs[2], outputs[3]};
        __m256i invalid = flags;
        std::size_t done = 0;
        for (;;) {
            std::ptrdiff_t left = end[0] - s[0];
            for (int k = 1; k < 4; ++k) left = std::min(left, end[k] - s[k]);
            if (left < 33) break;
            for (std::ptrdiff_t steps = left / 33; steps; --steps, done += 2) {
                const __m256i g0 = two_tokens(s[0], invalid), g1 = two_tokens(s[1], invalid);
                const __m256i g2 = two_tokens(s[2], invalid), g3 = two_tokens(s[3], invalid);
                const __m256i k = _mm256_set1_epi32(0x00012710);
                // 8-digit halves: [s0 high, s0 low, s1 high, s1 low | second tokens likewise].
                const __m256 h01 = _mm256_castsi256_ps(_mm256_madd_epi16(_mm256_packus_epi32(g0, g1), k));
                const __m256 h23 = _mm256_castsi256_ps(_mm256_madd_epi16(_mm256_packus_epi32(g2, g3), k));
                const __m256i high = _mm256_castps_si256(_mm256_shuffle_ps(h01, h23, 0x88));
                const __m256i low = _mm256_castps_si256(_mm256_shuffle_ps(h01, h23, 0xDD));
                const __m256i v = _mm256_add_epi32(_mm256_mullo_epi32(high, _mm256_set1_epi32(100000000)), low);
                // [s0 a, s0 b, s1 a, s1 b | s2 a, s2 b, s3 a, s3 b]
                const __m256i q = _mm256_permutevar8x32_epi32(v, _mm256_setr_epi32(0, 4, 1, 5, 2, 6, 3, 7));
                const __m128i q01 = _mm256_castsi256_si128(q), q23 = _mm256_extracti128_si256(q, 1);
                _mm_storel_epi64(reinterpret_cast<__m128i*>(out[0] + done), q01);
                _mm_storeh_pd(reinterpret_cast<double*>(out[1] + done), _mm_castsi128_pd(q01));
                _mm_storel_epi64(reinterpret_cast<__m128i*>(out[2] + done), q23);
                _mm_storeh_pd(reinterpret_cast<double*>(out[3] + done), _mm_castsi128_pd(q23));
            }
        }
        for (int k = 0; k < 4; ++k) streams[k] = s[k];
        flags = invalid;
        return done;
    }

    // Two tokens at s, as 4-digit groups [first | second]. Lengths outside 1..16 (repeated
    // whitespace, long tokens) set the sign bit of byte 15 or 31 of invalid.
    [[gnu::always_inline]] static __m256i two_tokens(const char*& s, __m256i& invalid) {
        const __m256i bytes = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(s));
        const std::uint32_t sep = separators(bytes);
        const auto first = std::size_t(std::countr_zero(sep));              // length of the first token
        const auto second = std::size_t(std::countr_zero(sep & (sep - 1)));  // 32 if none
        const __m256i windows =
            _mm256_inserti128_si256(bytes, _mm_loadu_si128(reinterpret_cast<const __m128i*>(s + first + 1)), 1);
        const __m256i rows = _mm256_set_m128i(align_row(second - first), align_row(first + 1));
        invalid = _mm256_or_si256(invalid, rows);
        s += second + 1;
        return digit_groups(_mm256_shuffle_epi8(_mm256_subs_epu8(windows, _mm256_set1_epi8('0')), rows));
    }

    static std::uint32_t one_token(const char*& s, __m256i& invalid) {
        const __m128i window = _mm_loadu_si128(reinterpret_cast<const __m128i*>(s));
        const unsigned n = unsigned(std::countr_zero(separators(window) | 0x10000));
        invalid = _mm256_or_si256(invalid, _mm256_castsi128_si256(align_row(n + 1)));
        s += n + 1;
        return std::uint32_t(parse16(window, n));
    }

    // The byte after the first separator at or after q.
    static const char* after_separator(const char* q) {
        for (;; q += 32)
            if (const std::uint32_t sep = separators(_mm256_loadu_si256(reinterpret_cast<const __m256i*>(q))))
                return q + std::countr_zero(sep) + 1;
    }

    static const char* skip_whitespace(const char* p) {
        while (static_cast<unsigned char>(*p) <= ' ') ++p;
        return p;
    }

    // Tokens in [p, end), where p starts a token.
    static std::size_t count_tokens(const char* p, const char* end) {
        std::size_t tokens = 1;
        for (const char* q = p + 1; q < end; ++q)
            tokens += static_cast<unsigned char>(*q) > ' ' && static_cast<unsigned char>(q[-1]) <= ' ';
        return tokens;
    }

    static const char* parse_slowly(const char* p, std::uint32_t* dst, std::size_t count) {
        for (std::size_t i = 0; i < count; ++i) {
            p = skip_whitespace(p);
            const __m128i window = _mm_loadu_si128(reinterpret_cast<const __m128i*>(p));
            const unsigned n = unsigned(std::countr_zero(separators(window) | 0x10000));
            dst[i] = std::uint32_t(parse16(window, n));
            p += n + 1;
        }
        return p;
    }
};

}  // namespace detail

// Token boundaries come from separator bitmasks of aligned 64-byte blocks: finding the next token
// clears one bit, so consecutive reads do not wait on each other's parsing.
class Reader {
public:
    // Takes everything that remains on fd (stdin by default).
    explicit Reader(int fd = 0) : input_(detail::open_input(fd)) { seek(input_.start); }

    ~Reader() { detail::release(input_); }

    Reader(const Reader&) = delete;
    Reader& operator=(const Reader&) = delete;

    // Next integer token, or the next non-whitespace character for char. MaxDigits, if set, promises
    // at most that many digits; for 64-bit types, 16 or fewer selects a faster parser.
    // Non-negative values parse faster as unsigned types (10-18%, see notes.md).
    template <class T, int MaxDigits = 0>
        requires std::integral<T> && (!std::same_as<T, bool>)
    T read() {
        if constexpr (std::same_as<T, char>) {
            skip_whitespace();
            return *cur_++;
        } else {
            const auto [start, length] = next_token();
            // A leading '-' sits below '0' and parses as a zero digit.
            const auto magnitude = parse<(sizeof(T) > 4), MaxDigits>(start + length, length);
            if constexpr (std::is_unsigned_v<T>) return T(magnitude);
            else return T(*start == '-' ? 0 - magnitude : magnitude);
        }
    }

    // count tokens into dst. uint32_t uses the AVX2 bulk parser; other types read one by one.
    template <int MaxDigits = 0, class T>
    void read(T* dst, std::size_t count) {
        if constexpr (std::same_as<T, std::uint32_t>) {
            skip_whitespace();
            const auto [stop, parsed] = detail::BulkParser::parse(cur_, input_.end, dst, count);
            seek(stop);
            for (std::size_t i = parsed; i < count; ++i) dst[i] = read<T>();
        } else {
            for (std::size_t i = 0; i < count; ++i) dst[i] = read<T, MaxDigits>();
        }
    }

    // Next token; valid while the Reader lives.
    std::string_view word() {
        const auto [start, length] = next_token();
        return {start, length};
    }

    // Tokenizer state, for custom token loops. separators has one bit per whitespace byte of the
    // 64-byte block at block, at or after cur. The lowest bit is the end of the token at cur: clear
    // it to move on. With no bits left, advance block by 64 and take detail::block_separators.
    struct Scan {
        const char* cur;
        const char* block;
        std::uint64_t separators;
    };

    Scan scan() const { return {cur_, block_, separators_}; }

    void resume(const Scan& scan) {
        cur_ = scan.cur;
        block_ = scan.block;
        separators_ = scan.separators;
    }

private:
    struct Token {
        const char* start;
        unsigned length;
    };

    // Continue reading at p.
    void seek(const char* p) {
        cur_ = p;
        block_ = reinterpret_cast<const char*>(reinterpret_cast<std::uintptr_t>(p) & ~std::uintptr_t(63));
        separators_ = detail::block_separators(block_) & ~std::uint64_t(0) << (cur_ - block_);
    }

    // Position of the next separator; at or after cur_.
    const char* next_separator() {
        while (!separators_) [[unlikely]] {
            block_ += 64;
            separators_ = detail::block_separators(block_);
        }
        return block_ + std::countr_zero(separators_);
    }

    void skip_whitespace() {
        while (next_separator() == cur_) {
            separators_ &= separators_ - 1;
            ++cur_;
        }
    }

    Token next_token() {
        for (;;) {
            const char* end = next_separator();
            separators_ &= separators_ - 1;
            const char* start = cur_;
            cur_ = end + 1;
            if (end != start) [[likely]] return {start, unsigned(end - start)};
        }
    }

    // Value of the n characters that end at end.
    template <bool Wide, int MaxDigits>
    static auto parse(const char* end, unsigned n) {
        if constexpr (!Wide) return std::uint32_t(detail::parse_ending16(end, n));
        else if constexpr (MaxDigits > 0 && MaxDigits <= 16) return detail::parse_ending16(end, n);
        else return detail::parse_ending24(end, n);
    }

    detail::Input input_;
    const char* cur_;             // next unread byte
    const char* block_;           // 64-byte block holding the next separator
    std::uint64_t separators_;    // separators in block_ at or after cur_
};

// Buffered output. write() takes any mix of integers, chars and strings:
//   out.write(x, ' ', y, '\n');
// MaxDigits, if set, promises integers of at most that many digits; for 64-bit types, 16 or fewer
// selects a faster formatter: out.write<16>(sum, '\n').
class Writer {
public:
    explicit Writer(int fd = 1) : fd_(fd) {}
    ~Writer() { flush(); }

    Writer(const Writer&) = delete;
    Writer& operator=(const Writer&) = delete;

    template <int MaxDigits = 0, class... Ts>
    void write(const Ts&... values) {
        const std::size_t needed = (std::size_t(0) + ... + max_size(values));
        if (needed > kCapacity) [[unlikely]] {
            (write_alone<MaxDigits>(values), ...);
            return;
        }
        if (std::size_t(buffer_ + kCapacity - cur_) < needed) [[unlikely]] flush();
        char* p = cur_;
        ((p = put<MaxDigits>(p, values)), ...);
        cur_ = p;
    }

    // Custom formatting: fill(p) may store up to max_size <= 64 KiB bytes at p and returns the end
    // of what it wrote.
    template <class Fill>
    void write_with(std::size_t max_size, Fill fill) {
        if (std::size_t(buffer_ + kCapacity - cur_) < max_size) [[unlikely]] flush();
        cur_ = fill(cur_);
    }

    // values[0..count) joined by separator. uint32_t uses the AVX2 formatter.
    template <int MaxDigits = 0, class T>
    void write_array(const T* values, std::size_t count, char separator) {
        if (!count) return;
        std::size_t i = 0;
        if constexpr (std::same_as<T, std::uint32_t>) {
            constexpr std::size_t kBatch = 8 * 11 + 16;  // eight values and separators, plus overhang
            char* p = cur_;
            for (; i + 8 <= count; i += 8) {
                if (std::size_t(buffer_ + kCapacity - p) < kBatch) [[unlikely]] {
                    cur_ = p;
                    flush();
                    p = cur_;
                }
                p = detail::format8(p, _mm256_loadu_si256(reinterpret_cast<const __m256i*>(values + i)), separator);
            }
            cur_ = p;
        }
        for (; i < count; ++i) write<MaxDigits>(values[i], separator);
        --cur_;  // no separator after the last value
    }

    void flush() {
        write_all(fd_, buffer_, std::size_t(cur_ - buffer_));
        cur_ = buffer_;
    }

private:
    static constexpr std::size_t kCapacity = std::size_t(1) << 16;

    template <class T>
    static constexpr bool kInteger = std::integral<T> && !std::same_as<T, char> && !std::same_as<T, bool>;

    // Bytes put() may store, which can exceed what it writes.
    template <class T>
    static std::size_t max_size(const T& value) {
        if constexpr (std::same_as<T, char>) return 1;
        else if constexpr (kInteger<T>) return 1 + 20;  // a sign, then format() stores up to 20 bytes
        else return std::string_view(value).size();
    }

    template <int MaxDigits, class T>
    static char* put(char* p, const T& value) {
        if constexpr (std::same_as<T, char>) {
            *p = value;
            return p + 1;
        } else if constexpr (kInteger<T>) {
            using U = std::conditional_t<sizeof(T) <= 4, std::uint32_t, std::uint64_t>;
            if constexpr (std::is_signed_v<T>) {
                *p = '-';
                p += value < 0;
                return put<MaxDigits>(p, value < 0 ? U(0 - U(value)) : U(value));
            } else if constexpr (sizeof(T) <= 4) {
                return detail::format(p, U(value));
            } else {
                return detail::format64<MaxDigits == 0 ? 20 : MaxDigits>(p, U(value));
            }
        } else {
            const std::string_view s(value);
            std::memcpy(p, s.data(), s.size());
            return p + s.size();
        }
    }

    // A value longer than the buffer: flush, then write it directly.
    template <int MaxDigits, class T>
    void write_alone(const T& value) {
        if constexpr (std::same_as<T, char> || kInteger<T>) {
            write<MaxDigits>(value);
        } else {
            flush();
            const std::string_view s(value);
            write_all(fd_, s.data(), s.size());
        }
    }

    static void write_all(int fd, const char* data, std::size_t size) {
        while (size) {
            const ssize_t put = ::write(fd, data, size);
            if (put > 0) data += put, size -= std::size_t(put);
            else if (put < 0 && errno == EINTR) continue;
            else std::abort();
        }
    }

    int fd_;
    char* cur_ = buffer_;
    alignas(64) char buffer_[kCapacity];
};

}  // namespace io

#ifndef IO_BULK32_TRANSPOSE
#ifdef __znver3__
#define IO_BULK32_TRANSPOSE 1
#else
#define IO_BULK32_TRANSPOSE 0
#endif
#endif

namespace io {
namespace detail {

// Parses uint32 tokens of at most 16 characters from the token at p into dst: at most count,
// which must be the tokens that follow. Stops when fewer than kMinTokens tokens remain. Returns
// where it stopped and the tokens parsed. As BulkParser in io.hpp, each chunk of input is cut into
// four streams at token boundaries that advance in lockstep, two tokens per step. A step stores
// its eight values as one vector, [a0 a1 a2 a3 b0 b1 b2 b3] for tokens a_k, b_k of stream k, and
// a transpose then puts each stream's values in order. On Zen 3 this is 17% faster than four
// 8-byte stores per step; on Intel (Emerald Rapids) 5% slower.
class BulkParser32 {
public:
    static constexpr std::size_t kMinTokens = 1024;

    struct Result {
        const char* end;
        std::size_t parsed;
    };

    static Result parse(const char* p, std::uint32_t* dst, std::size_t count) {
        std::uint32_t* const first = dst;
        while (count >= kMinTokens) {
            // The count tokens span at least 2 * count - 1 bytes. A chunk spans at most chunk + 17
            // bytes, so it holds at most chunk / 2 + 9 < count tokens, and loads stay below
            // p + chunk + 33: all within those bytes.
            const std::size_t chunk = std::min(kChunk, 2 * (count - 32)) & ~std::size_t(3);
            const std::size_t stream = chunk / 4;
            const char* s[4] = {p, after_separator(p + stream), after_separator(p + 2 * stream),
                                after_separator(p + 3 * stream)};
            const char* const end[4] = {s[1], s[2], s[3], after_separator(p + chunk)};
            __m256i invalid = _mm256_setzero_si256();
            const std::size_t steps = lockstep(s, end, invalid);
            std::size_t tail[4];
            bool overrun = false;
            for (int k = 0; k < 4; ++k) {
                tail[k] = 0;
                while (s[k] < end[k] && tail[k] < kTail) tails_[k][tail[k]++] = one_token(s[k], invalid);
                overrun |= s[k] != end[k];
            }
            if (overrun || (std::uint32_t(_mm256_movemask_epi8(invalid)) & 0x80008000)) [[unlikely]] {
                // Irregular whitespace or tokens: this chunk one token at a time.
                const std::size_t tokens = std::min(count_tokens(p, end[3]), count);
                p = parse_slowly(p, dst, tokens);
                dst += tokens;
                count -= tokens;
                continue;
            }
            std::uint32_t* out[4] = {dst};
            for (int k = 0; k < 3; ++k) out[k + 1] = out[k] + 2 * steps + tail[k];
            transpose(steps, out);
            for (int k = 0; k < 4; ++k) std::memcpy(out[k] + 2 * steps, tails_[k], tail[k] * sizeof(std::uint32_t));
            const auto parsed = std::size_t(out[3] + 2 * steps + tail[3] - dst);
            dst += parsed;
            count -= parsed;
            p = skip_whitespace(end[3]);
        }
        return {p, std::size_t(dst - first)};
    }

    static const char* skip_whitespace(const char* p) {
        while (static_cast<unsigned char>(*p) <= ' ') ++p;
        return p;
    }

private:
    static constexpr std::size_t kChunk = std::size_t(1) << 17;
    // A step of valid tokens advances a stream by at least 4 bytes; lockstep stops at kSteps.
    static constexpr std::size_t kSteps = kChunk / 16 + 16;
    // A token takes at least 2 bytes of a stream.
    static constexpr std::size_t kTail = kChunk / 8 + 32;
    alignas(64) static inline std::uint32_t steps_[8 * kSteps];
    alignas(64) static inline std::uint32_t tails_[4][kTail];

    // Steps all streams while each has 33 bytes left; returns the steps. Step j stores its values
    // at steps_ + 8j. Works on local copies of the stream state, which stay in registers.
    static std::size_t lockstep(const char* (&streams)[4], const char* const (&end)[4], __m256i& flags) {
        const char* s[4] = {streams[0], streams[1], streams[2], streams[3]};
        __m256i invalid = flags;
        std::size_t done = 0;
        for (;;) {
            std::ptrdiff_t left = end[0] - s[0];
            for (int k = 1; k < 4; ++k) left = std::min(left, end[k] - s[k]);
            const std::ptrdiff_t steps = std::min(left / 33, std::ptrdiff_t(kSteps - done));
            if (steps <= 0) break;
            for (std::uint32_t* v = steps_ + 8 * done; v != steps_ + 8 * (done + std::size_t(steps)); v += 8) {
                const __m256i g0 = two_tokens(s[0], invalid), g1 = two_tokens(s[1], invalid);
                const __m256i g2 = two_tokens(s[2], invalid), g3 = two_tokens(s[3], invalid);
                const __m256i k = _mm256_set1_epi32(0x00012710);
                // 8-digit halves: [s0 high, s0 low, s1 high, s1 low | second tokens likewise].
                const __m256 h01 = _mm256_castsi256_ps(_mm256_madd_epi16(_mm256_packus_epi32(g0, g1), k));
                const __m256 h23 = _mm256_castsi256_ps(_mm256_madd_epi16(_mm256_packus_epi32(g2, g3), k));
                const __m256i high = _mm256_castps_si256(_mm256_shuffle_ps(h01, h23, 0x88));
                const __m256i low = _mm256_castps_si256(_mm256_shuffle_ps(h01, h23, 0xDD));
                _mm256_store_si256(reinterpret_cast<__m256i*>(v),
                                   _mm256_add_epi32(_mm256_mullo_epi32(high, _mm256_set1_epi32(100000000)), low));
            }
            done += std::size_t(steps);
        }
        for (int k = 0; k < 4; ++k) streams[k] = s[k];
        flags = invalid;
        return done;
    }

    // The 2 * steps values of stream k from steps_ to out[k]: a 4x4 transpose of value pairs.
    static void transpose(std::size_t steps, std::uint32_t* const (&out)[4]) {
        const auto pairs = [](std::size_t j) {  // step j as [a0 b0 a1 b1 | a2 b2 a3 b3]
            const __m256i v = _mm256_load_si256(reinterpret_cast<const __m256i*>(steps_ + 8 * j));
            return _mm256_permutevar8x32_epi32(v, _mm256_setr_epi32(0, 4, 1, 5, 2, 6, 3, 7));
        };
        std::size_t j = 0;
        for (; j + 4 <= steps; j += 4) {
            const __m256i p0 = pairs(j), p1 = pairs(j + 1), p2 = pairs(j + 2), p3 = pairs(j + 3);
            const __m256i t0 = _mm256_unpacklo_epi64(p0, p1), t1 = _mm256_unpackhi_epi64(p0, p1);
            const __m256i t2 = _mm256_unpacklo_epi64(p2, p3), t3 = _mm256_unpackhi_epi64(p2, p3);
            const auto put = [j](std::uint32_t* to, __m256i v) {
                _mm256_storeu_si256(reinterpret_cast<__m256i*>(to + 2 * j), v);
            };
            put(out[0], _mm256_permute2x128_si256(t0, t2, 0x20));
            put(out[1], _mm256_permute2x128_si256(t1, t3, 0x20));
            put(out[2], _mm256_permute2x128_si256(t0, t2, 0x31));
            put(out[3], _mm256_permute2x128_si256(t1, t3, 0x31));
        }
        for (; j < steps; ++j)
            for (int k = 0; k < 4; ++k) {
                out[k][2 * j] = steps_[8 * j + k];
                out[k][2 * j + 1] = steps_[8 * j + 4 + k];
            }
    }

    // Two tokens at s, as 4-digit groups [first | second]. Lengths outside 1..16 (repeated
    // whitespace, long tokens) set the sign bit of byte 15 or 31 of invalid.
    [[gnu::always_inline]] static __m256i two_tokens(const char*& s, __m256i& invalid) {
        const __m256i bytes = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(s));
        const std::uint32_t sep = separators(bytes);
        const auto first = std::size_t(std::countr_zero(sep));              // length of the first token
        const auto second = std::size_t(std::countr_zero(sep & (sep - 1)));  // 32 if none
        const __m256i windows =
            _mm256_inserti128_si256(bytes, _mm_loadu_si128(reinterpret_cast<const __m128i*>(s + first + 1)), 1);
        const __m256i rows = _mm256_set_m128i(align_row(second - first), align_row(first + 1));
        invalid = _mm256_or_si256(invalid, rows);
        s += second + 1;
        return digit_groups(_mm256_shuffle_epi8(_mm256_subs_epu8(windows, _mm256_set1_epi8('0')), rows));
    }

    static std::uint32_t one_token(const char*& s, __m256i& invalid) {
        const __m128i window = _mm_loadu_si128(reinterpret_cast<const __m128i*>(s));
        const unsigned n = unsigned(std::countr_zero(separators(window) | 0x10000));
        invalid = _mm256_or_si256(invalid, _mm256_castsi128_si256(align_row(n + 1)));
        s += n + 1;
        return std::uint32_t(parse16(window, n));
    }

    // The byte after the first separator at or after q.
    static const char* after_separator(const char* q) {
        for (;; q += 32)
            if (const std::uint32_t sep = separators(_mm256_loadu_si256(reinterpret_cast<const __m256i*>(q))))
                return q + std::countr_zero(sep) + 1;
    }

    // Tokens in [p, end), where p starts a token.
    static std::size_t count_tokens(const char* p, const char* end) {
        std::size_t tokens = 1;
        for (const char* q = p + 1; q < end; ++q)
            tokens += static_cast<unsigned char>(*q) > ' ' && static_cast<unsigned char>(q[-1]) <= ' ';
        return tokens;
    }

    static const char* parse_slowly(const char* p, std::uint32_t* dst, std::size_t count) {
        for (std::size_t i = 0; i < count; ++i) {
            p = skip_whitespace(p);
            const __m128i window = _mm_loadu_si128(reinterpret_cast<const __m128i*>(p));
            const unsigned n = unsigned(std::countr_zero(separators(window) | 0x10000));
            dst[i] = std::uint32_t(parse16(window, n));
            p += n + 1;
        }
        return p;
    }
};

// count uint32 tokens into dst with BulkParser32, the rest one at a time.
inline void read_transposed(Reader& in, std::uint32_t* dst, std::size_t count) {
    std::size_t parsed = 0;
    if (count >= BulkParser32::kMinTokens) {
        const char* const start = BulkParser32::skip_whitespace(in.scan().cur);
        const auto [stop, done] = BulkParser32::parse(start, dst, count);
        // Continue the Reader at stop: its separator mask from there on.
        const auto* block = reinterpret_cast<const char*>(reinterpret_cast<std::uintptr_t>(stop) & ~std::uintptr_t(63));
        in.resume({stop, block, block_separators(block) & ~std::uint64_t(0) << (stop - block)});
        parsed = done;
    }
    for (std::size_t i = parsed; i < count; ++i) dst[i] = in.read<std::uint32_t>();
}

}  // namespace detail

// count uint32 tokens into dst: the same values as in.read(dst, count).
inline void read_bulk(Reader& in, std::uint32_t* dst, std::size_t count) {
#if IO_BULK32_TRANSPOSE
    detail::read_transposed(in, dst, count);
#else
    in.read(dst, count);
#endif
}

}  // namespace io
// lib/mem/huge.hpp
// Zero-filled memory in transparent huge pages (2 MiB) where the kernel allows. Never freed: the
// programs end with _exit. Linux or macOS. Measurements: lib/mem/notes.md.
//
//   auto* a = mem::huge<std::uint32_t>(n);   // n zeroed values, 2 MiB aligned
//   mem::Arena arena(bytes);                 // one mapping for several arrays
//   auto* b = arena.take<std::uint64_t>(m);  // m zeroed values, 64-byte aligned
//
// Pages fault in on first touch. An arena of B bytes holds takes whose sizes, each rounded up to
// 64 bytes, sum to at most B; it does not check.

#include <sys/mman.h>

#include <cstddef>
#include <cstdint>
#include <cstdlib>

namespace mem {

inline constexpr std::size_t kHugePage = std::size_t(1) << 21;

// bytes rounded up to whole huge pages, 2 MiB aligned.
inline void* map_huge(std::size_t bytes) {
    bytes = (bytes + kHugePage - 1) / kHugePage * kHugePage;
    void* region = ::mmap(nullptr, bytes + kHugePage, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    if (region == MAP_FAILED) std::abort();
    const std::uintptr_t aligned = (reinterpret_cast<std::uintptr_t>(region) + kHugePage - 1) & ~(kHugePage - 1);
#ifdef MADV_HUGEPAGE
    ::madvise(reinterpret_cast<void*>(aligned), bytes, MADV_HUGEPAGE);
#endif
    return reinterpret_cast<void*>(aligned);
}

// count values of T.
template <class T>
T* huge(std::size_t count) {
    return static_cast<T*>(map_huge(count * sizeof(T)));
}

// Bump allocation from one map_huge() mapping.
class Arena {
public:
    explicit Arena(std::size_t bytes) : cur_(reinterpret_cast<std::uintptr_t>(map_huge(bytes))) {}

    // count values of T; the next take starts at the next multiple of 64 bytes.
    template <class T>
    T* take(std::size_t count) {
        T* p = reinterpret_cast<T*>(cur_);
        cur_ += (count * sizeof(T) + 63) & ~std::size_t(63);
        return p;
    }

private:
    std::uintptr_t cur_;
};

}  // namespace mem
// lib/run/early.hpp
// Program entry for solutions. RUN_EARLY(solve) runs solve() from the executable's
// pre-initializers (.preinit_array), before the C++ runtime initializes iostreams and locales
// (lib/io uses neither) and before any static constructor, then ends the process with _exit(0):
// no exit handlers, no teardown, no unmapping. Elsewhere it defines main() { solve(); }.
// Measurements: lib/run/notes.md.
//
//   namespace {
//   void solve() { ... }  // flushes its output (io::Writer does on destruction)
//   }  // namespace
//
//   RUN_EARLY(solve)      // at namespace scope, once per program

#include <unistd.h>

#ifdef __ELF__
#define RUN_EARLY(solve)                                                                                  \
    namespace {                                                                                           \
    void run_early(int, char**, char**) {                                                                 \
        solve();                                                                                          \
        ::_exit(0);                                                                                       \
    }                                                                                                     \
    [[gnu::used, gnu::section(".preinit_array")]] void (*const preinit)(int, char**, char**) = run_early; \
    }                                                                                                     \
    int main() { solve(); }  // reached only if the loader skips .preinit_array
#else
#define RUN_EARLY(solve) \
    int main() { solve(); }
#endif
// problems/convolution/min_plus_convolution_convex_arbitrary/columns.hpp
// Fixed-width output of values < 2^31: each value right-aligned in W - 1 characters, then a space;
// the last separator is a newline. W = 10 for blocks whose values are all below 10^9, else 11.
// Judge-specific: the checker compares tokens, so the padding is accepted.
//
// Per value v: w = v / 10^(W - 9) as 8 digits, most significant first, in a qword (leading zeros
// blank); the tail holds the last W - 9 digits and the separator in a dword. 16 values per step,
// written as W 16-byte chunks built by pshufb from these sources. The divisions of the next step
// are issued before the digits of this one, so the two dependency chains overlap.
// Same scheme as ../convolution_mod/fields.hpp (W = 10 only); here the shuffle controls are
// generated for either width.

#include <immintrin.h>

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <string_view>
#include <utility>


namespace columns {

namespace detail {

using u32 = std::uint32_t;

struct alignas(32) Lanes {
    u32 lane[8];
};

constexpr Lanes all(u32 x) { return {{x, x, x, x, x, x, x, x}}; }
constexpr Lanes all16(u32 x) { return all(x * 0x10001); }

[[gnu::always_inline]] inline __m256i load(const Lanes& l) {
    return _mm256_load_si256(reinterpret_cast<const __m256i*>(&l));
}

// Sources of a step's text. Digit qwords: kD01 holds values [0, 1 | 8, 9], kD23 [2, 3 | 10, 11],
// kD45 [4, 5 | 12, 13], kD67 [6, 7 | 14, 15]. Tail dwords: kLowTail [0..3 | 8..11],
// kHighTail [4..7 | 12..15]. kSwapped: kD01 with its lanes exchanged (W = 11 only, for the
// digits of value 8, which end the low lane's last chunk).
enum Source { kD01, kD23, kD45, kD67, kLowTail, kHighTail, kSwapped, kSources };

constexpr int kZero = 0x80;  // shuffle control: zero byte

// Chunks of the 16W text bytes of a step: chunks [0, low) from the low lane (values 0-7, and
// value 8's digits when W = 11), chunks [low, W) from the high lane. Vector k holds chunk k in
// its low lane and chunk low + k in its high lane.
template <int W>
struct Layout {
    static constexpr int kLow = (8 * W + 15) / 16;
    static constexpr int kHigh = W - kLow;
    Lanes control[kLow][kSources] = {};
    bool used[kLow][kSources] = {};

    // Text byte at offset 16 * chunk + i, read in lane `lane`.
    constexpr void place(int k, int lane, int chunk, int i) {
        const int at = 16 * chunk + i, value = at / W, offset = at % W, j = value % 8;
        int source, byte;
        if (value / 8 != lane) {  // value 8's digits in the low lane
            source = kSwapped, byte = offset;
        } else if (offset < 8) {
            source = kD01 + j / 2, byte = 8 * (j % 2) + offset;
        } else {
            source = kLowTail + j / 4, byte = 4 * (j % 4) + offset - 8;
        }
        used[k][source] = true;
        const int b = 16 * lane + i;
        u32& word = control[k][source].lane[b / 4];
        word = (word & ~(0xFFu << 8 * (b % 4))) | u32(byte) << 8 * (b % 4);
    }

    constexpr Layout() {
        for (int k = 0; k < kLow; ++k)
            for (int s = 0; s < kSources; ++s)
                for (int b = 0; b < 32; ++b) control[k][s].lane[b / 4] |= u32(kZero) << 8 * (b % 4);
        for (int k = 0; k < kLow; ++k)
            for (int i = 0; i < 16; ++i) {
                place(k, 0, k, i);
                if (k < kHigh) place(k, 1, kLow + k, i);
            }
    }
};

template <int W>
inline constexpr Layout<W> kLayout{};

// Divisions: v / 10^(W - 9) = v * kDigits.multiplier >> kDigits.shift, exact for v < 2^31,
// and likewise v / 10^(W - 4) by kHigher.
struct Magic {
    u32 multiplier;
    int shift;
};

template <int W>
struct Constants;

template <>
struct Constants<10> {
    static constexpr Magic kDigits{429496730, 32};    // ceil(2^32 / 10), v < 2^30
    static constexpr Magic kHigher{1407374884, 47};   // ceil(2^47 / 10^5)
};

template <>
struct Constants<11> {
    static constexpr Magic kDigits{2748779070, 38};   // ceil(2^38 / 100), v < 2^32
    static constexpr Magic kHigher{2251799814, 51};   // ceil(2^51 / 10^6), v < 7 * 10^9
};

struct Common {
    Lanes pack = all(1 - 10000 * 65536u);  // [h, w - 10^4 h] in 16-bit halves = 2^16 w + h pack
    Lanes by100 = all16(5243), hundred = all16(100);  // x / 100 = (x * 5243 >> 16) >> 3 for x < 10^4
    Lanes by10 = all16(6554);       // z / 10 = z * 6554 >> 16 for z < 100
    Lanes tens_out = all16(2559);   // bytes [z / 10, z % 10] = 256 z - 2559 (z / 10)
    Lanes ones = all(~0u), zero = all(0x30303030), space = all(0x20202020);
    Lanes ten = all(10), hundred32 = all(100);
    Lanes tail10 = all(' ' << 8 | '0');               // units digit, space
    Lanes tail11 = all(' ' << 16 | '0' << 8 | '0');   // tens digit, units digit, space
    Lanes blank = all(0x10);                          // '0' - 0x10 = ' '
    Lanes digits_multiplier[2] = {all(Constants<10>::kDigits.multiplier), all(Constants<11>::kDigits.multiplier)};
    Lanes higher_multiplier[2] = {all(Constants<10>::kHigher.multiplier), all(Constants<11>::kHigher.multiplier)};
};

inline constexpr Common kCommon{};

// v / magic for eight dwords v; odd = v >> 32 per qword.
template <Magic M>
[[gnu::always_inline]] inline __m256i divide(__m256i v, __m256i odd, __m256i multiplier) {
    const __m256i even_q = _mm256_srli_epi64(_mm256_mul_epu32(v, multiplier), M.shift);
    const __m256i odd_q = _mm256_mul_epu32(odd, multiplier);
    return _mm256_blend_epi32(even_q, M.shift == 32 ? odd_q : _mm256_srli_epi64(odd_q, M.shift - 32), 0xAA);
}

// Eight values after the divisions: halves holds [w / 10^4, w % 10^4] in 16-bit halves;
// tail holds the last W - 9 digits and the separator as text.
struct Divided {
    __m256i halves, tail;
};

template <int W>
[[gnu::always_inline]] inline Divided divide(__m256i v, const Common& k) {
    const __m256i odd = _mm256_srli_epi64(v, 32);
    const __m256i w = divide<Constants<W>::kDigits>(v, odd, load(k.digits_multiplier[W - 10]));
    const __m256i h = divide<Constants<W>::kHigher>(v, odd, load(k.higher_multiplier[W - 10]));
    const __m256i halves = _mm256_add_epi32(_mm256_slli_epi32(w, 16), _mm256_mullo_epi32(h, load(k.pack)));
    if constexpr (W == 10) {
        return {halves, _mm256_sub_epi32(_mm256_add_epi32(v, load(k.tail10)), _mm256_mullo_epi32(w, load(k.ten)))};
    } else {
        // r = v % 100 < 100 in the low 16 bits; tail bytes [r / 10, r % 10, ' ', 0] as text,
        // the tens digit blank for v < 10 (then w = 0 and the digits are blank too).
        const __m256i r = _mm256_sub_epi32(v, _mm256_mullo_epi32(w, load(k.hundred32)));
        const __m256i tens = _mm256_mulhi_epu16(r, load(k.by10));
        const __m256i pair = _mm256_sub_epi16(_mm256_slli_epi16(r, 8), _mm256_mullo_epi16(tens, load(k.tens_out)));
        const __m256i small = _mm256_and_si256(_mm256_cmpgt_epi32(load(k.ten), v), load(k.blank));
        return {halves, _mm256_sub_epi32(_mm256_add_epi32(pair, load(k.tail11)), small)};
    }
}

// 16-bit z < 100 -> bytes [z / 10, z % 10].
[[gnu::always_inline]] inline __m256i two_digits(__m256i z, const Common& k) {
    const __m256i tens = _mm256_mulhi_epu16(z, load(k.by10));
    return _mm256_sub_epi16(_mm256_slli_epi16(z, 8), _mm256_mullo_epi16(tens, load(k.tens_out)));
}

// Qwords of 8 digits, most significant first -> text; leading zeros become spaces. x ^ (x - 1)
// sets the bits up to the lowest set one: 0xFF in leading zero bytes, < 0x10 in the first
// nonzero digit, 0 above. blendv takes the space where a byte's top bit is set.
[[gnu::always_inline]] inline __m256i text(__m256i digits, const Common& k) {
    const __m256i upto = _mm256_xor_si256(digits, _mm256_add_epi64(digits, load(k.ones)));
    return _mm256_blendv_epi8(_mm256_or_si256(digits, load(k.zero)), load(k.space), upto);
}

// Text of the 8 digits of w, two values per lane: values [0, 1 | 4, 5] of d in lo, [2, 3 | 6, 7]
// in hi. Per value, 16-bit [w / 10^6, w / 10^4 % 100, w / 100 % 100, w % 100] before two_digits.
[[gnu::always_inline]] inline void digits(const Divided& d, __m256i& lo, __m256i& hi, const Common& k) {
    const __m256i hundreds = _mm256_srli_epi16(_mm256_mulhi_epu16(d.halves, load(k.by100)), 3);
    const __m256i rest = _mm256_sub_epi16(d.halves, _mm256_mullo_epi16(hundreds, load(k.hundred)));
    lo = text(two_digits(_mm256_unpacklo_epi16(hundreds, rest), k), k);
    hi = text(two_digits(_mm256_unpackhi_epi16(hundreds, rest), k), k);
}

// Vector k of the step: the OR of one shuffle per source it uses.
template <int W, int K, std::size_t... S>
[[gnu::always_inline]] inline __m256i chunk(const __m256i (&source)[kSources], std::index_sequence<S...>) {
    constexpr const Layout<W>& layout = kLayout<W>;
    __m256i c = _mm256_setzero_si256();
    const auto add = [&](std::size_t s) {
        c = _mm256_or_si256(c, _mm256_shuffle_epi8(source[s], load(layout.control[K][s])));
    };
    ((layout.used[K][S] ? add(S) : void()), ...);
    return c;
}

// 16W bytes at p (16-byte aligned) for values x0..x15, divided as lo = [x0..x3 | x8..x11] and
// hi = [x4..x7 | x12..x15].
template <int W>
[[gnu::always_inline]] inline void store(char* p, const Divided& lo, const Divided& hi, const Common& k) {
    constexpr int kLow = Layout<W>::kLow, kHigh = Layout<W>::kHigh;
    __m256i source[kSources];
    digits(lo, source[kD01], source[kD23], k);
    digits(hi, source[kD45], source[kD67], k);
    source[kLowTail] = lo.tail, source[kHighTail] = hi.tail;
    source[kSwapped] = W == 11 ? _mm256_permute2x128_si256(source[kD01], source[kD01], 0x01) : source[kD01];
    __m256i c[kLow];
    [&]<std::size_t... K>(std::index_sequence<K...>) {
        ((c[K] = chunk<W, K>(source, std::make_index_sequence<kSources>())), ...);
    }(std::make_integer_sequence<std::size_t, kLow>());
    // Vector k whole at chunk kLow + k - 1: its high lane lands in place, its low lane on the slot
    // of the previous vector's high lane (or of chunk kLow - 1), which a later store fixes.
    for (int i = kHigh - 1; i >= 0; --i)
        _mm256_storeu_si256(reinterpret_cast<__m256i*>(p + 16 * (kLow + i - 1)), c[i]);
    for (int i = 0; i < kLow; ++i)
        _mm_store_si128(reinterpret_cast<__m128i*>(p + 16 * i), _mm256_castsi256_si128(c[i]));
}

// Values x[0, 16) in the lane order of store(), divided.
template <int W>
[[gnu::always_inline]] inline void divide16(const u32* x, Divided& lo, Divided& hi, const Common& k) {
    const auto at = [x](int i) { return _mm256_loadu_si256(reinterpret_cast<const __m256i*>(x + i)); };
    const auto both = [x](int i) { return _mm256_broadcastsi128_si256(_mm_loadu_si128(reinterpret_cast<const __m128i*>(x + i))); };
    lo = divide<W>(_mm256_blend_epi32(at(0), both(8), 0xF0), k);
    hi = divide<W>(_mm256_blend_epi32(at(8), both(4), 0x0F), k);
}

// Text of x[0, count), count a positive multiple of 16, at p (16-byte aligned).
template <int W>
void format(char* p, const u32* x, std::size_t count) {
    const Common& k = kCommon;
    Divided dl, dh;
    divide16<W>(x, dl, dh, k);
    for (std::size_t i = 16; i < count; i += 16, p += 16 * W) {
        Divided nl, nh;
        divide16<W>(x + i, nl, nh, k);
        store<W>(p, dl, dh, k);
        dl = nl, dh = nh;
    }
    store<W>(p, dl, dh, k);
}

inline u32 maximum(const u32* x, std::size_t count) {
    __m256i m = _mm256_setzero_si256();
    for (std::size_t i = 0; i < count; i += 8)
        m = _mm256_max_epu32(m, _mm256_loadu_si256(reinterpret_cast<const __m256i*>(x + i)));
    alignas(32) u32 lane[8];
    _mm256_store_si256(reinterpret_cast<__m256i*>(lane), m);
    return *std::max_element(lane, lane + 8);
}

}  // namespace detail

inline constexpr std::size_t kBlock = 25600;  // values per write(2), a multiple of 16
inline constexpr std::size_t kTextBytes = 11 * kBlock;

// values[0, count), count >= 1, each < 2^31; values[count, count rounded up to 16) must be
// readable and zero. text: kTextBytes bytes, 16-byte aligned. Blocks are longer than the
// Writer's buffer, so it hands each to write(2) directly.
inline void write(io::Writer& out, const std::uint32_t* values, std::size_t count, char* text) {
    for (std::size_t i = 0; i < count; i += kBlock) {
        const std::size_t n = std::min(kBlock, count - i), padded = (n + 15) / 16 * 16;
        const std::size_t width = detail::maximum(values + i, padded) < 1'000'000'000 ? 10 : 11;
        if (width == 10) detail::format<10>(text, values + i, padded);
        else detail::format<11>(text, values + i, padded);
        if (i + n == count) text[width * n - 1] = '\n';
        out.write(std::string_view(text, width * n));
    }
}

}  // namespace columns

namespace {

using u32 = std::uint32_t;

// Bounds on R(theta), the number of slopes s_y = a[y + 1] - a[y] (y < n - 1, non-increasing) with
// s_y >= theta. For columns d apart whose b values differ by g (newer minus older), the newer one
// wins where a[y + d] - a[y] >= g, y its offset into a. That sum of d slopes lies in
// [d s_{y+d-1}, d s_y], so with R = R(ceil(g / d)) the newer column wins at y <= R - d and loses
// at y >= R. Theta values go in buckets of 2^shift; the bounds are exact when shift = 0, that is
// when the slopes span fewer than kBuckets values.
class SlopeRank {
public:
    static constexpr u32 kBuckets = 1 << 15;

    struct Bounds {
        u32 low, high;  // low <= R(theta) <= high
    };

    // table: kBuckets entries.
    SlopeRank(const u32* a, u32 n, Bounds* table) : table_(table) {
        const u32 count = n - 1;
        if (count == 0) return;
        max_ = slope(a, 0);
        min_ = slope(a, count - 1);
        const u32 span = u32(max_ - min_) + 1;  // theta in [min_, max_ + 1]
        while (span >> shift_ >= kBuckets) ++shift_;
        u32 rank = count;  // R(theta) for the theta last queried
        const auto at_least = [&](std::int64_t theta) {
            while (rank > 0 && slope(a, rank - 1) < theta) --rank;
            return rank;
        };
        for (u32 i = 0; i <= span >> shift_; ++i) {
            const std::int64_t first = min_ + (std::int64_t(i) << shift_);
            table[i].high = at_least(first);
            table[i].low = at_least(first + (std::int64_t(1) << shift_) - 1);
        }
    }

    Bounds operator()(std::int32_t theta) const {
        return table_[u32(std::clamp(theta, min_, max_ + 1) - min_) >> shift_];
    }

private:
    static std::int32_t slope(const u32* a, u32 y) { return std::int32_t(a[y + 1] - a[y]); }

    const Bounds* table_;
    std::int32_t min_ = 0, max_ = 0;
    u32 shift_ = 0;
};

// A column in a sweep: its value at row offset t is a[offset + Step t] + bias (offset wraps mod
// 2^32). It beats the entry below up to row end and loses after; the bottom entry has end = len - 1.
struct Entry {
    u32 offset;
    u32 bias;  // b of the column
    u32 end;
};

// Sweeps len rows: first, first + Step, ... (Step = +1 or -1). Column enter_first + Step t joins
// at offset t for t < enter_count. c[x] = min(c[x], envelope at x). a must be readable 8 values
// beyond both ends.
template <int Step>
class Sweep {
public:
    Sweep(const u32* a, const u32* b, const SlopeRank& rank, u32 first, u32 len, Entry* stack)
        : a_(a), b_(b), rank_(rank), first_(first), len_(len), stack_(stack) {}

    void run(u32* c, u32 enter_first, u32 enter_count) {
        // A joining column is at a[first - enter_first] (a's first or last value).
        const u32 joining = a_[first_ - enter_first];
        Entry top = {first_ - enter_first, b_[enter_first], len_ - 1};
        c[first_] = std::min(c[first_], joining + top.bias);
        u32 t = 1;
        for (; t < enter_count; ++t) {
            while (top.end < t) top = stack_[--below_];
            u32 at_t = value(top, t);
            const u32 k = enter_first + Step * t;
            if (const u32 v = joining + b_[k]; v <= at_t) {
                top = insert({first_ - k, b_[k], 0}, t, top);
                at_t = v;
            }
            const u32 x = first_ + Step * t;
            c[x] = std::min(c[x], at_t);
        }
        // No more columns join: each entry owns its rows up to its end.
        stack_[below_++] = top;
        for (; t < len_; --below_) {
            const Entry& e = stack_[below_ - 1];
            if (e.end < t) continue;
            const u32 x0 = first_ + Step * t, x1 = first_ + Step * e.end;
            t = e.end + 1;
            const u32 column = first_ - e.offset;  // a's index at row x is x - column
            for (u32 x = std::min(x0, x1); x <= std::max(x0, x1); ++x) c[x] = std::min(c[x], a_[x - column] + e.bias);
        }
    }

private:
    static constexpr std::int32_t kNear = 1024;  // columns at most this far apart get rank brackets

    u32 value(const Entry& e, u32 t) const { return a_[e.offset + Step * t] + e.bias; }
    bool beats(const Entry& e, const Entry& o, u32 t) const { return value(e, t) <= value(o, t); }

    // Rows t, t + 1, ... where k beats q, counted up to the first loss, at most 8.
    u32 window(const Entry& k, const Entry& q, u32 t) const {
        constexpr int kShift = Step == 1 ? 0 : -7;  // Step -1: the rows' values run backwards
        const auto at = [&](const Entry& e) {
            const auto* p = reinterpret_cast<const __m256i*>(a_ + (e.offset + Step * t) + kShift);
            return _mm256_add_epi32(_mm256_loadu_si256(p), _mm256_set1_epi32(int(e.bias)));
        };
        const u32 loses = u32(_mm256_movemask_ps(_mm256_castsi256_ps(_mm256_cmpgt_epi32(at(k), at(q)))));
        if constexpr (Step == 1) return std::countr_zero(loses | 0x100);
        else return std::countl_zero(loses << 24 | 0x800000);
    }

    // The last row in [lo, hi) where k beats q; k beats q at lo and loses at hi.
    u32 crossing(const Entry& k, const Entry& q, u32 lo, u32 hi) const {
        if (const std::int32_t d = Step * std::int32_t(q.offset - k.offset); d <= kNear) {
            const std::int32_t gap = std::int32_t(k.bias - q.bias);
            std::int32_t theta = gap / d;
            theta += theta * d < gap;  // ceil(gap / d)
            // In the backward sweep k's offset into a falls as t grows: k wins at offsets >= R + d
            // and loses at offsets <= R, for R = R(1 - theta).
            const auto r = rank_(Step == 1 ? theta : 1 - theta);
            const std::int32_t offset = std::int32_t(k.offset);
            const std::int32_t wins = Step == 1 ? std::int32_t(r.low) - d - offset : offset - std::int32_t(r.high) - d;
            const std::int32_t loses = Step == 1 ? std::int32_t(r.high) - offset : offset - std::int32_t(r.low);
            lo = u32(std::max(std::int32_t(lo), wins));
            hi = u32(std::min(std::int32_t(hi), loses));
        }
        u32 m = window(k, q, lo);
        if (m == 8 && hi - lo > 8) {
            lo += 7;
            while (hi - lo > 8) {
                const u32 mid = lo + (hi - lo) / 2;
                (beats(k, q, mid) ? lo : hi) = mid;
            }
            m = window(k, q, lo);
        }
        return lo + m - 1;
    }

    // Column k joins at row t, where it beats q, the top; returns the new top.
    Entry insert(Entry k, u32 t, Entry q) {
        u32 lo = t;  // a row where k beats q
        for (;;) {
            if (!beats(k, q, q.end)) {
                k.end = crossing(k, q, lo, q.end);
                stack_[below_++] = q;
                return k;
            }
            lo = q.end;  // k beats q there, and q the entry below
            if (below_ == 0) {
                k.end = len_ - 1;
                return k;
            }
            q = stack_[--below_];
        }
    }

    const u32* a_;
    const u32* b_;
    const SlopeRank& rank_;
    u32 first_, len_;
    Entry* stack_;  // the entries below the top
    u32 below_ = 0;
};

void solve() {
    io::Reader in;
    const auto n = in.read<std::uint32_t>();
    const auto m = in.read<std::uint32_t>();
    std::uint32_t* const a = mem::huge<std::uint32_t>(n + 16) + 8;  // 8 readable values on each side
    std::uint32_t* const b = mem::huge<std::uint32_t>(m);
    const std::size_t count = n + m - 1;
    std::uint32_t* const c = mem::huge<std::uint32_t>((count + 15) / 16 * 16);  // tail stays 0
    char* const text = mem::huge<char>(columns::kTextBytes);
    mem::Arena arena(SlopeRank::kBuckets * sizeof(SlopeRank::Bounds) + std::min(n, m) * sizeof(Entry) + 64);
    auto* const table = arena.take<SlopeRank::Bounds>(SlopeRank::kBuckets);
    Entry* const stack = arena.take<Entry>(std::min(n, m));
    io::read_bulk(in, a, n);
    io::read_bulk(in, b, m);
    std::fill(c, c + count, ~0u);

    const SlopeRank rank(a, n, table);
    for (std::uint32_t j0 = 0; j0 < m; j0 += n) {
        const std::uint32_t j1 = std::min(m, j0 + n);
        Sweep<1>(a, b, rank, j0, n, stack).run(c, j0, j1 - j0);
        Sweep<-1>(a, b, rank, j1 + n - 2, n, stack).run(c, j1 - 1, j1 - j0);
    }

    io::Writer out;
    columns::write(out, c, count, text);
}

}  // namespace

RUN_EARLY(solve)
